### ISSUE TITLE
In gravitee 4.4.2

### ISSUE THREAD

**Issue by cschockaert** [gravitee-io/issues#10144]
Hello team,

We are running gravitee 4.4.2 on a Kubernetes cluster using a Helm chart.

In certain exceptional circumstances, when MongoDB wasn’t immediately available during the gateway bootstrap, the API endpoints were deployed, and health checks passed. However, this led to 404 responses for all requests when calling Gravitee, with only log messages like:

WARN  i.g.g.r.r.p.n.NotFoundProcessor - No handler can be found for request /xxx, returning NOT_FOUND (404)

However the pod HC is FINE:
http://localhost:18082_node/health?probes=sync-processe -> 200 OK

**Comment by cschockaert** [comment]
Here more startup log for the gateway in bad state:

```
12:25:09.823 [vert.x-eventloop-thread-2] [] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch: Failed to resolve 'gravitee-es8-elasticsearch.gravitee.svc-lb.domain' [A(1)] and search domain query
for configured domains failed as well: [gravitee.svc.cluster.local, svc.cluster.local, cluster.local, c.project-name.internal, google.internal]
12:25:09.823 [vert.x-eventloop-thread-2] [] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch: Failed to resolve 'gravitee-es8-elasticsearch.gravitee.svc-lb.domain' [A(1)] and search domain query
for configured domains failed as well: [gravitee.svc.cluster.local, svc.cluster.local, cluster.local, c.project-name.internal, google.internal]
12:25:15.504 [cluster-ClusterId{value='xxxx', description='null'}-gravitee-4-b-shard-00-02-pri.atlas-xxx.mongodb.net:27017] [] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description Se
rverDescription{address=gravitee-4-b-shard-00-02-pri.atlas-xxx.mongodb.net:27017, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNano
s=1111229069, setName='atlas-rsyv3k-shard-0', canonicalAddress=gravitee-4-b-shard-00-02-pri.atlas-xxx.mongodb.net:27017, hosts=[gravitee-4-b-shard-00-02-pri.atlas-xxx.mongodb.net:27017, gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017, gravitee-4-b-
shard-00-00-pri.atlas-xxx.mongodb.net:27017], passives=[], arbiters=[], primary='gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017', tagSet=TagSet{[Tag{name='availabilityZone', value='gcp-region'}, Tag{name='diskState', value='READY'}, Tag{na
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
        at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName(Unknown Source)
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:213)
        ... 7 common frames omitted
12:25:03.112 [cluster-ClusterId{value='xxxx', description='null'}-gravitee-4-b-shard-00-00-pri.atlas-xxx.mongodb.net:27017] [] INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server gravitee-4-b
-shard-00-00-pri.atlas-xxx.mongodb.net:27017
com.mongodb.MongoSocketException: gravitee-4-b-shard-00-00-pri.atlas-xxx.mongodb.net
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:221)
        at com.mongodb.internal.connection.ServerAddressWithResolver.getSocketAddresses(ServerAddressWithResolver.java:68)
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:100)
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:78)
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:211)
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:196)
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:156)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: gravitee-4-b-shard-00-00-pri.atlas-xxx.mongodb.net
        at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName(Unknown Source)
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:213)
        ... 7 common frames omitted
12:25:09.823 [vert.x-eventloop-thread-2] [] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch: Failed to resolve 'gravitee-es8-elasticsearch.gravitee.svc-lb.domain' [A(1)] and search domain query
for configured domains failed as well: [gravitee.svc.cluster.local, svc.cluster.local, cluster.local, c.project-name.internal, google.internal]
12:25:09.823 [vert.x-eventloop-thread-2] [] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch: Failed to resolve 'gravitee-es8-elasticsearch.gravitee.svc-lb.domain' [A(1)] and search domain query
for configured domains failed as well: [gravitee.svc.cluster.local, svc.cluster.local, cluster.local, c.project-name.internal, google.internal]
12:25:15.504 [cluster-ClusterId{value='xxxx', description='null'}-gravitee-4-b-shard-00-02-pri.atlas-xxx.mongodb.net:27017] [] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description Se
rverDescription{address=gravitee-4-b-shard-00-02-pri.atlas-xxx.mongodb.net:27017, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNano
s=1111229069, setName='atlas-rsyv3k-shard-0', canonicalAddress=gravitee-4-b-shard-00-02-pri.atlas-xxx.mongodb.net:27017, hosts=[gravitee-4-b-shard-00-02-pri.atlas-xxx.mongodb.net:27017, gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017, gravitee-4-b-
shard-00-00-pri.atlas-xxx.mongodb.net:27017], passives=[], arbiters=[], primary='gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017', tagSet=TagSet{[Tag{name='availabilityZone', value='gcp-region'}, Tag{name='diskState', value='READY'}, Tag{na
me='nodeType', value='ELECTABLE'}, Tag{name='provider', value='GCP'}, Tag{name='region', value='WESTERN_EUROPE'}, Tag{name='workloadType', value='OPERATIONAL'}]}, electionId=null, setVersion=3, topologyVersion=TopologyVersion{processId=671bfb959
0bc89524cbfb97e, counter=3}, lastWriteDate=Wed Oct 30 12:25:14 GMT 2024, lastUpdateTimeNanos=21220274618309}
12:25:15.504 [cluster-ClusterId{value='xxxx', description='null'}-gravitee-4-b-shard-00-00-pri.atlas-xxx.mongodb.net:27017] [] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description Se
rverDescription{address=gravitee-4-b-shard-00-00-pri.atlas-xxx.mongodb.net:27017, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNano
s=1110925909, setName='atlas-rsyv3k-shard-0', canonicalAddress=gravitee-4-b-shard-00-00-pri.atlas-xxx.mongodb.net:27017, hosts=[gravitee-4-b-shard-00-02-pri.atlas-xxx.mongodb.net:27017, gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017, gravitee-4-b-
shard-00-00-pri.atlas-xxx.mongodb.net:27017], passives=[], arbiters=[], primary='gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017', tagSet=TagSet{[Tag{name='availabilityZone', value='europe-west1-b'}, Tag{name='diskState', value='READY'}, Tag{na
me='nodeType', value='ELECTABLE'}, Tag{name='provider', value='GCP'}, Tag{name='region', value='WESTERN_EUROPE'}, Tag{name='workloadType', value='OPERATIONAL'}]}, electionId=null, setVersion=3, topologyVersion=TopologyVersion{processId=671bfaec4
5f326b082b58041, counter=3}, lastWriteDate=Wed Oct 30 12:25:14 GMT 2024, lastUpdateTimeNanos=21220274618829}
12:25:15.504 [cluster-ClusterId{value='xxxx', description='null'}-gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017] [] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description Se
rverDescription{address=gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=
1111246339, setName='atlas-rsyv3k-shard-0', canonicalAddress=gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017, hosts=[gravitee-4-b-shard-00-02-pri.atlas-xxx.mongodb.net:27017, gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017, gravitee-4-b-sh
ard-00-00-pri.atlas-xxx.mongodb.net:27017], passives=[], arbiters=[], primary='gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017', tagSet=TagSet{[Tag{name='availabilityZone', value='europe-west1-c'}, Tag{name='diskState', value='READY'}, Tag{name
='nodeType', value='ELECTABLE'}, Tag{name='provider', value='GCP'}, Tag{name='region', value='WESTERN_EUROPE'}, Tag{name='workloadType', value='OPERATIONAL'}]}, electionId=7fffffff0000000000000185, setVersion=3, topologyVersion=TopologyVersion{p
rocessId=671bfb4026d1ed986914b204, counter=5}, lastWriteDate=Wed Oct 30 12:25:14 GMT 2024, lastUpdateTimeNanos=21220274618319}
12:25:15.507 [cluster-ClusterId{value='xxxx', description='null'}-gravitee-4-b-shard-00-01-pri.atlas-xxx.mongodb.net:27017] [] INFO  org.mongodb.driver.cluster - Discovered replica set primary gravitee-4-b-shard-00-01-pri.atlas-xxx.m
ongodb.net:27017 with max election id 7fffffff0000000000000185 and max set version 3
12:25:15.728 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.node.plugin.cluster.standalone.StandaloneClusterManager
12:25:15.728 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: ServiceManager
12:25:15.729 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Plugins - Services Manager
12:25:15.737 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Endpoints Discovery
12:25:15.740 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Health-check service
12:25:15.740 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Asynchronous Rate Limit proxy
12:25:15.749 [graviteeio-node] [] INFO  i.g.g.s.r.AsyncRateLimitService - Register the rate-limit service bridge for synchronous and asynchronous mode
12:25:15.786 [graviteeio-node] [] INFO  i.g.g.s.h.i.HeartbeatEventScheduler - Starting gateway heartbeat
12:25:15.789 [graviteeio-node] [] INFO  i.g.g.s.h.i.HeartbeatEventScheduler - Monitoring scheduled with fixed delay 5000 MILLISECONDS
12:25:15.790 [graviteeio-node] [] INFO  i.g.g.s.h.i.HeartbeatEventScheduler - Start gateway heartbeat done successfully
12:25:15.790 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Gateway - Debug service
12:25:15.790 [graviteeio-node] [] INFO  i.g.gateway.debug.DebugService - Starting component: VertxDebugService
12:25:15.791 [graviteeio-node] [] INFO  i.g.g.debug.vertx.VertxDebugService - Starting Vertx DEBUG container and deploy only 1 Verticle
12:25:15.791 [graviteeio-node] [] INFO  i.g.gateway.debug.DebugService - Starting component: DebugReactorEventListener
12:25:15.791 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.gateway.reactive.debug.DebugReactorEventListener
12:25:15.791 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service com.graviteesource.reactor.message.subscription.MessageSubscriptionDispatcher
12:25:15.791 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: ManagementService
12:25:15.792 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Node Management API service
12:25:15.795 [vert.x-eventloop-thread-2] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - Start HTTP listener for Node Management API
12:25:15.795 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: NodeMonitoringEventHandler
12:25:15.795 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.node.monitoring.handler.NodeMonitoringEventHandler
12:25:15.798 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: NodeInfosService
12:25:15.798 [graviteeio-node] [] INFO  i.g.n.m.infos.NodeInfosService - Starting node infos service
12:25:15.798 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Node Infos Service
12:25:16.261 [vert.x-eventloop-thread-2] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - Register a new endpoint for Management API: GET /license [io.gravitee.node.license.management.NodeLicenseManagementEndpoint]
12:25:16.268 [graviteeio-node] [] INFO  i.g.n.m.infos.NodeInfosService - Start node infos service: DONE
12:25:16.268 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: NodeHealthCheckService
12:25:16.269 [vert.x-eventloop-thread-2] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - Register a new endpoint for Management API: GET /apis [io.gravitee.gateway.handlers.api.manager.endpoint.ApisManagementEndpoint]
12:25:16.269 [vert.x-eventloop-thread-2] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - Register a new endpoint for Management API: GET /apis/:apiId [io.gravitee.gateway.handlers.api.manager.endpoint.ApiManagementEndpoint]
12:25:16.269 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Node Health-check service
12:25:16.271 [graviteeio-node] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - Register a new endpoint for Management API: GET /health [io.gravitee.node.monitoring.healthcheck.NodeHealthCheckManagementEndpoint]
12:25:16.271 [vert.x-eventloop-thread-2] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - Register a new endpoint for Management API: GET / [io.gravitee.node.management.http.node.NodeEndpoint]
12:25:16.271 [vert.x-eventloop-thread-2] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - Register a new endpoint for Management API: GET /configuration [io.gravitee.node.management.http.configuration.ConfigurationEndpoint]
12:25:16.272 [vert.x-eventloop-thread-2] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - HTTP listener for Node Management bind to port TCP:18082
12:25:16.273 [vert.x-eventloop-thread-1] [] INFO  i.g.n.c.AbstractKeyStoreLoaderManager - Register and start new keystore loader for target: server{id: fe294f4f-83c9-4ca0-a94f-4f83c99ca031} of type: NoOpKeyStoreLoader with id: no-op
12:25:16.273 [graviteeio-node] [] INFO  i.g.n.m.h.NodeHealthCheckService - Node health check scheduled with fixed delay 5000 MILLISECONDS
12:25:16.273 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: NodeMonitorService
12:25:16.274 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Node Monitor Service
12:25:16.274 [vert.x-eventloop-thread-1] [] INFO  i.g.n.c.AbstractKeyStoreLoaderManager - Register and start new keystore loader for target: server{id: fe294f4f-83c9-4ca0-a94f-4f83c99ca031} of type: NoOpKeyStoreLoader with id: no-op
12:25:16.278 [graviteeio-node] [] INFO  i.g.n.m.monitor.NodeMonitorService - Node monitoring scheduled with fixed delay 5000 MILLISECONDS
12:25:16.279 [graviteeio-node] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - Register a new endpoint for Management API: GET /monitor [io.gravitee.node.monitoring.monitor.NodeMonitorManagementEndpoint]
12:25:16.279 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: ReporterManager
12:25:16.279 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Reporter service
12:25:16.281 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: VertxEmbeddedContainer
12:25:16.281 [graviteeio-node] [] INFO  i.g.g.s.vertx.VertxEmbeddedContainer - Starting Vertx container and deploy Gateway HTTP Verticles [2 instance(s)]
12:25:16.282 [graviteeio-node] [] INFO  i.g.g.s.vertx.VertxEmbeddedContainer - Starting Vertx container and deploy Gateway TCP Verticles [2 instance(s)]
12:25:16.282 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: AlertEventProducerManager
12:25:16.283 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Alert Engine - Event producer
12:25:16.283 [graviteeio-node] [] INFO  i.g.p.a.i.AlertEventProducerManagerImpl -       There is no event producer to start
12:25:16.286 [vert.x-eventloop-thread-0] [] INFO  i.g.n.r.vertx.ReporterManagerImpl - Starting reporter: io.gravitee.node.reporter.vertx.eventbus.EventBusReporterWrapper@76aac657
12:25:16.288 [vert.x-eventloop-thread-0] [] INFO  i.g.n.r.vertx.ReporterManagerImpl - Starting reporter: io.gravitee.node.reporter.vertx.eventbus.EventBusReporterWrapper@67701ee5
12:25:16.288 [vert.x-eventloop-thread-0] [] INFO  i.g.n.r.vertx.ReporterManagerImpl - Starting reporter: io.gravitee.node.reporter.vertx.eventbus.EventBusReporterWrapper@47c8f422
12:25:16.288 [vert.x-eventloop-thread-0] [] INFO  i.g.n.r.vertx.ReporterManagerImpl - Starting reporter: io.gravitee.node.reporter.vertx.eventbus.EventBusReporterWrapper@2e74a5ed
12:25:16.298 [vert.x-eventloop-thread-0] [] INFO  i.g.g.r.s.vertx.HttpProtocolVerticle - Starting HTTP servers...
12:25:16.298 [vert.x-eventloop-thread-0] [] INFO  i.g.n.c.AbstractKeyStoreLoaderManager - Register and start new keystore loader for target: server{id: http} of type: NoOpKeyStoreLoader with id: no-op
12:25:16.298 [vert.x-eventloop-thread-0] [] INFO  i.g.n.c.AbstractKeyStoreLoaderManager - Register and start new keystore loader for target: server{id: http} of type: NoOpKeyStoreLoader with id: no-op
12:25:16.300 [vert.x-eventloop-thread-1] [] INFO  i.g.g.r.d.v.DebugHttpProtocolVerticle - Starting debug HTTP server...
12:25:16.370 [vert.x-eventloop-thread-1] [] INFO  i.g.g.r.s.vertx.HttpProtocolVerticle - Starting HTTP servers...
12:25:16.279 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Reporter service
12:25:16.281 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: VertxEmbeddedContainer
12:25:16.281 [graviteeio-node] [] INFO  i.g.g.s.vertx.VertxEmbeddedContainer - Starting Vertx container and deploy Gateway HTTP Verticles [2 instance(s)]
12:25:16.282 [graviteeio-node] [] INFO  i.g.g.s.vertx.VertxEmbeddedContainer - Starting Vertx container and deploy Gateway TCP Verticles [2 instance(s)]
12:25:16.282 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode -       Starting component: AlertEventProducerManager
12:25:16.283 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Alert Engine - Event producer
12:25:16.283 [graviteeio-node] [] INFO  i.g.p.a.i.AlertEventProducerManagerImpl -       There is no event producer to start
12:25:16.286 [vert.x-eventloop-thread-0] [] INFO  i.g.n.r.vertx.ReporterManagerImpl - Starting reporter: io.gravitee.node.reporter.vertx.eventbus.EventBusReporterWrapper@76aac657
12:25:16.288 [vert.x-eventloop-thread-0] [] INFO  i.g.n.r.vertx.ReporterManagerImpl - Starting reporter: io.gravitee.node.reporter.vertx.eventbus.EventBusReporterWrapper@67701ee5
12:25:16.288 [vert.x-eventloop-thread-0] [] INFO  i.g.n.r.vertx.ReporterManagerImpl - Starting reporter: io.gravitee.node.reporter.vertx.eventbus.EventBusReporterWrapper@47c8f422
12:25:16.288 [vert.x-eventloop-thread-0] [] INFO  i.g.n.r.vertx.ReporterManagerImpl - Starting reporter: io.gravitee.node.reporter.vertx.eventbus.EventBusReporterWrapper@2e74a5ed
12:25:16.298 [vert.x-eventloop-thread-0] [] INFO  i.g.g.r.s.vertx.HttpProtocolVerticle - Starting HTTP servers...
12:25:16.298 [vert.x-eventloop-thread-0] [] INFO  i.g.n.c.AbstractKeyStoreLoaderManager - Register and start new keystore loader for target: server{id: http} of type: NoOpKeyStoreLoader with id: no-op
12:25:16.298 [vert.x-eventloop-thread-0] [] INFO  i.g.n.c.AbstractKeyStoreLoaderManager - Register and start new keystore loader for target: server{id: http} of type: NoOpKeyStoreLoader with id: no-op
12:25:16.300 [vert.x-eventloop-thread-1] [] INFO  i.g.g.r.d.v.DebugHttpProtocolVerticle - Starting debug HTTP server...
12:25:16.370 [vert.x-eventloop-thread-1] [] INFO  i.g.g.r.s.vertx.HttpProtocolVerticle - Starting HTTP servers...
12:25:16.371 [vert.x-eventloop-thread-1] [] INFO  i.g.g.r.d.v.DebugHttpProtocolVerticle - Debug HTTP server [fe294f4f-83c9-4ca0-a94f-4f83c99ca031] ready to accept requests on port 8482
12:25:16.372 [vert.x-eventloop-thread-0] [] INFO  i.g.g.r.s.vertx.HttpProtocolVerticle - HTTP server [http] ready to accept requests on port 8082
12:25:16.372 [vert.x-eventloop-thread-1] [] INFO  i.g.g.r.s.vertx.HttpProtocolVerticle - HTTP server [http] ready to accept requests on port 8082
12:25:16.521 [vert.x-worker-thread-0] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.reporter.elasticsearch.ElasticsearchReporter
12:25:16.521 [vert.x-worker-thread-0] [] INFO  i.g.r.e.ElasticsearchReporter - Starting Elastic reporter engine...
12:25:16.649 [graviteeio-node] [] INFO  i.g.node.container.AbstractNode - Gravitee.io - API Gateway id[2ec76ef2-680a-4f46-876e-f2680aff463f] version[4.4.2] pid[1] build[747359#f6f138213a2c7a5a05f325daf2d6353e62c080ef] jvm[Eclipse Adoptium/OpenJD
K 64-Bit Server VM/17.0.9+9] started in 52978 ms.
12:25:17.114 [vert.x-eventloop-thread-0] [] INFO  i.g.r.e.ElasticsearchReporter - Starting Elastic reporter engine... DONE
12:25:17.115 [vert.x-eventloop-thread-0] [] INFO  i.g.r.e.ElasticsearchReporter - Index mapping template successfully defined
12:30:01.994 [vert.x-eventloop-thread-1] [] WARN  i.g.g.r.r.p.n.NotFoundProcessor - No handler can be found for request /XXX, returning NOT_FOUND (404)
12:30:02.414 [vertx-blocked-thread-checker] [] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2205 ms, time limit is 2000 ms
12:30:28.653 [vert.x-eventloop-thread-0] [] WARN  i.g.g.r.r.p.n.NotFoundProcessor - No handler can be found for request /XXX, returning NOT_FOUND (404)
12:31:08.427 [vert.x-eventloop-thread-1] [] WARN  i.g.g.r.r.p.n.NotFoundProcessor - No handler can be found for request /XXX, returning NOT_FOUND (404)
12:32:27.793 [vert.x-eventloop-thread-1] [] WARN  i.g.g.r.r.p.n.NotFoundProcessor - No handler can be found for request /XXX, returning NOT_FOUND (404)
12:32:27.983 [vert.x-eventloop-thread-0] [] WARN  i.g.g.r.r.p.n.NotFoundProcessor - No handler can be found for request /XXX, returning NOT_FOUND (404)
12:32:29.039 [vert.x-eventloop-thread-0] [] WARN  i.g.g.r.r.p.n.NotFoundProcessor - No handler can be found for request /XXX, returning NOT_FOUND (404
)
```
