### ISSUE TITLE
apim-gateway 1.12.5 complains com.mongodb.MongoException: java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension

### ISSUE THREAD

**Issue by hfuru** [gravitee-io/issues#1029]
APIM Gateway cannot talk to MongoDB.  It shows the backtrace below, but the central point
is presumably the one in the title - missing  sun/security/ssl/SupportedEllipticCurvesExtension.

It worked some days ago, then we changed the install scripts a bit and updated from
Gravitee 1.12.2 to 1.12.5 and now it doesn't work.  So I wonder if we triggered it somehow or if RedHat upgraded Java to a buggy version in the meantime... it's a bug which shows up in many variants on Google.

```
19:06:00.001 [sync-1] [] INFO  org.mongodb.driver.cluster - No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=apim-utv50.uio.no:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoException: java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}, caused by {java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}}, ServerDescription{address=apim-utv49.uio.no:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoException: java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}, caused by {java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}}]}. Waiting for 1000 ms before timing out
19:06:01.001 [sync-1] [] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.dao.DataAccessResourceFailureException: Timed out after 1000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=apim-utv50.uio.no:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoException: java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}, caused by {java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}}, {address=apim-utv49.uio.no:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoException: java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}, caused by {java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 1000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=apim-utv50.uio.no:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoException: java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}, caused by {java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}}, {address=apim-utv49.uio.no:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoException: java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}, caused by {java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}}]
        at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:73)
        at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2011)
        at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1894)
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1705)
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1688)
        at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:601)
        at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$Execution.readCollection(AbstractMongoQuery.java:170)
        at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$CollectionExecution.execute(AbstractMongoQuery.java:193)
        at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:104)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:413)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:391)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy42.findAll(Unknown Source)
        at io.gravitee.repository.mongodb.management.MongoApiRepository.findAll(MongoApiRepository.java:71)
        at io.gravitee.gateway.services.sync.SyncManager.refresh(SyncManager.java:85)
        at io.gravitee.gateway.services.sync.ScheduledSyncService.doSync(ScheduledSyncService.java:95)
        at io.gravitee.gateway.services.sync.ScheduledSyncService.run(ScheduledSyncService.java:87)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 1000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=apim-utv50.uio.no:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoException: java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}, caused by {java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}}, {address=apim-utv49.uio.no:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoException: java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}, caused by {java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension}}]
        at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:377)
        at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:104)
        at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
        at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
        at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:402)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:510)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:81)
        at com.mongodb.Mongo.execute(Mongo.java:836)
        at com.mongodb.Mongo$2.execute(Mongo.java:823)
        at com.mongodb.DBCursor.initializeCursor(DBCursor.java:870)
        at com.mongodb.DBCursor.hasNext(DBCursor.java:142)
        at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1880)
        ... 26 common frames omitted

```

### Expected Behavior

Gateway which can talk to MongoDB.  Looks like the regular pings/health checks etc fails, no user involvement.

### Steps to Reproduce (for bugs)

1.  Install Gravitee (apim gateway + management + ui) + mongodb + elasticsearch es5 reporter,
with nginx in front of mgmt + ui for HTTPS.  Not in front of apim-gw, we forgot that.  haproxy in front of apim ui+gw.

### Context

We're trying to get Gravitee up and running.  Some of our problems have been our own fault, some not.

### Your Environment

* Version used: Gravitee 1.12.5. MongoDB 3.4.  Java RPM java-1.8.0-openjdk-headless.x86_64.
* Browser Name and version: Firefox, but looks irrelevant
* Operating System and version: Red Hat Enterprise Linux Server release 7.4, x86_64

**Comment by hfuru** [comment]
Fixed: yum downgrade java-1.8.0-openjdk-headless
This downgraded from 1.8.0.161-0.b14 to 1.8.0.151-5.b12.

Some reports said downgrade and re-upgrade would help, but upgrading broke it again.  Unless I read those reports too quickly:
https://tickets.puppetlabs.com/plugins/servlet/mobile#issue/SERVER-1720
https://groups.google.com/forum/m/#!topic/icatgroup/n9-paaersNQ

**Comment by brasseld** [comment]
Issue with the OpenJDK version.

**Comment by hfuru** [comment]
The workaround was incomplete, we also needed to keep java from being upgraded again.  So:
  yum -y install yum-plugin-versionlock
  yum -y downgrade java-1.8.0-openjdk-headless
  yum -y versionlock java-1.8.0-openjdk-headless
