### ISSUE TITLE
Internal server error when the failover timeout is set to 0

### ISSUE THREAD

**Issue by aurelien-pacaud** [gravitee-io/issues#1038]
When failover is enabled the timeout can't be set to 0. An internal server error is thrown for each call, see stacktrace below:

Caused by: java.lang.IllegalArgumentException: Cannot schedule a timer with delay < 1 ms
        at io.vertx.core.impl.VertxImpl.scheduleTimeout(VertxImpl.java:462)
        at io.vertx.core.impl.VertxImpl.setTimer(VertxImpl.java:325)
        at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.executeOperation(CircuitBreakerImpl.java:327)
        at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.executeAndReportWithFallback(CircuitBreakerImpl.java:231)
        at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.executeWithFallback(CircuitBreakerImpl.java:373)
        at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.execute(CircuitBreakerImpl.java:378)
        at io.gravitee.gateway.http.core.invoker.failover.FailoverInvoker.invoke(FailoverInvoker.java:63)
        at io.gravitee.gateway.handlers.api.ApiReactorHandler.lambda$handleClientRequest$6(ApiReactorHandler.java:156)
        at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:65)
        at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
        at io.gravitee.gateway.policy.NoOpPolicyChain.doNext(NoOpPolicyChain.java:41)
        at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63)
        at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
        at io.gravitee.gateway.policy.NoOpPolicyChain.doNext(NoOpPolicyChain.java:41)
        at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63)
        at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
        at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:76)
        at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
        at io.gravitee.policy.keyless.KeylessPolicy.onRequest(KeylessPolicy.java:39)
        ... 64 common frames omitted

### Your Environment
* Version used: 1.12.4

**Comment by NicolasGeraud** [comment]
So there is 2 parameters : max retry and timeout
The max-retry iterate over each endpoints, so the value `0` doesn't make sense.
The Vertx CircuitBreaker doesn't allow 0. Its default value is 10000. This will become our new default value.
