### ISSUE TITLE
[gateway] NullPointerException

### ISSUE THREAD

**Issue by David-V2** [gravitee-io/issues#1041]
### Current Behavior

There is some Unhandled NullPointerException in the gateway :

```
Unhandled exception java.lang.NullPointerException: null
 at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:94)
 at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:33)
 at io.gravitee.gateway.handlers.api.ApiReactorHandler.lambda$null$3(ApiReactorHandler.java:168)
 at io.gravitee.gateway.handlers.api.logging.LoggableClientRequest.lambda$bodyHandler$0(LoggableClientRequest.java:63)
 at io.gravitee.gateway.standalone.vertx.VertxHttpServerRequest.lambda$bodyHandler$0(VertxHttpServerRequest.java:152)
 at io.vertx.core.http.impl.HttpServerRequestImpl.handleData(HttpServerRequestImpl.java:373)
 at io.vertx.core.http.impl.ServerConnection.handleChunk(ServerConnection.java:293)
 at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:435)
 at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131)
 at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:678)
 at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:573)
 at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71)
 at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
 at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
 at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71)
 at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.http1(HttpServerImpl.java:1064)
 at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.channelRead(HttpServerImpl.java:1035)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
 at java.lang.Thread.run(Thread.java:748)
```

### Expected Behavior

Error should be catched and handled.
The error message should contain the questionned API

**Comment by brasseld** [comment]
The stack trace is not really helpful.
Also you miss the OS, the JDK version and the Gravitee version....

We need more to analyze a potential issue.

**Comment by David-V2** [comment]
Sorry I do not have anything else than this stack-trace : I am unable to link the error with a specific API or policy.

There is only 7 API declared on this platform, and 3 sorts of policies : 
- mock : on one API only, on one path, used for diagnostic purposes.
- rate limiting : one one API only (gods help me !)
- transformation header : on 3 publicly exposed API, in order to give the api-key to the internal gateway.

We are talking about : 
- Gravitee 1.10.5
- jdk 1.8.0_131
- centos 7
- kernel 3.10.0-514.26.2.el7.x86_64

**Comment by brasseld** [comment]
In that case, only the API with the mock policy is involved.
Can you private an export of the API (in private) ?

**Comment by David-V2** [comment]
done !

**Comment by brasseld** [comment]
Not reproducible.
