### ISSUE TITLE
java.lang.NullPointerException with 1.13.2 and OpenJDK

### ISSUE THREAD

**Issue by hfuru** [gravitee-io/issues#1069]
ElasticSearch won't show up in Dashboard

### Current Behavior

Backtrace in /opt/gravitee/apim_api/logs/gravitee.log:

```
14:03:38.775 [gravitee-listener-27] INFO  i.g.m.s.f.JWTAuthenticationFilter - Authorization schema not found
14:03:47.711 [gravitee-listener-27] ERROR i.g.m.rest.provider.ThrowableMapper - Internal error
java.lang.NullPointerException: null
	at io.gravitee.management.repository.proxy.AnalyticsRepositoryProxy.query(AnalyticsRepositoryProxy.java:33)
	at io.gravitee.management.service.impl.AnalyticsServiceImpl.execute(AnalyticsServiceImpl.java:145)
	at io.gravitee.management.rest.resource.PlatformAnalyticsResource.executeGroupBy(PlatformAnalyticsResource.java:140)
	at io.gravitee.management.rest.resource.PlatformAnalyticsResource.platformAnalytics(PlatformAnalyticsResource.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:74)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:202)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:388)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:346)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:337)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:280)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:316)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1084)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:418)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1712)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at io.gravitee.management.security.filter.AuthenticationSuccessFilter.doFilter(AuthenticationSuccessFilter.java:128)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at io.gravitee.management.security.filter.JWTAuthenticationFilter.doFilter(JWTAuthenticationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1699)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:523)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)

```

### Steps to Reproduce (for bugs)

1. Install Gravitee 1.13.2 with OpenJDK
2. Login, go to Dashboard. 

### Your Environment

* Version used: Gravitee 1.13.2.  OpenJDK 1.8.0_151-b12
* Browser Name and version: Firefox 52.6.0
* Operating System and version: RHEL 7.3, x86_64

**Comment by brasseld** [comment]
I think you may have an other issue in your log while starting the process.
Please check.

**Comment by hfuru** [comment]
There are two WARNs and some nulls:

```
...
13:59:05.239 [gravitee] INFO  i.g.m.r.p.RepositoryPluginHandler - Register a new repository: repository-mongodb [io.gravitee.repository.mongodb.MongoRepository]
13:59:06.687 [gravitee] WARN  org.dozer.config.GlobalSettings - Dozer configuration file not found: dozer.properties.  Using defaults for all Dozer global properties.
13:59:07.106 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - Installing IDENTITY_PROVIDER plugins...
...
13:59:07.281 [gravitee] INFO  i.g.p.p.internal.PolicyPluginHandler - Register a new policy: key-less [io.gravitee.policy.keyless.KeylessPolicy]
13:59:07.282 [gravitee] INFO  i.g.p.p.i.PolicyConfigurationClassFinder - No policy configuration class defined for policy io.gravitee.policy.keyless.KeylessPolicy
...
13:59:07.347 [gravitee] INFO  i.g.p.p.internal.PolicyPluginHandler - Register a new policy: logging [io.gravitee.policy.logging.LoggingPolicy]
13:59:07.348 [gravitee] INFO  i.g.p.p.i.PolicyConfigurationClassFinder - No policy configuration class defined for policy io.gravitee.policy.logging.LoggingPolicy
...
13:59:07.660 [gravitee] INFO  i.g.m.standalone.node.ManagementNode - 	Starting component: JettyEmbeddedContainer
13:59:07.677 [gravitee] WARN  o.e.j.server.handler.ContextHandler - o.e.j.s.ServletContextHandler@79cb8ffa{/,null,null} contextPath ends with /*
13:59:07.711 [gravitee] INFO  org.eclipse.jetty.server.Server - jetty-9.3.13.v20161014
13:59:07.729 [gravitee] INFO  o.e.j.server.AbstractNCSARequestLog - Opened /opt/gravitee/apim_api/logs/gravitee_accesslog_2018_02_07.log
13:59:07.926 [gravitee] INFO  i.g.m.s.c.BasicSecurityConfigurerAdapter - Loading authentication providers
13:59:07.965 [gravitee] INFO  i.g.m.s.c.BasicSecurityConfigurerAdapter - Loading authentication identity providers for Basic authentication
13:59:07.967 [gravitee] INFO  i.g.m.s.c.BasicSecurityConfigurerAdapter - Loading authentication provider of type ldap at position 0
13:59:08.080 [gravitee] INFO  i.g.m.i.l.lookup.LdapIdentityLookup - User identifier is based on the [uid] attribute
13:59:08.081 [gravitee] INFO  i.g.m.i.l.lookup.LdapIdentityLookup - User search is based on DN [cn=users,cn=system,dc=uio,dc=no]
13:59:08.081 [gravitee] INFO  i.g.m.i.l.a.LdapAuthenticationProvider - Configuring an LDAP Identity Provider
13:59:10.946 [gravitee] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@79cb8ffa{/management,null,AVAILABLE}
13:59:10.950 [gravitee] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@2c731a16{HTTP/1.1,[http/1.1]}{0.0.0.0:8083}
13:59:10.951 [gravitee] INFO  org.eclipse.jetty.server.Server - Started @9675ms
13:59:10.951 [gravitee] INFO  i.g.m.standalone.node.ManagementNode - 	Starting component: InitializerService
13:59:10.952 [gravitee] INFO  i.g.common.service.AbstractService - Initializing service Initializer Service
13:59:10.977 [sync-1] INFO  i.g.m.services.sync.ApiManager - Deployment of ApiEntity{id='884ea786-d66c-4626-8ea7-86d66c9626a4', name='httpbin2', version='1.1', description='test av httpbin', proxy=io.gravitee.definition.model.Proxy@1b117d18, paths={/=io.gravitee.definition.model.Path@78648b4c}, createdAt=Wed Feb 07 13:35:22 CET 2018, updatedAt=Wed Feb 07 13:37:27 CET 2018, visibility=PRIVATE, state=STARTED, primaryOwner=null, role=null, tags=[], view=null, groups=null}
13:59:10.986 [sync-1] INFO  i.g.m.s.d.DynamicPropertiesService - Dynamic properties service is disabled for: httpbin2 [1.1]
13:59:10.987 [sync-1] INFO  i.g.m.services.sync.ApiManager - Deployment of ApiEntity{id='7bda4d7f-ac51-4d2f-9a4d-7fac51dd2f82', name='uh-person', version='v1', description='Default API description', proxy=io.gravitee.definition.model.Proxy@5d0cb59d, paths={/uio.no/*=io.gravitee.definition.model.Path@1ee6b9b, /=io.gravitee.definition.model.Path@ab195ad}, createdAt=Fri Feb 02 13:16:28 CET 2018, updatedAt=Fri Feb 02 15:18:41 CET 2018, visibility=PRIVATE, state=STARTED, primaryOwner=null, role=null, tags=[], view=null, groups=null}
13:59:11.005 [sync-1] INFO  i.g.m.s.d.DynamicPropertiesService - Dynamic properties service is disabled for: uh-person [v1]
13:59:11.017 [gravitee] INFO  i.g.m.service.impl.RoleServiceImpl -       - <MANAGEMENT> ADMIN (system)
13:59:11.026 [gravitee] INFO  i.g.m.service.impl.RoleServiceImpl -       - <PORTAL> ADMIN (system)
13:59:11.033 [gravitee] INFO  i.g.m.service.impl.RoleServiceImpl -       - <API> PRIMARY_OWNER (system)
13:59:11.037 [gravitee] INFO  i.g.m.service.impl.RoleServiceImpl -       - <APPLICATION> PRIMARY_OWNER (system)
13:59:11.041 [gravitee] INFO  i.g.m.standalone.node.ManagementNode - Gravitee.io - Management API id[0c76a8ce-0294-4f14-b6a8-ce02946f14fa] version[1.13.2] pid[60764] build[273#ca2d2c41a5418ecb371e90fa7cd8291c343b2c7c] jvm[Oracle Corporation/OpenJDK 64-Bit Server VM/25.151-b12] started in 6262 ms.
14:02:59.406 [gravitee-listener-24] INFO  i.g.m.s.f.JWTAuthenticationFilter - Authorization schema not found
14:02:59.534 [gravitee-listener-21] INFO  i.g.m.s.f.JWTAuthenticationFilter - Authorization schema not found
...
14:03:47.711 [gravitee-listener-27] ERROR i.g.m.rest.provider.ThrowableMapper - Internal error

```

**Comment by brasseld** [comment]
Please provide complete log file
