### ISSUE TITLE
[management-api] Error when checking health of api

### ISSUE THREAD

**Issue by chansdad** [gravitee-io/issues#1080]
Brand new Install , trying to get the echo api to work 

While browsing the portal , seeing the following on console 

07:04:01.006 [gravitee-listene
r-22] ERROR i.g.m.s.impl.HealthCheckServiceImpl - An unexpected error occurs while searching for health data.
java.lang.NullPointerException: null
        at io.gravitee.management.repository.proxy.HealthCheckRepositoryProxy.query(HealthCheckRepositoryProxy.java
:34)
        at io.gravitee.management.service.impl.HealthCheckServiceImpl.getResponseTime(HealthCheckServiceImpl.java:1
82)
        at io.gravitee.management.rest.resource.ApiHealthResource.health(ApiHealthResource.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(Resour
ceMethodInvocationHandlerFactory.java:74)

**Comment by brasseld** [comment]
Hi @chansdad 

You may probably have other issues when starting management-api relative to Elasticsearch.
This kind of NullPointerException is usually a problem with Elasticsearch installation / configuration.

You can provide the full log if you want.

**Comment by brasseld** [comment]
Hi @chansdad 

any news ?

**Comment by brasseld** [comment]
Closing for inactivity
