### ISSUE TITLE
Running AM Gateway from the command line[Stacktrace while startup][NoClassDefFoundError]

### ISSUE THREAD

**Issue by BlackTurtle123** [gravitee-io/issues#1215]
While starting up the access management I get  huge stacktrace about NoCLassDefFoundError
### Expected Behavior
Program starting up properly

### Current Behavior
StackTrace+ shutdown

### Steps to Reproduce (for bugs)
1. Follow this tutorial: https://docs.gravitee.io/am_installguide_gateway.html#running_am_gateway_from_the_command_line
2. By the step to run from command line the stack trace appears.
3.
4.

### Context
Installing the AM Gateway for my paper.
I think it might be a java version issue?

### Your Environment
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.am.gateway.bootstrap.Bootstrap.start(Bootstrap.java:157)
	at io.gravitee.am.gateway.bootstrap.Bootstrap.main(Bootstrap.java:166)
Caused by: java.lang.NoClassDefFoundError: io/gravitee/repository/Repository
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at io.gravitee.plugin.core.api.PluginClassLoader.loadClass(PluginClassLoader.java:72)
	at io.gravitee.am.gateway.repository.plugin.RepositoryPluginHandler.handle(RepositoryPluginHandler.java:79)
	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:108)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:103)
	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:88)
	at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.common.node.AbstractNode.doStart(AbstractNode.java:53)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.am.gateway.container.Container.start(Container.java:103)
	... 6 more
Caused by: java.lang.ClassNotFoundException: io.gravitee.repository.Repository
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 52 more
```
* Version used: latest
* Operating System and version: Centos7
* Java Version: java version "1.8.0_161"

**Comment by brasseld** [comment]
I'm a bit surprised, missing class `io.gravitee.repository.Repository` is coming from gravitee.io APIM and not AM, so I don't understand why you need such class.

Can you indicate me what did you do exactly, I mean how you install AM.

Thanks

**Comment by BlackTurtle123** [comment]
Nevermind, I saw the error.
Manual error with changing from mongo to mysql.
Sorry :p

**Comment by BlackTurtle123** [comment]
I guess this one is something I did wrong on my end also?
`12:52:25.087 [sync-1] [] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at io.gravitee.am.gateway.repository.proxy.DomainRepositoryProxy.findAll(DomainRepositoryProxy.java:36)
	at io.gravitee.am.gateway.service.impl.DomainServiceImpl.findAll(DomainServiceImpl.java:91)
	at io.gravitee.am.gateway.services.sync.SyncManager.refresh(SyncManager.java:52)
	at io.gravitee.am.gateway.services.sync.ScheduledSyncService.doSync(ScheduledSyncService.java:79)
	at io.gravitee.am.gateway.services.sync.ScheduledSyncService.run(ScheduledSyncService.java:69)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by brasseld** [comment]
Seems that AM is not able to access your datastorage, that's the reason why you get such error.

**Comment by BlackTurtle123** [comment]
Ha yes, I see it already, it doesn't support jdbc/mysql according to the documentation, that would tell why I get this error ofc.

**Comment by brasseld** [comment]
Yeah, we only have a Mongo implementation for now.

May I close this ticket ? (you can also do it).
