### ISSUE TITLE
Portal is sending GET to /user resource, returns 500 error

### ISSUE THREAD

**Issue by jbarbeira** [gravitee-io/issues#1216]
After deploying gravitee using the docker-compose example, when accessing the portal, I get this error from my browser developer console

Request URL:http://xxxxxx:8005/management/user/
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:10.21.208.36:8005
Referrer Policy:no-referrer-when-downgrade

and the response payload was 

{
  "message" : "Cannot pass null or empty values to constructor",
  "http_status" : 500
}

### Expected Behavior
No 500 error. 

### Current Behavior
500 error

### Possible Solution
Probably the portal should be GETing the /users/ resource?

### Steps to Reproduce (for bugs)
1. install service using docker-compose.yml provided at gravitee site
2. access the portal

### Context
Trialing the solution

### Your Environment

* Version used:  official gravitee docker  image:latest
* Browser Name and version: chrome Version 62.0.3202.75 
* Operating System and version: docker latest version running on RHEL7

**Comment by jbarbeira** [comment]
Log from the management API

java.lang.IllegalArgumentException: Cannot pass null or empty values to constructor
        at org.springframework.security.core.userdetails.User.<init>(User.java:101)
        at org.springframework.security.core.userdetails.User.<init>(User.java:74)
        at io.gravitee.management.idp.api.authentication.UserDetails.<init>(UserDetails.java:41)
        at io.gravitee.management.rest.resource.CurrentUserResource.getCurrentUser(CurrentUserResource.java:99)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by brasseld** [comment]
Hi @jbarbeira

Which user did you use to login ?
