### ISSUE TITLE
[gateway] Call an HTTPS API behind a proxy

### ISSUE THREAD

**Issue by NFortun** [gravitee-io/issues#1229]
I tried to call the https://swapi.co/api/people/1/ behind a corporate proxy. In the logs, it returns me a http 502 error. This is weird because https://demo.gravitee.io/gateway/echo/ and http://httpbin.org/anything work.

### Expected Behavior

It should return the response of the swapi.

### Current Behavior

On the API logs dashboard, I get a 502 error with the following message : Failed to create SSL connection. Moreover, the gateway logs are :

```
08:34:01.887 [vert.x-eventloop-thread-3] [] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
        at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1010)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420)
        at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:225)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:219)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
        at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:292)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1248)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1194)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        ... 23 common frames omitted
```

### Steps to Reproduce (for bugs)

1. Create a new API
2. Create an HTTPS endpoint, enable HTTP PROXY and SSL client
3. curl the api created
4. Get a 502 error

### Your Environment

Running Gravitee through Docker, using the docker-compose files provided. Docker is running inside a Debian VM. All of these are running behind a corporate proxy. I redirect all the calls via a local proxy ( Fiddler) in order to use the correct configuration. I am able to see the request to swapi.

* Version used: 1.15.1
* Browser Name and version: Firefox 59.0.3 (64 bits)
* Operating System and version: Virtual machine : debian/stretch64  using vagrant,  Host : Windows 7

**Comment by NFortun** [comment]
Remark: This does not happen whith the standalone installation

**Comment by NFortun** [comment]
The curl command works well.

bash-4.4# curl -v -k https://swapi.co/api/people/1/
*   Trying 10.35.3.109...
* TCP_NODELAY set
* Connected to 10.35.3.109 (10.35.3.109) port 8888 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to swapi.co:443
> CONNECT swapi.co:443 HTTP/1.1
> Host: swapi.co:443
> User-Agent: curl/7.59.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering http/1.1
* ignoring certificate verify locations due to disabled peer verification
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni134910.cloudflaressl.com
*  start date: May 16 00:00:00 2018 GMT
*  expire date: Nov 22 23:59:59 2018 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /api/people/1/ HTTP/1.1
> Host: swapi.co
> User-Agent: curl/7.59.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 17 May 2018 13:27:36 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=dfafa205f96e19a9e2fcb8b4e20e11e821526563656; expires=Fri, 17-May-19 13:27:36 GMT; path=/; domain=.swapi.co; HttpOnly; Secure
< Vary: Accept, Cookie
< Etag: "145c70f4eca80b4752674d42e5bf1bcf"
< X-Frame-Options: SAMEORIGIN
< Allow: GET, HEAD, OPTIONS
< Via: 1.1 vegur
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 41c66c22cd57a845-CDG
<
* Connection #0 to host 10.35.3.109 left intact
{"name":"Luke Skywalker","height":"172","mass":"77","hair_color":"blond","skin_color":"fair","eye_color":"blue","birth_year":"19BBY","gender":"male","homeworld":"https://swapi.co/api/planets/1/","films":["https://swapi.co/api/films/2/","https://swapi.co/api/films/6/","https://swapi.co/api/films/3/","https://swapi.co/api/films/1/","https://swapi.co/api/films/7/"],"species":["https://swapi.co/api/species/1/"],"vehicles":["https://swapi.co/api/vehicles/14/","https://swapi.co/api/vehicles/30/"],"starships":["https://swapi.co/api/starships/12/","https://swapi.co/api/starships/22/"],"created":"2014-12-09T13:50:51.644000Z","edited":"2014-12-20T21:17:56.891000Z","url":"https://swapi.co/api/people/1/"}

**Comment by brasseld** [comment]
Hi @NFortun 

Gravitee.io 1.15 was based on Oracle JDK. For a better SSL support, it may requires to install JCE (https://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html).

Since Gravitee.io 1.19 we have moved to OpenJDK in our Docker images. So there are high chance that this issue has been resolved implicitly.
