### ISSUE TITLE
Unable to start the AM Gateway

### ISSUE THREAD

**Issue by bielesibub** [gravitee-io/issues#1272]
Hi there,

Love the idea of this, sadly I'm unable to run the AM Gateway.

I downloaded the standalone gateway - 1.6.2, extracted the zip file, updated ./config/gravitee.yml to point to my mongo instance, ran ./bin/gravitee 

I'm running Ubuntu 18.04 LTS (GNU/Linux 4.15.0-22-generic x86_64)

I get the following error:

=========================================================================

  Gravitee.io - Access Management - Gateway

  GRAVITEE_HOME: /home/xxxx/gravitee-am-gateway-standalone-1.6.2

  GRAVITEE_OPTS: 

  JAVA: /usr/lib/jvm/java-11-openjdk-amd64/bin/java

  JAVA_OPTS:  -Djava.net.preferIPv4Stack=true -Xms1024m -Xmx1024m -Djava.awt.headless=true -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8

  CLASSPATH: /home/xxxx/gravitee-am-gateway-standalone-1.6.2/lib/gravitee-am-gateway-standalone-bootstrap-1.6.2.jar

=========================================================================
16:18:05.386 [gravitee] [] INFO  i.g.am.gateway.container.Container - Initializing Gravitee.io Access Management Gateway context...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/home/xxxx/gravitee-am-gateway-standalone-1.6.2/lib/ext/spring-core-4.3.3.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
16:18:06.313 [gravitee] [] INFO  i.g.a.g.s.PropertiesConfiguration - Loading configuration.
16:18:06.323 [gravitee] [] INFO  i.g.a.g.s.PropertiesConfiguration - 	Configuration loaded from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/config/gravitee.yml
16:18:06.415 [gravitee] [] INFO  i.g.a.g.s.PropertiesConfiguration - Loading configuration. DONE
16:18:06.436 [gravitee] [] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - Loading plugin handlers
16:18:06.442 [gravitee] [] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - Find 5 plugin handler(s):
16:18:06.443 [gravitee] [] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - 	io.gravitee.am.gateway.services.plugins.ServicePluginHandler
16:18:06.445 [gravitee] [] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - 	io.gravitee.am.gateway.extensiongrant.plugin.ExtensionGrantPluginHandler
16:18:06.446 [gravitee] [] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - 	io.gravitee.am.gateway.certificate.plugin.CertificatePluginHandler
16:18:06.447 [gravitee] [] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - 	io.gravitee.am.gateway.idp.plugin.IdentityProviderPluginHandler
16:18:06.448 [gravitee] [] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - 	io.gravitee.am.gateway.repository.plugin.RepositoryPluginHandler
16:18:07.217 [gravitee] [] INFO  i.g.a.g.r.p.RepositoryPluginHandler - Loading repository for scope MANAGEMENT: mongodb
16:18:07.218 [gravitee] [] INFO  i.g.a.g.r.p.RepositoryPluginHandler - Loading repository for scope OAUTH2: mongodb
16:18:07.324 [gravitee] [] INFO  org.eclipse.jetty.util.log - Logging initialized @2696ms
16:18:07.555 [gravitee] [] INFO  i.g.am.gateway.container.Container - Start Gravitee.io Access Management Gateway...
16:18:07.555 [gravitee] [] INFO  i.g.am.gateway.node.GatewayNode - Gravitee.io - Access Management - Gateway is now starting...
16:18:07.557 [gravitee] [] INFO  i.g.am.gateway.node.GatewayNode - 	Starting component: PluginEventListener
16:18:07.558 [gravitee] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.plugin.core.internal.PluginEventListener
16:18:07.559 [gravitee] [] INFO  i.g.c.event.impl.EventManagerImpl - Register new listener PluginEventListener for event type class io.gravitee.plugin.core.api.PluginEvent
16:18:07.560 [gravitee] [] INFO  i.g.am.gateway.node.GatewayNode - 	Starting component: PluginRegistry
16:18:07.561 [gravitee] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.plugin.core.internal.PluginRegistryImpl
16:18:07.567 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Initializing plugin registry.
16:18:07.567 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugins from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins
16:18:07.570 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/gravitee-am-identityprovider-oauth2-generic-1.6.2.zip
16:18:07.678 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/.work/gravitee-am-identityprovider-oauth2-generic-1.6.2/gravitee-am-identityprovider-oauth2-generic-1.6.2.jar
16:18:07.684 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/gravitee-am-extensiongrant-jwtbearer-1.6.2.zip
16:18:07.698 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/.work/gravitee-am-extensiongrant-jwtbearer-1.6.2/gravitee-am-extensiongrant-jwtbearer-1.6.2.jar
16:18:07.702 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/gravitee-am-gateway-services-sync-1.6.2.zip
16:18:07.711 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/.work/gravitee-am-gateway-services-sync-1.6.2/gravitee-am-gateway-services-sync-1.6.2.jar
16:18:07.720 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/gravitee-am-certificate-javakeystore-1.6.2.zip
16:18:07.732 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/.work/gravitee-am-certificate-javakeystore-1.6.2/gravitee-am-certificate-javakeystore-1.6.2.jar
16:18:07.735 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/gravitee-am-identityprovider-ldap-1.6.2.zip
16:18:07.811 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/.work/gravitee-am-identityprovider-ldap-1.6.2/gravitee-am-identityprovider-ldap-1.6.2.jar
16:18:07.813 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/gravitee-am-identityprovider-inline-1.6.2.zip
16:18:07.821 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/.work/gravitee-am-identityprovider-inline-1.6.2/gravitee-am-identityprovider-inline-1.6.2.jar
16:18:07.822 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/gravitee-am-repository-mongodb-1.6.2.zip
16:18:07.851 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/.work/gravitee-am-repository-mongodb-1.6.2/gravitee-am-repository-mongodb-1.6.2.jar
16:18:07.854 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/gravitee-am-identityprovider-mongo-1.6.2.zip
16:18:07.891 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/.work/gravitee-am-identityprovider-mongo-1.6.2/gravitee-am-identityprovider-mongo-1.6.2.jar
16:18:07.897 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/gravitee-am-identityprovider-github-1.6.2.zip
16:18:07.917 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/xxxx/gravitee-am-gateway-standalone-1.6.2/plugins/.work/gravitee-am-identityprovider-github-1.6.2/gravitee-am-identityprovider-github-1.6.2.jar
16:18:07.920 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available policy: 
16:18:07.922 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available reporter: 
16:18:07.923 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available service: 
16:18:07.924 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - 	> sync-service [1.6.2] has been loaded
16:18:07.924 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available repository: 
16:18:07.924 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - 	> repository-am-mongodb [1.6.2] has been loaded
16:18:07.925 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available identity_provider: 
16:18:07.925 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - 	> oauth2-generic-am-idp [1.6.2] has been loaded
16:18:07.926 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - 	> ldap-am-idp [1.6.2] has been loaded
16:18:07.926 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - 	> inline-am-idp [1.6.2] has been loaded
16:18:07.927 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - 	> mongo-am-idp [1.6.2] has been loaded
16:18:07.927 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - 	> github-am-idp [1.6.2] has been loaded
16:18:07.928 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available resource: 
16:18:07.929 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available fetcher: 
16:18:07.933 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available certificate: 
16:18:07.934 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - 	> javakeystore-am-certificate [1.6.2] has been loaded
16:18:07.934 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available extension_grant: 
16:18:07.938 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - 	> jwtbearer-am-extension-grant [1.6.2] has been loaded
16:18:07.938 [gravitee] [] INFO  i.g.p.c.internal.PluginEventListener - All plugins have been loaded. Installing...
16:18:07.938 [gravitee] [] INFO  i.g.p.c.internal.PluginEventListener - Installing REPOSITORY plugins...
16:18:07.942 [gravitee] [] INFO  i.g.a.g.r.p.RepositoryPluginHandler - Register a new repository: repository-am-mongodb [io.gravitee.am.repository.mongodb.MongoRepository]
16:18:09.511 [gravitee] [] INFO  i.g.p.c.internal.PluginEventListener - Installing IDENTITY_PROVIDER plugins...
16:18:09.512 [gravitee] [] INFO  i.g.a.g.i.p.IdentityProviderPluginHandler - Register a new identity provider plugin: ldap-am-idp [io.gravitee.am.identityprovider.ldap.LdapIdentityProvider]
16:18:09.520 [gravitee] [] INFO  i.g.a.g.i.p.IdentityProviderPluginHandler - Register a new identity provider plugin: oauth2-generic-am-idp [io.gravitee.am.identityprovider.oauth2.OAuth2GenericIdentityProvider]
16:18:09.525 [gravitee] [] INFO  i.g.a.g.i.p.IdentityProviderPluginHandler - Register a new identity provider plugin: mongo-am-idp [io.gravitee.am.identityprovider.mongo.MongoIdentityProvider]
16:18:09.526 [gravitee] [] INFO  i.g.a.g.i.p.IdentityProviderPluginHandler - Register a new identity provider plugin: inline-am-idp [io.gravitee.am.identityprovider.inline.InlineIdentityProvider]
16:18:09.527 [gravitee] [] INFO  i.g.a.g.i.p.IdentityProviderPluginHandler - Register a new identity provider plugin: github-am-idp [io.gravitee.am.identityprovider.github.GithubIdentityProvider]
16:18:09.537 [gravitee] [] INFO  i.g.p.c.internal.PluginEventListener - Installing RESOURCE plugins...
16:18:09.537 [gravitee] [] INFO  i.g.p.c.internal.PluginEventListener - Installing POLICY plugins...
16:18:09.537 [gravitee] [] INFO  i.g.p.c.internal.PluginEventListener - Installing SERVICE plugins...
16:18:09.538 [gravitee] [] INFO  i.g.a.g.s.p.ServicePluginHandler - Register a new service: sync-service [io.gravitee.am.gateway.services.sync.ScheduledSyncService]
16:18:09.733 [gravitee] [] INFO  i.g.p.c.internal.PluginEventListener - Installing REPORTER plugins...
16:18:09.733 [gravitee] [] INFO  i.g.p.c.internal.PluginEventListener - Installing FETCHER plugins...
16:18:09.744 [gravitee] [] INFO  i.g.p.c.internal.PluginEventListener - Installing CERTIFICATE plugins...
16:18:09.745 [gravitee] [] INFO  i.g.a.g.c.p.CertificatePluginHandler - Register a new certificate plugin: javakeystore-am-certificate [io.gravitee.am.certificate.javakeystore.JavaKeyStore]
16:18:09.746 [gravitee] [] INFO  i.g.p.c.internal.PluginEventListener - Installing EXTENSION_GRANT plugins...
16:18:09.749 [gravitee] [] INFO  i.g.a.g.e.p.ExtensionGrantPluginHandler - Register a new extension grant plugin: jwtbearer-am-extension-grant [io.gravitee.am.extensiongrant.jwtbearer.JwtBearerExtensionGrant]
16:18:09.749 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Plugins have been loaded and installed.
16:18:09.750 [gravitee] [] INFO  i.g.am.gateway.node.GatewayNode - 	Starting component: HttpServer
16:18:09.751 [gravitee] [] INFO  i.g.a.g.core.http.HttpServerFactory - Loading instances for type io.gravitee.am.gateway.core.http.HttpServer
16:18:09.809 [gravitee] [] INFO  i.g.a.g.c.c.ContextFactoryRegistry - Loading instances for type io.gravitee.am.gateway.core.context.ContextFactory
16:18:09.963 [gravitee] [] INFO  org.eclipse.jetty.server.Server - jetty-9.3.14.v20161028
16:18:10.004 [gravitee] [] INFO  o.e.j.server.AbstractNCSARequestLog - Opened /home/xxxx/gravitee-am-gateway-standalone-1.6.2/logs/gravitee_accesslog_2018_05_29.log
16:18:10.563 [gravitee] [] WARN  o.s.s.o.p.t.s.JwtAccessTokenConverter - Unable to create an RSA verifier from verifierKey (ignoreable if using MAC)
16:18:10.677 [gravitee] [] WARN  o.s.w.c.s.AnnotationConfigWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/UnmarshalException
16:18:10.684 [gravitee] [] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/UnmarshalException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1023)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at io.gravitee.am.gateway.handler.management.context.ManagementContextLoaderListener.contextInitialized(ManagementContextLoaderListener.java:35)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at io.gravitee.am.gateway.jetty.handler.security.SecurityDomainHandlerCollection.doStart(SecurityDomainHandlerCollection.java:141)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.gravitee.am.gateway.jetty.JettyHttpServer.doStart(JettyHttpServer.java:64)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.common.node.AbstractNode.doStart(AbstractNode.java:53)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.am.gateway.container.Container.start(Container.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.gravitee.am.gateway.bootstrap.Bootstrap.start(Bootstrap.java:157)
	at io.gravitee.am.gateway.bootstrap.Bootstrap.main(Bootstrap.java:166)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/UnmarshalException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 49 common frames omitted

Many thanks in advance,

**Comment by tcompiegne** [comment]
Hi @bielesibub,

Can you try with a JDK 8 ?

JDK 9 has done some changes for java.xml.bind and other java EE modules.

https://docs.oracle.com/javase/9/docs/api/java.xml.bind-summary.html

Regards

**Comment by bielesibub** [comment]
Thanks for your quick response. I installed Oracle JDK 8 and it looks like the AM Gateway has started. I get the following response when trying to hit it via CURL:

{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

Thanks again, I'm sure I'll be back :)
