### ISSUE TITLE
Error while runnig Docker compose

### ISSUE THREAD

**Issue by sofGitAdmin** [gravitee-io/issues#1274]
I'm trying to run Gravity docker compose , but i encounter this error every time : 

```
 java.net.UnknownHostException: failed to resolve 'demo-elasticsearch' after 2 queries
local_gateway_1        |        at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:721)
local_gateway_1        |        at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:663)
local_gateway_1        |        at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:306)
local_gateway_1        |        at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:295)
local_gateway_1        |        at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:636)
local_gateway_1        |        at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:342)
local_gateway_1        |        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
local_gateway_1        |        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
local_gateway_1        |        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
local_gateway_1        |        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
local_gateway_1        |        at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:197)
local_gateway_1        |        at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:180)
local_gateway_1        |        at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:965)
local_gateway_1        |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
local_gateway_1        |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
local_gateway_1        |        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
local_gateway_1        |        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
local_gateway_1        |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
local_gateway_1        |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
local_gateway_1        |        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
local_gateway_1        |        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
local_gateway_1        |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
local_gateway_1        |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
local_gateway_1        |        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
local_gateway_1        |        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
local_gateway_1        |        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
local_gateway_1        |        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
local_gateway_1        |        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
local_gateway_1        |        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
local_gateway_1        |        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
local_gateway_1        |        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
local_gateway_1        |        at java.lang.Thread.run(Thread.java:748)
```

**Comment by NicolasGeraud** [comment]
hi, is your elasticsearch container running ?

**Comment by sofGitAdmin** [comment]
i have checked it ,and it's not runnig .

**Comment by NicolasGeraud** [comment]
try to restart your es container and copy/paste the logs here

**Comment by sofGitAdmin** [comment]
how can i do that if i'm running Gravitee with docker-compose with this commands lines:  

# Download compose files
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/environments/demo/common.yml -o "common.yml"
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/environments/demo/docker-compose-local.yml -o "docker-compose-local.yml"

# (Optional step: pull to ensure that you are running latest images)
$ docker-compose -f docker-compose-local.yml pull

# And run...
$ docker-compose -f docker-compose-local.yml up

**Comment by NicolasGeraud** [comment]
it's not a gravitee problem. The default elasticsearch container cannot start successfuly on your computer.

try this command : 
```
docker run -p 9300:9300 \
           -p 9200:9200 \
           -e "http.host=0.0.0.0" \
           -e "transport.host=0.0.0.0" \
           -e 'xpack.security.enabled=false' \
           -e 'xpack.monitoring.enabled=false' \
           -e 'cluster.name=elasticsearch' \
           --name es5 \
           docker.elastic.co/elasticsearch/elasticsearch:5
```

**Comment by sofGitAdmin** [comment]
i have corrected the problem by adjusting the max virtual memory areas vm.max_map_count , but now i have a problem with the management-api it's unreacheable .

i tried to test it by using curl http://127.0.0.1:8005/management/ , but it returun this 
curl: (56) Recv failure: Connection reset by peer



http://localhost:8005/management
--




http://localhost:8005/management
--

**Comment by NicolasGeraud** [comment]
please, share your management-api container logs

**Comment by brasseld** [comment]
According to the initial comment, there is still an issue with DNS resolution:
`java.net.UnknownHostException: failed to resolve 'demo-elasticsearch' after 2 queries` 

Current workaround is to edit ${gravitee_home}/bin/gravitee to add a new system properties.

This issue will be fixed in the next release 1.17 and the upgrade to Vert.x 3.5.2 (and Netty.io indirectly)

**Comment by aelamrani** [comment]
FYI, i had the same error.

I figured out a way to solve this problem by removing old images and running again docker compose...

**Comment by jantoniucci** [comment]
I created a [PR](https://github.com/gravitee-io/gravitee-docker/pull/28) to add elastic env variables that solves this problem

**Comment by ericalexanderorg** [comment]
Ran into the same issue. Fixed by running **sysctl -w vm.max_map_count=262144** before **docker-compose -f docker-compose-local.yml up**
