### ISSUE TITLE
[management-api] Unable to start Management API

### ISSUE THREAD

**Issue by bielesibub** [gravitee-io/issues#1275]
Sorry, I'm back. I'm so close - I think! I *really* want this to work!

I've got AM side of things up and running using a remote Mongo. I'm serving the webui with NGINX.
On the API side, I've got the GW running, the webui served by NGINX, but I get the following error when trying to run the Management API - 

```
15:54:03.056 [gravitee] ERROR i.g.management.standalone.Container - An unexpected error occurs while starting Gravitee Management API
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [io.gravitee.repository.mongodb.management.internal.model.RolePkMongo]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:313)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:176)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:832)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1224)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.access$200(MappingMongoConverter.java:85)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1170)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getValueInternal(MappingMongoConverter.java:880)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:272)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:239)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:199)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:195)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:85)
	at org.springframework.data.mongodb.core.MongoTemplate$ReadDbObjectCallback.doWith(MongoTemplate.java:2305)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1950)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1768)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1751)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:621)
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:359)
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:513)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:498)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:475)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy85.findAll(Unknown Source)
	at io.gravitee.repository.mongodb.management.MongoRoleRepository.findAll(MongoRoleRepository.java:117)
	at io.gravitee.management.repository.proxy.RoleRepositoryProxy.findAll(RoleRepositoryProxy.java:51)
	at io.gravitee.management.service.impl.RoleServiceImpl.findAll(RoleServiceImpl.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy35.findAll(Unknown Source)
	at io.gravitee.management.service.impl.InitializerServiceImpl.doStart(InitializerServiceImpl.java:85)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.common.node.AbstractNode.doStart(AbstractNode.java:53)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.management.standalone.Container.start(Container.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.gravitee.management.standalone.boostrap.Bootstrap.start(Bootstrap.java:157)
	at io.gravitee.management.standalone.boostrap.Bootstrap.main(Bootstrap.java:166)
```

Many thanks in advance,

**Comment by brasseld** [comment]
We need more information:
- How do you run components (Docker, zip, ...)
- Which version of the JDK
- Which version of Gravitee.io 
- which version of MongoDB
 
May I ask you to share a dump of your MongoDB database ?

Regards,

**Comment by bielesibub** [comment]
Ooops sorry, in my haste I should have referenced my earlier issue. Heres what you asked for:

Ubuntu Ubuntu 18.04 LTS (GNU/Linux 4.15.0-22-generic x86_64)
I'm running from the zip files.
I am using Oracle JDK 8
Gravitee.io v1.6.2
MongoDb db version v3.2.20

I've attached a dump of the gravitee database

Heres a copy of the startup header - 
xxxx:~/gravitee/apiManagement/management$ sudo ./bin/gravitee
=========================================================================

  Gravitee.IO Management Standalone Runtime Bootstrap Environment

  GRAVITEE_HOME: /home/xxxx/gravitee/apiManagement/management

  GRAVITEE_OPTS: 

  JAVA: /usr/bin/java

  JAVA_OPTS:  -Djava.net.preferIPv4Stack=true -Xms1024m -Xmx2048m -Djava.awt.headless=true -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8

  CLASSPATH: /home/xxxx/gravitee/apiManagement/management/lib/gravitee-management-api-standalone-bootstrap-1.16.2.jar

=========================================================================

Many thanks,

[mongoDump.zip](https://github.com/gravitee-io/issues/files/2061976/mongoDump.zip)

**Comment by brasseld** [comment]
Hey @bielesibub,

Did you use Gravitee.io before 1.16.x ?
I mean, did you upgrade from a previous version to the latest ?

Because, IMHO, it seems that your issue is mainly due to bad data in MongoDB.

**Comment by bielesibub** [comment]
v1.16.2 is the first version I've used.

Should I delete the db in Mongo and restart?

**Comment by brasseld** [comment]
Yes, you can have a try since we now have a backup of your data.

**Comment by brasseld** [comment]
Don't forget to restart the management api once done

**Comment by bielesibub** [comment]
I dropped the database and have been able to start the management-api now. I can only think it was caused by me experimenting by adding a couple of Roles into the database before I had even fired up the api management-api.
Thanks again for your support.
