### ISSUE TITLE
Gateway fail to answer calls few seconds after API Start with an unhandled exception

### ISSUE THREAD

**Issue by wpottier** [gravitee-io/issues#1336]
Hi,

Since few days we are facing a problem with our gravitee gateway.
When we start an API, it will respond fine during few seconds and shortly fall to 504 HTTP Error answer.

Our backend API keep responding fine (tested with curl on the gravitee gateway host).

### Expected Behavior
API keep responding fine through the gateway

### Current Behavior
Here is the log we see on the gateway when API responding 504 errors.

```
08:36:04.405 [vert.x-eventloop-thread-1] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Response is closed
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:548)
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:162)
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:53)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.gravitee.common.http.HttpHeaders.forEach(HttpHeaders.java:389)
	at io.gravitee.gateway.standalone.vertx.VertxHttpServerResponse.writeHeaders(VertxHttpServerResponse.java:105)
	at io.gravitee.gateway.standalone.vertx.VertxHttpServerResponse.end(VertxHttpServerResponse.java:97)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.lambda$null$9(ApiReactorHandler.java:202)
	at io.gravitee.gateway.api.stream.SimpleReadWriteStream.end(SimpleReadWriteStream.java:53)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.lambda$null$12(ApiReactorHandler.java:215)
	at io.gravitee.gateway.http.client.vertx.VertxProxyResponse.resume(VertxProxyResponse.java:91)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleProxyResponse(ApiReactorHandler.java:228)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.lambda$null$1(ApiReactorHandler.java:153)
	at io.gravitee.gateway.http.client.vertx.VertxProxyConnection.handleResponse(VertxProxyConnection.java:83)
	at io.gravitee.gateway.http.client.vertx.VertxHttpClient.lambda$request$3(VertxHttpClient.java:154)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:130)
	at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:50)
	at io.vertx.core.http.impl.HttpClientRequestBase.timeout(HttpClientRequestBase.java:179)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleTimeout(HttpClientRequestBase.java:162)
	at io.vertx.core.http.impl.HttpClientRequestBase.lambda$setTimeout$0(HttpClientRequestBase.java:115)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

We have try to turn on or off all endpoints options in gravitee (keepalive, pipeline,...) without impact on the behavior.

### Your Environment
Gravitee 1.17.0 build as docker image on Alpine distribution
Kubernetes 1.10.4 hosted on GCP cluster
API & Gateway is behind own Nginx server.

**Comment by brasseld** [comment]
Hi @wpottier 

Can you provide a json export of your api ?

**Comment by wpottier** [comment]
@brasseld you want a JSON (like http://jsonapi.org/) describing my API or a sample response of this API?

**Comment by brasseld** [comment]
There is an export feature in gravitee. From the API, MAin screen, there is an export button.

**Comment by wpottier** [comment]
Oh yes :)
Here it is
[Tython-Editorial-1-0.json.zip](https://github.com/gravitee-io/issues/files/2127101/Tython-Editorial-1-0.json.zip)

**Comment by brasseld** [comment]
Ok, it is a very simple API...

Is there any RP between the gateway and the backend API?

**Comment by wpottier** [comment]
Yes, we use an nginx ingress controller in front ok our docker pods.
Our stack look like this : 

Inbound Web -> Nginx Ingress -> Gravitee Gateway -> | -> Nginx Ingress -> Nginx Pod -> PHP FastCGI serving API

(The part left and right parts are 2 kubernetes cluster hosted in GCP)

**Comment by wpottier** [comment]
Some news... the error disappear without any change during the week-end and everything works fine now...

**Comment by brasseld** [comment]
Hey great news (for us) @wpottier 

Doing nothing is the best thing we are doing ;)
