### ISSUE TITLE
No plugin registry configured

### ISSUE THREAD

**Issue by LGouellec** [gravitee-io/issues#1356]
No plugin registry configured exception

### Context
In my environnement i have a mongo db and elastic search db. It's been good configuration.
But, when i launch gravitee gateway batch, i have this exception : 

java.lang.RuntimeException: No plugin registry configured.
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:92)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.common.node.AbstractNode.doStart(AbstractNode.java:53)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.gateway.standalone.Container.start(Container.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:162)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)

### Environment
* Version used: 1.17.0
* Browser Name and version: Firefox
* Operating System and version: Windows 7

**Comment by NicolasGeraud** [comment]
please provide a full gravitee.log

**Comment by LGouellec** [comment]
[gravitee.log](https://github.com/gravitee-io/issues/files/2158173/gravitee.log)
Please found in attachment the full log of gravitee

**Comment by brasseld** [comment]
Fixed by downgrading to JDK 8.
