### ISSUE TITLE
Authentication in Gateway

### ISSUE THREAD

**Issue by sunilb20** [gravitee-io/issues#1389]
I understand that API's in gateway can be secured using API Key, Oauth2 policies(per api), But I am not getting the understanding of the below configuration for basic auth.

Even documentation doesnt say much about this config.

services:
  core:
    http:
      enabled: true
      port: 18082
      host: localhost
      authentication:
        # authentication type to be used for the core services
        # - none : to disable authentication
        # - basic : to use basic authentication
        # default is "basic"
        type: basic
        users:
          admin: adminadmin

**Comment by brasseld** [comment]
Hi @sunilb20 

Can you tell what do you want to achieve exactly ?

**Comment by sunilb20** [comment]
Basic Auth + SSL -> First level Security

**Comment by sunilb20** [comment]
And what is the above configuration for ?

**Comment by sunilb20** [comment]
Its present and there was no change in gravitee script.

# Execute the JVM in the foreground
daemon=`echo $* | egrep -- '(^-d |-d$| -d |--daemon$|--daemon )'`
if [ -z "$daemon" ] ; then
	exec "$JAVA" $JAVA_OPTS \
        -javaagent:$GRAVITEE_HOME/boot/jetty-alpn-agent-2.0.7.jar \
        -Dvertx.disableFileCaching=true \
        -Dvertx.disableFileCPResolving=true \
        -Dvertx.disableContextTiming=true \
        -Dvertx.disableWebsockets=true \
        -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory \
        -cp "$GRAVITEE_BOOT_CLASSPATH" \
        $GRAVITEE_OPTS \
        io.gravitee.gateway.standalone.boostrap.Bootstrap \
        "$@"

**Comment by brasseld** [comment]
Sorry but, according to what I'm seeing in the stack trace:

```
Caused by: java.nio.file.AccessDeniedException: E:\Softwares\gateways\gravitee\graviteeio-full-1.16.3\graviteeio-gateway-1.16.3\bin.vertx\file-cache-0a6b1f8f-78cb-468e-a569-bd7d48e862ca
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
```

You are running Gravitee on a windows platform... and according to the bat file, these properties are not settled: https://github.com/gravitee-io/gravitee-gateway/blob/master/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/bin/gravitee.bat#L71

So I don't know from where you took properties in your previous comment.

**Comment by sunilb20** [comment]
There are 2 files in bin folder : 
1. gravitee 
2. gravitee.bat

The above confs are mentioned in gravitee and I am running the gateway using gravitee command instead of gravitee.bat

**Comment by brasseld** [comment]
My question was: are you running Gravitee on Windows ?
If yes, you are probably running the bat file, and not the other one (which should be used for Linux platforms).

**Comment by sunilb20** [comment]
Yes I am running Gravitee in Windows. But I am specifically typing/triggering gravitee command not the gravitee.bat.
Here is the maximum logs I could collect : 

[gravitee.log](https://github.com/gravitee-io/issues/files/2200751/gravitee.log)

**Comment by brasseld** [comment]
You should not have this exception is Vert.x cache is really disabled, so it means clearly that the system properties `-Dvertx.disableFileCaching=true` is not properly settled.

**Comment by sunilb20** [comment]
Agree and I have copied this property to gravitee.bat and Server starts well. 
There are 2 issues : 
1. Why do I have to do this manual step for Windows ?
2. Server stops with an error. ps : SSL is configured
Here are the relevant logs: 

16:20:20.305 [gravitee] [] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'reactor'
16:20:20.305 [gravitee] [] DEBUG o.s.b.f.annotation.InjectionMetadata - Processing injected element of bean 'graviteeVerticle': AutowiredFieldElement for private io.gravitee.gateway.standalone.vertx.VertxHttpServerConfiguration io.gravitee.gateway.standalone.vertx.GraviteeVerticle.httpServerConfiguration
16:20:20.305 [gravitee] [] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'httpServerConfiguration'
16:20:20.305 [gravitee] [] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Finished creating instance of bean 'graviteeVerticle'
16:20:20.311 [gravitee] [] INFO  i.g.g.standalone.node.GatewayNode - Gravitee.io - Gateway id[b999bf1d-f913-4572-99bf-1df913957223] version[1.16.3] pid[348] build[318#ca142dd548d7dffd9e5c62231190dbc42df310bc] jvm[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/25.66-b18] started in 12827 ms.
16:20:20.323 [vert.x-eventloop-thread-3] [] ERROR i.g.g.s.vertx.VertxEmbeddedContainer - Unable to start HTTP server
io.vertx.core.VertxException: java.lang.NullPointerException
        at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:455)
        at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:482)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:254)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:212)
        at io.gravitee.gateway.standalone.vertx.GraviteeVerticle.start(GraviteeVerticle.java:52)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
        at io.vertx.core.impl.FileResolver.unpackFromFileURL(FileResolver.java:149)
        at io.vertx.core.impl.FileResolver.unpackFromFileURL(FileResolver.java:173)
        at io.vertx.core.impl.FileResolver.resolveFile(FileResolver.java:130)
        at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:776)
        at io.vertx.core.net.impl.KeyStoreHelper.lambda$create$0(KeyStoreHelper.java:77)
        at io.vertx.core.net.impl.KeyStoreHelper.loadJKSOrPKCS12(KeyStoreHelper.java:268)
        at io.vertx.core.net.impl.KeyStoreHelper.create(KeyStoreHelper.java:83)
        at io.vertx.core.net.impl.KeyStoreHelper.create(KeyStoreHelper.java:115)
        at io.vertx.core.net.TrustOptions.getTrustManagerFactory(TrustOptions.java:43)
        at io.vertx.core.net.impl.SSLHelper.getTrustMgrFactory(SSLHelper.java:322)
        at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:453)
        ... 12 common frames omitted
16:20:20.341 [gravitee-finalizer] [] INFO  i.g.gateway.standalone.Container - Shutting-down Gravitee Gateway...
16:20:20.341 [gravitee-finalizer] [] INFO  i.g.g.standalone.node.GatewayNode - Gravitee.io - Gateway is stopping
16:20:20.342 [gravitee-finalizer] [] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'container'
16:20:20.342 [gravitee-finalizer] [] INFO  i.g.g.standalone.node.GatewayNode -  Stopping component: VertxEmbeddedContainer
16:20:20.342 [gravitee-finalizer] [] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'reporterService'

**Comment by brasseld** [comment]
```
Caused by: java.lang.NullPointerException: null
at io.vertx.core.impl.FileResolver.unpackFromFileURL(FileResolver.java:149)
```

I suppose this is because of a bad configuration for ssl keystore in `gravitee.yml`...

**Comment by brasseld** [comment]
Hi @sunilb20 

Any news about this ticket ?

**Comment by sunilb20** [comment]
I have configured the below in gravitee yml. I dont think something is wrong here. Still getting the above error.

# Gateway HTTP server
http:
  port: 8082
  host: localhost
  idleTimeout: 0
  tcpKeepAlive: true
  compressionSupported: false
  instances: 0
  secured: true
  alpn: false
  ssl:
    clientAuth: false
    keystore:
      path: ${gravitee.home}/keystores_and_certs/server-keystore.jks
      #path: E:/Softwares/gateways/gravitee/graviteeio-full-1.16.3/keystores_and_certs/server-keystore.jks
      password: secret
    truststore:
      path: 
      password:

**Comment by brasseld** [comment]
Thanks for your feedback @sunilb20 

About your queries:
1) you can update the documentation and provide a PR ?
2) most of our users are using a Unix platform, but a PR is welcomed to update system properties for windows platforms
3) I don't understand why you need basic auth on Jetty container. Jetty is only used for management-api, not the api gateway itself. The configuration mentioned above is for the internal technical API. We are currently working on the documentation of the technical API. Will keep you in touch as soon as this doc is published.

**Comment by sunilb20** [comment]
Okay Agreed for first 2 points. I am exploring this on Windows and will be deploying the solution on Unix later.

Regarding point 3, What I meant was gateway http server. so in context to that, is there any basic authentication designed ? or API key can be assumed as basic auth alternative for gateways?

Also I need to know the usage of the configuration mentioned in the top of this issues.

**Comment by brasseld** [comment]
About point 3), there is a basic authentication policy, but for the moment, you aren't able to associate basic authentication to a plan.

**Comment by sunilb20** [comment]
Any milestones for the policy to make it available ?

**Comment by sunilb20** [comment]
Okay. We can live without basic auth for now. All other issues are fixed as part of this ticket.
