### ISSUE TITLE
NoClassDefFoundError oAuth2Response

### ISSUE THREAD

**Issue by PierrickI3** [gravitee-io/issues#1396]
When I add a new plan with OAuth2, I get this error in the gateway:

```
 08:25:30.009 [sync-1] [64549cb1-2053-4bcb-949c-b12053cbcbab] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - Deploying 1 plan(s) for API 64549cb1-2053-4bcb-949c-b12053cbcbab:
08:25:30.009 [sync-1] [64549cb1-2053-4bcb-949c-b12053cbcbab] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - 	- Free
08:25:30.010 [sync-1] [64549cb1-2053-4bcb-949c-b12053cbcbab] INFO  i.g.g.r.h.i.DefaultReactorHandlerRegistry - Updating handler for Api{id='64549cb1-2053-4bcb-949c-b12053cbcbab', name='System Users API', version='1'}
08:25:30.010 [sync-1] [64549cb1-2053-4bcb-949c-b12053cbcbab] INFO  i.g.g.r.h.i.DefaultReactorHandlerRegistry - Handler was previously map to /api/v1/sysusers/
08:25:30.010 [sync-1] [64549cb1-2053-4bcb-949c-b12053cbcbab] INFO  i.g.g.r.h.i.DefaultReactorHandlerRegistry - Preparing a new handler for Api{id='64549cb1-2053-4bcb-949c-b12053cbcbab', name='System Users API', version='1'}
08:25:30.034 [sync-1] [64549cb1-2053-4bcb-949c-b12053cbcbab] INFO  i.g.g.s.core.SecurityProviderLoader - Loading instances for type io.gravitee.gateway.security.core.AuthenticationHandler
08:25:30.038 [sync-1] [64549cb1-2053-4bcb-949c-b12053cbcbab] INFO  i.g.g.h.a.p.s.PlanBasedAuthenticationHandlerEnhancer - API [System Users API (1)] requires the following security providers:
08:25:30.038 [sync-1] [64549cb1-2053-4bcb-949c-b12053cbcbab] INFO  i.g.g.h.a.p.s.PlanBasedAuthenticationHandlerEnhancer - 	* oauth2
08:25:30.048 [sync-1] [64549cb1-2053-4bcb-949c-b12053cbcbab] INFO  i.g.g.handlers.api.ApiReactorHandler - API handler is now starting, preparing API context...
08:25:30.050 [sync-1] [64549cb1-2053-4bcb-949c-b12053cbcbab] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NoClassDefFoundError: io/gravitee/resource/oauth2/api/OAuth2Response
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.reflections.ReflectionUtils.getMethods(ReflectionUtils.java:84)
	at io.gravitee.plugin.policy.internal.PolicyMethodResolver.resolve(PolicyMethodResolver.java:48)
	at io.gravitee.gateway.policy.impl.DefaultPolicyManager.lambda$initialize$6(DefaultPolicyManager.java:167)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.gravitee.gateway.policy.impl.DefaultPolicyManager.initialize(DefaultPolicyManager.java:131)
	at io.gravitee.gateway.policy.impl.DefaultPolicyManager.doStart(DefaultPolicyManager.java:72)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.doStart(ApiReactorHandler.java:332)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.gateway.reactor.handler.impl.DefaultReactorHandlerRegistry.prepare(DefaultReactorHandlerRegistry.java:61)
	at io.gravitee.gateway.reactor.handler.impl.DefaultReactorHandlerRegistry.update(DefaultReactorHandlerRegistry.java:80)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.onEvent(DefaultReactor.java:116)
	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
	at io.gravitee.gateway.handlers.api.manager.impl.ApiManagerImpl.update(ApiManagerImpl.java:96)
	at io.gravitee.gateway.services.sync.SyncManager.lambda$computeEvents$5(SyncManager.java:167)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.gravitee.gateway.services.sync.SyncManager.computeEvents(SyncManager.java:134)
	at io.gravitee.gateway.services.sync.SyncManager.refresh(SyncManager.java:127)
	at io.gravitee.gateway.services.sync.ScheduledSyncService.run(ScheduledSyncService.java:87)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.gravitee.resource.oauth2.api.OAuth2Response
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 common frames omitted 
```

### Steps to Reproduce
1. Deploy Gravitee in Kubernetes with an integration with Keycloak

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravitee-managementapi
  labels:
    app: gravitee-managementapi
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gravitee-managementapi
  template:
    metadata:
      labels:
        app: gravitee-managementapi
    spec:
      containers:
      - name: gravitee-managementapi
        env:
        - name: GRAVITEE_MANAGEMENT_MONGODB_URI
          value: mongodb://gravitee-mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
        - name: GRAVITEE_RATELIMIT_MONGODB_URI
          value: mongodb://gravitee-mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
        - name: GRAVITEE_ANALYTICS_ELASTICSEARCH_ENDPOINTS_0
          value: http://gravitee-elasticsearch:9200
        - name: GRAVITEE_SECURITY_PROVIDERS_2_TYPE
          value: oauth2
        - name: GRAVITEE_SECURITY_PROVIDERS_2_CLIENTID
          value: gravitee
        - name: GRAVITEE_SECURITY_PROVIDERS_2_CLIENTSECRET
          value: 215021be-0162-40c6-a4a3-d866507f3597
        - name: GRAVITEE_SECURITY_PROVIDERS_2_TOKENENDPOINT
          value: https://keycloak.comply-online.com/auth/realms/master/protocol/openid-connect/token
        - name: GRAVITEE_SECURITY_PROVIDERS_2_TOKENINTROSPECTIONENDPOINT
          value: https://keycloak.comply-online.com/auth/realms/master/protocol/openid-connect/token/introspect
        - name: GRAVITEE_SECURITY_PROVIDERS_2_USERINFOENDPOINT
          value: https://keycloak.comply-online.com/auth/realms/master/protocol/openid-connect/userinfo
        - name: GRAVITEE_SECURITY_PROVIDERS_2_ACCESSTOKENPROPERTY
          value: access_token
        - name: GRAVITEE_SECURITY_PROVIDERS_2_AUTHORIZATIONHEADER
          value: "Bearer %s"
        - name: GRAVITEE_SECURITY_PROVIDERS_2_MAPPING_ID
          value: sub
        - name: GRAVITEE_SECURITY_PROVIDERS_2_MAPPING_EMAIL
          value: email
        - name: GRAVITEE_SECURITY_PROVIDERS_2_MAPPING_LASTNAME
          value: family_name
        - name: GRAVITEE_SECURITY_PROVIDERS_2_MAPPING_FIRSTNAME
          value: given_name
        image: graviteeio/management-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          protocol: TCP
```

2. Create a new API
3. Create a new Plan with oAuth2
4. Deploy and Publish

### Your Environment
* Version used: latest

**Comment by brasseld** [comment]
Hi @PierrickI3,

Did you create an oauth2 resource for your API ?
It is required for oauth2 / jwt plans.

**Comment by PierrickI3** [comment]
I see. I haven't done that indeed. Thanks for the reply.
