### ISSUE TITLE
Gravity:latest Management API - "no null host accepted"

### ISSUE THREAD

**Issue by ipirva** [gravitee-io/issues#1419]
### Expected Behavior

I am running Gravitee:latest with containers and docker stack

### Current Behavior

The containers are started successfully, but I cannot get the UI web page
It says: Management API unreachable or error occurs, please check logs

Checking the Management API logs, it says every 5 seconds:

docker logs c20043a07428
```
00:51:19.887 [RxComputationThreadPool-4] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
java.lang.NullPointerException: no null host accepted
        at java.util.Objects.requireNonNull(Objects.java:228)
        at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:999)
        at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:993)
        at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:519)
        at io.vertx.ext.web.client.impl.HttpContext.sendRequest(HttpContext.java:190)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:113)
        at io.gravitee.elasticsearch.client.http.HttpClient$1.handle(HttpClient.java:134)
        at io.gravitee.elasticsearch.client.http.HttpClient$1.handle(HttpClient.java:122)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:111)
        at io.vertx.ext.web.client.impl.HttpContext.interceptAndSend(HttpContext.java:82)
        at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:224)
        at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:199)
        at io.vertx.reactivex.ext.web.client.HttpRequest.send(HttpRequest.java:485)
        at io.vertx.reactivex.ext.web.client.HttpRequest.lambda$rxSend$10(HttpRequest.java:502)
        at io.vertx.reactivex.core.impl.AsyncResultSingle.subscribeActual(AsyncResultSingle.java:42)
        at io.reactivex.Single.subscribe(Single.java:3096)
        at io.reactivex.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
        at io.reactivex.Single.subscribe(Single.java:3096)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3096)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3096)
        at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:13234)
        at io.reactivex.Flowable.subscribe(Flowable.java:13180)
        at io.reactivex.internal.operators.flowable.FlowableRepeatWhen$WhenReceiver.onNext(FlowableRepeatWhen.java:101)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:282)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:660)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:129)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:68)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:52)
        at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:113)
        at io.reactivex.internal.operators.observable.ObservableDelay$DelayObserver$OnNext.run(ObservableDelay.java:114)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
Thank you for looking into this.

### Your Environment

* Version used: latests
* Browser Name and version: Chrome latest
* Operating System and version: Mac OS latest

**Comment by brasseld** [comment]
Can you tell us how you're running the stack ?
You have followed the documentation? You have used a docker compose ?

**Comment by ipirva** [comment]
I am using docker-composer. In regards to the management-api and elasticsearcg the services look like:

`  gravitee_management-api:
    image: graviteeio/management-api:latest
    deploy:
      placement:
        constraints: [node.hostname==nuke]
      labels:
        traefik.backend: gravitee_management-api
        traefik.docker.network: traefik_net
        traefik.frontend.rule: Host:xxx
        restart: unless-stopped
    environment:
      - gravitee_management_mongodb_uri=mongodb://gravitee_mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5
000
      - gravitee_ratelimit_mongodb_uri=mongodb://gravitee_mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=50
00
      - gravitee_analytics_elasticsearch_endpoints_0=http://gravitee_elasticsearch:9200
    volumes:
      - /data/gravitee_data/logs/gravitee_management-api:/home/gravitee/logs
    depends_on:
      - gravitee_elasticsearch
      - gravitee_mongodb

  gravitee_elasticsearch:
    image: elasticsearch:5.6.3
    #image: elasticsearch:latest
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=gravitee_elasticsearch
    volumes:
      - /data/gravitee_data/gravitee_elasticsearch:/usr/share/elasticsearch/data
      - /data/gravitee_data/logs/gravitee_elasticsearch:/var/log/elasticsearch
`

All the hosts are reachable from within the containers.

**Comment by brasseld** [comment]
Ok I got it.

It's because of the `_` symbol in the elasticsearch URI.

If you change container name for something like gravitee-elasticsearch, it works well.

**Comment by ipirva** [comment]
Thank you - replacing _ with - made the error "no null host accepted" disappear.

There still seems to be a problem somewhere, because now Gravitee management API container says "connection refused":

```
09:45:17.804 [gravitee] INFO  i.g.m.r.p.RepositoryPluginHandler - Register a new repository: repository-elasticsearch [io.gravitee.repository.elasticsearch.ElasticsearchRepository]
09:45:19.781 [vert.x-eventloop-thread-3] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: gravitee-elasticsearch/10.0.0.200:9200
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
        ... 11 common frames omitted
09:45:19.784 [vert.x-eventloop-thread-2] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: gravitee-elasticsearch/10.0.0.200:9200
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
        ... 11 common frames omitted

```

From an Ubuntu container on the same network:

docker exec -ti 8e06a9ee60fc  curl http://gravitee-elasticsearch:9200
{
  "name" : "2uBvcq6",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "v7hQA9f0R1mvw8MtsvumjQ",
  "version" : {
    "number" : "5.6.3",
    "build_hash" : "1a2f265",
    "build_date" : "2017-10-06T20:33:39.012Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}

A reload of the container management API allows it to start without the previous error:

```
09:58:28.636 [gravitee] INFO  i.g.m.r.p.RepositoryPluginHandler - Register a new repository: repository-elasticsearch [io.gravitee.repository.elasticsearch.ElasticsearchRepository]
09:58:29.693 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - Installing IDENTITY_PROVIDER plugins...
09:58:29.694 [gravitee] INFO  i.g.m.i.c.p.IdentityProviderPluginHandler - Register a new identity provider plugin: ldap-idp [io.gravitee.management.idp.ldap.LdapIdentityProvider]
```

but still on the UI I get "Management API unreachable or error occurs, please check logs"

**Comment by ipirva** [comment]
Thank you, DNS resolution problem for the management API endpoint.
Thank you once more for your support!
