### ISSUE TITLE
[policy] [jwt] Signature length not correct: got 128 but was expecting 512 

### ISSUE THREAD

**Issue by DominikSammerLocoso** [gravitee-io/issues#1422]
Trying to add JWT policy to my API. Unfortunally I get ERROR io.gravitee.policy.jwt.JWTPolicy - Unable to verify RSA signature using configured PublicKey. Signature length not correct: got 128 but was expecting 512

### Expected Behavior
A created JWT token can be used to access my API

### Current Behavior
After creating a key at page [](https://jwt.io/) gravitee.io always permits accessing my API.

I have gone through the steps described in https://docs.gravitee.io/apim_policies_jwt.html. What I wanted to achieve is, testing the JWT token policies for a api that is accessible through gravitee. As differrent Github issues explained I generated a key in Windows using ssh-keygen and entered a file default. This procedure created a public and private key in a file stored in .ssh/id_default.

The public key looks like following:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDK+bNXgoqdUL6IEvsXEyiE/FWZHbYW8vbofLEGC7H2WiwVwLX2I9Bww8U6fLnoYSpFg/CR9m7I+WkGBo9Ic967hsrUHzuImU1zJgVQPOS9TqCOq+YJbiWpNiXMZ+zyd63oa7MKHRSxR/1ZAe2gwP+Eoijup3TwU289VAVrC4tii6J+LE/mbW+COga38epvdWmGlfzwbaKsA5LLBnrNO6l8L6z7mNFYVdD7s3CnVDWE+AbqcMVmmjl6RKl+ItMyZbv3RIkT3fY7ZwXm5TYJ0XDnAcquGLaaMcxp+bxDEJomU/JiDRwVOSB02AtXCORGzhQGdtbAV4WWnEuFk2BFnsOwp+TluPAIM3/iGH42cNlmJmYiNSAMujuxAjOlhycxUMjlckaH+zTp7D33BfwOBqckP7PwcL0wbYA4s7KKxgXojqfAcq8wMTEAc7PvlIdmWqABFr+XBYq0jlTBNUfmmgjOFbDg00qKSjBwwfXwzqWmiAMZ2mcQJw8AVPNuiTqD91RpYHGvttN9PF4exMpJGQVk+4o6iL2if2bSUlY7LsbUejBpGkVQORwbwQS6Oe8kgxmgEuzZ/wwPdm2p72aXXR2Eo2e7q4OeOfcmAzO47zGymZdRcefD1R7RNebAE6vJ5o+ppA46Shxh65fvjD633HWU72bEQOaZ282KfDuQ5ZpVrQ== sammer@locoso@LOCDEV04

I entered that into the JSON Web Tokens policy like that:
![capture](https://user-images.githubusercontent.com/41911485/43889163-b1b4578a-9bc3-11e8-805a-0bb0d6c1ccd0.PNG)

If I now access the API with postman I get a 401 exception - that is ok because there is no token set.
That was why I created a token with [](https://jwt.io/). I set the algorithm to RS512 and entered the public as well as the private key. 
But when I use that token I get the following exception:

```
11:05:26.801 [vert.x-eventloop-thread-6] ERROR io.gravitee.policy.jwt.JWTPolicy - Unable to verify RSA signature using configured PublicKey. Signature length not correct: got 128 but was expecting 512
java.security.SignatureException: Signature length not correct: got 128 but was expecting 512
	at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:189)
	at java.security.Signature$Delegate.engineVerify(Signature.java:1219)
	at java.security.Signature.verify(Signature.java:652)
	at io.jsonwebtoken.impl.crypto.RsaSignatureValidator.doVerify(RsaSignatureValidator.java:63)
	at io.jsonwebtoken.impl.crypto.RsaSignatureValidator.isValid(RsaSignatureValidator.java:47)
	at io.jsonwebtoken.impl.crypto.DefaultJwtSignatureValidator.isValid(DefaultJwtSignatureValidator.java:47)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:339)
	at io.gravitee.policy.jwt.JWTPolicy.validateJsonWebToken(JWTPolicy.java:224)
	at io.gravitee.policy.jwt.JWTPolicy.onRequest(JWTPolicy.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:89)
	at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:44)
	at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:44)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:66)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63)
	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
	at io.gravitee.gateway.policy.NoOpPolicyChain.doNext(NoOpPolicyChain.java:41)
	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63)
	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:76)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
	at io.gravitee.policy.keyless.KeylessPolicy.onRequest(KeylessPolicy.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:89)
	at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:44)
	at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:44)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:66)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:202)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:136)
	at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:75)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$0(DefaultReactor.java:81)
	at io.gravitee.gateway.reactor.handler.transaction.TransactionHandler.handle(TransactionHandler.java:57)
	at io.gravitee.gateway.reactor.handler.transaction.TransactionHandler.handle(TransactionHandler.java:28)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:92)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:37)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:27)
	at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:453)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:144)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:666)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:619)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.HttpServerImpl$Http2UpgradeHandler.channelRead(HttpServerImpl.java:968)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Is there something I missed to do?

**Comment by brasseld** [comment]
Sorry but I don't understand how you have generate the jwt token you are using to make call. Can you explain please ?

**Comment by DominikSammerLocoso** [comment]
I tried to generate the jwt token with a tool that is accessible via [](https://jwt.io/). There it is possible to enter the private as well as the public key for RSA encryption.
However I tried to generate the token with the Access Management afterwards since that is also a tool provided by your project.(API http://localhost:8093/admin/token). Unfortunally that also does not work as expected. There I got the same error message.

**Comment by brasseld** [comment]
Ok in that case, please provide the name of the tool you're trying because I'm a bit surprised. Thanks

**Comment by DominikSammerLocoso** [comment]
I am sorry, the tool wasn't in my comment as expected. It is the tool that is mentioned in gravitee.io documentation when you are explaining jwt. (https://jwt.io/)

**Comment by brasseld** [comment]
I'm sorry but I'm not able to reproduce.

Please provide a json export of your API definition, perhaps I've missed something...

**Comment by DominikSammerLocoso** [comment]
Attached there is my api definition.

[NeuerTest123-2.zip](https://github.com/gravitee-io/issues/files/2292973/NeuerTest123-2.zip)

**Comment by DominikSammerLocoso** [comment]
And my configuration looks like that:

[gravitee.zip](https://github.com/gravitee-io/issues/files/2292990/gravitee.zip)

**Comment by tcompiegne** [comment]
Hi @DominikSammerLocoso,

Your public key seems to have some whitespaces after `...Lugd` and `...gCFQs` and `...AK5D`.

Can you remove them and retry ?

Regards

**Comment by DominikSammerLocoso** [comment]
Ok now I get ERROR io.gravitee.policy.jwt.JWTPolicy - signing key cannot be null

**Comment by tcompiegne** [comment]
Can you share your API definition ?

**Comment by DominikSammerLocoso** [comment]
There you are:
[Test-1.zip](https://github.com/gravitee-io/issues/files/2294145/Test-1.zip)

I found out that this error occurs in the JWTPolicy class in method getPublickKeyByPolicySettings when calling givenKey = executionContext.getTemplateEngine().convert(givenKey);. 
The stack outlines: 
Transform given key 0007ssh-rsa MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoHqYNVYWCWLlHTd6UbeY/UoveaEZC6lAbNi75fyPeBI26ct1VlR9scTZvCuj8vKOJl2ETPV9yrl2S40dI7J6Uph9ZQPGeWW+ZyJAQu/P6y8hNdgR4D7+1lhk2dHfQYzbVulm/4DYk5513ozaRBcC/eRGLkMwDGx0ZlLAYAX4u8JsMqZJpI1RsAkQ7NFR53qWmcmtmuHnPRJ0/uNYmt+DpUlX8mXmCjEIcSB3Fbr2F/41VN+tpfN3LF1YPEbI/BIcCG0gc1NLneS4oWmOD9RMwvWyDEiYeWFAoucCcJ0fVRjUb7ErPKn/nKLLh1hnOjDgBXOhDkvzLPtxqb/8/p3PwIDAQAB sammer@locoso@LOCDEV04 using template e


I changed the key definition to 0007ssh-rsa for testing but since that wasn't working I changed it back to ssh-rsa.

**Comment by tcompiegne** [comment]
Does-it work now (by removing 0007) ?

**Comment by DominikSammerLocoso** [comment]
Unfortunately not..

**Comment by tcompiegne** [comment]
What error do you have ?

**Comment by DominikSammerLocoso** [comment]
It's exactly the same as I had before removing 0007

**Comment by tcompiegne** [comment]
Are you sure you sign and verify your JWT token with the same private/public key pair ?

It seems that the token has been signed with another private key ...

**Comment by DominikSammerLocoso** [comment]
Yes I am sure that they have the same private/public key pair.
I don't understand why the JWT token provided by access management can't be used. I get there ERROR io.gravitee.policy.jwt.JWTPolicy - signing key cannot be null.

**Comment by brasseld** [comment]
Which versions of APIM and AM

**Comment by DominikSammerLocoso** [comment]
AM version 2.0.4, APIM version 1.18.1

**Comment by DominikSammerLocoso** [comment]
Ok somehow the error message changed: 
ERROR io.gravitee.policy.jwt.JWTPolicy - SSH key prefix not found

**Comment by brasseld** [comment]
Hi @DominikSammerLocoso 

Why did you close this issue ?
You found the cause ?

**Comment by DominikSammerLocoso** [comment]
Yes, the problem was that I created the JWT private token wrong. 
If you are using windows you can do following steps:
ssh-keygen -h to generate a new key pair

This generates a key pair in C:\Users\user\.ssh -> for example that can be id_rsa.pub + id_rsa.

In the file id_rsa.pub the public key is saved that has the syntax needed for configuration in the policy:
ssh-rsa + some string 

Now it is time to generate a valid token:
The private key can be directly taken from the id_rsa file. The public key must be generated by calling 
C:\Users\user\.ssh\id_rsa.pub -e -m pem.

This will print some string like this:
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAux3Hq3ACvtN/LfgrIXR65TsFk9XXIAEEknUykvP94gMKG/4VRpMk
l0Dww9TKkfbvtwQDTt5bbmZ89vRXHCE8fx8cFBoOedrCxfzvJW8HlXLp/OBOIDsl
qJdt+I01eIjjN4hYpXHFyRZ7egEePmYMDFmErXZvv2orp8lMp92IyM018x7O4CxU
zGJQUDNAx3YNlAm9iuNz1fiHeJKmb7FSjcNcIs0yebYPmbDI2poWJoRE6E4rV2e5
TCvK7+ZQXgr41SHeh/uPeux0V/PahbxhaUjWV+nA4EhpNF39k/AwqrFUjb3AXFOq
UMUpxkfkceCS3YHgtiysUM2WGii1bvkVNwIDAQAB
-----END RSA PUBLIC KEY-----

This public key together with the private key can be taken to generate a valid jwt token.
