### ISSUE TITLE
Unable to access Gravitee access manager

### ISSUE THREAD

**Issue by JiceGi** [gravitee-io/issues#1436]
Hello,

I have installed both the access management gateway & the administration UI but whenever I try to access the login portal I am directly redirected toward this uri
http://localhost:8092/portal/oauth/callback which ends up in a 404

Also when starting gravitee (/bin/gravitee -d -p=_$PathTo$_/am_gio.pid), I get this error:
```
15:57:58.819 [gravitee] [] INFO  i.g.am.gateway.node.GatewayNode - Gravitee.io - Access Management - Gateway id[5f720513-2fac-4dc3-b205-132facedc3d0] version[1.5.2] pid[4398] build[46#${env.GIT_COMMIT}] jvm[Oracle Corporation/OpenJDK 64-Bit Server VM/25.181-b13] started in 3044 ms.
15:58:00.488 [sync-1] [admin] INFO  i.g.a.g.h.o.OAuth2SecurityConfiguration - Loading identity providers to handle user authentication
15:58:00.497 [sync-1] [admin] INFO  i.g.a.g.h.o.s.i.IdentityProviderManagerImpl - Initializing identity providers for domain admin
15:58:00.510 [sync-1] [admin] INFO  i.g.a.g.h.o.s.i.IdentityProviderManagerImpl -       Initializing identity provider: Publishers [http-am-idp]
15:58:00.510 [sync-1] [admin] ERROR i.g.a.g.i.c.i.IdentityProviderPluginManagerImpl - No identity provider is registered for type http-am-idp
15:58:00.511 [sync-1] [admin] WARN  o.s.w.c.s.AnnotationConfigWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.gravitee.am.gateway.handler.oauth2.CustomAuthorizationServerEndpointsConfiguration': Unsatisfied dependency expressed through field 'configurers'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.gravitee.am.gateway.handler.oauth2.AuthorizationServerConfiguration': Unsatisfied dependency expressed through field 'tokenStore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.gravitee.am.gateway.handler.oauth2.OAuth2SecurityConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userAuthenticationProvider': Unsatisfied dependency expressed through field 'identityProviderManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityProviderManager' defined in io.gravitee.am.gateway.handler.oauth2.spring.OAuth2Configuration: Invocation of init method failed; nested exception is java.lang.IllegalStateException: No identity provider is registered for type http-am-idp
15:58:00.514 [sync-1] [admin] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.gravitee.am.gateway.handler.oauth2.CustomAuthorizationServerEndpointsConfiguration': Unsatisfied dependency expressed through field 'configurers'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.gravitee.am.gateway.handler.oauth2.AuthorizationServerConfiguration': Unsatisfied dependency expressed through field 'tokenStore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.gravitee.am.gateway.handler.oauth2.OAuth2SecurityConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userAuthenticationProvider': Unsatisfied dependency expressed through field 'identityProviderManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityProviderManager' defined in io.gravitee.am.gateway.handler.oauth2.spring.OAuth2Configuration: Invocation of init method failed; nested exception is java.lang.IllegalStateException: No identity provider is registered for type http-am-idp
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at io.gravitee.am.gateway.handler.oauth2.context.OAuth2ContextLoaderListener.contextInitialized(OAuth2ContextLoaderListener.java:35)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at io.gravitee.am.gateway.jetty.handler.security.SecurityDomainHandlerCollection.addHandler(SecurityDomainHandlerCollection.java:102)
        at io.gravitee.am.gateway.jetty.handler.security.SecurityDomainHandlerCollection.create(SecurityDomainHandlerCollection.java:79)
        at io.gravitee.am.gateway.jetty.handler.security.SecurityDomainHandlerCollection.onEvent(SecurityDomainHandlerCollection.java:63)
        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
        at io.gravitee.am.gateway.services.sync.SyncManager.lambda$refresh$4(SyncManager.java:86)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at io.gravitee.am.gateway.services.sync.SyncManager.refresh(SyncManager.java:83)
        at io.gravitee.am.gateway.services.sync.ScheduledSyncService.doSync(ScheduledSyncService.java:79)
        at io.gravitee.am.gateway.services.sync.ScheduledSyncService.run(ScheduledSyncService.java:69)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

## Constants.json ##
```
{
  "portalTitle": "Access Management",
  "baseURL": "http://localhost:8083/management",
  "authentication": {
    "oauth2": {
      "authorize": "http://localhost:8092/admin/oauth/authorize",
      "userInfo": "http://localhost:8092/admin/userinfo",
      "clientId": "admin",
      "redirectUri": "http://localhost:8092/portal/oauth/callback",
      "logoutUri": "http://localhost:8092/admin/logout?target_url=http://localhost:8092/portal/logout/callback"
    }
  }
}
```

**Comment by brasseld** [comment]
Hello,

Did you have a look to the documentation?

See: https://docs.gravitee.io/am/2.x/am_installguide_introduction.html
With docker: https://docs.gravitee.io/am/2.x/am_installguide_docker.html#running_am_in_a_single_line

**Comment by JiceGi** [comment]
Hi,
Thank you for your answer.
I actually did.. and a lot too. I tried multiple reinstall too.  (Can't use docker in our environment).
I am debugging the work of an old colleague who left my company.  I'm also pretty new to this.

I will try to reinstall all the components once more carefully following this procedure. And post the results here afterward.

**Comment by brasseld** [comment]
According to the stack trace, it seems that you're trying to use an identity provider: 

`Initializing identity provider: Publishers [http-am-idp]` 

We are not providing this IDP in the default distribution so this one has been probably developed by your old colleague.

**Comment by JiceGi** [comment]
I knew some parts were custom made, now I hope to find the root cause of this.
Thanks for your help.

**Comment by brasseld** [comment]
So, according to the stack trace you've provided in the initial issue, the custom IDP is missing, that's the reason of your issue.

**Comment by JiceGi** [comment]
Yes indeed, now finding why it is failing is my burden ^^.
I think you can close this issue.

Many thanks for your help.
