### ISSUE TITLE
[gateway] No null host accepted

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#1446]
Endpoint is define with a target containing an underscore.

Example: `http://my_api_backend/path/to/api`

```
local_gateway_1        | Caused by: java.lang.NullPointerException: no null host accepted
local_gateway_1        | 	at java.util.Objects.requireNonNull(Objects.java:228)
local_gateway_1        | 	at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:999)
local_gateway_1        | 	at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:993)
local_gateway_1        | 	at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:519)
local_gateway_1        | 	at io.gravitee.gateway.http.client.vertx.VertxHttpClient.request(VertxHttpClient.java:119)
local_gateway_1        | 	at io.gravitee.gateway.core.invoker.DefaultInvoker.invoke(DefaultInvoker.java:89)
local_gateway_1        | 	at io.gravitee.gateway.handlers.api.ApiReactorHandler.lambda$handleClientRequest$6(ApiReactorHandler.java:160)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:65)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
local_gateway_1        | 	at io.gravitee.gateway.policy.NoOpPolicyChain.doNext(NoOpPolicyChain.java:41)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
local_gateway_1        | 	at io.gravitee.gateway.policy.NoOpPolicyChain.doNext(NoOpPolicyChain.java:41)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:76)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
local_gateway_1        | 	at io.gravitee.policy.keyless.KeylessPolicy.onRequest(KeylessPolicy.java:39)
local_gateway_1        | 	... 56 common frames omitted
```

**Comment by brasseld** [comment]
Actually its the RFC952 and RFC1123 which specify the syntax of the hostname. And as per those, underscore is not a valid character in the hostname.

**Comment by mielune** [comment]
Hi @brasseld 

Working with Gravitee APIM 1.26.0

I'm using a docker swarm network to link gateway and backends.
The services names are built like "[stack]_[service]" so the _ is used for the virtual hostname.

---

All the calls from gateway to backend failed with 502.
The endpoint is setup to `http://api-demo-dev_api/demo/1.0`
Portal API's logs trap Consumer request and response by nothing for the Gateway.

---

From the gateway container, I can request the backend like this:
```
curl -v http://api-demo-dev_api/demo/1.0/version
*   Trying 10.0.57.2...
* TCP_NODELAY set
* Connected to api-demo-dev_api (10.0.57.2) port 80 (#0)
> GET /demo/1.0/version HTTP/1.1
> Host: api-demo-dev_api
> User-Agent: curl/7.61.1
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: application/json
< Content-Length: 23
< Server: Werkzeug/0.15.4 Python/3.7.3
< Date: Thu, 23 May 2019 10:04:03 GMT
< 
{"version":"1.0.123"}
* Closing connection 0
```

---

I setup a heltchcheck but the Gateway healthcheck write in logs:
```
10:03:30.039 [vert.x-eventloop-thread-0] [] ERROR i.g.g.s.h.h.HttpEndpointRuleHandler - An unexpected error occurs
java.lang.NullPointerException: no null host accepted
	at java.util.Objects.requireNonNull(Objects.java:228)
	at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:1015)
	at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:1009)
	at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:515)
	at io.gravitee.gateway.services.healthcheck.http.HttpEndpointRuleHandler.handle(HttpEndpointRuleHandler.java:286)
	at io.gravitee.gateway.services.healthcheck.http.HttpEndpointRuleHandler.handle(HttpEndpointRuleHandler.java:66)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:907)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:866)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

---

I tried with the service VIP in the endpoint URL and the Portal API's logs said:
`Host is unreachable: /10.0.57.52:80`
Portal API's logs trap Consumer and Gateway request and response but still 502.


Hope it can help

**Comment by ehinolakingsley** [comment]
I also came had some trouble with this error. I was able to fix it through the management UI. The issue occurred when i didn't append the endpoint target server with either http:// or https://.
![image](https://user-images.githubusercontent.com/11755340/76553847-2a2b9900-646b-11ea-848a-05f31ea549c4.png)

**Comment by gaetanmaisse** [comment]
Closing as per comment about the RFCs: https://github.com/gravitee-io/issues/issues/1446#issuecomment-415672950. Feels free to reopen if needed
