### ISSUE TITLE
[gateway] API Properties : NullPointerException

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#145]
Inside the Dynamic Routing policy, when i make reference to a properties (#properties['xxx']) that does not exist, we have a NullPointerException thrown (see below stacktrace)

```java
17:40:58.877 [vert.x-eventloop-thread-0] [] ERROR i.g.g.policy.impl.RequestPolicyChain - Unexpected error while running policy io.gravitee.gateway.policy.impl.PolicyImpl@9541cb7
java.lang.reflect.InvocationTargetException: null
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:92)
    at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:46)
    at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:40)
    at io.gravitee.gateway.policy.impl.AbstractPolicyChain.doNext(AbstractPolicyChain.java:65)
    at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
    at io.gravitee.policy.dynamicrouting.DynamicRoutingPolicy.onRequest(DynamicRoutingPolicy.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:92)
    at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:46)
    at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:40)
    at io.gravitee.gateway.policy.impl.AbstractPolicyChain.doNext(AbstractPolicyChain.java:65)
    at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
    at io.gravitee.policy.groovy.GroovyPolicy.executeScript(GroovyPolicy.java:108)
    at io.gravitee.policy.groovy.GroovyPolicy.onRequest(GroovyPolicy.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:92)
    at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:46)
    at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:40)
    at io.gravitee.gateway.policy.impl.AbstractPolicyChain.doNext(AbstractPolicyChain.java:65)
    at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
    at io.gravitee.policy.apikey.ApiKeyPolicy.onRequest(ApiKeyPolicy.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:92)
    at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:46)
    at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:40)
    at io.gravitee.gateway.policy.impl.AbstractPolicyChain.doNext(AbstractPolicyChain.java:65)
    at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
    at io.gravitee.gateway.handlers.api.ApiReactorHandler.handle(ApiReactorHandler.java:164)
    at io.gravitee.gateway.reactor.impl.DefaultReactor.process(DefaultReactor.java:72)
    at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handleRequest(VertxReactorHandler.java:39)
    at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:35)
    at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:25)
    at io.vertx.core.http.impl.ServerConnection.handleRequest(ServerConnection.java:286)
    at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:412)
    at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:139)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$createConnAndHandle$1(HttpServerImpl.java:712)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:357)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:234)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.createConnAndHandle(HttpServerImpl.java:706)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:625)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:522)
    at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:76)
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.http1(HttpServerImpl.java:1019)
    at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.channelRead(HttpServerImpl.java:990)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
    at io.gravitee.gateway.http.core.invoker.AbstractHttpInvoker.invoke(AbstractHttpInvoker.java:88)
    at io.gravitee.gateway.handlers.api.ApiReactorHandler.lambda$handle$7(ApiReactorHandler.java:111)
    at io.gravitee.gateway.policy.impl.AbstractPolicyChain.doNext(AbstractPolicyChain.java:74)
    at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
    at com.decathlon.apimgmt.policies.XForwardedForHeadersPolicy.onRequest(XForwardedForHeadersPolicy.java:51)
    ... 80 common frames omitted
```

**Comment by aelamrani** [comment]
Not reproductible on 1.6
