### ISSUE TITLE
[docker] Creating Gravitee images for docker

### ISSUE THREAD

**Issue by girishmanwani** [gravitee-io/issues#1457]
I know their is a demo set of gravitee - ready-made images for docker available.
But my requirement is to build my own set of images after changes/customization such as:

1. Adding custom plugins
2. Adding SSL support

My question is :

1. What are all the images that have to be built for the entire suite.
2. What changes are mandatory requirements for building production ready images.
3. Are there certain Best Practices/Guidelines/Documentation available for the same.

Rgds
Girish

**Comment by brasseld** [comment]
Hi @girishmanwani 

Our docker images are ready for production, we have numbered of users / customers who are using them for a long time.

For both requirements (plugins and SSL), you can make use of environment variable.

Here is an example to add a second folder containing customer plugins:
https://github.com/gravitee-io/breizhcamp-2018-tia/blob/master/docker-compose.yml#L58

Here is an example of a gravitee installation with complete SSL support for both the portal, the management-api and the gateway:
https://github.com/gravitee-io/gravitee-docker/blob/master/platform/docker-compose.yml

**Comment by MiguelTVMS** [comment]
We did exactly what @NicolasGeraud said. and its working fine.

**Comment by NicolasGeraud** [comment]
Cool,
I have to think to a mechanism to help customers to do that.

May we close this issue?

**Comment by girishmanwani** [comment]
I think I am getting a permission issue here 

I am running the following sudo command from the platform folder >>
sudo docker-compose –f docker-compose.yml up

I get the following error:
**gio_platform_elasticsearch | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment**
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.3.1.jar:6
.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch | Caused by: java.lang.IllegalStateException: Failed to create node environment
gio_platform_elasticsearch |    at org.elasticsearch.node.Node.<init>(Node.java:273) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    ... 6 more
gio_platform_elasticsearch | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
gio_platform_elasticsearch |    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
gio_platform_elasticsearch |    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
gio_platform_elasticsearch |    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
gio_platform_elasticsearch |    at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:385) ~[?:?]
gio_platform_elasticsearch |    at java.nio.file.Files.createDirectory(Files.java:682) ~[?:?]
gio_platform_elasticsearch |    at java.nio.file.Files.createAndCheckIsDirectory(Files.java:789) ~[?:?]
gio_platform_elasticsearch |    at java.nio.file.Files.createDirectories(Files.java:775) ~[?:?]
gio_platform_elasticsearch |    at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:203) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.node.Node.<init>(Node.java:270) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.3.1.jar:6.3.1]
gio_platform_elasticsearch |    ... 6 more

**Comment by brasseld** [comment]
Closing this issue for inactivity.
Answer has been provided in comments.
