### ISSUE TITLE
[policy] [api-key] Tried to secure using api-key, but receiving "500 - An error occurs in policy[api-key] "

### ISSUE THREAD

**Issue by create-renegr** [gravitee-io/issues#1885]
Created a new API, secured it with api-key.

### Expected Behavior

It should be possible to pass the api-key (either in header or query param), to access the API

### Current Behavior

it returns a 500. Log says this:

```
An error occurs in policy[api-key] error[io.gravitee.gateway.policy.PolicyChainException: io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:46) at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:74) at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:55) at io.gravitee.gateway.policy.impl.PolicyChain.process(PolicyChain.java:101) at io.gravitee.gateway.core.processor.ProviderProcessorChain.process(ProviderProcessorChain.java:83) at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:139) at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:123) at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:88) at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$0(DefaultReactor.java:81) at io.gravitee.gateway.reactor.handler.transaction.TransactionHandler.handle(TransactionHandler.java:57) at io.gravitee.gateway.reactor.handler.transaction.TransactionHandler.handle(TransactionHandler.java:28) at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:92) at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:42) at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:29) at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:453) at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:144) at io.vertx.core.http.impl.Http1xServerHandler.handleMessage(Http1xServerHandler.java:74) at io.vertx.core.http.impl.Http1xServerHandler.handleMessage(Http1xServerHandler.java:35) at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146) at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195) at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.vertx.core.http.impl.HttpServerImpl$Http2UpgradeHandler.channelRead(HttpServerImpl.java:984) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748) Caused by: io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:96) at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:49) at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:44) ... 45 more Caused by: java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:94) ... 47 more Caused by: java.lang.NoSuchMethodError: io.gravitee.gateway.api.Request.timestamp()Ljava/time/Instant; at io.gravitee.policy.apikey.ApiKeyPolicy.onRequest(ApiKeyPolicy.java:93) ... 52 more ]
```

### Steps to Reproduce (for bugs)

The config is attached:
[mockbin-1-0.zip](https://github.com/gravitee-io/issues/files/2821239/mockbin-1-0.zip)

### Your Environment
* Version used: gateway 1.22.0 
* Browser Name and version: curl
* Operating System and version: linux, current manjaro; testing with docker-compose example from docs

**Comment by brasseld** [comment]
Hi @create-renegr 

Which version of the api-key policy are you using ?

**Comment by create-renegr** [comment]
Hi @brasseld  1.6.2

**Comment by brasseld** [comment]
Hi @create-renegr 

I just had a try with latest docker-compose.
I've imported your API definition and took a look...

There is one mistake: you've defined an api-key plan and you've also put api-key policy in API's policies. But you don't need to put api-key policy by yourself since it's implicit because of the plan's security type.

I would advice you to remove the api-key policy and have a try.

Regards,

**Comment by create-renegr** [comment]
@brasseld I know, i tried with, and without. still same result. 500

it returns a 403 when I pass a wrong API key. but using the correct key, returns 500.

**Comment by brasseld** [comment]
Cloned and fixed by https://github.com/gravitee-io/issues/issues/1888
