### ISSUE TITLE
Having two "admins" in database

### ISSUE THREAD

**Issue by create-renegr** [gravitee-io/issues#1925]
### Expected Behavior
I deleted the admin user (memory) after I created one.

The admin users shows up after some time in the admin interface again (can not say, what makes this happen).

But this time it occurs two times.

When I loose my session, I can no longer login, because the Management API fires a HTTP-500:

```
2/15/2019 4:03:13 PMorg.springframework.dao.IncorrectResultSizeDataAccessException: Query { "$java" : Query: { "source" : "memory", "sourceId" : "admin" }, Fields: { }, Sort: { } } returned non unique result.
2/15/2019 4:03:13 PM	at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.oneValue(ExecutableFindOperationSupport.java:145)
2/15/2019 4:03:13 PM	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.lambda$getExecution$4(AbstractMongoQuery.java:124)
2/15/2019 4:03:13 PM	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:97)
2/15/2019 4:03:13 PM	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:590)
2/15/2019 4:03:13 PM	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
2/15/2019 4:03:13 PM	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
2/15/2019 4:03:13 PM	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
2/15/2019 4:03:13 PM	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
2/15/2019 4:03:13 PM	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
2/15/2019 4:03:13 PM	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
2/15/2019 4:03:13 PM	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
2/15/2019 4:03:13 PM	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
2/15/2019 4:03:13 PM	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
```

### Your Environment
* Version used: latest v1.22.0
* Browser Name and version: Chrome (latest)
* Operating System and version: Linux

**Comment by brasseld** [comment]
Did you move from 1.20 to 1.22 or something like this quite recently?

**Comment by create-renegr** [comment]
Nope. It was a fresh install today. But what I did, that I started with nightly docker image, and switched a few minutes later, back to "latest".

May this be the source of the problem? 

Would it help to start with a fresh database?

**Comment by brasseld** [comment]
Yes, it would help.

**Comment by create-renegr** [comment]
It did help. closing, because it is fixed.
