### ISSUE TITLE
[scim] org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class io.gravitee.am.gateway.handler.scim.model.Attribute

### ISSUE THREAD

**Issue by caraquista-rokk3r** [gravitee-io/issues#1953]
Hello everybody!!

I am trying to register my user with SCIM but throw this error:

```
gio_am_gateway | 16:23:14.050 [Thread-6] [] ERROR i.g.a.g.h.scim.impl.UserServiceImpl - An error occurs while trying to create a user
gio_am_gateway | org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class io.gravitee.am.gateway.handler.scim.model.Attribute.
gio_am_nginx  | 172.24.0.1 - - [20/Feb/2019:16:23:14 +0000] "POST /am/test-local/scim/Users HTTP/1.1" 500 149 "-" "PostmanRuntime/7.6.0"
gio_am_gateway | 	at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
gio_am_gateway | 	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
gio_am_gateway | 	at org.bson.codecs.configuration.ChildCodecRegistry.get(ChildCodecRegistry.java:51)
gio_am_gateway | 	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:184)
gio_am_gateway | 	at org.bson.codecs.DocumentCodec.writeIterable(DocumentCodec.java:207)
gio_am_gateway | 	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:180)
gio_am_gateway | 	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:199)
gio_am_gateway | 	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:141)
gio_am_gateway | 	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
gio_am_gateway | 	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
gio_am_gateway | 	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
gio_am_gateway | 	at com.mongodb.operation.BulkWriteBatch$WriteRequestEncoder.encode(BulkWriteBatch.java:387)
gio_am_gateway | 	at com.mongodb.operation.BulkWriteBatch$WriteRequestEncoder.encode(BulkWriteBatch.java:377)
gio_am_gateway | 	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
gio_am_gateway | 	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
gio_am_gateway | 	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:75)
gio_am_gateway | 	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59)
gio_am_gateway | 	at com.mongodb.internal.connection.BsonWriterHelper.writePayloadArray(BsonWriterHelper.java:51)
gio_am_gateway | 	at com.mongodb.internal.connection.SplittablePayloadBsonWriter.writeEndDocument(SplittablePayloadBsonWriter.java:51)
gio_am_gateway | 	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:118)
gio_am_gateway | 	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:41)
gio_am_gateway | 	at com.mongodb.internal.connection.CommandMessage.addDocumentWithPayload(CommandMessage.java:179)
gio_am_gateway | 	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:163)
gio_am_gateway | 	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138)
gio_am_gateway | 	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:57)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceiveAsync(InternalStreamConnection.java:319)
gio_am_gateway | 	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceiveAsync(UsageTrackingInternalConnection.java:114)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceiveAsync(DefaultConnectionPool.java:455)
gio_am_gateway | 	at com.mongodb.internal.connection.CommandProtocolImpl.executeAsync(CommandProtocolImpl.java:78)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.executeAsync(DefaultServer.java:215)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocolAsync(DefaultServerConnection.java:285)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultServerConnection.commandAsync(DefaultServerConnection.java:156)
gio_am_gateway | 	at com.mongodb.operation.MixedBulkWriteOperation.executeCommandAsync(MixedBulkWriteOperation.java:427)
gio_am_gateway | 	at com.mongodb.operation.MixedBulkWriteOperation.executeBatchesAsync(MixedBulkWriteOperation.java:334)
gio_am_gateway | 	at com.mongodb.operation.MixedBulkWriteOperation.access$900(MixedBulkWriteOperation.java:67)
gio_am_gateway | 	at com.mongodb.operation.MixedBulkWriteOperation$2$1.call(MixedBulkWriteOperation.java:234)
gio_am_gateway | 	at com.mongodb.operation.OperationHelper.validateWriteRequests(OperationHelper.java:177)
gio_am_gateway | 	at com.mongodb.operation.MixedBulkWriteOperation$2.call(MixedBulkWriteOperation.java:217)
gio_am_gateway | 	at com.mongodb.operation.OperationHelper$7.onResult(OperationHelper.java:512)
gio_am_gateway | 	at com.mongodb.operation.OperationHelper$7.onResult(OperationHelper.java:509)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:109)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:98)
gio_am_gateway | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultConnectionPool.openAsync(DefaultConnectionPool.java:192)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultConnectionPool.getAsync(DefaultConnectionPool.java:149)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultServer.getConnectionAsync(DefaultServer.java:98)
gio_am_gateway | 	at com.mongodb.binding.AsyncClusterBinding$AsyncClusterBindingConnectionSource.getConnection(AsyncClusterBinding.java:131)
gio_am_gateway | 	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:509)
gio_am_gateway | 	at com.mongodb.operation.OperationHelper.access$100(OperationHelper.java:63)
gio_am_gateway | 	at com.mongodb.operation.OperationHelper$AsyncCallableWithConnectionAndSourceCallback.onResult(OperationHelper.java:529)
gio_am_gateway | 	at com.mongodb.operation.OperationHelper$AsyncCallableWithConnectionAndSourceCallback.onResult(OperationHelper.java:517)
gio_am_gateway | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
gio_am_gateway | 	at com.mongodb.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:105)
gio_am_gateway | 	at com.mongodb.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:99)
gio_am_gateway | 	at com.mongodb.internal.connection.BaseCluster$ServerSelectionRequest.onResult(BaseCluster.java:433)
gio_am_gateway | 	at com.mongodb.internal.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:297)
gio_am_gateway | 	at com.mongodb.internal.connection.BaseCluster.selectServerAsync(BaseCluster.java:157)
gio_am_gateway | 	at com.mongodb.internal.connection.SingleServerCluster.selectServerAsync(SingleServerCluster.java:41)
gio_am_gateway | 	at com.mongodb.binding.AsyncClusterBinding.getAsyncClusterBindingConnectionSource(AsyncClusterBinding.java:99)
gio_am_gateway | 	at com.mongodb.binding.AsyncClusterBinding.getWriteConnectionSource(AsyncClusterBinding.java:94)
gio_am_gateway | 	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:468)
gio_am_gateway | 	at com.mongodb.operation.MixedBulkWriteOperation.executeAsync(MixedBulkWriteOperation.java:211)
gio_am_gateway | 	at com.mongodb.async.client.OperationExecutorImpl$2.onResult(OperationExecutorImpl.java:112)
gio_am_gateway | 	at com.mongodb.async.client.OperationExecutorImpl$2.onResult(OperationExecutorImpl.java:104)
gio_am_gateway | 	at com.mongodb.async.client.ClientSessionHelper$2.onResult(ClientSessionHelper.java:80)
gio_am_gateway | 	at com.mongodb.async.client.ClientSessionHelper$2.onResult(ClientSessionHelper.java:73)
gio_am_gateway | 	at com.mongodb.internal.connection.BaseCluster$ServerSelectionRequest.onResult(BaseCluster.java:433)
gio_am_gateway | 	at com.mongodb.internal.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:297)
gio_am_gateway | 	at com.mongodb.internal.connection.BaseCluster.selectServerAsync(BaseCluster.java:157)
gio_am_gateway | 	at com.mongodb.internal.connection.SingleServerCluster.selectServerAsync(SingleServerCluster.java:41)
gio_am_gateway | 	at com.mongodb.async.client.ClientSessionHelper.createClientSession(ClientSessionHelper.java:68)
gio_am_gateway | 	at com.mongodb.async.client.ClientSessionHelper.withClientSession(ClientSessionHelper.java:51)
gio_am_gateway | 	at com.mongodb.async.client.OperationExecutorImpl.execute(OperationExecutorImpl.java:104)
gio_am_gateway | 	at com.mongodb.async.client.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1026)
gio_am_gateway | 	at com.mongodb.async.client.MongoCollectionImpl.executeInsertOne(MongoCollectionImpl.java:489)
gio_am_gateway | 	at com.mongodb.async.client.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:472)
gio_am_gateway | 	at com.mongodb.reactivestreams.client.internal.MongoCollectionImpl$8.apply(MongoCollectionImpl.java:426)
gio_am_gateway | 	at com.mongodb.reactivestreams.client.internal.MongoCollectionImpl$8.apply(MongoCollectionImpl.java:423)
gio_am_gateway | 	at com.mongodb.async.client.SingleResultCallbackSubscription.requestInitialData(SingleResultCallbackSubscription.java:38)
gio_am_gateway | 	at com.mongodb.async.client.AbstractSubscription.tryRequestInitialData(AbstractSubscription.java:153)
gio_am_gateway | 	at com.mongodb.async.client.AbstractSubscription.request(AbstractSubscription.java:84)
gio_am_gateway | 	at com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1$1.request(ObservableToPublisher.java:50)
gio_am_gateway | 	at io.reactivex.internal.operators.single.SingleFromPublisher$ToSingleObserver.onSubscribe(SingleFromPublisher.java:60)
gio_am_gateway | 	at com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onSubscribe(ObservableToPublisher.java:39)
gio_am_gateway | 	at com.mongodb.async.client.SingleResultCallbackSubscription.<init>(SingleResultCallbackSubscription.java:33)
gio_am_gateway | 	at com.mongodb.async.client.Observables$2.subscribe(Observables.java:76)
gio_am_gateway | 	at com.mongodb.reactivestreams.client.internal.ObservableToPublisher.subscribe(ObservableToPublisher.java:36)
gio_am_gateway | 	at io.reactivex.internal.operators.single.SingleFromPublisher.subscribeActual(SingleFromPublisher.java:35)
gio_am_gateway | 	at io.reactivex.Single.subscribe(Single.java:3220)
gio_am_gateway | 	at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
gio_am_gateway | 	at io.reactivex.Single.subscribe(Single.java:3220)
gio_am_gateway | 	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
gio_am_gateway | 	at io.reactivex.internal.operators.maybe.MaybeIsEmptySingle$IsEmptyMaybeObserver.onComplete(MaybeIsEmptySingle.java:98)
gio_am_gateway | 	at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onComplete(MaybeMap.java:99)
gio_am_gateway | 	at io.reactivex.internal.operators.observable.ObservableElementAtMaybe$ElementAtObserver.onComplete(ObservableElementAtMaybe.java:103)
gio_am_gateway | 	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onComplete(ObservableFromPublisher.java:46)
gio_am_gateway | 	at com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onComplete(ObservableToPublisher.java:78)
gio_am_gateway | 	at com.mongodb.async.client.AbstractSubscription.onComplete(AbstractSubscription.java:147)
gio_am_gateway | 	at com.mongodb.async.client.AbstractSubscription.processResultsQueue(AbstractSubscription.java:213)
gio_am_gateway | 	at com.mongodb.async.client.AbstractSubscription.tryProcessResultsQueue(AbstractSubscription.java:161)
gio_am_gateway | 	at com.mongodb.async.client.AbstractSubscription.addToQueue(AbstractSubscription.java:112)
gio_am_gateway | 	at com.mongodb.async.client.SingleResultCallbackSubscription$1.onResult(SingleResultCallbackSubscription.java:47)
gio_am_gateway | 	at com.mongodb.async.client.FindIterableImpl$1$1.onResult(FindIterableImpl.java:211)
gio_am_gateway | 	at com.mongodb.async.client.FindIterableImpl$1$1.onResult(FindIterableImpl.java:204)
gio_am_gateway | 	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:141)
gio_am_gateway | 	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:100)
gio_am_gateway | 	at com.mongodb.async.client.FindIterableImpl$1.onResult(FindIterableImpl.java:204)
gio_am_gateway | 	at com.mongodb.async.client.FindIterableImpl$1.onResult(FindIterableImpl.java:198)
gio_am_gateway | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
gio_am_gateway | 	at com.mongodb.async.client.OperationExecutorImpl$1$1.onResult(OperationExecutorImpl.java:82)
gio_am_gateway | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
gio_am_gateway | 	at com.mongodb.operation.FindOperation$3.onResult(FindOperation.java:806)
gio_am_gateway | 	at com.mongodb.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:359)
gio_am_gateway | 	at com.mongodb.operation.CommandOperationHelper$2.onResult(CommandOperationHelper.java:405)
gio_am_gateway | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:227)
gio_am_gateway | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
gio_am_gateway | 	at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:85)
gio_am_gateway | 	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:461)
gio_am_gateway | 	at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:111)
gio_am_gateway | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:379)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:356)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:651)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:618)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:494)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:491)
gio_am_gateway | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:237)
gio_am_gateway | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:220)
gio_am_gateway | 	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
gio_am_gateway | 	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157)
gio_am_gateway | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:553)
gio_am_gateway | 	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:276)
gio_am_gateway | 	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:297)
gio_am_gateway | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream.readAsync(AsynchronousSocketChannelStream.java:132)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:491)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:74)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:608)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:593)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:494)
gio_am_gateway | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:491)
gio_am_gateway | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:237)
gio_am_gateway | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:220)
gio_am_gateway | 	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
gio_am_gateway | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:430)
gio_am_gateway | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
gio_am_gateway | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
gio_am_gateway | 	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
gio_am_gateway | 	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
gio_am_gateway | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
gio_am_gateway | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
gio_am_gateway | 	at java.lang.Thread.run(Thread.java:748) 
```

I am using the docker images 
graviteeio/am-gateway:2
graviteeio/am-management-api:2
graviteeio/am-management-ui:2

My request is:

```
URL: POST http://localhost/am/test-local/scim/Users
Data: {
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User"
  ],
  "id": "123456789",
  "externalId": "123456789",
  "userName": "daniel.diaz+test@test.com",
  "name": {
    "formatted": "Prueba SCIM",
    "familyName": "SCIM",
    "givenName": "prueba",
    "middleName": "prueba"
  },
  "displayName": "Prueba",
  "nickName": "prueba",
  "userType": "user",
  "active": true,
  "password": "trudat",
  "emails": [
    {
      "value": "daniel.diaz+test@test.com",
      "type": "principal",
      "primary": true
    }
  ]
}
```
i didn't find a posible solution.

Please help me :-)

PD: Sorry for my wrong english..

**Comment by tcompiegne** [comment]
It's definitely a bug. Should be fixed for the next release 2.3.0 scheduled for this week.

Thank you for pointing out this issue
