### ISSUE TITLE
[gateway] NPE when no endpoints found for FailoverInvoker

### ISSUE THREAD

**Issue by briankrug** [gravitee-io/issues#1963]
I see the following stack trace in the logs:
```
Feb 22, 2019 9:58:59 AM EST ERROR   [io.vertx.core.impl.ContextImpl] Unhandled exception
java.lang.NullPointerException: null
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:94)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:33)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.lambda$null$4(ApiReactorHandler.java:173)
	at io.gravitee.gateway.core.failover.FailoverRequest.lambda$bodyHandler$0(FailoverRequest.java:55)
	at io.gravitee.gateway.standalone.vertx.VertxHttpServerRequest.lambda$bodyHandler$0(VertxHttpServerRequest.java:178)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleData(HttpServerRequestImpl.java:384)
	at io.vertx.core.http.impl.Http1xServerConnection.handleChunk(Http1xServerConnection.java:307)
	at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:474)
	at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:459)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:144)
	at io.vertx.core.http.impl.Http1xServerHandler.handleMessage(Http1xServerHandler.java:74)
	at io.vertx.core.http.impl.Http1xServerHandler.handleMessage(Http1xServerHandler.java:35)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

This is occurring when the API has no available Endpoints and the client sends body content for the request (such as with a post request). I believe this occurs because first the request headers are processed and when do so an early DirectProxyConnection is used with a static status code and the stream's bodyHandler is never set (as it is at io.gravitee.gateway.core.invoker.EndpointInvoker, line 104). And then body content is processed and it tries to write that chunk of data to the bodyHandler but gets a NullPointerException. This does not result in an adverse response to the client, but does clutter the logs with stace traces.

### Possible Solution
Add a null check at io/gravitee/gateway/policy/impl/StreamablePolicyChain.java:94

### Your Environment
* Version used: 1.18.0

**Comment by brasseld** [comment]
Do you think you can provide us with an API example (json export) to reproduce the issue?

I had a try but was not able to reproduce it using failover and health-check.

FYI, I had a try with Gravitee 1.22.x
Gravitee 1.18.x (which is an STS / Short term support) is no more supported from us.

Regards,

**Comment by brasseld** [comment]
Here is the API I'm using to reproduce the issue (remove the .txt extension).

[Echo-APIs-1.json.txt](https://github.com/gravitee-io/issues/files/2895908/Echo-APIs-1.json.txt)

And the curl command:

```shell
curl -k -vvv -X POST http://localhost:8082/echo --header "Content-Type: application/json" --data '{"username":"xyz","password":"xyz"}'
```
