### ISSUE TITLE
AM thread Blocked

### ISSUE THREAD

**Issue by saraAlizadeh** [gravitee-io/issues#2027]
Hi, I'm using AM V2.2. sometimes it logs some warnings and during these warning are coming, my service is not responding and its port (both 8092 (gateway) and 8093 (management api)) are not listening.

`Mar 12, 2019 11:55:57 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-4,5,main] has been blocked for 90150 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:235)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:201)
	at io.vertx.reactivex.core.http.HttpServer.listen(HttpServer.java:278)
	at io.gravitee.am.gateway.vertx.GraviteeVerticle.start(GraviteeVerticle.java:53)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
	at io.vertx.core.impl.DeploymentManager$$Lambda$95/232886115.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.vertx.core.impl.ContextImpl$$Lambda$96/1296612741.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`
why my service thread is getting blocked?
my Virtual Machine has 3 cores each having 3 sockets.

for each core, cpu MH is 2996.529.
my physical server model model is Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz

**Comment by tcompiegne** [comment]
Hi @saraAlizadeh ,

Do you have some custom plugins ?

**Comment by saraAlizadeh** [comment]
No. None

**Comment by tcompiegne** [comment]
Can you share the full warning log ?

**Comment by saraAlizadeh** [comment]
@tcompiegne 
actually this is the full log but its been repeated for thousand times!!

**Comment by tcompiegne** [comment]
Maybe related to : https://github.com/vert-x3/issues/issues/244

Can you try update your `/etc/hosts` file ?

**Comment by saraAlizadeh** [comment]
I read your link and also the stackoverflow link in your link!
it seems that this problem is for MacOS but I can try putting my machine name in /etc/hosts, too.
the warning are gone right now, buy I will monitor logs to if this solution works.
thanks btw.

**Comment by tcompiegne** [comment]
All right, keep me apprised if we can close this issue.

**Comment by saraAlizadeh** [comment]
Hi @tcompiegne 
I've been checking my services logs for 4 days and fortunately, warnings are gone. 
So I believe you can close this issue. thank you so much for your time.

**Comment by tcompiegne** [comment]
👍
