### ISSUE TITLE
java.lang.NoClassDefFoundError: io/gravitee/resource/oauth2/api/OAuth2Response

### ISSUE THREAD

**Issue by n2ygk** [gravitee-io/issues#2078]
This seems similar to #1396.

### Expected Behavior

OAuth2Response should be found.

### Current Behavior

OAuth2Response is not found

### Steps to Reproduce (for bugs)

1. Create a new API with an OAuth2 plan and resource by importing the attached.
2. Note the error logged
```
local_gateway_1        | 14:50:41.376 [sync-1] [92c6a4dc-be4d-4c4f-86a4-dcbe4d0c4f1e] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
local_gateway_1        | java.lang.NoClassDefFoundError: io/gravitee/resource/oauth2/api/OAuth2Response
local_gateway_1        | 	at java.lang.Class.getDeclaredMethods0(Native Method)
local_gateway_1        | 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
local_gateway_1        | 	at java.lang.Class.getDeclaredMethods(Class.java:1975)
local_gateway_1        | 	at org.reflections.ReflectionUtils.getMethods(ReflectionUtils.java:96)
local_gateway_1        | 	at io.gravitee.plugin.policy.internal.PolicyMethodResolver.resolve(PolicyMethodResolver.java:48)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.DefaultPolicyManager.lambda$initialize$2(DefaultPolicyManager.java:142)
local_gateway_1        | 	at java.lang.Iterable.forEach(Iterable.java:75)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.DefaultPolicyManager.initialize(DefaultPolicyManager.java:106)
local_gateway_1        | 	at io.gravitee.gateway.policy.impl.DefaultPolicyManager.doStart(DefaultPolicyManager.java:72)
local_gateway_1        | 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
local_gateway_1        | 	at io.gravitee.gateway.handlers.api.ApiReactorHandler.doStart(ApiReactorHandler.java:276)
local_gateway_1        | 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
local_gateway_1        | 	at io.gravitee.gateway.reactor.handler.impl.DefaultReactorHandlerRegistry.prepare(DefaultReactorHandlerRegistry.java:61)
local_gateway_1        | 	at io.gravitee.gateway.reactor.handler.impl.DefaultReactorHandlerRegistry.create(DefaultReactorHandlerRegistry.java:44)
local_gateway_1        | 	at io.gravitee.gateway.reactor.impl.DefaultReactor.onEvent(DefaultReactor.java:129)
local_gateway_1        | 	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
local_gateway_1        | 	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
local_gateway_1        | 	at io.gravitee.gateway.handlers.api.manager.impl.ApiManagerImpl.deploy(ApiManagerImpl.java:67)
local_gateway_1        | 	at io.gravitee.gateway.services.sync.SyncManager.lambda$computeApiEvents$11(SyncManager.java:242)
local_gateway_1        | 	at java.util.HashMap.forEach(HashMap.java:1289)
local_gateway_1        | 	at io.gravitee.gateway.services.sync.SyncManager.computeApiEvents(SyncManager.java:211)
local_gateway_1        | 	at io.gravitee.gateway.services.sync.SyncManager.synchronizeApis(SyncManager.java:152)
local_gateway_1        | 	at io.gravitee.gateway.services.sync.SyncManager.refresh(SyncManager.java:100)
local_gateway_1        | 	at io.gravitee.gateway.services.sync.ScheduledSyncService.run(ScheduledSyncService.java:87)
local_gateway_1        | 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
local_gateway_1        | 	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
local_gateway_1        | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
local_gateway_1        | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
local_gateway_1        | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
local_gateway_1        | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
local_gateway_1        | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
local_gateway_1        | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
local_gateway_1        | 	at java.lang.Thread.run(Thread.java:748)
local_gateway_1        | Caused by: java.lang.ClassNotFoundException: io.gravitee.resource.oauth2.api.OAuth2Response
local_gateway_1        | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
local_gateway_1        | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
local_gateway_1        | 	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
local_gateway_1        | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
local_gateway_1        | 	... 33 common frames omitted
```

### Context

I was playing around with the docker-compose quickstart and trying to configure an external OAuth2 AS.

### Your Environment

* Version used: 1.24.0 (Graviteeio-demo "latest" per https://github.com/gravitee-io/gravitee-docker/blob/master/README.adoc)
* Browser Name and version: Chrome 72.0.3626.121
* Operating System and version: MacOS Mojave 10.14.3 
* Docker: 18.09.2
* Docker-compose: 1.23.2
```
docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                    NAMES
3a089a9c41bf        graviteeio/management-api:latest                      "./bin/gravitee"         56 seconds ago      Up 54 seconds       0.0.0.0:8005->8083/tcp   graviteeio-demo_local_managementapi_1
ea3916dd00ae        graviteeio/gateway:latest                             "./bin/gravitee"         56 seconds ago      Up 54 seconds       0.0.0.0:8000->8082/tcp   graviteeio-demo_local_gateway_1
b1b9fed977dc        docker.elastic.co/elasticsearch/elasticsearch:5.4.3   "/bin/bash bin/es-do…"   57 seconds ago      Up 55 seconds       9200/tcp, 9300/tcp       graviteeio-demo_local_elasticsearch_1
9eda15a87fdf        mongo:3.4                                             "docker-entrypoint.s…"   57 seconds ago      Up 55 seconds       27017/tcp                graviteeio-demo_local_mongodb_1
6e4305678657        graviteeio/management-ui:latest                       "sh /run.sh"             57 seconds ago      Up 55 seconds       0.0.0.0:8002->80/tcp     graviteeio-demo_local_managementui_1
```

**Comment by n2ygk** [comment]
[django-jsonapi-1-redacted.json.txt](https://github.com/gravitee-io/issues/files/2997024/django-jsonapi-1-redacted.json.txt)

**Comment by brasseld** [comment]
Hi @n2ygk 

It seems that your oauth2 resource is not well configured.
To configure a resource you should go to API > Design > Resources and create an oauth2 resource.

**Comment by n2ygk** [comment]
@brasseld A little confused here. I don't se API > Design > Resource as a separate option in the management UI. What I did to create the oauth resource was create a new API and configure it with a pasted in JSON document under v1.23.0. Then I exported the config. The next time to reproduce I wiped everything and imported the API config with the attached JSON doc.

Now I'm trying to reproduce my steps from scratch with 1.24.0 and seem to be missing the oauth2 Plan option when setting up a plan... It only shows options of API Key or Public yet http://localhost:8002/#!/management/settings/portal shows all 4 plans are available:

Security plans type available
- [x] Keyless plans
- [x] Api-key plans
- [x] Oauth2 plans
- [x] JWT plans



I'll wipe everything and dig some more.

**Comment by n2ygk** [comment]
Now I remember what I did differently. After deploying the API, I went back in to add a new plan which has a more complex UI than the original plan UI that is part of creating the API initially: http://localhost:8002/#!/management/apis/b001a889-f1e6-4da0-81a8-89f1e6eda0aa/plans/new

From there I added Oauth2 and pasted in my JSON, saved and published the plan.

Then I create a new application called myclient and gave it the client_id of one of my existing defined clients in the external AS.

Then I went to the API gallery and subcribed my client to my API with the oauth plan.

And I had to start the API...

After all those steps then I go to http://localhost:8000/v1 in Postman and it fails with 404 Not Found "No context-path matches the request URI" but it logs java.lang.NoClassDefFoundError which I think is the real cause of the 404.

**Comment by n2ygk** [comment]
@brasseld I can grab a series of screen shots if that will help demonstrate...

**Comment by n2ygk** [comment]
Just found this clicking around: http://localhost:8002/#!/management/apis/b001a889-f1e6-4da0-81a8-89f1e6eda0aa/resources

I guess the "resource" input is actually the name of the resource, not the value. Since it showed me a green checkmark I figured it liked by input.

I think I've got this now!

**Comment by n2ygk** [comment]
Yes I can now use my external AS.
