### ISSUE TITLE
[management-api] NPE when importing OAS 3.0.1 schema

### ISSUE THREAD

**Issue by n2ygk** [gravitee-io/issues#2082]
NullPointerException thrown when attempting to create an API by importing an OAS 3.0.1 schema.
### Expected Behavior

Should create a new API using the OAS schema.
### Current Behavior

Internal Server Error
### Possible Solution

Workaround: Do not select `with mocks`.

### Steps to Reproduce (for bugs)

1. Create a valid OAS 3.0.1 schema in SwaggerEditor.
2. Validate that the schema parses properly with a simple app that uses the same version of `io.swagger.v3.parser.OpenAPIV3Parser` that gravitee 1.24.0 uses.
3. Go to [create API](http://localhost:8002/#!/management/apis/new) and import file.
4. See Internal Server Error response in the UI and this log:
```
local_managementapi_1  | 17:01:18.895 [gravitee-listener-61] INFO  i.g.m.s.impl.SwaggerServiceImpl - Trying to loading a Swagger descriptor in v2
local_managementapi_1  | 17:01:19.146 [gravitee-listener-61] INFO  i.g.m.s.impl.SwaggerServiceImpl - Trying to loading an OpenAPI descriptor
local_managementapi_1  | 17:01:19.345 [gravitee-listener-61] ERROR i.g.m.rest.provider.ThrowableMapper - Internal error
local_managementapi_1  | java.lang.NullPointerException: null
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.getResponseFromSimpleRef(SwaggerServiceImpl.java:489)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.lambda$getResponseProperties$6(SwaggerServiceImpl.java:518)
local_managementapi_1  | 	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
local_managementapi_1  | 	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
local_managementapi_1  | 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
local_managementapi_1  | 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
local_managementapi_1  | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
local_managementapi_1  | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
local_managementapi_1  | 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
local_managementapi_1  | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
local_managementapi_1  | 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.getResponseProperties(SwaggerServiceImpl.java:514)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.getResponseFromSimpleRef(SwaggerServiceImpl.java:510)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.lambda$getResponseProperties$6(SwaggerServiceImpl.java:518)
local_managementapi_1  | 	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
local_managementapi_1  | 	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
local_managementapi_1  | 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
local_managementapi_1  | 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
local_managementapi_1  | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
local_managementapi_1  | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
local_managementapi_1  | 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
local_managementapi_1  | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
local_managementapi_1  | 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.getResponseProperties(SwaggerServiceImpl.java:514)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.getResponseFromSimpleRef(SwaggerServiceImpl.java:510)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.lambda$getResponseFromSimpleRef$5(SwaggerServiceImpl.java:498)
local_managementapi_1  | 	at java.util.ArrayList.forEach(ArrayList.java:1257)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.getResponseFromSimpleRef(SwaggerServiceImpl.java:496)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.getResponseFromSimpleRef(SwaggerServiceImpl.java:493)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.processResponseSchema(SwaggerServiceImpl.java:476)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.getSwaggerVerb(SwaggerServiceImpl.java:455)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.lambda$mapOpenApiToNewApi$4(SwaggerServiceImpl.java:410)
local_managementapi_1  | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
local_managementapi_1  | 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
local_managementapi_1  | 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
local_managementapi_1  | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
local_managementapi_1  | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
local_managementapi_1  | 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
local_managementapi_1  | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
local_managementapi_1  | 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.mapOpenApiToNewApi(SwaggerServiceImpl.java:429)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.prepareV3(SwaggerServiceImpl.java:149)
local_managementapi_1  | 	at io.gravitee.management.service.impl.SwaggerServiceImpl.prepare(SwaggerServiceImpl.java:95)
local_managementapi_1  | 	at io.gravitee.management.rest.resource.ApisResource.importSwagger(ApisResource.java:196)
local_managementapi_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
local_managementapi_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
local_managementapi_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
local_managementapi_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
local_managementapi_1  | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
local_managementapi_1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
local_managementapi_1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
local_managementapi_1  | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
local_managementapi_1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
local_managementapi_1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
local_managementapi_1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
local_managementapi_1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
local_managementapi_1  | 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
local_managementapi_1  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
local_managementapi_1  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
local_managementapi_1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
local_managementapi_1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
local_managementapi_1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
local_managementapi_1  | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
local_managementapi_1  | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
local_managementapi_1  | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
local_managementapi_1  | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
local_managementapi_1  | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
local_managementapi_1  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
local_managementapi_1  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
local_managementapi_1  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
local_managementapi_1  | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
local_managementapi_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
local_managementapi_1  | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
local_managementapi_1  | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
local_managementapi_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at io.gravitee.management.security.filter.JWTAuthenticationFilter.doFilter(JWTAuthenticationFilter.java:123)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
local_managementapi_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
local_managementapi_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
local_managementapi_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
local_managementapi_1  | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
local_managementapi_1  | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
local_managementapi_1  | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
local_managementapi_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
local_managementapi_1  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
local_managementapi_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
local_managementapi_1  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701)
local_managementapi_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
local_managementapi_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
local_managementapi_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
local_managementapi_1  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
local_managementapi_1  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
local_managementapi_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
local_managementapi_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
local_managementapi_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
local_managementapi_1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
local_managementapi_1  | 	at org.eclipse.jetty.server.Server.handle(Server.java:502)
local_managementapi_1  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
local_managementapi_1  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
local_managementapi_1  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
local_managementapi_1  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
local_managementapi_1  | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
local_managementapi_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
local_managementapi_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
local_managementapi_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
local_managementapi_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
local_managementapi_1  | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
local_managementapi_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
local_managementapi_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
local_managementapi_1  | 	at java.lang.Thread.run(Thread.java:748)
```
### Context

Trying to import an existing OAS 3.0.1 definition.

### Your Environment

* Version used: 1.24.0
* Browser Name and version: Chrome 72.0.3626.121
* Operating System and version: MacOS Mojave 10.14.3 
* Docker version: 18.09.2
* Docker-compose version: 1.23.2

### Attached files
* [openapi.yaml](https://github.com/gravitee-io/issues/files/3000619/openapi.yaml.txt)
* [Simple test App](https://github.com/gravitee-io/issues/files/3000626/App.java.txt)
* [Simple test App output](https://github.com/gravitee-io/issues/files/3000627/App.txt)

**Comment by n2ygk** [comment]
All four import options were selected:
Swagger import configurations:
- [x] Create documentation
        Add a documentation page with the content of the swagger descriptor.
- [x] Create the path-mapping for analytics
        Create each paths from the swagger descriptor.
- [x] Create policies on paths
        Create each paths from the swagger descriptor.
     - [x] With mocks
             Add mocks on each paths from the swagger descriptor.

---

Deselecting `With mocks` allows the import to happen.

**Comment by brasseld** [comment]
It seems to be due to the `^(?!id$|type$)\w[-\w_]*$` property from `relationship` resource.

**Comment by n2ygk** [comment]
@brasseld I've removed the pattern validation and made quite a few other changes which I've validated with swagger-editor. It still NPE's if I select mocking. The [swagger-ui documentation page](http://localhost:8002/#!/apis/db6f8437-d539-4f27-af84-37d5396f27ab/pages/c88e0b44-0160-4c5a-8e0b-4401600c5a13) does work properly against the backend.

Admittedly this OAS 3.0 schema is (perhaps overly) complicated but I am trying to fully document the API so that a client can use something like https://www.npmjs.com/package/angular-swagger-form-field to do input validation.

Attached:
- [myapp.json OAS 3.0 document](https://github.com/gravitee-io/issues/files/3026813/myapp.json.txt)
- [NPE log](https://github.com/gravitee-io/issues/files/3026823/npe-log.txt)
- [django-jsonapi-training-example-1-0-0.json.txt exported API](https://github.com/gravitee-io/issues/files/3026837/django-jsonapi-training-example-1-0-0.json.txt) (contains a copy of myapp.json but also the plan, oauth resource, etc.)

**Comment by aelamrani** [comment]
Cannot be reproduced in version 3.0.16 of Gravitee.io
