### ISSUE TITLE
[oauth2] unexpectedly tacks on '127.0.0.1' to host part of introspection URL

### ISSUE THREAD

**Issue by n2ygk** [gravitee-io/issues#2109]
### Expected Behavior

I've configured Gravitee to validate an OAuth2 Authorization Bearer token using my external AS
at https://oauth-dev.cuit.columbia.edu:8443. It should introspect the token, as configured in the `oauth-dev` resource.

### Current Behavior

It somehow tacks `/127.0.0.1` onto the end of the hostname, resulting in the following
behavior with Postman:

Request: `GET http://api.company.com:8000/v1/courses/`
Headers:
```
Authorization: Bearer oNdYa7FT7INirGdcrkGkpyOIYJt0
```

Response status: 401 Unauthorized

body: 
```
Connection refused: oauth-dev.cuit.columbia.edu/127.0.0.1:8443
```
headers:
```
X-Gravitee-Transaction-Id →3fdbaea4-0b6e-4ff5-9bae-a40b6efff5cf
WWW-Authenticate →Bearer realm=gravitee.io
Connection →close
Content-Length →62
Content-Type →application/json
```

Corresponding Gravitee log:
```
local_managementapi_1  | 17:03:20.129 [sync-1] INFO  i.g.m.services.sync.ApiManager - Deployment of ApiEntity{id='db6f8437-d539-4f27-af84-37d5396f27ab', name='django-jsonapi-training example', version='1.0.0', description='A sample API that uses courses as an example to demonstrate representing [JSON:API 1.0](http://jsonapi.org/format) in the OpenAPI 3.0 specification.', proxy=io.gravitee.definition.model.Proxy@6ef243d5, paths={/courses/:id/=io.gravitee.definition.model.Path@3383740e, /courses/=io.gravitee.definition.model.Path@56a36f2d}, createdAt=Sun Mar 31 15:22:25 UTC 2019, updatedAt=Sun Mar 31 16:51:33 UTC 2019, visibility=PRIVATE, state=STARTED, primaryOwner=io.gravitee.management.model.PrimaryOwnerEntity@79462cda, tags=[], view=null, groups=null, pathMappings=[/courses/:id/, /courses/, /]}
local_managementapi_1  | 17:03:20.133 [sync-1] INFO  i.g.m.s.d.DynamicPropertiesService - Dynamic properties service is disabled for: django-jsonapi-training example [1.0.0]
local_gateway_1        | 17:04:03.452 [vert.x-eventloop-thread-0] [] ERROR i.g.r.o.g.OAuth2GenericResource - An error occurs while checking OAuth2 token
local_gateway_1        | io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: oauth-dev.cuit.columbia.edu/127.0.0.1:8443
local_gateway_1        | 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
local_gateway_1        | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
local_gateway_1        | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
local_gateway_1        | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
local_gateway_1        | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
local_gateway_1        | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
local_gateway_1        | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
local_gateway_1        | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
local_gateway_1        | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
local_gateway_1        | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
local_gateway_1        | 	at java.lang.Thread.run(Thread.java:748)
local_gateway_1        | Caused by: java.net.ConnectException: Connection refused
local_gateway_1        | 	... 11 common frames omitted
```
### Steps to Reproduce (for bugs)

1. Configure an API with a generic oauth2 resource.
2. Configure a plan that references that resource with the following enabled:
   - Extract Payload
   - Check scopes (auth-columbia)
   - Propagate Authorization header
3. Acquire an OAuth2 Bearer token (e.g. Authorize in Postman)
4. Do a GET w/the Authorization: Bearer token

### Context

I'm trying to have the gateway do preliminary token introspection and minimal scope validation, then passing the Bearer token to the backend for deeper introspection (e.g. permissions based on the `sub` and additional scope validations.)

### Your Environment

* Version used: 1.24.0
* Browser Name and version: Postman 6.6.1
* Operating System and version: MacOS Mojave 10.14.3 
* Docker version: 18.09.2
* Docker-compose version: 1.23.2

N.B. It might not matter, but the oauth2-dev server certificate is self-signed.

See attached exported API here: https://github.com/gravitee-io/issues/issues/2082#issuecomment-478355868 which contains this resource:

```
  "resources": [
    {
      "name": "oauth-dev",
      "type": "oauth2",
      "enabled": true,
      "configuration": {
        "authorizationServerUrl": "https://oauth-dev.cuit.columbia.edu:8443",
        "introspectionEndpoint": "/as/authorization.oauth2",
        "introspectionEndpointMethod": "POST",
        "scopeSeparator": " ",
        "userInfoEndpoint": "/idp/userinfo.openid",
        "userInfoEndpointMethod": "GET",
        "useClientAuthorizationHeader": true,
        "clientAuthorizationHeaderName": "Authorization",
        "clientAuthorizationHeaderScheme": "Basic",
        "tokenIsSuppliedByQueryParam": false,
        "tokenQueryParamName": "token",
        "tokenIsSuppliedByHttpHeader": false,
        "tokenIsSuppliedByFormUrlEncoded": true,
        "tokenFormUrlEncodedName": "token",
        "userClaim": "sub",
        "clientId": "gravitee_validator",
        "clientSecret": "SaulGoodman"
      }
    }
  ]
```

**Comment by n2ygk** [comment]
I don't know for sure if this is the fix, but I've deleted and recreated the API and appended a trailing slash to the authorizationServerUrl and now it is working:
```diff
<         "authorizationServerUrl": "https://oauth-dev.cuit.columbia.edu:8443",
---
>         "authorizationServerUrl": "https://oauth-dev.cuit.columbia.edu:8443/",
```

**Comment by brasseld** [comment]
Thanks for spotting this @n2ygk 

I will have a look

**Comment by n2ygk** [comment]
Ugh, sorry @brasseld, I was mistaken. I had tested swagger form within the portal and that seems to work but an curl/Postman request still tacks on the 127.0.0.1.

**Comment by n2ygk** [comment]
Any pointers to where I should look in the code? It wasn't immediately apparent to me how this data gets passed to the gateway.

**Comment by n2ygk** [comment]
I did `docker exec -it graviteeio-demo_local_gateway_1 sh` and find that the correct URL is logged and then the connection refused shows the incorrect one:

```
551:16:20:35.039 [sync-1] [f1c6d640-1687-4e14-86d6-4016879e143d] INFO  i.g.g.r.internal.ResourceManagerImpl - Start resource oauth-dev [class io.gravitee.resource.oauth2.generic.OAuth2GenericResource]
553:16:20:35.039 [sync-1] [f1c6d640-1687-4e14-86d6-4016879e143d] INFO  i.g.r.o.g.OAuth2GenericResource - Starting an OAuth2 resource using authorization server at https://oauth-dev.cuit.columbia.edu:8443/
563:io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: oauth-dev.cuit.columbia.edu/127.0.0.1:8443
578:io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: oauth-dev.cuit.columbia.edu/127.0.0.1:8443
```

**Comment by brasseld** [comment]
Are you sure that domain oauth-dev.cuit.columbia.edu can be reach from the docker container?

**Comment by n2ygk** [comment]
Yeah you found it just as I did. oauth-dev is another container running on localhost. I turned on io.netty debugging. It's just a weird thing that the hostname it creates tacks on 127.0.0.1 like that. I need to put oauth-dev in the containers /etc/hosts I think as whatever the IP address of the container's host is....

**Comment by brasseld** [comment]
You have to link containers to use their "docker" container's hostname.
But you're on a good way :)

**Comment by n2ygk** [comment]
Yeah, googling that now;-) actually the "container" for oauth-dev is a vagrant box. Thanks.

This is a cool tool.

**Comment by brasseld** [comment]
Thanks :)

**Comment by n2ygk** [comment]
Note quite right but this gets me to my AS:
```
diff --git a/docker-compose-local.yml b/docker-compose-local.yml
index 38c34e4..057b9ae 100644
--- a/docker-compose-local.yml
+++ b/docker-compose-local.yml
@@ -42,6 +42,9 @@ services:
       - "local_elasticsearch:demo-elasticsearch"
     ports:
       - "8000:8082"
+    extra_hosts:
+      # alias to host.docker.internal
+      - "oauth-dev.cuit.columbia.edu:192.168.65.2"
     volumes:
       - ./logs/gateway:/etc/gravitee.io/log
     environment:
```
