### ISSUE TITLE
[management] Delete the default app

### ISSUE THREAD

**Issue by gfpa88** [gravitee-io/issues#2237]
Deleting the default app (is the one that is already created when launch a clean instance of gravitee), with the admin user, causes an Internal Server Error

In the management-api logs I get this:

_java.lang.NullPointerException: null
at io.gravitee.repository.mongodb.management.MongoApplicationRepository.update(MongoApplicationRepository.java:78)
at io.gravitee.repository.mongodb.management.MongoApplicationRepository.update(MongoApplicationRepository.java:36)
at io.gravitee.management.repository.proxy.ApplicationRepositoryProxy.update(ApplicationRepositoryProxy.java:58)
at io.gravitee.management.repository.proxy.ApplicationRepositoryProxy.update(ApplicationRepositoryProxy.java:33)
at io.gravitee.management.service.impl.ApplicationServiceImpl.archive(ApplicationServiceImpl.java:452)_

### Your Environment
* Version used: 1.25.1

**Comment by phiz71** [comment]
Hi @gfpa88, did you upgrade your Gravitee instance from a former version to 1.25.1 or was it a new installation ?
