### ISSUE TITLE
Problems in Use

### ISSUE THREAD

**Issue by wutongan** [gravitee-io/issues#2328]
When I created a keyless plan api, the user did not display the URI of the API after subscribing, so the user's experience was not very good. In addition, when I created an API key plan, when I got URI and api-key, there would be 401 errors in access. Whether it was due to the wrong settings when I created the API (using post and api-key to access successfully, our platform's API defaults to GET access).

**Comment by aelamrani** [comment]
`When I created a keyless plan api, the user did not display the URI of the API after subscribing, so the user's experience was not very good` => how do you subscribe to a keyless plan? ATM, this is not possible as this is a pass-through plan.

The cURL generated is an example of use with the selected security type, we do not provide sample requests based on the API definition and this is not the goal here.

**Comment by wutongan** [comment]
非常感谢。部署完成以后，获取到api-key访问会出现401错误是因为我在部署的时候对api的设置有误么？还是因为别的原因，我的api只是一个测试使用的api，没有任何校验。

**Comment by wutongan** [comment]
Thank you very much. After deployment, there will be 401 errors in accessing api-key because I set the API incorrectly at deployment time? Or for other reasons, my API is just a test API without any validation

**Comment by aelamrani** [comment]
After subscribing to an api-key plan, you should be able to use the API. I do not know if that answers your question?

**Comment by wutongan** [comment]
Yes, but after I subscribed to the api key plan and got the api key, the access will have a 401 error, is it because of problems in my deployment api, or because my settings are not complete. The api I deployed is a test api and does not have any security and permission checks.

**Comment by aelamrani** [comment]
I just had a try and no problem at all here. Can you share an export of your API here?

**Comment by wutongan** [comment]
{
  "name": "根据表号更新设备信息",
  "version": "1.0",
  "description": "更新设备信息接口。",
  "visibility": "PUBLIC",
  "paths": {
    "/": [
      {
        "methods": [
          "POST"
        ],
        "api-key": {
          "propagateApiKey": true
        },
        "description": "Description of the ApiKey Gravitee Policy",
        "enabled": true
      }
    ]
  },
  "services": {
    "health-check": {
      "enabled": true,
      "trigger": {
        "rate": 1,
        "unit": "HOURS"
      },
      "steps": [
        {
          "name": "default-step",
          "request": {
            "path": "/iotface/device/updatebyid",
            "method": "POST",
            "headers": [
              {
                "name": "Content-Type",
                "value": "application/json"
              }
            ],
            "body": "{\n\t\"meternum\": \"5100401000000100000718\",\n\t\"fullorgid\": \"100000,100002\",\n\t\"orgid\": \"100000\",\n\t\"siteid\": \"1111\",\n\t\"longitude\": 134.1231,\n\t\"latitude\": 113.123\n}",
            "fromRoot": true
          },
          "response": {
            "assertions": [
              "#response.status == 200"
            ]
          }
        }
      ]
    }
  },
  "resources": [],
  "properties": [],
  "groups": [
    "测试组",
    "高级权限组"
  ],
  "members": [
    {
      "username": "admin",
      "role": "PRIMARY_OWNER"
    }
  ],
  "pages": [],
  "plans": [
    {
      "id": "db1dbbef-695d-4f05-9dbb-ef695daf055b",
      "name": "使用apikey",
      "description": "使用apikey",
      "validation": "MANUAL",
      "security": "API_KEY",
      "securityDefinition": "{\"propagateApiKey\":false,\"extractPayload\":false,\"checkRequiredScopes\":false,\"requiredScopes\":[],\"publicKeyResolver\":\"GIVEN_KEY\",\"extractClaims\":false}",
      "type": "API",
      "status": "PUBLISHED",
      "apis": [
        "0c7ad079-db4d-42d3-bad0-79db4de2d346"
      ],
      "order": 0,
      "characteristics": [],
      "created_at": 1559037044797,
      "updated_at": 1559037053036,
      "published_at": 1559037053036,
      "paths": {
        "/": []
      },
      "excluded_groups": []
    }
  ],
  "path_mappings": [],
  "proxy": {
    "context_path": "/iot/device",
    "strip_context_path": false,
    "groups": [
      {
        "name": "default-group",
        "endpoints": [
          {
            "name": "default",
            "target": "http://localhost/iotface/device/updatebyid",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "http": {
              "connectTimeout": 5000,
              "idleTimeout": 60000,
              "keepAlive": true,
              "readTimeout": 10000,
              "pipelining": false,
              "maxConcurrentConnections": 100,
              "useCompression": true,
              "followRedirects": false
            },
            "ssl": {
              "trustAll": true,
              "hostnameVerifier": false
            }
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        }
      }
    ]
  }
}

**Comment by aelamrani** [comment]
please attach a file

**Comment by wutongan** [comment]
[test.docx](https://github.com/gravitee-io/issues/files/3250071/test.docx)

**Comment by wutongan** [comment]
[Test.zip](https://github.com/gravitee-io/issues/files/3250074/Test.zip)

**Comment by aelamrani** [comment]
Can you try removing the policy API key because it is already handled by the plan?

**Comment by wutongan** [comment]
I tried to delete the policy API key or the previous 401 error.

**Comment by aelamrani** [comment]
Did you deploy your API?

**Comment by wutongan** [comment]
Yes, I have deployed

**Comment by aelamrani** [comment]
Can you put here the result of: `curl -v your_gateway/iot/device -H 'X-Gravitee-Api-Key:your_api_key'?

**Comment by wutongan** [comment]
![test](https://user-images.githubusercontent.com/19904538/58860370-8ee8e480-86de-11e9-86a0-dafacd238ba6.jpg)
This is the problem that occurred when I visited.

**Comment by aelamrani** [comment]
Can you check the subscription is well accepted? API > Subscriptions

**Comment by wutongan** [comment]
Yes, my subscription was successful and I got the api-key. Then access it via api-key.

**Comment by aelamrani** [comment]
Can you share the logs of the gateway?

**Comment by wutongan** [comment]
[logs.zip](https://github.com/gravitee-io/issues/files/3270200/logs.zip)

**Comment by wutongan** [comment]
![WechatIMG3188](https://user-images.githubusercontent.com/19904538/59175081-c1835900-8b86-11e9-97cd-23eab8018239.png)

**Comment by brasseld** [comment]
There are several logs relative to authentication issues to MongoDB:

```
Caused by: org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 13 (Unauthorized): 'command createIndexes requires authentication' on server localhost:15278. The full response is { "ok" : 0.0, "errmsg" : "command createIndexes requires authentication", "code" : 13, "codeName" : "Unauthorized" }; nested exception is com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command createIndexes requires authentication' on server localhost:15278. The full response is { "ok" : 0.0, "errmsg" : "command createIndexes requires authentication", "code" : 13, "codeName" : "Unauthorized" }
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:138)
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2774)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:540)
	at org.springframework.data.mongodb.core.DefaultIndexOperations.execute(DefaultIndexOperations.java:218)
	at org.springframework.data.mongodb.core.DefaultIndexOperations.ensureIndex(DefaultIndexOperations.java:121)
	at io.gravitee.repository.mongodb.ratelimit.MongoRateLimitRepository.ensureTTLIndex(MongoRateLimitRepository.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 52 common frames omitted
Caused by: com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command createIndexes requires authentication' on server localhost:15278. The full response is { "ok" : 0.0, "errmsg" : "command createIndexes requires authentication", "code" : 13, "codeName" : "Unauthorized" }
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:293)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:242)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:233)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:170)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:163)
	at com.mongodb.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:174)
	at com.mongodb.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:169)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:448)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:410)
	at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:169)
	at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:70)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:193)
	at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:805)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:788)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:783)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:768)
	at org.springframework.data.mongodb.core.DefaultIndexOperations.lambda$ensureIndex$0(DefaultIndexOperations.java:135)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:538)
	... 62 common frames omitted
```

Please resolve them before we'll have a deep dive into your issue.
