### ISSUE TITLE
[gateway] [oauth2] io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException when using oAuth2 plan

### ISSUE THREAD

**Issue by RickardR** [gravitee-io/issues#2415]
I've been unable to set up an oAuth2 plan. When I do set it up, and try to consume the api I only get io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException and a 500 error.
I'm running Gravitee 1.27.0 in docker, using docker-compose. There is *no* stacktrace coming out the logs (viewing the logs with docker-compose logs -f so I get all containers). Only logs when stopping/starting the API is shown.
If I set up an API Key plan, and use that it instead, it works like a charm, but as soon as I try to use the oAuth policy it fails. I've set it up from scratch serveral times by dropping the MongoDB database completely
My oAuth2 resource (identityserver 4) do get a successful token instrospection from gravitee , so the oAuth2 resource integration seems to work properly.

Any help is appreciated, since I don't understand why it doesn't work. Am i missing something trivial? Is there something fishy in the oAuth integration?. Any tips or pointers how I can debug this (can I increase logging for example somehow? Since I dont se a stacktrace in the logs for example...), I've been banging my head against this for like 2 days now and post this in hope of any pointers.

### Expected Behavior
When using oAuth2 with a proper authtoken, the API should be accessible

### Current Behavior
When using oAuth2, with a validated token  i get internal server error and no logs.
When using an expired/incorrect key I get a proper 401 Unauthorized response.

### Steps to Reproduce (for bugs)
Well this is what I did (i've dropped the MongoDB database serveral times to make sure it's clean)
1. Create an API called Flow: Manually (*not* through swagger/link import). No policys or anything, just basic setup, pointing to my internal API backend.
2. Create an oAuth2 resource with the name DOCIS4
3. Create an application with an client_id (lets say client_api)
4. Create a oAuth2 plan called <customername> Backend, using DOCIS4 and subscribed the application to it
5. open postman, call the api: I get 401 Unauthorized 
6. Requests a client_credential auth token from my Identityserver 4 and use that for authorization
7. I now get 500 internal server error with body:
{
    "message": "io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException",
    "http_status_code": 500
}
8. Nothing seems to be logged in the docker logs. Successful token introspection is logged in Identityserver 4. The internal API does not get any connection from gravitee at all.
9. I add a API key plan and subscribe it, and use the header with the API key instead: Call is successful, but oauth keeps throwing 500 back.
   

### Context
I want to secure my API through oAuth2 with our own IDP, and use claims in the token to be able to sandbox the consumer (the customers organisation ID etc). This is then read from the token and added as headers to the backend systems.

### Your Environment

* Version used: 1.27.0 (docker containers)
* Running Docker 18.09.2 on Ubuntu through docker-compose
* MongoDB: Standalone install on Ubuntu, version 3.6.3 
* Elasticsearch 6.7.0 (Docker container)
* oAuth2 resource: Identityserver 4 version 2.3
* calling API with Postman 7.2.0 on Windows 10

**Comment by brasseld** [comment]
Can you share an export of the API ?

**Comment by RickardR** [comment]
[Flow-1-0.txt](https://github.com/gravitee-io/issues/files/3339818/Flow-1-0.txt)

**Comment by brasseld** [comment]
Do you have any logs from the gateway ?

**Comment by brasseld** [comment]
and why do you need a selection_rule for the oauth2 plan ? 

`"selection_rule": "#context.attributes['jwt'].claims['client_id'] == 'capio_api'"`

**Comment by RickardR** [comment]
Just experimented with it to see if it made any difference (it did not).

**Comment by brasseld** [comment]
did you check api logs ?
from your flow API, go to Analytics > Log > you must see all the API calls in 500, just select on of them and you should be able to get a more complete stack trace.

**Comment by brasseld** [comment]
What is strange to me is this: 

> I add a API key plan and subscribe it, and use the header with the API key instead: Call is successful, but oauth keeps throwing 500 back.

So it means that the issue is not relative to oauth2 since api-key does not involve the oauth2 resource (or perhaps you've added the policy by yourself ?)

**Comment by RickardR** [comment]
Embarrased, didn't know that the stacktrace could be seen in the analytics part, that it was pushed to Elastic...

Here it is:
An error occurs in policy[rate-limit] error[io.gravitee.gateway.policy.PolicyChainException: io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException
	at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:47)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:72)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:54)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:105)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:42)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:59)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:55)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:89)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:54)
	at io.gravitee.gateway.security.oauth2.policy.CheckSubscriptionPolicy.onRequest(CheckSubscriptionPolicy.java:90)
	at io.gravitee.gateway.policy.AbstractPolicy.onRequest(AbstractPolicy.java:35)
	at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:45)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:72)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:54)
	at io.gravitee.policy.oauth2.Oauth2Policy.lambda$handleResponse$1(Oauth2Policy.java:199)
	at io.gravitee.resource.oauth2.generic.OAuth2GenericResource.lambda$null$2(OAuth2GenericResource.java:199)
	at io.vertx.core.http.impl.HttpClientResponseImpl$BodyHandler.notifyHandler(HttpClientResponseImpl.java:296)
	at io.vertx.core.http.impl.HttpClientResponseImpl.lambda$bodyHandler$0(HttpClientResponseImpl.java:196)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:252)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.endResponse(Http1xClientConnection.java:493)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.access$000(Http1xClientConnection.java:194)
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:652)
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:602)
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:560)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:390)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1429)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException
	at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:97)
	at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:50)
	at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:45)
	... 63 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:95)
	... 65 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.gravitee.repository.ratelimit.api.RateLimitService' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:335)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1123)
	at io.gravitee.gateway.reactor.handler.context.ReactableExecutionContext.getComponent(ReactableExecutionContext.java:106)
	at io.gravitee.policy.ratelimit.RateLimitPolicy.onRequest(RateLimitPolicy.java:84)
	... 70 more
]

**Comment by RickardR** [comment]
@brasseld Yes, I first set up *only* oAuth2, the API key I set up when oAuth didn't work to se if there was something wrong with my setup, but when I use API key (remove Auth header, and send X-Gravitee-Api-Key with the key instead) everything works fine. So it's only when It chooses the oAuth2 policy it doesnt rowk.

**Comment by brasseld** [comment]
No worries, you don't have to be embarrassed and I would say that it's quite normal because we do not have documentation for all the features.

Anyway, stacktrace helps me a lot to understand your issue, and I can tell you that this latest is not about oauth2 since we can see this log

> Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.gravitee.repository.ratelimit.api.RateLimitService' available 

Which means that you didn't configure correctly the rate-limit repository (in a very similar way as for the management repository). Please check `gravitee.yml` from the gateway component: https://github.com/gravitee-io/gravitee-gateway/blob/master/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L103

Looking for your feedback.

Regards,

**Comment by brasseld** [comment]
I forgot to say that you have rate-limiting for oauth2 plan but not for api-key, that's the reason why it works well for api-key plan and not for oauth2.

But again, it's not about the authorization_server, just check your config :)

**Comment by RickardR** [comment]
Works like a charm without Rate limiting. That I never tried removing it boggles me.
Didn't know i need an extra setup for that, thank you SO much , you've saved me! Ill try to get the ratelimiting repo up and running and I'm gtg.

**Comment by brasseld** [comment]
Perfect !

Enjoy your platform :)
