### ISSUE TITLE
[gateway] I encountered a bug(Memory leak)

### ISSUE THREAD

**Issue by 2690522020** [gravitee-io/issues#2516]
[vert.x-eventloop-thread-146] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Result is already complete: failed
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:87)
        at io.gravitee.gateway.core.failover.FailoverInvoker$2.lambda$null$0(FailoverInvoker.java:64)
        at io.gravitee.gateway.http.connector.VertxProxyConnection.handleResponse(VertxProxyConnection.java:85)
        at io.gravitee.gateway.http.connector.VertxHttpClient.lambda$request$3(VertxHttpClient.java:159)
        at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:139)
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleException(Http1xClientConnection.java:515)
        at io.vertx.core.http.impl.Http1xClientConnection.handleClosed(Http1xClientConnection.java:883)
        at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$5(VertxHandler.java:164)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
        at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:164)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.handler.codec.http.HttpContentDecoder.channelInactive(HttpContentDecoder.java:205)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
        at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:282)
        at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

My Environment
Version : 1.28.0

I have no effective way to solve the whole problem, and this problem will lead to the program can not run properly.

**Comment by 2690522020** [comment]
@NicolasGeraud

**Comment by brasseld** [comment]
@2690522020  Can you explain why this would be a memory leak?

**Comment by 2690522020** [comment]
A file is generated during the running of the program,And the program can't handle any requests
java_pid1048.hprof

**Comment by brasseld** [comment]
Are you looking to provide java_pid1048.hprof?

**Comment by 2690522020** [comment]
This file has 500MB. How can I provide it to you?

**Comment by brasseld** [comment]
Pushing it somewhere and provide a link?

**Comment by 2690522020** [comment]
This is the connection to the file：
https://github.com/2690522020/hprof/blob/master/java_pid1048.hprof

**Comment by 2690522020** [comment]
@brasseld 
07:01:38.920 [vert.x-eventloop-thread-154] [] ERROR i.g.g.http.connector.VertxHttpClient - Unexpected error while handling backend response for request POST http://15.86.12.11:9182/GetUserList - Connection reset by peer
07:01:38.921 [vert.x-eventloop-thread-154] [] ERROR i.g.g.http.connector.VertxHttpClient - Unexpected error while handling backend response for request POST http://15.86.12.11:9182/GetUserList - Connection was closed
07:02:07.398 [vert.x-eventloop-thread-155] [] ERROR i.g.g.http.connector.VertxHttpClient - Unexpected error while handling backend response for request POST http://15.86.12.10:9182/GetUserList - Connection was closed
07:07:11.171 [vert.x-eventloop-thread-81] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:15.026 [vert.x-eventloop-thread-44] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:15.807 [vert.x-eventloop-thread-9] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:17.539 [vert.x-eventloop-thread-77] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:19.262 [vert.x-eventloop-thread-64] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:19.876 [vert.x-eventloop-thread-91] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:20.058 [vert.x-eventloop-thread-84] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:20.626 [vertx-blocked-thread-checker] [] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-133,5,main] has been blocked for 8691 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:408)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
07:07:22.625 [vert.x-eventloop-thread-23] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:25.277 [vert.x-eventloop-thread-128] [] WARN  io.netty.channel.nio.NioEventLoop - Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:25.277 [vert.x-eventloop-thread-126] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:25.277 [vert.x-eventloop-thread-152] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:25.278 [sync-1] [] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by 2690522020** [comment]
@brasseld
07:02:07.398 [vert.x-eventloop-thread-155] [] ERROR i.g.g.http.connector.VertxHttpClient - Unexpected error while handling backend response for request POST http://*****/user- Connection was closed
07:07:11.171 [vert.x-eventloop-thread-81] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:15.026 [vert.x-eventloop-thread-44] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:15.807 [vert.x-eventloop-thread-9] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:17.539 [vert.x-eventloop-thread-77] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:19.262 [vert.x-eventloop-thread-64] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:19.876 [vert.x-eventloop-thread-91] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:20.058 [vert.x-eventloop-thread-84] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:20.626 [vertx-blocked-thread-checker] [] WARN i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-133,5,main] has been blocked for 8691 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:408)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
07:07:22.625 [vert.x-eventloop-thread-23] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:25.277 [vert.x-eventloop-thread-128] [] WARN io.netty.channel.nio.NioEventLoop - Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:25.277 [vert.x-eventloop-thread-126] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:25.277 [vert.x-eventloop-thread-152] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
07:07:25.278 [sync-1] [] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by 2690522020** [comment]
@brasseld This is the latest error message.

**Comment by brasseld** [comment]
Which version of gravitee ?

**Comment by 2690522020** [comment]
1.25.9

**Comment by brasseld** [comment]
Did you made any change into Gravitee (plugins, ...)?

Also can you tell me if you're transferring large files through the gateway.

**Comment by 2690522020** [comment]
no,I haven't changed it.
but My request for return will be very large.

**Comment by 2690522020** [comment]
![image](https://user-images.githubusercontent.com/26107727/64313846-8f479300-cfdf-11e9-9cac-e16960393875.png)

**Comment by brasseld** [comment]
Perhaps logging is enabled for this api ?

**Comment by 2690522020** [comment]
how can I check it?

**Comment by brasseld** [comment]
Hi,

It seems to be due to failover you've set for an API.
Can you check it by disabling failover for the API?

**Comment by 2690522020** [comment]
I'll try to disable it，Look at the results.

**Comment by brasseld** [comment]
Looking for feedback on this.

**Comment by 2690522020** [comment]
this is my gravitee.yml
reporters:
  # logging configuration
  #logging:
  #  max_size: -1 # max size per API log content respectively : client-request, client-response, proxy-request and proxy-response in MB (-1 means no limit)
  # Elasticsearch reporter
  elasticsearch:
    enabled: true # Is the reporter enabled or not (default to true)
    endpoints:
      - http://${ds.elastic.host}:${ds.elastic.port}
#    index: gravitee
#    index_per_type: true
    bulk:
      actions: 100           # Number of requests action before flush
      flush_interval: 5       # Flush interval in seconds
    settings:
      number_of_shards: 5
      number_of_replicas: 1
      refresh_interval: 5s
#    pipeline:
#      plugins:
#        ingest: geoip, user_agent
#    security:
#      username: user
#      password: secret
    http:
      timeout: 60000 # in milliseconds

**Comment by aelamrani** [comment]
Can you try by changing the bulk values with:

```
    bulk:
      actions: 1000           # Number of requests action before flush
      flush_interval: 5       # Flush interval in seconds
```

**Comment by brasseld** [comment]
Problem is with failover as per my previous comment...

**Comment by 2690522020** [comment]
I changed it to see if it would happen again.

**Comment by 2690522020** [comment]
But I think any problem should not kill the program itself.
