### ISSUE TITLE
SMTP issue TLS 'Could not convert socket to TLS' for SSL - Could not connect to SMTP host: xx@xx.com, port: 465

### ISSUE THREAD

**Issue by Subbu0117** [gravitee-io/issues#2721]
### Expected Behavior
SMTP TLS and SSL should send email using configured smtp details.

### Current Behavior
Both TLS and SSL setting are failing for Spring javax mail. 

 SMTP TLS is failing with 'Could not convert socket to TLS' 
I set the below gravitee param:
email:
  enabled: true
  host: xx.com
  subject: "[ API Dev Portal] %s"
  port: 587 
  from: no-reply@xx.com
  username: no-reply@xx.com
  password: I123456
  protocal: smtp
  properties:
    auth: true
    starttls.enable: true
    ssl.trust: xx.com

Exception:
 javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?. Failed messages: javax.mail.MessagingException: Could not convert socket to TLS;
     
   Caused by: org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
        javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?. Failed messages: javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
        javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:447)
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:360)
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:355)
        at io.gravitee.management.service.impl.EmailServiceImpl.sendEmailNotification(EmailServiceImpl.java:104)
        ... 14 common frames omitted
Caused by: javax.mail.MessagingException: Could not convert socket to TLS
        at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1907)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:666)
        at javax.mail.Service.connect(Service.java:295)
        at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:517)
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:436)
        ... 17 common frames omitted

**With SSL connection:

Configuration:**
 
email:
  enabled: true
  host: xx.com
  subject: "[API Dev Portal] %s"
  port: 465
  from: no-reply@xx.com
  username: no-reply@xx.com
  password: 123456 
  ssl.trust:xx.com
  socketFactory.port: 465
  properties:
    auth: true
    ssl.enable: true
	socketFactory.class: javax.net.ssl.SSLSocketFactory

 
Caused by: org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: xx@xx.com, port: 465;
  nested exception is:
        java.net.SocketException: Connection reset. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: xx@xx.com, port: 465;

### Possible Solution
better to replace spring Javax mail with generic mail(mail.jar, activation.jar), it works for all Gmail and other commercial mails.  
### Steps to Reproduce (for bugs)
1. 
2.
3.
4.

### Context
 I ram simple java code using mail.jar it worked very will on the same host for TLS and SSL. 

I also tested using spring Javax mail. it failed with same error. 

### Your Environment
* Version used: 1.27
* Operating System and version: Redhat 7.4

**Comment by Subbu0117** [comment]
SMTP issue was fixed after so much trial and error.  
Option I found was :  
Reduce security level in the mail server  cpanel and add with below settings gravitee

 enabled: true
  host: xxx.com
  subject: "xxx"
  port: 587
  from: xxx.xxx.com
  username: xxx.com
  password: ******
  properties:
    auth: true
