### ISSUE TITLE
[management] Error while importing OAI with a variable on the server's URL

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#3086]
```
08:57:08.764 [gravitee-listener-65] INFO  i.g.r.a.s.impl.SwaggerServiceImpl - Trying to load an OpenAPI descriptor
java.net.URISyntaxException: Illegal character in path at index 31: http://demo.gravitee.io/portal/{envId}
	at java.base/java.net.URI$Parser.fail(URI.java:2936)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3107)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3189)
	at java.base/java.net.URI$Parser.parse(URI.java:3137)
	at java.base/java.net.URI.<init>(URI.java:623)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.getServer(OpenAPIDeserializer.java:414)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.getServersList(OpenAPIDeserializer.java:380)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.parseRoot(OpenAPIDeserializer.java:167)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.deserialize(OpenAPIDeserializer.java:119)
	at io.swagger.v3.parser.OpenAPIV3Parser.readWithInfo(OpenAPIV3Parser.java:119)
	at io.swagger.v3.parser.OpenAPIV3Parser.readWithInfo(OpenAPIV3Parser.java:157)
	at io.gravitee.rest.api.service.impl.SwaggerServiceImpl.prepareV3(SwaggerServiceImpl.java:165)
```

**Comment by gcusnieux** [comment]
Fix by gravitee-io/issues#3246
