### ISSUE TITLE
[management] Unable to write/show analytics

### ISSUE THREAD

**Issue by MarFloALI** [gravitee-io/issues#3093]
For a couple of days, Gravitee is unable to write/show any analytics. I have data from before, that I can see, but any data since are ending in a "Unable to calculate" console error.

Error from Gravitee:
`Exception in thread "vert.x-eventloop-thread-4" io.reactivex.exceptions.OnErrorNotImplementedException: The timeout period of 30000ms has been exceeded while executing POST /_bulk for host elasticsearch
at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:52)
at io.vertx.reactivex.ext.web.client.HttpRequest$4.handle(HttpRequest.java:369)
at io.vertx.reactivex.ext.web.client.HttpRequest$4.handle(HttpRequest.java:364)
at io.vertx.ext.web.client.impl.HttpContext.lambda$sendRequest$6(HttpContext.java:167)
at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:130)
at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:50)
at io.vertx.core.http.impl.HttpClientRequestBase.timeout(HttpClientRequestBase.java:179)
at io.vertx.core.http.impl.HttpClientRequestBase.handleTimeout(HttpClientRequestBase.java:162)
at io.vertx.core.http.impl.HttpClientRequestBase.lambda$setTimeout$0(HttpClientRequestBase.java:115)
at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
Caused by: io.vertx.core.http.impl.HttpClientRequestBase$1: The timeout period of 30000ms has been exceeded while executing POST /_bulk for host elasticsearch`

From ElasticsSearch:
`[2020-01-14T10:15:03,655][WARN ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213582] overhead, spent [1.4s] collecting in the last [2.1s]
[2020-01-14T10:15:05,347][WARN ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213583] overhead, spent [1.3s] collecting in the last [1.6s]
[2020-01-14T10:15:06,953][WARN ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213584] overhead, spent [1.2s] collecting in the last [1.4s]
[2020-01-14T10:15:08,798][WARN ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213585] overhead, spent [1.3s] collecting in the last [1.9s]
[2020-01-14T10:15:14,929][INFO ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213591] overhead, spent [305ms] collecting in the last [1s]
[2020-01-14T10:15:17,930][INFO ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213594] overhead, spent [299ms] collecting in the last [1s]
[2020-01-14T10:15:38,135][INFO ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213614] overhead, spent [316ms] collecting in the last [1.1s]
[2020-01-14T10:15:40,215][WARN ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213615] overhead, spent [1.1s] collecting in the last [1.9s]
[2020-01-14T10:15:41,745][WARN ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213616] overhead, spent [1.2s] collecting in the last [1.6s]
[2020-01-14T10:15:43,315][WARN ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213617] overhead, spent [1.1s] collecting in the last [1.5s]
[2020-01-14T10:15:44,783][WARN ][o.e.m.j.JvmGcMonitorService] [-8Y2YgJ] [gc][213618] overhead, spent [1s] collecting in the last [1.4s]
`
### Your Environment
* Version used: Gravite: Version: 1.22.1 | ES: 5.4.3
* Docker environnement

**Comment by brasseld** [comment]
Hi @MarFloALI 

Two things here:
* You are using a very old version of gravitee which no more supported and we've done several enhancements about reporting to ES
* Seems the issue is more relative to the sizing of your ES instance / cluster. You need to upgrade memory.
