### ISSUE TITLE
[repository] [jdbc] Database objects missing when initially starting management api

### ISSUE THREAD

**Issue by StodaraHodan** [gravitee-io/issues#3272]
we tried to start the management api for the first time, we use mssql for the database

It seems to boil down to these objects missing:

Invalid object name 'dashboards'.
Invalid column name 'api_lifecycle_state'.
The object 'pk_ratelimit' is dependent on column 'key'. [Failed SQL: (5074) ALTER TABLE ratelimit ALTER COLUMN [key] nvarchar(128)]

when i look at the sql query of the second issue and look for the column in the table, it isn't there:

select av.*, a.id, a.name, a.description, a.version, a.deployed_at, a.created_at, a.updated_at, a.visibility, a.lifecycle_state, a.picture, **a.api_lifecycle_state** from apis a left join api_views av on a.id = av.api_id order by a.name

![E10C43912F02588](https://user-images.githubusercontent.com/40172043/75552048-bd111000-5a35-11ea-9161-fb257908d22a.png)

### Expected Behavior
management api starts and creates all necessary database objects

### Current Behavior
there are databse objects missing

### Possible Solution
-

### Steps to Reproduce (for bugs)
initially start management api with mssql database through jdbc connection

### Context
we created an empty database and a service user with db_owner permissions

### Your Environment

* Version used: graviteeio-management-api-1.30.4
* Browser Name and version: -
* Operating System and version: - mgmt api server: Debian 10, db: MSSQL Server 2017 Enterprise

Log, some Error Messages:

```
12:43:20.150 [sync-1] ERROR i.g.m.services.sync.SyncManager - An error occurs while synchronizing APIs
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select av.*, a.id, a.name, a.description, a.version, a.deployed_at, a.created_at, a.updated_at, a.visibility, a.lifecycle_state, a.picture, a.api_lifecycle_state from apis a left join api_views av on a.id = av.api_id order by a.name]; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'api_lifecycle_state'.
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1444)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:632)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:728)
	at io.gravitee.repository.jdbc.management.JdbcApiRepository.findByCriteria(JdbcApiRepository.java:272)
	at io.gravitee.repository.jdbc.management.JdbcApiRepository.search(JdbcApiRepository.java:212)
	at io.gravitee.management.repository.proxy.ApiRepositoryProxy.search(ApiRepositoryProxy.java:70)
	at io.gravitee.management.services.sync.SyncManager.synchronizeApis(SyncManager.java:116)
	at io.gravitee.management.services.sync.SyncManager.refresh(SyncManager.java:94)
	at io.gravitee.management.services.sync.ScheduledSyncService.doSync(ScheduledSyncService.java:86)
	at io.gravitee.management.services.sync.ScheduledSyncService.run(ScheduledSyncService.java:76)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'api_lifecycle_state'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:444)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:678)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 18 common frames omitted
12:43:20.152 [refresher-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select av.*, a.id, a.name, a.description, a.version, a.deployed_at, a.created_at, a.updated_at, a.visibility, a.lifecycle_state, a.picture, a.api_lifecycle_state from apis a left join api_views av on a.id = av.api_id order by a.name]; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'api_lifecycle_state'.
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1444)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:632)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:728)
	at io.gravitee.repository.jdbc.management.JdbcApiRepository.findByCriteria(JdbcApiRepository.java:272)
	at io.gravitee.repository.jdbc.management.JdbcApiRepository.search(JdbcApiRepository.java:212)
	at io.gravitee.management.repository.proxy.ApiRepositoryProxy.search(ApiRepositoryProxy.java:70)
	at io.gravitee.management.service.impl.ApiServiceImpl.findAllLight(ApiServiceImpl.java:702)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy42.findAllLight(Unknown Source)
	at io.gravitee.management.services.subscriptions.ScheduledSubscriptionsService.run(ScheduledSubscriptionsService.java:88)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'api_lifecycle_state'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:444)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:678)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 28 common frames omitted
```

```
13:04:39.983 [graviteeio-node] ERROR i.g.r.j.c.AbstractJdbcRepositoryConfiguration - Failed to set up database: 
liquibase.exception.MigrationFailedException: Migration failed for change set liquibase/changelogs/v1_25_2/schema.yml::1.25.2::GraviteeSource Team:
     Reason: liquibase.exception.DatabaseException: The object 'pk_ratelimit' is dependent on column 'key'. [Failed SQL: (5074) ALTER TABLE ratelimit ALTER COLUMN [key] nvarchar(128)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:646)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at io.gravitee.repository.jdbc.common.AbstractJdbcRepositoryConfiguration.runLiquibase(AbstractJdbcRepositoryConfiguration.java:159)
	at io.gravitee.repository.jdbc.common.AbstractJdbcRepositoryConfiguration.graviteeDataSource(AbstractJdbcRepositoryConfiguration.java:113)
	at io.gravitee.repository.jdbc.common.AbstractJdbcRepositoryConfiguration.setApplicationContext(AbstractJdbcRepositoryConfiguration.java:84)
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:120)
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:96)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1754)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at io.gravitee.plugin.core.internal.PluginContextFactoryImpl.create(PluginContextFactoryImpl.java:59)
	at io.gravitee.management.repository.plugins.RepositoryPluginHandler.loadRepository(RepositoryPluginHandler.java:122)
	at io.gravitee.management.repository.plugins.RepositoryPluginHandler.handle(RepositoryPluginHandler.java:99)
	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:112)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:110)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:107)
	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:88)
	at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:74)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.gravitee.management.standalone.boostrap.Bootstrap.start(Bootstrap.java:162)
	at io.gravitee.management.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)
Caused by: liquibase.exception.DatabaseException: The object 'pk_ratelimit' is dependent on column 'key'. [Failed SQL: (5074) ALTER TABLE ratelimit ALTER COLUMN [key] nvarchar(128)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:402)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1273)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1255)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:609)
	... 63 common frames omitted
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The object 'pk_ratelimit' is dependent on column 'key'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:398)
	... 68 common frames omitted
```

**Comment by aelamrani** [comment]
Which version of the plugin JDBC are you using?

**Comment by StodaraHodan** [comment]
We use gravitee-repository-jdbc-1.30.2

**Comment by aelamrani** [comment]
Ok, can you share the starting logs of the management API?

**Comment by StodaraHodan** [comment]
Hi, i attached the log, we upgraded to graviteeio-management-api-1.30.5 since it became available in the meantime.

We also switched to mongodb which works with no issues, so we are no longer pursuing mssql for our deployment since we don't really trust the production worthiness of this implementation but i try to help find the cause of this issue

[gravitee_2020-03-02.log](https://github.com/gravitee-io/issues/files/4286276/gravitee_2020-03-02.log)

**Comment by aelamrani** [comment]
Ok, here you can find the supported versions: https://docs.gravitee.io/apim_installguide_repositories_jdbc.html

Which exact version are you using?

MSSQL Server 2017 CUXX?

**Comment by StodaraHodan** [comment]
We use 14.0.3257.3 so that is SQL Server 2017 CU18 Enterprise Edition.
The Database is a member in an Always ON Availability Group

**Comment by aelamrani** [comment]
Ok so we are supporting officially until CU12.

**Comment by aelamrani** [comment]
@StodaraHodan i'm able to reproduce, i'll fix it. Thanks for having reporting this.
