### ISSUE TITLE
[gravitee-gateway]mvn clean compile exec:java ... start error

### ISSUE THREAD

**Issue by JanWarlen** [gravitee-io/issues#3286]
### Current Behavior

17:35:20.428 [io.gravitee.gateway.standalone.GatewayContainer.main()] [] INFO  i.g.g.r.p.RepositoryPluginHandler - Repository [MANAGEMENT] loaded by mongodb
17:35:20.487 [io.gravitee.gateway.standalone.GatewayContainer.main()] [] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [io.gravitee.repository.mongodb.management.ManagementRepositoryConfiguration]; nested exception is java.io.FileNotFoundException: class path resource [io/gravitee/repository/management/api/ThemeRepository.class] cannot be opened because it does not exist
17:35:20.489 [io.gravitee.gateway.standalone.GatewayContainer.main()] [] ERROR i.g.p.c.i.PluginContextFactoryImpl - Unable to refresh plugin context
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [io.gravitee.repository.mongodb.management.ManagementRepositoryConfiguration]; nested exception is java.io.FileNotFoundException: class path resource [io/gravitee/repository/management/api/ThemeRepository.class] cannot be opened because it does not exist
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:181)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
        at io.gravitee.plugin.core.internal.PluginContextFactoryImpl.create(PluginContextFactoryImpl.java:59)
        at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.loadRepository(RepositoryPluginHandler.java:128)
        at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.handle(RepositoryPluginHandler.java:101)
        at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:112)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:110)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:107)
        at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:88)
        at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:74)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.gateway.standalone.GatewayContainer.main(GatewayContainer.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: class path resource [io/gravitee/repository/management/api/ThemeRepository.class] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:51)
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
        at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123)
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81)
        at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:685)
        at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getInterfaces(ConfigurationClassParser.java:1011)
        at org.springframework.context.annotation.ConfigurationClassParser.processInterfaces(ConfigurationClassParser.java:375)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:323)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:191)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:295)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:167)
        ... 49 common frames omitted
17:35:20.491 [io.gravitee.gateway.standalone.GatewayContainer.main()] [] ERROR i.g.g.r.p.RepositoryPluginHandler - Unexpected error while creating context for repository instance
java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@d7baee has not been refreshed yet
        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1092)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1104)
        at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.registerRepositoryDefinitions(RepositoryPluginHandler.java:153)
        at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.loadRepository(RepositoryPluginHandler.java:136)
        at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.handle(RepositoryPluginHandler.java:101)
        at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:112)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:110)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:107)
        at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:88)
        at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:74)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.gateway.standalone.GatewayContainer.main(GatewayContainer.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:748)
17:35:20.491 [io.gravitee.gateway.standalone.GatewayContainer.main()] [] ERROR i.g.g.r.p.RepositoryPluginHandler - Unable to load repository MANAGEMENT for scope repository-mongodb. Retry in 5 seconds...
### Steps to Reproduce (for bugs)

1. mvn clean compile exec:java -Pdev -pl gravitee-gateway-standalone/gravitee-gateway-standalone-container
2.
3.
4.

### Your Environment

* Version used: 
* Browser Name and version: gravitee-gateway branch:1.30.x
* Operating System and version: mac 10.15.2 (19C57)

**Comment by JanWarlen** [comment]
[start.log](https://github.com/gravitee-io/issues/files/4287559/start.log)

**Comment by aelamrani** [comment]
```
Copying gravitee-repository-mongodb-3.0.0-SNAPSHOT.zip
``` 
That's your problem here.

You cannot start the Gateway 1.30.X with the MongoDB plugin on 3.0.0-SNAPSHOT (master branch).

**Comment by JanWarlen** [comment]
> ```
> Copying gravitee-repository-mongodb-3.0.0-SNAPSHOT.zip
> ```
> 
> That's your problem here.
> 
> You cannot start the Gateway 1.30.X with the MongoDB plugin on 3.0.0-SNAPSHOT (master branch).

branch is 1.30.x,not master....i'm so sure about this.

**Comment by JanWarlen** [comment]
this was referenced by "gravitee-gateway/gravitee-gateway-standalone/gravitee-gateway-standalone-container/pom.xml/",the config used version is "<version>LATEST</version>",maybe should change this into definite version number?

**Comment by JanWarlen** [comment]
i switched into tag "1.30.5",and this errror still there.

**Comment by JanWarlen** [comment]
![image](https://user-images.githubusercontent.com/9626238/75956649-496a7980-5ef3-11ea-99c9-8a778b5792ef.png)
this solved problem,but i cannot understand...

**Comment by JanWarlen** [comment]
i deleted local jar cache,try re-compile,this is compile log
`Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/gravitee/repository/gravitee-repository-mongodb/maven-metadata.xml (2.5 kB at 2.1 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/gravitee/repository/gravitee-repository-mongodb/3.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/gravitee/repository/gravitee-repository-mongodb/3.0.0-SNAPSHOT/maven-metadata.xml (972 B at 1.6 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/gravitee/repository/gravitee-repository-mongodb/3.0.0-SNAPSHOT/gravitee-repository-mongodb-3.0.0-20200228.123155-6.zip
`

**Comment by JanWarlen** [comment]
![image](https://user-images.githubusercontent.com/9626238/75958400-1cb86100-5ef7-11ea-86ec-3b9113d05e8b.png)
after specify the version,the error not happen again
`[INFO] Configured Artifact: io.gravitee.repository:gravitee-repository-mongodb:1.30.3:zip
Downloading from maven2: http://110:8081/content/groups/public/io/gravitee/repository/gravitee-repository-mongodb/1.30.3/gravitee-repository-mongodb-1.30.3.zip
Downloaded from maven2: http://110:8081/content/groups/public/io/gravitee/repository/gravitee-repository-mongodb/1.30.3/gravitee-repository-mongodb-1.30.3.zip (12 MB at 142 kB/s)
[INFO] Configured Artifact: io.gravitee.repository:gravitee-repository-elasticsearch:1.30.3:zip
Downloading from maven2: http://110:8081/content/groups/public/io/gravitee/repository/gravitee-repository-elasticsearch/1.30.3/gravitee-repository-elasticsearch-1.30.3.zip
Downloaded from maven2: http://11:8081/content/groups/public/io/gravitee/repository/gravitee-repository-elasticsearch/1.30.3/gravitee-repository-elasticsearch-1.30.3.zip (5.3 MB at 135 kB/s)
`

**Comment by brasseld** [comment]
Obviously.

We have to find a way to fix the correct version on different branch.

Thanks for your feedback!

**Comment by JanWarlen** [comment]
Lol,this is really good product,appreciate your work.
let's make it better
