### ISSUE TITLE
[kubernetes] [gateway] Gateway doesn`t start because of error 

### ISSUE THREAD

**Issue by xrow** [gravitee-io/issues#3327]
### Expected Behavior
All apps should start

### Current Behavior
Gateway doesn`t start

The log shows:

```
10:25:10.287 [graviteeio-node] [] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpServerConfiguration': Unsatisfied dependency expressed through field 'port'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "tcp://172.29.115.207:8080"
--
  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpServerConfiguration': Unsatisfied dependency expressed through field 'port'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "tcp://172.29.115.207:8080"
  | at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
  | at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
  | at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
  | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
  | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
  | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
  | at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
  | at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
  | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
  | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
  | at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
  | at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
  | at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
  | at io.gravitee.node.container.spring.SpringBasedContainer.initializeContext(SpringBasedContainer.java:61)
  | at io.gravitee.node.container.spring.SpringBasedContainer.initialize(SpringBasedContainer.java:51)
  | at io.gravitee.node.container.AbstractContainer.<init>(AbstractContainer.java:41)
  | at io.gravitee.node.container.spring.SpringBasedContainer.<init>(SpringBasedContainer.java:44)
  | at io.gravitee.gateway.standalone.GatewayContainer.<init>(GatewayContainer.java:27)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at java.lang.Class.newInstance(Class.java:442)
  | at io.gravitee.gateway.standalone.boostrap.Bootstrap.init(Bootstrap.java:56)
  | at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:158)
  | at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)
  | Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "tcp://172.29.115.207:8080"
  | at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:79)
  | at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1195)
  | at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
  | at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
  | ... 25 more
  | Caused by: java.lang.NumberFormatException: For input string: "tcp://172.29.115.207:8080"
  | at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  | at java.lang.Integer.parseInt(Integer.java:580)
  | at java.lang.Integer.valueOf(Integer.java:766)
  | at org.springframework.util.NumberUtils.parseNumber(NumberUtils.java:211)
  | at org.springframework.beans.propertyeditors.CustomNumberEditor.setAsText(CustomNumberEditor.java:115)
  | at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:429)
  | at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:402)
  | at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:155)
  | at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)
  | ... 28 more


```

### Possible Solution
unkown

### Steps to Reproduce (for bugs)

1. helm upgrade --install graviteeio-apim graviteeio/apim

### Context
Can`t install the app

### Your Environment

* Version used: latest
* Operating System and version: OpenShift 3.11 on Centos 7

**Comment by brasseld** [comment]
Hi @xrow 

Can you share how you configure the gateway ?
It seems that one of the value you're setting is wrong.
