### ISSUE TITLE
[repository] [mongodb] Error with CosmosDB (Mongo 3.6) and TTL index at startup

### ISSUE THREAD

**Issue by LoicTosser** [gravitee-io/issues#3374]
We are using Gravitee with Azure CosmosDB as database. We are trying to migrate our CosmosDB Mongo API version from 3.2 to 3.6.
After database migration, Gravitee doesn't start anymore, because of a CosmosDB error when creating TTL index on `command` collection.
Here is the code where the index is created
With CosmosDB, TTL index creation is only possible for `_ts` field (https://docs.microsoft.com/bs-latn-ba/azure/cosmos-db/mongodb-time-to-live). Otherwise, an error is thrown. That's what happens in our case.
And after this error, as many Spring beans were not able to been instanciate, Spring context is not up and Gravitee is not able to start.

### Expected Behavior
Gravitee is able to start with mongodb repository plugin and CosmosDB database with Mongo API 3.6.

### Current Behavior
While mongodb repository plugin initialization, we first encounter this exception: 
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoCommandRepository': Invocation of init method failed; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 2 (BadValue): 'The 'expireAfterSeconds' option is supported on '_ts' field only.' on server apimgt-euw-dev-cosmos-01-westeurope.mongo.cosmos.azure.com:10255. The full response is { "ok" : 0.0, "errmsg" : "The 'expireAfterSeconds' option is supported on '_ts' field only.", "code" : 2, "codeName" : "BadValue" }; nested exception is com.mongodb.MongoCommandException: Command failed with error 2 (BadValue): 'The 'expireAfterSeconds' option is supported on '_ts' field only.' on server apimgt-euw-dev-cosmos-01-westeurope.mongo.cosmos.azure.com:10255. The full response is { "ok" : 0.0, "errmsg" : "The 'expireAfterSeconds' option is supported on '_ts' field only.", "code" : 2, "codeName" : "BadValue" }
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1754)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at io.gravitee.plugin.core.internal.PluginContextFactoryImpl.create(PluginContextFactoryImpl.java:59)
	at io.gravitee.management.repository.plugins.RepositoryPluginHandler.handle(RepositoryPluginHandler.java:93)
	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:111)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:109)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:106)
	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:88)
	at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:74)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.management.standalone.boostrap.Bootstrap.start(Bootstrap.java:162)
	at io.gravitee.management.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)

Caused by: org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 2 (BadValue): 'The 'expireAfterSeconds' option is supported on '_ts' field only.' on server apimgt-euw-dev-cosmos-01-westeurope.mongo.cosmos.azure.com:10255. The full response is { "ok" : 0.0, "errmsg" : "The 'expireAfterSeconds' option is supported on '_ts' field only.", "code" : 2, "codeName" : "BadValue" }; nested exception is com.mongodb.MongoCommandException: Command failed with error 2 (BadValue): 'The 'expireAfterSeconds' option is supported on '_ts' field only.' on server apimgt-euw-dev-cosmos-01-westeurope.mongo.cosmos.azure.com:10255. The full response is { "ok" : 0.0, "errmsg" : "The 'expireAfterSeconds' option is supported on '_ts' field only.", "code" : 2, "codeName" : "BadValue" }
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:138)
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2774)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:540)
	at org.springframework.data.mongodb.core.DefaultIndexOperations.execute(DefaultIndexOperations.java:218)
	at org.springframework.data.mongodb.core.DefaultIndexOperations.ensureIndex(DefaultIndexOperations.java:121)
	at io.gravitee.repository.mongodb.management.MongoCommandRepository.ensureTTLIndex(MongoCommandRepository.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 52 common frames omitted

Caused by: com.mongodb.MongoCommandException: Command failed with error 2 (BadValue): 'The 'expireAfterSeconds' option is supported on '_ts' field only.' on server apimgt-euw-dev-cosmos-01-westeurope.mongo.cosmos.azure.com:10255. The full response is { "ok" : 0.0, "errmsg" : "The 'expireAfterSeconds' option is supported on '_ts' field only.", "code" : 2, "codeName" : "BadValue" }
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:293)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:242)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:233)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:170)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:163)
	at com.mongodb.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:174)
	at com.mongodb.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:169)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:448)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:410)
	at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:169)
	at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:70)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:193)
	at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:805)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:788)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:783)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:768)
	at org.springframework.data.mongodb.core.DefaultIndexOperations.lambda$ensureIndex$0(DefaultIndexOperations.java:135)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:538)
	... 62 common frames omitted
```
Then, a lot of this kind of exceptions:

```
java.lang.NullPointerException: null
	at io.gravitee.management.repository.proxy.DictionaryRepositoryProxy.findAll(DictionaryRepositoryProxy.java:51)
	at io.gravitee.management.services.sync.SyncManager.synchronizeDictionaries(SyncManager.java:154)
	at io.gravitee.management.services.sync.SyncManager.refresh(SyncManager.java:100)
	at io.gravitee.management.services.sync.ScheduledSyncService.doSync(ScheduledSyncService.java:86)
	at io.gravitee.management.services.sync.ScheduledSyncService.run(ScheduledSyncService.java:76)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

And 

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'graviteeTransactionManager' available: No matching PlatformTransactionManager bean found for qualifier 'graviteeTransactionManager' - neither qualifier match nor bean name match!
	at org.springframework.beans.factory.annotation.BeanFactoryAnnotationUtils.qualifiedBeanOfType(BeanFactoryAnnotationUtils.java:136)
	at org.springframework.beans.factory.annotation.BeanFactoryAnnotationUtils.qualifiedBeanOfType(BeanFactoryAnnotationUtils.java:95)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.determineQualifiedTransactionManager(TransactionAspectSupport.java:406)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.determineTransactionManager(TransactionAspectSupport.java:384)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:284)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy56.search(Unknown Source)
	at io.gravitee.management.services.search.ScheduledSearchIndexerService.run(ScheduledSearchIndexerService.java:92)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Possible Solution
The problem seems to be issued from this part of code (`io.gravitee.repository.mongodb.management.MongoCommandRepository` class):

```
@PostConstruct
    public void ensureTTLIndex() {
        mongoOperations.indexOps("commands").ensureIndex(new IndexDefinition() {
            @Override
            public Document getIndexKeys() {
                return new Document("expiredAt", 1L);
            }

            @Override
            public Document getIndexOptions() {
                // To expire Documents at a Specific Clock Time we have to specify an expireAfterSeconds value of 0.
                return new Document("expireAfterSeconds", 0L);
            }
        });
    }
```
With CosmosDB, TTL index creation is only possible for `_ts` field (https://docs.microsoft.com/bs-latn-ba/azure/cosmos-db/mongodb-time-to-live). Here you're trying to create a TTL index on `expiredAt` field.
A solution could be to use a Spring property for the field name. by default, it is set to `expiredAt`, but it is possible to change it. Therefore, CosmosDB users would be albe to set it to `_ts`  and be compliant with CosmosDB behaviour.

### Steps to Reproduce (for bugs)
1. Configure Gravitee to run with a CosmosDB database, with Mongo API 3.6
2. Start Gravitee
[firstException.txt](https://github.com/gravitee-io/issues/files/4386650/firstException.txt)

### Context
We are trying to migrate our CosmosDB Mongo API version from 3.2 to 3.6. We migrate our existing CosmosDB database (Mongo 3.2) to another one (Mongo 3.6).

### Your Environment
* Version used: 1.25.9
* MongoDB repository plugin version: 1.25.1
* Spring-data-mongo version: 2.1.5.RELEASE
* mongo driver version: 3.8.0
* CosmosDB database Mongo API: 3.6

**Comment by LoicTosser** [comment]
And I guess the problem would be the same with the index created in `io.gravitee.repository.mongodb.ratelimit.MongoRateLimitRepository` class, even if this time it's the reactive stack that is used.

**Comment by LoicTosser** [comment]
We didn't encounter this error with a CosmosDB database with Mongo API version 3.2, because in this version, the TTL per document is a preview feature and is not activated.
But, even if we don't have any error, the TTL index is not working. The old documents are not cleaned up.
As the rate limiting collection has also a TTL index, I'm wondering about the impacts of such an incorrect behaviour. Does the rate limiting feature work correctly if documents are not automatically cleaned up?

**Comment by NicolasGeraud** [comment]
Hi @LoicTosser ,

Indeed we do not officially support CosmoDB and we will not support an override feature for mongo document attribute because otherwise, all upgrade scripts that we will provide have a risk to not working. 

> Does the rate limiting feature work correctly if documents are not automatically cleaned up?

Yes, we always programmatically if the data is still valid because Mongodb cannot guarantee that out of date document are not present.

**Comment by bestkanthed** [comment]
So what's the solution?
How to make it work?

**Comment by brasseld** [comment]
@bestkanthed 

No solution at all, we are not supporting anymore CosmoDB because of this `_ts`
