### ISSUE TITLE
[management] export API with enum value in lowercase

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#3406]
Currently, when we export API the enum values are in uppercase
Like on the rest api, the enum values can be filled in lowercase

**Comment by jhaeyaert** [comment]
This has repercussions on the gateway which can no longer deploy APIs because now events are serialized using lower case enum while gateway expect them in uppercase.

Before:

```
{
    "_id" : "8e020337-c530-472f-8203-37c530c72f66",
    "type" : "START_API",
    "payload" : "{\n  
....
 \"updatedAt\" : 1587455615658,\n  \"visibility\" : \"PRIVATE\",\n  \"lifecycleState\" : \"STARTED\",\n  \"apiLifecycleState\" : \"CREATED\"\n}",
    "properties" : {
        "api_id" : "12342fd2-8fa0-4d04-b42f-d28fa08d04d3",
        "origin" : "127.0.0.1",
        "user" : "ae0d50c4-dbcc-4271-8d50-c4dbcc527155"
    },
    "createdAt" : ISODate("2020-04-21T07:53:35.658Z"),
    "updatedAt" : ISODate("2020-04-21T07:53:35.658Z"),
    "_class" : "io.gravitee.repository.mongodb.management.internal.model.EventMongo"
}
```

After:

```
{
    "_id" : "66597e01-7d29-4b07-997e-017d298b07d9",
    "type" : "STOP_API",
    "payload" : "{\n  
.....
  \"updatedAt\" : 1588352166916,\n  \"visibility\" : \"private\",\n  \"lifecycleState\" : \"stopped\",\n  \"apiLifecycleState\" : \"created\"\n}",
    "properties" : {
        "api_id" : "f7410e00-df3b-4955-810e-00df3b49559b",
        "origin" : "127.0.0.1",
        "user" : "ae0d50c4-dbcc-4271-8d50-c4dbcc527155"
    },
    "createdAt" : ISODate("2020-05-01T16:56:07.076Z"),
    "updatedAt" : ISODate("2020-05-01T16:56:07.076Z"),
    "_class" : "io.gravitee.repository.mongodb.management.internal.model.EventMongo"
}
```

@brasseld special attention should be paid to version 1.30.10, which is scheduled to be released

I reopen the issue as a reminder waiting for a decision.

```
18:32:15.012 [sync-1] [] ERROR i.g.g.services.sync.SyncManager - Error while determining deployed APIs store into events payload
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `io.gravitee.repository.management.model.Visibility` from String "private": not one of the values accepted for Enum class: [PUBLIC, PRIVATE]
 at [Source: (String)"{
  "id" : "f7410e00-df3b-4955-810e-00df3b49559b",
  "name" : "echo",
  "description" : "echo",
  "version" : "1.0",
  "definition" : "{\n  \"id\" : \"f7410e00-df3b-4955-810e-00df3b49559b\",\n  \"name\" : \"echo\",\n  \"version\" : \"1.0\",\n  \"proxy\" : {\n    \"virtual_hosts\" : [ {\n      \"path\" : \"/test\"\n    } ],\n    \"strip_context_path\" : false,\n    \"preserve_host\" : false,\n    \"groups\" : [ {\n      \"name\" : \"default-group\",\n      \"endpoints\" : [ {\n        \"name\" : "[truncated 864 chars]; line: 10, column: 18] (through reference chain: io.gravitee.repository.management.model.Api["visibility"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1679)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:935)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3182)
	at io.gravitee.gateway.services.sync.SyncManager.lambda$computeApiEvents$11(SyncManager.java:224)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at io.gravitee.gateway.services.sync.SyncManager.computeApiEvents(SyncManager.java:212)
	at io.gravitee.gateway.services.sync.SyncManager.synchronizeApis(SyncManager.java:153)
	at io.gravitee.gateway.services.sync.SyncManager.refresh(SyncManager.java:101)
	at io.gravitee.gateway.services.sync.ScheduledSyncService.run(ScheduledSyncService.java:87)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by brasseld** [comment]
Already fixed by https://github.com/gravitee-io/gravitee-gateway/pull/520
