### ISSUE TITLE
Error setting available processors

### ISSUE THREAD

**Issue by aibar** [gravitee-io/issues#3430]
I'm trying to run gravitee api manager using docker-compose https://docs.gravitee.io/apim/1.x/apim_installguide_docker_compose.html

### Expected Behavior
All services up and running

### Current Behavior
gateway and management_api docker containers are restarting. Here is the docker container short log:
`Caused by: java.lang.IllegalArgumentException: availableProcessors: 0 (expected: > 0)
	at io.netty.util.internal.ObjectUtil.checkPositive(ObjectUtil.java:44)
	at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:44)
	at io.netty.util.NettyRuntime$AvailableProcessorsHolder.availableProcessors(NettyRuntime.java:70)
	at io.netty.util.NettyRuntime.availableProcessors(NettyRuntime.java:98)
	at io.netty.channel.MultithreadEventLoopGroup.<clinit>(MultithreadEventLoopGroup.java:41)`

**Comment by brasseld** [comment]
Hi @aibar 

Seems there are no core cpu to run the processes...

Please check your docker host configuration.

Regards,
