### ISSUE TITLE
[repository] [mongodb] Mongo db.auth(user,password) is return 1 but  gravitee.io console log is return unauthenticated

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#3501]
The log is ;

```
Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server agwdevdb01.com.tr:27017. The full response is {"ok": 0.0, "errmsg": "Authentication failed.", "code": 18, "codeName": "AuthenticationFailed"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:303)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:259)
	at com.mongodb.internal.connection.Comm
```

**Comment by jinshuchu** [comment]
Have you solved it ，I have the same problem

**Comment by brasseld** [comment]
It is probably due to a misconfiguration from gravitee.yml
