### ISSUE TITLE
[reporter] [file] Gateway seems to fail to load FileReporter plugin

### ISSUE THREAD

**Issue by tapiiron** [gravitee-io/issues#3915]
APIM: gateway seems to fail to load FileReporter plugin.

### Expected Behavior
Filereporter plugin on gateway instances seem to fail on start. The gateway does start without problems.

### Current Behavior
When starting the gw instance getting this on log files:
13:26:05.592 [graviteeio-node] [] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.gravitee.reporter.file.FileReporter': Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError            
13:26:05.623 [graviteeio-node] [] ERROR i.g.p.c.i.PluginContextFactoryImpl - Unable to refresh plugin context
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.gravitee.reporter.file.FileReporter': Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError 

access logs dont seem to be updated on access because of this failed plugin load.

### Possible Solution
-

### Steps to Reproduce (for bugs)
1. start gateway instance
2. check the logs for filereporter exceptions
3. notice that gw access.logs wont update

### Context
Access logs are quite important when auditing or debugging the system. 

### Your Environment
* Version used: 1.30.11
* Operating System and version: Linux RHEL8, PostgreSQL10, Java11

**Comment by brasseld** [comment]
Can you provide full stack trace ?

**Comment by tapiiron** [comment]
Sure can. It follows:
13:26:05.592 [graviteeio-node] [] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.gravitee.reporter.file.FileReporter': Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
13:26:05.623 [graviteeio-node] [] ERROR i.g.p.c.i.PluginContextFactoryImpl - Unable to refresh plugin context
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.gravitee.reporter.file.FileReporter': Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1320)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at io.gravitee.plugin.core.internal.PluginContextFactoryImpl.create(PluginContextFactoryImpl.java:59)
        at io.gravitee.plugin.core.internal.PluginContextFactoryImpl.create(PluginContextFactoryImpl.java:73)
        at io.gravitee.plugin.core.api.AbstractSpringPluginHandler.handle(AbstractSpringPluginHandler.java:42)
        at io.gravitee.plugin.core.api.AbstractPluginHandler.handle(AbstractPluginHandler.java:66)
        at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:112)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:110)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:107)
        at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:93)
        at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:74)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:162)
        at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)
Caused by: java.lang.ExceptionInInitializerError: null
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                                                                                             at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1312)
        ... 53 common frames omitted
Caused by: java.lang.NullPointerException: null
        at java.base/java.lang.String$CaseInsensitiveComparator.compare(String.java:1224)
        at java.base/java.lang.String$CaseInsensitiveComparator.compare(String.java:1218)
        at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
        at java.base/java.util.TreeMap.getEntry(TreeMap.java:343)
        at java.base/java.util.TreeMap.containsKey(TreeMap.java:231)
        at org.apache.commons.lang3.time.FastDateParser$TimeZoneStrategy.<init>(FastDateParser.java:784)
        at org.apache.commons.lang3.time.FastDateParser.getLocaleSpecificStrategy(FastDateParser.java:570)
        at org.apache.commons.lang3.time.FastDateParser.getStrategy(FastDateParser.java:539)
        at org.apache.commons.lang3.time.FastDateParser.init(FastDateParser.java:174)
        at org.apache.commons.lang3.time.FastDateParser.<init>(FastDateParser.java:145)
        at org.apache.commons.lang3.time.FastDateFormat.<init>(FastDateFormat.java:395)
        at org.apache.commons.lang3.time.FastDateFormat.<init>(FastDateFormat.java:379)
        at org.apache.commons.lang3.time.FastDateFormat$1.createInstance(FastDateFormat.java:101)
        at org.apache.commons.lang3.time.FastDateFormat$1.createInstance(FastDateFormat.java:98)
        at org.apache.commons.lang3.time.FormatCache.getInstance(FormatCache.java:82)
        at org.apache.commons.lang3.time.FastDateFormat.getInstance(FastDateFormat.java:129)
        at io.gravitee.reporter.file.FileReporter.<clinit>(FileReporter.java:57)
        ... 60 common frames omitted
13:26:05.623 [graviteeio-node] [] ERROR i.g.n.r.plugin.ReporterPluginHandler - Unexpected error while creating file
java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@22decfa2 has not been refreshed yet
        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1095)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
        at io.gravitee.plugin.core.api.AbstractSpringPluginHandler.handle(AbstractSpringPluginHandler.java:43)
        at io.gravitee.plugin.core.api.AbstractPluginHandler.handle(AbstractPluginHandler.java:66)
        at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:112)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:110)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:107)
        at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:93)
        at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:74)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:162)
        at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)

**Comment by brasseld** [comment]
Hi @tapiiron 

Which JDK version?

**Comment by tapiiron** [comment]
java -version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10-LTS, mixed mode, sharing)

**Comment by brasseld** [comment]
Ok, there is some issues with commons-lang3.

We have to upgrade the dependency: https://github.com/apache/commons-lang/pull/117
