### ISSUE TITLE
[management] Audit stackoverflow

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3990]
```
07:13:35.990 [gravitee-listener-83] ERROR i.g.m.rest.provider.ThrowableMapper - Internal error
java.lang.StackOverflowError: null
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
	at io.gravitee.management.service.impl.AuditServiceImpl.createApplicationAuditLog(AuditServiceImpl.java:259)
```

**Comment by phiz71** [comment]
duplicates  #3991 ? ;)
