### ISSUE TITLE
[management] nimbus dependency is missing

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#4184]
It is required to load identity providers such as the OAuth2 Generic IDP.

```
at io.gravitee.am.management.handlers.management.api.idp.impl.IdentityProviderManagerImpl.loadUserProvider(IdentityProviderManagerImpl.java:50)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at io.gravitee.am.management.handlers.management.api.idp.impl.IdentityProviderManagerImpl.afterPropertiesSet(IdentityProviderManagerImpl.java:46)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758)
	... 42 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.nimbusds.jose.JWSAlgorithm
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 87 common frames omitted
```

**Comment by bcollard** [comment]
solves #4084 ? :)
