### ISSUE TITLE
[JWT Plan] need some help configuring my first JWT plan in gravitee

### ISSUE THREAD

**Issue by tboksebeld** [gravitee-io/issues#4188]
Ola !
My first time using gravitee. All seems very nice so far, but i am now trying to secure an API through an JWT plan and I have to ask some help. I do not get what's wrong, but gateway seems to not be able to find my idp's jwk at the JWKS_URL. 
Could be an issue at plan configuration, or inside my idp itself. not sure and i would like your mind about it.

I got configured my API in management.
Ofc I tried first using a keyless plan.
Everything works fine, my API is reachable through the gateway.
Now, it's time for JWT plan configuration.
Thank you for your help.

### Question
Do you see any error in my configuration that should explain my current problem ?
Is there any prerequisite in the IDP JWKS json that I would have to know and I didn't get ? (I could share it to you if necessary)

### Current Behavior

My JWT plan is configured like that :
`{
   "_id":"006d7d80-2e5b-4c4f-ad7d-802e5b2c4f2b",
   "name":"JWT",
   "description":"JWT",
   "validation":"MANUAL",
   "type":"API",
   "status":"PUBLISHED",
   "security":"JWT",
   "order":1,
   "api":"bab761a1-229b-477e-b761-a1229ba77e33",
   "definition":"{\n  \"/\" : [ ]\n}",
   "characteristics":[],
   "publishedAt":{
      "$date":"2020-08-13T15:14:17.540Z"
   },
   "securityDefinition":"{\"signature\":\"RSA_RS256\",\"publicKeyResolver\":\"JWKS_URL\",\"extractClaims\":false,\"propagateAuthHeader\":true,\"userClaim\":\"sub\",\"resolverParameter\":\"https://OIDCAppUrl/jwks\"}",
   "needRedeployAt":{
      "$date":"2020-08-13T15:43:59.219Z"
   },
   "commentRequired":false,
   "createdAt":{
      "$date":"2020-08-13T15:14:14.770Z"
   },
   "updatedAt":{
      "$date":"2020-08-13T15:43:59.219Z"
   },
   "_class":"io.gravitee.repository.mongodb.management.internal.model.PlanMongo"
}`

Then, 
- I published&redeployed my Api (keyless plan is now closed, jwt plan is published)
- I created an Application with the correct client_id, and subscribed to the API JWT Plan
- I accepted the subscription in the Api

I did many many tests while applying the configuration step by step. I got many many 401 response again and again. But now, everything should be well configured for me, and the result is always the same : 401 Unauthorized !

At this step, according to gateway's log, the issue should be "easy" to determine, and I hope, to solve.

> 13:31:37.044 [vert.x-eventloop-thread-3] [] ERROR io.gravitee.policy.jwt.JWTPolicy - [request-id:43651db0-3406-4bc8-a51d-b03406dbc881] [request-path:/my-api] java.lang.IllegalArgumentException: The JWK source must not be null,
java.lang.IllegalArgumentException: The JWK source must not be null,
	at com.nimbusds.jose.proc.AbstractJWKSelectorWithSource.<init>(AbstractJWKSelectorWithSource.java:48),
	at com.nimbusds.jose.proc.JWSVerificationKeySelector.<init>(JWSVerificationKeySelector.java:71),
	at io.gravitee.policy.jwt.processor.JWKSKeyProcessor.jwsKeySelector(JWKSKeyProcessor.java:32),
	at io.gravitee.policy.jwt.processor.AbstractKeyProcessor.lambda$process$0(AbstractKeyProcessor.java:54),
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source),
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source),
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source),
	at io.gravitee.policy.jwt.vertx.VertxCompletableFuture.lambda$new$2(VertxCompletableFuture.java:85),
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source),
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source),
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source),
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source),
	at io.gravitee.policy.jwt.vertx.VertxCompletableFuture.completeFromAsyncResult(VertxCompletableFuture.java:736),
	at io.gravitee.policy.jwt.vertx.VertxCompletableFuture.lambda$from$6(VertxCompletableFuture.java:174),
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107),
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152),
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113),
	at io.gravitee.policy.jwt.jwks.retriever.VertxResourceRetriever$1$1.handle(VertxResourceRetriever.java:64),
	at io.gravitee.policy.jwt.jwks.retriever.VertxResourceRetriever$1$1.handle(VertxResourceRetriever.java:61),
	at io.vertx.core.http.impl.HttpClientResponseImpl$BodyHandler.notifyHandler(HttpClientResponseImpl.java:292),
	at io.vertx.core.http.impl.HttpClientResponseImpl.lambda$bodyHandler$0(HttpClientResponseImpl.java:193),
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:248),
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$beginResponse$0(Http1xClientConnection.java:480),
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237),
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127),
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.endResponse(Http1xClientConnection.java:499),
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.access$000(Http1xClientConnection.java:237),
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:634),
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:584),
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:566),
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369),
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43),
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232),
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173),
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379),
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365),
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357),
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436),
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324),
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296),
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251),
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379),
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365),
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357),
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518),
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267),
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314),
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501),
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440),
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276),
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379),
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365),
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357),
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410),
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379),
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365),
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919),
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163),
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714),
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650),
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576),
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493),
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989),
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74),
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30),
	at java.base/java.lang.Thread.run(Unknown Source),

I went to the _gravitee-policy-jwt_ checking the code by myself to understand what's wrong with my configuration or my idp jwks, but it starts to be too tricky for me.

**Comment by tboksebeld** [comment]
Soooooo, I finally get to make it "work". Yipee.
Here are some notes about my obstacle course, just in case it could help someone.

My first problem was `java.lang.IllegalArgumentException: The JWK source must not be null`
As the log mention it, the problem occure when Gravitee wants to load the JWKS (using `com.nimbusds.jose`) from my IdentityProvider endpoint.
In my case, I am using `JWKS_URL` as `JWKS resolver mode`.

- Be sure the url you provide is reachable by gateway's server (you can easy test it by connecting locally and wget it)
- It could be nice if the verification(s) could be down directly inside Management UI IHM, but it's fine. (reachability, and parsing !!!!). What do you think  about it?

Then, it was not over for me... I can not completly explain why, but my jwks endpoint is providing a result that is not parsable by `com.nimbusds.jose` (-_-)
I understood it using this online parser : https://8gwifi.org/jwkconvertfunctions.jsp

-  I didn't get what is wrong with my IdentityProvider on this point... I know that is around the "x5c" property which cause errors, but I have no detail. 
- If you have knowledge about it, plz share ;)

I switch to another OIDC server, and JWKS parsing worked well.

-----------

At this point, when I was calling my API with my token, I didn't get error anymore in the gateway log file. But, always an `401 Unauthorize` response... 
But I had an error in my API's Analytics' Logs IHM, in Management UI : `JOSE header "typ" (type) "at+jwt" not allowed`

Well, here I don't know exactly why it does not work again. `typ` is a property of my access token. `at-jwt` means `access-token jwt`. JOSE library have changed recently. Now, it accepts ONLY `JWT` value on this property (by default, without any specific configuration) :

- https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/366/caused-by
- https://stackoverflow.com/questions/61952366/decode-of-jwt-error-when-token-type-is-atjwt-for-spring-boot-2-2-7
- https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/ee6aec33c6349ebc85de37f4b76da7f1feeb0ee5#chg-src/main/java/com/nimbusds/jose/proc/DefaultJOSEObjectTypeVerifier.java

I have a kind of solution. I am using my `ID_TOKEN` and not my `ACCESS_TOKEN` to call my API. `Id_token` seems to have `JWT` in `typ` property. 
**With this one, it "works", I reach my API.**

- however, I don't know if this is really a solution
- do you think it is good to use the id_token?
- the `at+jwt` value provided in my access_token is deprecated or something ?
- some post talk about add `jwtProcessor.setJWSTypeVerifier(new DefaultJOSEObjectTypeVerifier(new JOSEObjectType("at+jwt")));` to allow `at+jwt`. What do you think about this point ?

**Comment by aelamrani** [comment]
Thanks for sharing your experience.

Can we close the issue or do you think we can improve something?
