### ISSUE TITLE
[gateway] Chunked responses do not pass through the gateway

### ISSUE THREAD

**Issue by bursauxa** [gravitee-io/issues#4189]
We have a service that returns chunked data. This is properly handled with the `Transfer-Encoding: chunked` header. We can not work around this, as a single response potentially represents gigabytes of data.

Calling the service directly works fine.

We have an existing installation of Gravitee 1.29.5 were this service is declared as an API, and it works fine too.

We have a new installation of Gravitee 3.1.2 and calling the same API does not work: the connection between gateway and  backend is interrupted after a few bytes, and the client never receives any data (although the connection between client and gateway itself is not interrupted , `curl` just outputs nothing until manually interrupted).

The API was manually recreated in the 3.1.2 UI, as we started from a brand new empty Mongo. So this is not an issue with database migration.

**Comment by bursauxa** [comment]
This may be related to https://github.com/gravitee-io/issues/issues/4156, but in our case it is a plain old HTTP GET, no Stomp is involved.

This may also be related to https://github.com/gravitee-io/issues/issues/4169 as we noticed similar errors in our logs, but could not be sure they were linked to the interrupted requests. In addition, we do not have any rate-limiting set on this API.

**Comment by gianx89** [comment]
I think it's related too to https://github.com/gravitee-io/issues/issues/4156 .

Not a "small" problem for us.

**Comment by brasseld** [comment]
Hi @bursauxa 

Do you have any particular logs from the gateway console / log file?

**Comment by bursauxa** [comment]
First I have this, although I never receive a 401 error code (I just never receive anything):

```
08:36:20.011 [vert.x-eventloop-thread-3] [] WARN  i.g.g.h.a.p.plan.PlanPolicyResolver - No plan has been selected to process request 29054aa1-90e2-4a9a-854a-a190e2ba9abd. Returning an unauthorized HTTP status (401)
```

And at some point later:

```
08:37:26.002 [vert.x-eventloop-thread-3] [] ERROR i.g.g.h.c.http.HttpProxyConnection - Unexpected error while handling backend response for request GET http://<redacted> - Connection was closed
08:37:26.003 [vert.x-eventloop-thread-3] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
	at io.gravitee.gateway.http.connector.http.HttpProxyConnection.lambda$handleUpstreamResponse$8(HttpProxyConnection.java:181)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleException(HttpClientResponseImpl.java:263)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleException(Http1xClientConnection.java:526)
	at io.vertx.core.http.impl.Http1xClientConnection.handleClosed(Http1xClientConnection.java:800)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$4(VertxHandler.java:162)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:224)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:162)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:288)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by brasseld** [comment]
Hi @bursauxa 

That is most probably a duplicate of https://github.com/gravitee-io/issues/issues/4175

We are looking to release 3.1.3 very soon.

**Comment by gianx89** [comment]
@brasseld could be really related to this one? Chunked responses, but with websockets and stomp https://github.com/gravitee-io/issues/issues/4156

**Comment by loriepisicchio** [comment]
Hello @bursauxa. The issue #4175 have been fixed and released in APIM 3.1.3. Could you please check that it also solves your issue ?

**Comment by bursauxa** [comment]
Hello @loriepisicchio and @brasseld 

I completed integration and tests of 3.1.3 from the distribution downloads, and things are working fine again. Thanks!

**Comment by brasseld** [comment]
Thanks for your feedback @bursauxa!

Cheers,
