### ISSUE TITLE
[management-api] Startup repository error when using MySQL plugin/driver

### ISSUE THREAD

**Issue by StephaneTrebel** [gravitee-io/issues#4255]
### Expected Behavior
Repository should be properly created in MySQL database

### Current Behavior
When using MySQL connector driver 8.0.21 and graviteeio mysql plugin 3.1.3 with a 8.0.15 MySQL instance, repository is not created and this is logged:

```
15:14:45.233 [graviteeio-node] INFO  i.g.r.a.r.p.RepositoryPluginHandler - Repository [MANAGEMENT] loaded by jdbc
15:14:57.144 [graviteeio-node] ERROR liquibase.changelog.ChangeSet - Change Set liquibase/changelogs/v3_0_0/schema.yml::3.0.0::GraviteeSource Team failed.  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system, created_at, updated_at) select 'ORGANIZATION', r.name, r.description, r.' at line 1 [Failed SQL: (1064) insert into roles (scope, name, description, default_role, system, created_at, updated_at) select 'ORGANIZATION', r.name, r.description, r.default_role, r.system, r.created_at, r.updated_at from roles r where r.scope = 'MANAGEMENT' and exists (select 1 from role_permissions rp where rp.role_id = CONCAT('ORGANIZATION_',r.name))]
15:14:57.165 [graviteeio-node] ERROR i.g.r.j.c.AbstractJdbcRepositoryConfiguration - Failed to set up database:
liquibase.exception.MigrationFailedException: Migration failed for change set liquibase/changelogs/v3_0_0/schema.yml::3.0.0::GraviteeSource Team:
     Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system, created_at, updated_at) select 'ORGANIZATION', r.name, r.description, r.' at line 1 [Failed SQL: (1064) insert into roles (scope, name, description, default_role, system, created_at, updated_at) select 'ORGANIZATION', r.name, r.description, r.default_role, r.system, r.created_at, r.updated_at from roles r where r.scope = 'MANAGEMENT' and exists (select 1 from role_permissions rp where rp.role_id = CONCAT('ORGANIZATION_',r.name))]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:646)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
…
```

This is a brand new install so I dropped and recreated the database and the issue is the same.

Additionally, I tried the aforementioned query in mysql CLI and there is indeed an issue:
```
mysql> insert into roles (scope, name, description, default_role, system, created_at, updated_at) select 'ORGANIZATION', r.name, r.description, r.default_role, r.system, r.created_at, r.updated_at from roles r where r.scope = 'MANAGEMENT' and exists (select 1 from role_permissions rp where rp.role_id = CONCAT('ORGANIZATION_',r.name))
    -> ;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system, created_at, updated_at) select 'ORGANIZATION', r.name, r.description, r.' at line 1
```

### Possible Solution
Maybe there is an issue in liquibase query generation ?

### Steps to Reproduce (for bugs)
1. Download mysql-connector and mount it in `/opt/graviteeio-management-api/lib/ext/`
2. Download gravitee-repository-jdbc-3.1.3.zip and mount it in `/opt/graviteeio-management-api/plugin-ext`
3. Set GRAVITEE_PLUGINS_PATH_0 to `/opt/graviteeio-management-api/plugins`
4. Set GRAVITEE_PLUGINS_PATH_1 to `/opt/graviteeio-management-api/plugins-ext`
5. Set GRAVITEE_MANAGEMENT_TYPE to `jdbc`
6. Set GRAVITEE_MANAGEMENT_JDBC_URL to jdbc:mysql://host:port/database?useSSL=false&user=user&password=password
7. Create a brand new `gravitee` database on MySQL 8.0 instance
8. Start gravitee-management-api (I do it through our own docker-compose)

### Context
I'm trying to setup graviteeio with a MySQL instance because my target deployment will not support MongoDB (it's an Azure MySQL instance).
I tried without JDBC (so only MongoDB) and it worked fine.

### Your Environment
* Version used: 3.1.3
* Operating System and version: docker 19, docker-compose 1.26, mysql server 8.0.15

**Comment by jhaeyaert** [comment]
'system' is now a keyword since mysql 8.0.3 (see https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-8-0-S).
We need to escape it.
