### ISSUE TITLE
[management-api] How to connect to LDAP from API Management

### ISSUE THREAD

**Issue by kyooki210** [gravitee-io/issues#4330]
i want my gravitee API Management to connect to LDAP

### Expected Behavior

i can login with user from my LDAP connection
### Current Behavior
cannot connect to LDAP

### Your Environment
* Version used: gravitee 1.28.0
* Browser Name and version: Chrome 85.0.4183.102 (Official Build) (64-bit)
* Operating System and version: windows server 2016

**Comment by brasseld** [comment]
Hi @kyooki210 

Any stacktrace to share ?

**Comment by kyooki210** [comment]
hi, 
this is my setting for LDAP.. 

- type: ldap
      context:
        username: "uid=SD,ou=Head Office"
        password: "******"
        url: "ldap://ipipip:port/dc=id,dc=co,dc=ciputralife-local"
        base: "c=id,c=co,o=ciputralife-local"
      authentication:
        user:
          base: "o=Head Office"
          filter: "uid={0}"
        group:
          base: "o=Users"
          filter: "member={0}"
          role:
            attribute: "cn"
            mapper: {
              GRAVITEE-USERS: User
            }
      lookup:
        user:
          base: "o=Head Office"
          filter: "(&(objectClass=User)(|(cn=*{0}*)(uid={0})))"

**Comment by kyooki210** [comment]
when i want to login to API Management Portal with my LDAP User, its always say username or password wrong..

**Comment by brasseld** [comment]
No particular stack trace in the management-api logs ?

**Comment by kyooki210** [comment]
![image](https://user-images.githubusercontent.com/30793405/93991444-85452d80-fdb6-11ea-9990-5b46c08927ce.png)

**Comment by kyooki210** [comment]
no error.. when i try to connect, i see in console log the message was Unauthorized..

**Comment by kyooki210** [comment]
its the message in browser console log.. Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by brasseld** [comment]
Can you change log level for LDAP from logback.xml (management-api) to check what's going wrong?

**Comment by kyooki210** [comment]
how to do it sir?

**Comment by kyooki210** [comment]
sorry, i found how to do it.. i got this error, [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903D3, comment: AcceptSecurityContext error, data 52e, v3839 ]

**Comment by kyooki210** [comment]
when i search about that error, it says invalid credential.. i was input the correct credential..

**Comment by brasseld** [comment]
Are you sure about the `dn` for the username you are using to authenticate to the LDAP?

**Comment by kyooki210** [comment]
yes.. even i try login with mine, it still happening..

**Comment by kyooki210** [comment]
my current setup : 
- type: ldap
      password-encoding-algo: none
      context:
        url: "ldap://ipipipipip:389/dc=xxx,dc=co,dc=id"
        base: "dc=xxx,dc=co,dc=id"
      authentication:
        user:
          base: "o=Head Office"
          filter: "uid={0}"
        group:
          base: "o=Head Office"
          filter: "member={0}"
          role:
            attribute: "uid"
            mapper: {
              GRAVITEE-ADMINS: ADMIN,
              GRAVITEE-USERS: USER
            }
      lookup:
        user:
          base: "o=Head Office"
          filter: "(objectClass=User)"

**Comment by kyooki210** [comment]
now the error was like this : 
java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:459)
	at org.springframework.ldap.core.support.SimpleDirContextAuthenticationStrategy.setupEnvironment(SimpleDirContextAuthenticationStrategy.java:42)
	at org.springframework.security.ldap.DefaultSpringSecurityContextSource$1.setupEnvironment(DefaultSpringSecurityContextSource.java:94)
	at org.springframework.ldap.core.support.AbstractContextSource.setupAuthenticatedEnvironment(AbstractContextSource.java:194)
	at org.springframework.ldap.core.support.AbstractContextSource.getAuthenticatedEnv(AbstractContextSource.java:582)
	at org.springframework.ldap.core.support.AbstractContextSource.doGetContext(AbstractContextSource.java:134)
	at org.springframework.ldap.core.support.AbstractContextSource.getReadOnlyContext(AbstractContextSource.java:158)
	at org.springframework.ldap.core.LdapTemplate.executeReadOnly(LdapTemplate.java:802)
	at org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForSingleEntry(SpringSecurityLdapTemplate.java:316)
	at org.springframework.security.ldap.search.FilterBasedLdapUserSearch.searchForUser(FilterBasedLdapUserSearch.java:128)
	at org.springframework.security.ldap.authentication.BindAuthenticator.authenticate(BindAuthenticator.java:95)
	at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:187)
	at org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:85)
	at io.gravitee.management.idp.ldap.authentication.LdapAuthenticationProviderProxy.authenticate(LdapAuthenticationProviderProxy.java:43)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:200)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:180)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at io.gravitee.management.security.filter.JWTAuthenticationFilter.doFilter(JWTAuthenticationFilter.java:128)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kyooki210** [comment]
when i use this setup, it always return  [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903D3, comment: AcceptSecurityContext error, data 52e, v3839 ]

- type: ldap
      password-encoding-algo: none
      context:
        username: "uid=CIPUTRALIFE\\\\sd,ou=ou"
        password: "Rasuna123!"
        url: "ldap://ipipipip:389/dc=xxxx,dc=co,dc=id"
        base: "ou=ou"
      authentication:
        user:
          base: "ou=ou"
          filter: "uid={0}"
        group:
          base: "ou=ou"
          filter: "member={0}"
          role:
            attribute: "cn"
            mapper: {
              GRAVITEE-ADMINS: ADMIN,
              GRAVITEE-USERS: USER
            }
      lookup:
        user:
          base: "ou=ou"
          filter: "(&(objectClass=Person)(uid={0}))"

**Comment by kyooki210** [comment]
where did i do wrong sir?

**Comment by brasseld** [comment]
Think the username should be something like:

`username: "uid=SD,ou=Head Office,dc=id,dc=co,dc=ciputralife-local"`

**Comment by kyooki210** [comment]
try that, the result was same.. [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903D3, comment: AcceptSecurityContext error, data 52e, v3839 ]

**Comment by kyooki210** [comment]
its possible to connect to LDAP in API Management Portal without using Gravitee Access Management?

**Comment by aelamrani** [comment]
Hi @kyooki210 

Yes it is. It seems you have an invalid credentials error here.
