### ISSUE TITLE
[management-api] Update version Gravitee to 3.2.0

### ISSUE THREAD

**Issue by kyooki210** [gravitee-io/issues#4337]
My API List from gravitee 1.28.0 not show in API Management 3.2.0

### Expected Behavior
i want my API list from 1.28.0 show up in API Management 3.2.0

### Current Behavior
after upgrading to API Managament 3.2.0, my API from version 1.28.0 not show up

i attached the error log..
ERROR i.g.r.api.services.sync.SyncManager - Error while determining deployed APIs store into events payload
java.lang.NullPointerException: null
	at io.gravitee.rest.api.services.sync.SyncManager.convert(SyncManager.java:340)
	at io.gravitee.rest.api.services.sync.SyncManager.lambda$computeApiEvents$12(SyncManager.java:227)
	at java.util.HashMap.forEach(HashMap.java:1288)
	at io.gravitee.rest.api.services.sync.SyncManager.computeApiEvents(SyncManager.java:213)
	at io.gravitee.rest.api.services.sync.SyncManager.synchronizeApis(SyncManager.java:148)
	at io.gravitee.rest.api.services.sync.SyncManager.refresh(SyncManager.java:96)
	at io.gravitee.rest.api.services.sync.ScheduledSyncService.doSync(ScheduledSyncService.java:86)
	at io.gravitee.rest.api.services.sync.ScheduledSyncService.run(ScheduledSyncService.java:76)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by brasseld** [comment]
Hi @kyooki210 

Did you follow the migration guide ? 

https://docs.gravitee.io/apim/3.x/apim_installguide_migration.html

**Comment by kyooki210** [comment]
yes i did.. already running all the .js command too.. list api not show up, and the error still there..

**Comment by phiz71** [comment]
Hi @kyooki210, have you also launched this .js ?
https://github.com/gravitee-io/release/blob/master/upgrades/3.x/3.0.2/mongodb/1-rename-view-in-category.js

**Comment by kyooki210** [comment]
Yes sir.. all the script .js that are in the migration guide already run it.. the error still same.. and my api list not show up in new portal version 3.2.0..

**Comment by phiz71** [comment]
I think this error happens when the managment API try to load your APIs from the `events` collection, by parsing the `payload`.

Could you paste here the payload of one of your events (choose an event with type "START_API") ?

It should looks like this : 
`"payload" : "{\n  \"id\" : \"22826b2e-125c-4426-826b-2e125cb426cf\",\n  \"environmentId\" : \"DEFAULT\",\n  \"name\" : \"echo\",\n  \"description\" : \"Echo API\",\n  \"version\" : \"1.0\",\n  \"definition\" : \"{\\n  \\\"id\\\" : \\\"22826b2e-125c-4426-826b-2e125cb426cf\\\",\\n  \\\"name\\\" : \\\"echo\\\",\\n  \\\"version\\\" : \\\"1.0\\\",\\n  \\\"proxy\\\" : {\\n    \\\"virtual_hosts\\\" : [ {\\n      \\\"path\\\" : \\\"/echo\\\"\\n    } ],\\n    \\\"strip_context_path\\\" : false,\\n    \\\"preserve_host\\\" : false,\\n    \\\"groups\\\" : [ {\\n      \\\"name\\\" : \\\"default-group\\\",\\n      \\\"endpoints\\\" : [ {\\n        \\\"name\\\" : \\\"default\\\",\\n        \\\"target\\\" : \\\"http://localhost:8181\\\",\\n        \\\"weight\\\" : 1,\\n        \\\"backup\\\" : false,\\n        \\\"type\\\" : \\\"HTTP\\\",\\n        \\\"inherit\\\" : true\\n      } ],\\n      \\\"load_balancing\\\" : {\\n        \\\"type\\\" : \\\"ROUND_ROBIN\\\"\\n      },\\n      \\\"http\\\" : {\\n        \\\"connectTimeout\\\" : 5000,\\n        \\\"idleTimeout\\\" : 60000,\\n        \\\"keepAlive\\\" : true,\\n        \\\"readTimeout\\\" : 10000,\\n        \\\"pipelining\\\" : false,\\n        \\\"maxConcurrentConnections\\\" : 100,\\n        \\\"useCompression\\\" : true,\\n        \\\"followRedirects\\\" : false\\n      }\\n    } ]\\n  },\\n  \\\"paths\\\" : {\\n    \\\"/\\\" : [ ]\\n  },\\n  \\\"properties\\\" : [ ]\\n}\",\n  \"deployedAt\" : 1601018288582,\n  \"createdAt\" : 1601018282989,\n  \"updatedAt\" : 1601018288582,\n  \"visibility\" : \"PRIVATE\",\n  \"lifecycleState\" : \"STOPPED\",\n  \"disableMembershipNotifications\" : false,\n  \"apiLifecycleState\" : \"CREATED\"\n}"`
