### ISSUE TITLE
[notifier] [email] Exception when providing inline base64 image in message payload

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#4366]
```
18:02:51.090 [vert.x-eventloop-thread-7] [] INFO  c.g.a.n.n.i.NotificationServiceImpl - Fire a new notification for trigger id[dbe124da-1f58-4a0e-a124-da1f588a0e20] name[Erreur 500] source[REQUEST] severity[INFO]
sept. 30, 2020 6:02:51 PM io.vertx.core.impl.ContextImpl
GRAVE: Unhandled exception
java.lang.NoClassDefFoundError: com/sun/activation/registries/LogSupport
	at javax.activation.MimetypesFileTypeMap.<init>(MimetypesFileTypeMap.java:130)
	at javax.activation.FileTypeMap.getDefaultFileTypeMap(FileTypeMap.java:140)
	at io.gravitee.notifier.email.EmailNotifier.getContentTypeByFileName(EmailNotifier.java:167)
	at io.gravitee.notifier.email.EmailNotifier.addContentInMessage(EmailNotifier.java:151)
	at io.gravitee.notifier.email.EmailNotifier.doSend(EmailNotifier.java:94)
	at io.gravitee.notifier.api.AbstractNotifier.send(AbstractNotifier.java:47)
	at com.graviteesource.ae.notifier.notification.impl.NotificationServiceImpl.lambda$send$0(NotificationServiceImpl.java:78)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at com.graviteesource.ae.notifier.notification.impl.NotificationServiceImpl.lambda$send$1(NotificationServiceImpl.java:74)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
```

**Comment by aelamrani** [comment]
Seems to produce only with Java > 11 when an exception is thrown
