### ISSUE TITLE
kubernetes deployement api

### ISSUE THREAD

**Issue by aeoct** [gravitee-io/issues#4391]
hi

Kubernetes - Graviteeio

During gravteeio kubernetes deployement, i'm facing this error when api pod starts.

error log api message:
```shell

08:44:24.395 [graviteeio-node] INFO  i.g.r.a.s.impl.UpgraderServiceImpl - Running upgrader io.gravitee.rest.api.service.impl.upgrade.SearchIndexUpgrader
08:44:24.761 [graviteeio-node] INFO  i.g.r.a.s.impl.UpgraderServiceImpl - Running upgrader io.gravitee.rest.api.service.impl.upgrade.DefaultApiHeaderUpgrader
08:44:24.855 [SimpleAsyncTaskExecutor-1] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.index(io.gravitee.rest.api.model.search.Indexable,boolean)
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at io.gravitee.rest.api.service.impl.search.lucene.transformer.UserDocumentTransformer.transform(UserDocumentTransformer.java:79)
	at io.gravitee.rest.api.service.impl.search.lucene.transformer.UserDocumentTransformer.transform(UserDocumentTransformer.java:31)
	at io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.lambda$indexLocally$1(SearchEngineServiceImpl.java:175)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.indexLocally(SearchEngineServiceImpl.java:173)
	at io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.index(SearchEngineServiceImpl.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
08:44:25.065 [graviteeio-node] INFO  i.g.r.a.s.impl.UpgraderServiceImpl - Running upgrader io.gravitee.rest.api.service.impl.upgrade.IdentityProviderUpgrader

```

Log files:

[Logs API](https://drive.google.com/file/d/1S45cQ_F_p8zK2kEc7-J5ird5nvrQZ8no/view?usp=sharing)

[Logs Gateway](https://drive.google.com/file/d/1hB8OS6JMTGWw34KSpbC1fEYa8LQCEaZe/view?usp=sharing)

Yaml values file  used:

[YAML FILE](https://drive.google.com/file/d/12rcXzek6s61uClWcfzs8c6LW-vUpitr5/view?usp=sharing)

I'm looking for wich param i need to change (or add) in yaml to fix this.
Sorry for the probable lack of information

###Environment
Kubernetes v1.19.2
Helm v2.16.8
Docker 19.03.13
Rancher v2.4.8 

thx

**Comment by aelamrani** [comment]
Hi @aeoct 

Seems you have the issue referenced here: https://github.com/gravitee-io/issues/issues/4204

Can you check the version of Gravitee.io you are running?

**Comment by aeoct** [comment]
@aelamrani
 
i'm running version 3.1.3

**Comment by aelamrani** [comment]
Ok so move at least on a 3.1.4 (or a 3.2.x).

Waiting for your feedback.

**Comment by aeoct** [comment]
oups sorry.  v3.2.1 is ok 
Now i try to fix /managment 404 and /portal  errors.unexpected

thank you

**Comment by aeoct** [comment]
hi

I'm facing similar issue when 'graviteeio-apim3-ui'  and 'graviteeio-apim3-portal' start, when they open json file. 

**graviteeio-apim3-ui**
```yaml
image: graviteeio/apim-management-ui:latest
        imagePullPolicy: Always
```
Digest: sha256:1a7c3844af69996acc432deb68df26183a96a25a5192efe374cb7d6951b390d3

Logs: graviteeio-apim3-ui
```shell

2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO Backend set to env
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO Starting confd
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO Backend source(s) set to
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO /usr/share/nginx/html/constants.json has UID 0 should be 101
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO /usr/share/nginx/html/constants.json has GID 0 should be 101
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO /usr/share/nginx/html/constants.json has md5sum a8de7ca0c868ee5ab1affc4a7d9ae1e8 should be ff97bde2b7e7c488b29b08da1e673078
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO Target config /usr/share/nginx/html/constants.json out of sync
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: ERROR open /usr/share/nginx/html/constants.json: read-only file system
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO /etc/nginx/conf.d/default.conf has GID 0 should be 101
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO /etc/nginx/conf.d/default.conf has md5sum 411a0b28ff9b21a1cd94a6cb2ae2217d should be 32f9f14968ac47f311aaa48c98c991bf
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO Target config /etc/nginx/conf.d/default.conf out of sync
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: INFO Target config /etc/nginx/conf.d/default.conf has been updated
2020-10-08T18:41:22Z graviteeio-apim3-ui-546ddc6976-46vsn /bin/confd[6]: FATAL open /usr/share/nginx/html/constants.json: read-only file system
172.16.40.231 - - [08/Oct/2020:18:41:57 +0000] "GET / HTTP/1.1" 200 1215 "-" "kube-probe/1.15" "-"
```


**graviteeio-apim3-portal**
```yaml
image: graviteeio/apim-portal-ui:latest
        imagePullPolicy: Always
```
Digest: sha256:acf63d63a1451193d0e82d12e58c4e6665e064f6f939b26cda723e6f98036169

Logs: graviteeio-apim3-portal
```Shell
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO Backend set to env
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO Starting confd
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO Backend source(s) set to
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO /usr/share/nginx/html/assets/config.json has UID 0 should be 101
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO /usr/share/nginx/html/assets/config.json has GID 0 should be 101
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO /usr/share/nginx/html/assets/config.json has md5sum 68b4d48af9a261a62f9b6122d8cdbce5 should be 1a6bf2161cceffc5a40948fdb2b33d77
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO Target config /usr/share/nginx/html/assets/config.json out of sync
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: ERROR open /usr/share/nginx/html/assets/config.json: read-only file system
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO /etc/nginx/conf.d/default.conf has GID 0 should be 101
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO /etc/nginx/conf.d/default.conf has md5sum 411a0b28ff9b21a1cd94a6cb2ae2217d should be d3a274061048e4ad3e0a013f60c7323c
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO Target config /etc/nginx/conf.d/default.conf out of sync
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: INFO Target config /etc/nginx/conf.d/default.conf has been updated
2020-10-08T18:41:18Z graviteeio-apim3-portal-6d856cdd66-v55cm /bin/confd[6]: FATAL open /usr/share/nginx/html/assets/config.json: read-only file system

```

have i to change version?
 
thank you for your advice

**Comment by aelamrani** [comment]
IMHO it is not related to the initial issue. May I ask you to open another ticket?
