### ISSUE TITLE
[management] Cannot reorder a page anymore

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4417]
Seems introduced by this commit https://github.com/gravitee-io/gravitee-management-rest-api/commit/c3115398fc4eff3fb866d085a53624b0bce97e53

```
18:51:07.593 [gravitee-listener-204] ERROR i.g.r.a.m.r.provider.ThrowableMapper - Internal error
java.lang.NullPointerException: null
	at io.gravitee.rest.api.service.impl.PageServiceImpl.update(PageServiceImpl.java:970)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy59.update(Unknown Source)
	at io.gravitee.rest.api.management.rest.resource.ApiPageResource.partialUpdatePage(ApiPageResource.java:186)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by gcusnieux** [comment]
Backport #4655 to 3.2.x
