### ISSUE TITLE
[policy] [json-to-json] Error occurred while starting graviteeio-gateway in Windows 7 Env 

### ISSUE THREAD

**Issue by krish2609** [gravitee-io/issues#461]
An error occurs while starting component PluginRegistry - gravitee-policy-json-to-json-1.0.0
### Expected Behavior

1. Navigate to "graviteeio-full-1.3.3\graviteeio-gateway-1.3.3\bin"
2. Run gravitee.bat
3. garviteeio-gateway should start without any issues but its fail to start in windows 7 environment
### Current Behavior

Getting below exception while starting graviteeio-gateway and its looks like path issue:
14:16:07.376 [gravitee] [] ERROR i.g.g.standalone.node.GatewayNode - An error occurs while starting component PluginRegistry
java.nio.file.InvalidPathException: Illegal char <:> at index 137: G:\graviteeio\Graviteeio-bin\graviteeio-full-1.3.3\graviteeio-gateway-1.3.3\plugins\.work\gravitee-policy-json-to-json-1.0.0\/schemas/urn:jsonschema:io:gravitee:policy:json2json:configuration:JsonToJsonTransformationPolicyConfiguration.json
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at io.gravitee.plugin.core.utils.FileUtils$1.visitFile(FileUtils.java:86)
        at io.gravitee.plugin.core.utils.FileUtils$1.visitFile(FileUtils.java:82)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at io.gravitee.plugin.core.utils.FileUtils.unzip(FileUtils.java:82)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.loadPlugin(PluginRegistryImpl.java:166)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.loadPlugins(PluginRegistryImpl.java:114)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:101)
        at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:79)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.common.node.AbstractNode.doStart(AbstractNode.java:52)
        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
        at io.gravitee.gateway.standalone.Container.start(Container.java:108)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:162)
        at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)
14:16:07.381 [gravitee] [] ERROR i.g.gateway.standalone.Container - An unexpected error occurs while starting gateway

### Steps to Reproduce (for bugs)

1. Navigate to "graviteeio-full-1.3.3\graviteeio-gateway-1.3.3\bin"
2. Run gravitee.bat
3. garviteeio-gateway is not starting in windows 7 environment
4. verify the log for below details:
14:16:07.384 [gravitee] [] INFO  i.g.gateway.standalone.Container - Shutting-down Gravitee Gateway...
14:16:07.385 [gravitee] [] INFO  i.g.g.standalone.node.GatewayNode - Gravitee.io - Gateway is stopping
14:16:07.390 [gravitee] [] INFO  i.g.g.standalone.node.GatewayNode -    Stopping component: PluginEventListener
14:16:07.391 [gravitee] [] INFO  i.g.common.service.AbstractService - Destroying service io.gravitee.plugin.core.internal.PluginEventListener
14:16:07.392 [gravitee] [] INFO  i.g.g.standalone.node.GatewayNode - Gravitee.io - Gateway stopped

### Your Environment

* Version used: graviteeio-full-1.3.3
* Browser Name and version:
* Operating System and version: Windows7

**Comment by zapacila89** [comment]
Same problem on windows 10. 

It seems that after the plugin is unzipped, file "urn:jsonschema:io:gravitee:policy:json2json:configuration:JsonToJsonTransformationPolicyConfiguration.json" is missing from schema folder.

**Comment by NicolasGeraud** [comment]
hi @krish2609 this is a problem due to windows filesystem, 
we have fix this bug with #140 but this policy was forgotten.

Sorry for that, this will be fixed in the next release.
