### ISSUE TITLE
[policy] [cors] Error on call to api with policy CORS

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#464]
### Current Behavior

i put CORS policy on my api.
i deleted field Access-Control-Expose-Headers. 
When i call api, it's OK, return 200

if modify CORS policy but other fied, like add another allowed method. when i call api, i have error 503:
in gateway log:
13:14:59.616 [vert.x-eventloop-thread-3] [] ERROR i.g.g.p.impl.ResponsePolicyChain - Unexpected error while running policy io.gravitee.gateway.policy.impl.PolicyImpl@55809251
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:89)
        at io.gravitee.gateway.policy.impl.PolicyImpl.onResponse(PolicyImpl.java:50)
        at io.gravitee.gateway.policy.impl.ResponsePolicyChain.execute(ResponsePolicyChain.java:41)
 

when i look back on portal CORS policy and i delete expose Access-Control-Expose-Headers or fill field, call is OK

### Your Environment
* Version used: 1.3.3

**Comment by brasseld** [comment]
Hi @vdelattre 

I think you did not provide the complete stack trace. 
I do not see any trace about the CORS policy...
Are you able to provide us with the complete stack ?
