### ISSUE TITLE
 Cannot convert [PORTAL] to enum of type class io.gravitee.repository.management.model.Audit$AuditReferenceType

### ISSUE THREAD

**Issue by azizkhani** [gravitee-io/issues#4848]
```
gio_apim_management_api |       at com.github.dozermapper.core.converters.EnumConverter.convert(EnumConverter.java:44)
gio_apim_management_api |       ... 131 common frames omitted
gio_apim_management_api | 12:23:47.381 [gravitee-listener-72] ERROR i.g.r.a.m.r.provider.ThrowableMapper - Internal error
gio_apim_management_api | com.github.dozermapper.core.MappingException: Cannot convert [PORTAL] to enum of type class io.gravitee.repository.management.model.Audit$AuditReferenceType
gio_apim_management_api |       at com.github.dozermapper.core.util.MappingUtils.throwMappingException(MappingUtils.java:87)
gio_apim_management_api |       at com.github.dozermapper.core.converters.EnumConverter.convert(EnumConverter.java:47)
gio_apim_management_api |       at com.github.dozermapper.core.converters.PrimitiveOrWrapperConverter.convert(PrimitiveOrWrapperConverter.java:83)
gio_apim_management_api |       at com.github.dozermapper.core.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:497)
gio_apim_management_api |       at com.github.dozermapper.core.MappingProcessor.mapFromFieldMap(MappingProcessor.java:405)
gio_apim_management_api |       at com.github.dozermapper.core.MappingProcessor.mapField(MappingProcessor.java:355)
gio_apim_management_api |       at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:315)
gio_apim_management_api |       at com.github.dozermapper.core.MappingProcessor.mapToDestObject(MappingProcessor.java:264)
gio_apim_management_api |       at com.github.dozermapper.core.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:237)
gio_apim_management_api |       at com.github.dozermapper.core.MappingProcessor.mapGeneral(MappingProcessor.java:210)
gio_apim_management_api |       at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:133)
gio_apim_management_api |       at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:128)
gio_apim_management_api |       at com.github.dozermapper.core.DozerBeanMapper.map(DozerBeanMapper.java:129)
gio_apim_management_api |       at io.gravitee.repository.mongodb.management.mapper.GraviteeDozerMapper.map(GraviteeDozerMapper.java:43)
gio_apim_management_api |       at io.gravitee.repository.mongodb.management.mapper.GraviteeDozerMapper.collection2list(GraviteeDozerMapper.java:79)
gio_apim_management_api |       at io.gravitee.repository.mongodb.management.MongoAuditRepository.search(MongoAuditRepository.java:54)
gio_apim_management_api |       at io.gravitee.rest.api.repository.proxy.AuditRepositoryProxy.search(AuditRepositoryProxy.java:57)
gio_apim_management_api |       at io.gravitee.rest.api.service.impl.AuditServiceImpl.search(AuditServiceImpl.java:106)
gio_apim_management_api |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gio_apim_management_api |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
gio_apim_management_api |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
gio_apim_management_api |       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
gio_apim_management_api |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
gio_apim_management_api |       at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
gio_apim_management_api |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
gio_apim_management_api |       at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
gio_apim_management_api |       at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
gio_apim_management_api |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
gio_apim_management_api |       at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
gio_apim_management_api |       at com.sun.proxy.$Proxy37.search(Unknown Source)
gio_apim_management_api |       at io.gravitee.rest.api.management.rest.resource.AuditResource.getAudits(AuditResource.java:91)
gio_apim_management_api |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gio_apim_management_api |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
gio_apim_management_api |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
gio_apim_management_api |       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
gio_apim_management_api |       at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
gio_apim_management_api |       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
gio_apim_management_api |       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
gio_apim_management_api |       at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
gio_apim_management_api |       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
gio_apim_management_api |       at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
gio_apim_management_api |       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
gio_apim_management_api |       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
gio_apim_management_api |       at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
gio_apim_management_api |       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
gio_apim_management_api |       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
gio_apim_management_api |       at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
gio_apim_management_api |       at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
gio_apim_management_api |       at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
gio_apim_management_api |       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
gio_apim_management_api |       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
gio_apim_management_api |       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
gio_apim_management_api |       at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
gio_apim_management_api |       at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
gio_apim_management_api |       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
gio_apim_management_api |       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
gio_apim_management_api |       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
gio_apim_management_api |       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
gio_apim_management_api |       at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
gio_apim_management_api |       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
gio_apim_management_api |       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:155)
gio_apim_management_api |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at io.gravitee.rest.api.security.filter.TokenAuthenticationFilter.doFilter(TokenAuthenticationFilter.java:155)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at io.gravitee.rest.api.security.filter.RecaptchaFilter.doFilter(RecaptchaFilter.java:86)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at io.gravitee.rest.api.security.filter.CsrfIncludeFilter.doFilter(CsrfIncludeFilter.java:41)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
gio_apim_management_api |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
gio_apim_management_api |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
gio_apim_management_api |       at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
gio_apim_management_api |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
gio_apim_management_api |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
gio_apim_management_api |       at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
gio_apim_management_api |       at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
gio_apim_management_api |       at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
gio_apim_management_api |       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
gio_apim_management_api |       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
gio_apim_management_api |       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
gio_apim_management_api |       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
gio_apim_management_api |       at org.eclipse.jetty.server.Server.handle(Server.java:500)
gio_apim_management_api |       at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
gio_apim_management_api |       at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
gio_apim_management_api |       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
gio_apim_management_api |       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
gio_apim_management_api |       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
gio_apim_management_api |       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
gio_apim_management_api |       at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
gio_apim_management_api |       at java.base/java.lang.Thread.run(Unknown Source)
gio_apim_management_api | Caused by: java.lang.IllegalArgumentException: No enum constant io.gravitee.repository.management.model.Audit.AuditReferenceType.PORTAL
gio_apim_management_api |       at java.base/java.lang.Enum.valueOf(Unknown Source)
gio_apim_management_api |       at com.github.dozermapper.core.converters.EnumConverter.convert(EnumConverter.java:44)
gio_apim_management_api |       ... 131 common frames omitted

```

**Comment by aelamrani** [comment]
Same kind of issue as per https://github.com/gravitee-io/issues/issues/4845
