### ISSUE TITLE
API: failed to connect, no password specified?

### ISSUE THREAD

**Issue by wangfeng-1** [gravitee-io/issues#4861]
api version : 3.5.0
Account password configured
email:                                                          
  enabled: true                                              
  host: smtp.qiye.aliyun.com        
  subject: "[gravitee] %s"                                                      
  port: 465                                                                     
  from: xxxx                        
  username: xxxxx               
  password: xxxxxx        
  properties:                                                                   
    auth: true                                      
    starttls.enable: false                          
    localhost: xxxxx

06:18:00.457 [SimpleAsyncTaskExecutor-9] ERROR i.g.r.a.s.impl.EmailServiceImpl - Error while sending email notification
org.springframework.mail.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: failed to connect, no password specified?
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:440)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)
	at io.gravitee.rest.api.service.impl.EmailServiceImpl.sendEmailNotification(EmailServiceImpl.java:128)
	at io.gravitee.rest.api.service.impl.EmailServiceImpl.sendAsyncEmailNotification(EmailServiceImpl.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.mail.AuthenticationFailedException: failed to connect, no password specified?
	at javax.mail.Service.connect(Service.java:329)
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437)
	... 17 common frames omitted
06:18:00.458 [SimpleAsyncTaskExecutor-9] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void io.gravitee.rest.api.service.impl.EmailServiceImpl.sendAsyncEmailNotification(io.gravitee.rest.api.service.EmailNotification,io.gravitee.rest.api.service.common.GraviteeContext$ReferenceContext)
io.gravitee.rest.api.service.exceptions.TechnicalManagementException: Error while sending email notification
	at io.gravitee.rest.api.service.impl.EmailServiceImpl.sendEmailNotification(EmailServiceImpl.java:131)
	at io.gravitee.rest.api.service.impl.EmailServiceImpl.sendAsyncEmailNotification(EmailServiceImpl.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.mail.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: failed to connect, no password specified?
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:440)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)
	at io.gravitee.rest.api.service.impl.EmailServiceImpl.sendEmailNotification(EmailServiceImpl.java:128)
	... 14 common frames omitted
Caused by: javax.mail.AuthenticationFailedException: failed to connect, no password specified?
	at javax.mail.Service.connect(Service.java:329)
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437)
	... 17 common frames omitted

**Comment by brasseld** [comment]
Hi,

Can you ensure that the gravitee.yaml indentation is correct ?

Regards,

**Comment by wangfeng-1** [comment]
> Hi,
> 
> Can you ensure that the gravitee.yaml indentation is correct ?
> 
> Regards,

![image](https://user-images.githubusercontent.com/47658706/103399561-90111a80-4b7c-11eb-8dc9-5e657d18ae06.png)
Yes, I was deployed by Helm, established gravitee. YAMl as an indent that doesn't have a problem.

**Comment by brasseld** [comment]
I just have a try with a google mailbox and it's working fine. Can you please check your credentials ?

Regards,

**Comment by wangfeng-1** [comment]
> I just have a try with a google mailbox and it's working fine. Can you please check your credentials ?
> 
> Regards,

The problem is confirmed. Alicloud enterprise mailbox does not support TLS 587 protocol. Thank you for your help.
