### ISSUE TITLE
[gateway] [webauthn] AndroidSafetynetAttestation validation failure

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#4880]
```
2021-01-07 14:14:48:540     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    2021-01-07 14:14:48:540     at java.base/java.lang.Thread.run(Unknown Source)
    2021-01-07 14:14:48:518     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    2021-01-07 14:14:48:518     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    2021-01-07 14:14:48:517     at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
    2021-01-07 14:14:48:517     at com.mongodb.internal.connection.tlschannel.async.AsynchronousTlsChannel$3$1.run(AsynchronousTlsChannel.java:151)
    2021-01-07 14:14:48:517     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    2021-01-07 14:14:48:516     at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
    2021-01-07 14:14:48:516     at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
    2021-01-07 14:14:48:516     at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
    2021-01-07 14:14:48:515     at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:677)
    2021-01-07 14:14:48:515     at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:644)
    2021-01-07 14:14:48:514     at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
    2021-01-07 14:14:48:514     at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:399)
    2021-01-07 14:14:48:514     at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:376)
    2021-01-07 14:14:48:513     at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:253)
    2021-01-07 14:14:48:513     at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
    2021-01-07 14:14:48:513     at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:85)
    2021-01-07 14:14:48:513     at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:467)
    2021-01-07 14:14:48:513     at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:111)
    2021-01-07 14:14:48:512     at com.mongodb.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:412)
    2021-01-07 14:14:48:512     at com.mongodb.operation.CommandOperationHelper$10.onResult(CommandOperationHelper.java:481)
    2021-01-07 14:14:48:512     at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
    2021-01-07 14:14:48:511     at com.mongodb.async.client.OperationExecutorImpl$1$1$1.onResult(OperationExecutorImpl.java:94)
    2021-01-07 14:14:48:511     at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
    2021-01-07 14:14:48:511     at com.mongodb.operation.FindOperation$3.onResult(FindOperation.java:827)
    2021-01-07 14:14:48:510     at com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:53)
    2021-01-07 14:14:48:510     at com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:46)
    2021-01-07 14:14:48:510     at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
    2021-01-07 14:14:48:509     at com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:89)
    2021-01-07 14:14:48:509     at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:198)
    2021-01-07 14:14:48:509     at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:134)
    2021-01-07 14:14:48:509     at com.mongodb.async.client.MongoIterableSubscription.requestMoreData(MongoIterableSubscription.java:89)
    2021-01-07 14:14:48:508     at com.mongodb.async.client.AbstractSubscription.onComplete(AbstractSubscription.java:154)
    2021-01-07 14:14:48:508     at com.mongodb.async.client.AbstractSubscription.processResultsQueue(AbstractSubscription.java:225)
    2021-01-07 14:14:48:508     at com.mongodb.async.client.AbstractSubscription.tryProcessResultsQueue(AbstractSubscription.java:172)
    2021-01-07 14:14:48:508     at com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:105)
    2021-01-07 14:14:48:507     at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onComplete(ObservableFromPublisher.java:46)
    2021-01-07 14:14:48:507     at com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onComplete(ObservableToPublisher.java:76)
    2021-01-07 14:14:48:506     at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onSuccess(SingleResumeNext.java:65)
    2021-01-07 14:14:48:506     at io.reactivex.internal.operators.observable.ObservableCollectSingle$CollectObserver.onComplete(ObservableCollectSingle.java:119)
    2021-01-07 14:14:48:506     at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
    2021-01-07 14:14:48:505     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
    2021-01-07 14:14:48:503     at io.reactivex.Single.subscribe(Single.java:3666)
    2021-01-07 14:14:48:502     at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onSuccess(SingleResumeNext.java:65)
    2021-01-07 14:14:48:502     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
    2021-01-07 14:14:48:502     at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
    2021-01-07 14:14:48:501     at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onSuccess(MaybeFlatten.java:119)
    2021-01-07 14:14:48:501     at io.reactivex.internal.operators.maybe.MaybeFromSingle$FromSingleObserver.onSuccess(MaybeFromSingle.java:76)
    2021-01-07 14:14:48:500     at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onSuccess(SingleResumeNext.java:65)
    2021-01-07 14:14:48:500     at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle$SwitchIfEmptyMaybeObserver.onSuccess(MaybeSwitchIfEmptySingle.java:82)
    2021-01-07 14:14:48:500     at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:89)
    2021-01-07 14:14:48:499     at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
    2021-01-07 14:14:48:499     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
    2021-01-07 14:14:48:494     at io.vertx.reactivex.ext.web.RoutingContext.next(RoutingContext.java:123)
    2021-01-07 14:14:48:494     at io.reactivex.internal.operators.single.SingleDoFinally$DoFinallyObserver.runFinally(SingleDoFinally.java:97)
    2021-01-07 14:14:48:494     at io.reactivex.internal.operators.single.SingleDoFinally$DoFinallyObserver.onSuccess(SingleDoFinally.java:74)
    2021-01-07 14:14:48:493     at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:153)
    2021-01-07 14:14:48:493     at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
    2021-01-07 14:14:48:493     at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
    2021-01-07 14:14:48:493     at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:160)
    2021-01-07 14:14:48:492     at io.gravitee.am.gateway.handler.common.vertx.web.handler.impl.internal.PolicyChainHandlerImpl.resolve(PolicyChainHandlerImpl.java:110)
    2021-01-07 14:14:48:492     at io.gravitee.am.gateway.handler.common.vertx.web.handler.impl.internal.PolicyChainHandlerImpl.handle(PolicyChainHandlerImpl.java:69)
    2021-01-07 14:14:48:492     at io.gravitee.am.gateway.handler.common.vertx.web.handler.impl.internal.PolicyChainHandlerImpl.handle(PolicyChainHandlerImpl.java:47)
    2021-01-07 14:14:48:492     at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:155)
    2021-01-07 14:14:48:491     at io.reactivex.Single.subscribe(Single.java:3666)
    2021-01-07 14:14:48:491     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
    2021-01-07 14:14:48:491     at io.reactivex.Single.subscribe(Single.java:3666)
    2021-01-07 14:14:48:491     at io.reactivex.Single.subscribe(Single.java:3652)
    2021-01-07 14:14:48:490     at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
    2021-01-07 14:14:48:490     at io.reactivex.Observable.subscribe(Observable.java:12284)
    2021-01-07 14:14:48:490     at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
    2021-01-07 14:14:48:490     at io.reactivex.Single.subscribe(Single.java:3666)
    2021-01-07 14:14:48:490     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
    2021-01-07 14:14:48:484     at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
    2021-01-07 14:14:48:484     at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:113)
    2021-01-07 14:14:48:484     at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:58)
    2021-01-07 14:14:48:484     at io.reactivex.Observable.subscribe(Observable.java:12284)
    2021-01-07 14:14:48:483     at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
    2021-01-07 14:14:48:483     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
    2021-01-07 14:14:48:483     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
    2021-01-07 14:14:48:483     at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:111)
    2021-01-07 14:14:48:482     at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:160)
    2021-01-07 14:14:48:482     at io.vertx.reactivex.ext.web.RoutingContext.next(RoutingContext.java:123)
    2021-01-07 14:14:48:482     at io.gravitee.am.gateway.handler.common.vertx.web.handler.impl.internal.PolicyChainHandlerImpl.lambda$handle$3(PolicyChainHandlerImpl.java:79)
    2021-01-07 14:14:48:482     at io.gravitee.am.gateway.handler.common.vertx.web.handler.impl.internal.PolicyChainHandlerImpl.lambda$resolve$4(PolicyChainHandlerImpl.java:111)
    2021-01-07 14:14:48:481     at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:153)
    2021-01-07 14:14:48:481     at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
    2021-01-07 14:14:48:481     at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
    2021-01-07 14:14:48:480     at io.gravitee.am.gateway.handler.root.resources.handler.client.ClientRequestParseHandler.handle(ClientRequestParseHandler.java:55)
    2021-01-07 14:14:48:480     at io.gravitee.am.gateway.handler.root.resources.handler.client.ClientRequestParseHandler.handle(ClientRequestParseHandler.java:34)
    2021-01-07 14:14:48:480     at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:155)
    2021-01-07 14:14:48:479     at io.reactivex.Maybe.subscribeWith(Maybe.java:4360)
    2021-01-07 14:14:48:479     at io.reactivex.Maybe.subscribe(Maybe.java:4277)
    2021-01-07 14:14:48:479     at io.gravitee.am.gateway.handler.root.resources.handler.client.ClientRequestParseHandler.authenticate(ClientRequestParseHandler.java:75)
    2021-01-07 14:14:48:478     at io.reactivex.internal.operators.maybe.MaybeJust.subscribeActual(MaybeJust.java:36)
    2021-01-07 14:14:48:478     at io.reactivex.Maybe.subscribe(Maybe.java:4290)
    2021-01-07 14:14:48:477     at io.gravitee.am.gateway.handler.root.resources.handler.client.ClientRequestParseHandler.lambda$handle$0(ClientRequestParseHandler.java:64)
    2021-01-07 14:14:48:477     at io.gravitee.am.gateway.handler.root.resources.handler.client.ClientRequestParseHandler.lambda$authenticate$1(ClientRequestParseHandler.java:76)
    2021-01-07 14:14:48:477     at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onSuccess(MaybeCallbackObserver.java:71)
    2021-01-07 14:14:48:476     at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:160)
    2021-01-07 14:14:48:476     at io.vertx.reactivex.ext.web.RoutingContext.next(RoutingContext.java:123)
    2021-01-07 14:14:48:475     at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:153)
    2021-01-07 14:14:48:475     at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
    2021-01-07 14:14:48:475     at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:95)
    2021-01-07 14:14:48:474     at io.gravitee.am.gateway.handler.root.resources.handler.webauthn.WebAuthnAccessHandler.handle(WebAuthnAccessHandler.java:30)
    2021-01-07 14:14:48:474     at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:155)
    2021-01-07 14:14:48:473     at io.vertx.reactivex.ext.web.RoutingContext.next(RoutingContext.java:123)
    2021-01-07 14:14:48:473     at io.gravitee.am.gateway.handler.root.resources.handler.webauthn.WebAuthnAccessHandler.handle(WebAuthnAccessHandler.java:46)
    2021-01-07 14:14:48:462     at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:95)
    2021-01-07 14:14:48:462     at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:160)
    2021-01-07 14:14:48:461     at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:153)
    2021-01-07 14:14:48:461     at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
    2021-01-07 14:14:48:460     at io.gravitee.am.gateway.handler.root.resources.endpoint.webauthn.WebAuthnResponseEndpoint.handle(WebAuthnResponseEndpoint.java:109)
    2021-01-07 14:14:48:460     at io.gravitee.am.gateway.handler.root.resources.endpoint.webauthn.WebAuthnResponseEndpoint.handle(WebAuthnResponseEndpoint.java:56)
    2021-01-07 14:14:48:460     at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:155)
    2021-01-07 14:14:48:459     at io.gravitee.am.gateway.handler.vertx.auth.webauthn.impl.WebAuthnImpl.verifyWebAuthNCreate(WebAuthnImpl.java:526)
    2021-01-07 14:14:48:459     at io.gravitee.am.gateway.handler.vertx.auth.webauthn.impl.WebAuthnImpl.authenticate(WebAuthnImpl.java:379)
    2021-01-07 14:14:48:458     at java.base/java.util.Base64$Decoder.decode(Unknown Source)
    2021-01-07 14:14:48:458     at io.gravitee.am.gateway.handler.vertx.auth.webauthn.impl.attestation.AndroidSafetynetAttestation.validate(AndroidSafetynetAttestation.java:107)
    2021-01-07 14:14:48:457     at java.base/java.util.Base64$Decoder.decode(Unknown Source)
    2021-01-07 14:14:48:456 java.lang.IllegalArgumentException: Illegal base64 character 2f
    2021-01-07 14:14:48:456     at java.base/java.util.Base64$Decoder.decode0(Unknown Source)
    2021-01-07 14:14:48:454 14:14:48.453 [async-channel-group-0-handler-executor] [] ERROR i.g.a.g.h.r.r.e.w.WebAuthnResponseEndpoint - Unexpected exception
```

**Comment by tcompiegne** [comment]
```
2021-01-19 19:51:59:963		at io.gravitee.am.gateway.handler.vertx.auth.webauthn.impl.attestation.AndroidSafetynetAttestation.validate(AndroidSafetynetAttestation.java:156)
	2021-01-19 19:51:59:963		at io.gravitee.am.gateway.handler.vertx.auth.webauthn.impl.WebAuthnImpl.verifyWebAuthNCreate(WebAuthnImpl.java:526)
	2021-01-19 19:51:59:962	java.lang.NullPointerException: null
```
