### ISSUE TITLE
[management] Unexpected error while generating API definition

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#5042]
While trying to access the list of APIs in the console I get this error:

```
08:04:24.940 [gravitee-listener-225] ERROR i.g.r.a.service.impl.ApiServiceImpl - Unexpected error while generating API definition
com.fasterxml.jackson.databind.JsonMappingException: Index -1 out of bounds for length 6
 at [Source: UNKNOWN; line: -1, column: -1]
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:274)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1844)
	at io.gravitee.definition.jackson.datatype.services.core.deser.ServicesDeserializer.deserialize(ServicesDeserializer.java:77)
	at io.gravitee.definition.jackson.datatype.services.core.deser.ServicesDeserializer.deserialize(ServicesDeserializer.java:37)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2476)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1765)
	at io.gravitee.definition.jackson.datatype.api.deser.ApiDeserializer.deserialize(ApiDeserializer.java:88)
	at io.gravitee.definition.jackson.datatype.api.deser.ApiDeserializer.deserialize(ApiDeserializer.java:42)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3182)
	at io.gravitee.rest.api.service.impl.ApiServiceImpl.convert(ApiServiceImpl.java:2597)
	at io.gravitee.rest.api.service.impl.ApiServiceImpl.lambda$convert$70(ApiServiceImpl.java:2577)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.gravitee.rest.api.service.impl.ApiServiceImpl.convert(ApiServiceImpl.java:2578)
	at io.gravitee.rest.api.service.impl.ApiServiceImpl.search(ApiServiceImpl.java:2165)
	at jdk.internal.reflect.GeneratedMethodAccessor904.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy45.search(Unknown Source)
	at io.gravitee.rest.api.management.rest.resource.EnvironmentAnalyticsResource.executeCount(EnvironmentAnalyticsResource.java:168)
	at io.gravitee.rest.api.management.rest.resource.EnvironmentAnalyticsResource.getPlatformAnalytics(EnvironmentAnalyticsResource.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
```

While debugging, I suppose that the old format of Health Check Service is not well handled:

```
{"health-check":{"enabled":false}}
```

or 

```
{"health-check":{"enabled":true,"trigger":{"rate":5,"unit":"SECONDS"},"steps":[{"name":"default-step","request":{"path":"/","method":"GET","fromRoot":false},"response":{"assertions":["#response.status == 200"]}}]},"dynamic-property":{"enabled":false,"provider":"HTTP","configuration":{"url":"https://url_poll","specification":"[\n  {\n    \"operation\": \"shift\",\n    \"spec\": {\n      \"*\": {\n        \"@(objectid)\": \"[&].key\",\n        \"@(label)\": \"[&].value\"\n      }\n    }\n  }\n]"}}}
```

Seems related to https://github.com/gravitee-io/issues/issues/4043

**Comment by phiz71** [comment]
Blocked by #5046
