### ISSUE TITLE
[gateway] HTTP headers for health-check are not serializable

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5070]
```
Caused by: java.io.NotSerializableException: io.gravitee.common.http.HttpHeader


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)


        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)


        at java.base/java.util.ArrayList.writeObject(ArrayList.java:897)


        at java.base/jdk.internal.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)


        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


        at java.base/java.lang.reflect.Method.invoke(Method.java:566)


        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1145)


        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1497)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)


        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)


        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)


        at java.base/java.util.ArrayList.writeObject(ArrayList.java:897)


        at java.base/jdk.internal.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)


        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


        at java.base/java.lang.reflect.Method.invoke(Method.java:566)


        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1145)


       at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1497)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)


        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)


        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)


        at java.base/java.util.HashSet.writeObject(HashSet.java:288)


        at java.base/jdk.internal.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)


        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


        at java.base/java.lang.reflect.Method.invoke(Method.java:566)


        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1145)


        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1497)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)


        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)


        at java.base/java.util.HashSet.writeObject(HashSet.java:288)


        at java.base/jdk.internal.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)


        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


        at java.base/java.lang.reflect.Method.invoke(Method.java:566)


        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1145)


        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1497)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)


        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)


        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)


        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)


        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)


        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)


        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:116)


        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:109)


        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)


        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:154)


        ... 24 common frames omitted
```

**Comment by aelamrani** [comment]
Already fixed by https://github.com/gravitee-io/issues/issues/4963
