### ISSUE TITLE
[policy] [hmac]Error 500 on HMAC Http Signature policy

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5180]
### Steps to Reproduce (for bugs)
1. in APIM, create and deploy an API (ie HMAC Signature) 
2. In the Design settings add an API Flows with an HTTP Signature (Security)
3. In Postman, create a Get request (https://<apim-gateway>/http-signature) with the attached code 
[postman-request.txt](https://github.com/gravitee-io/issues/files/6110014/postman-request.txt
)
4. Add Header : KEY Authorization VALUE {{signature}}
5. Sending the request in Postman will give :

{
    "message": "io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException",
    "http_status_code": 500
}

6. Analytics in Console will show :

An error occurs in policy[http-signature] error[io.gravitee.gateway.policy.PolicyChainException: io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException
	at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:47)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:72)
...
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
Caused by: org.tomitribe.auth.signatures.MissingKeyIdException
	at org.tomitribe.auth.signatures.Signature.fromString(Signature.java:466)
	at org.tomitribe.auth.signatures.Signature.fromString(Signature.java:536)
	at io.gravitee.policy.httpsignature.HttpSignaturePolicy.extractSignature(HttpSignaturePolicy.java:170)
	at io.gravitee.policy.httpsignature.HttpSignaturePolicy.onRequest(HttpSignaturePolicy.java:56)
	... 100 more

### Your Environment
* Version used: 3.6
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by apoddany** [comment]
From the specification : https://tools.ietf.org/html/draft-cavage-http-signatures-12#appendix-C.1
The Signature should be :
`Signature keyId="gravitee",algorithm="hmac-sha1",signature="HU91saJzo6wdLVtS0%2F4VXINpGXM%3D"`
instead of
`Signature keyId=gravitee,algorithm=hmac-sha1,signature=HU91saJzo6wdLVtS0%2F4VXINpGXM%3D`

By testing with the first one in Postman, we still get an error :
{
"message": "Invalid HTTP Signature",
"http_status_code": 401
}
