### ISSUE TITLE
error on elastic

### ISSUE THREAD

**Issue by kyooki210** [gravitee-io/issues#5227]
i have an error on my elasticsearch-log file saying like attach below. how this error occured and how to fix it?

[2021-03-15T00:00:12,782][DEBUG][o.e.a.b.TransportShardBulkAction] [SERVER_NAME] [gravitee-2021.03.15][0] failed to execute bulk item (index) BulkShardRequest [[gravitee-2021.03.15][0]] containing [9] requests
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
	at org.elasticsearch.index.mapper.DocumentParser.wrapInMapperParsingException(DocumentParser.java:176) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:69) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:277) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:530) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:507) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.prepareIndexOperationOnPrimary(TransportShardBulkAction.java:458) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:466) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:145) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:114) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:69) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:975) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:944) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:345) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:270) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:924) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:921) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:151) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1659) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:933) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:92) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:291) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:266) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:248) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675) [elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.16.jar:5.6.16]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate Object entries
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@562c37d8; line: 1, column: 95]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:761) ~[jackson-core-2.8.6.jar:2.8.6]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:55) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:398) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:373) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:93) ~[elasticsearch-5.6.16.jar:5.6.16]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:66) ~[elasticsearch-5.6.16.jar:5.6.16]
	... 30 more

**Comment by aelamrani** [comment]
Hi @kyooki210 

Do you have extended mappings?

Which exact version of Gravitee.io?

**Comment by kyooki210** [comment]
Hi, 

I used gravitee comunity version 3.3.3

**Comment by aelamrani** [comment]
This version is not supported anymore, are you able to upgrade to see if it has been fixed?

Do you have extended mappings defined on your Gravitee install?

**Comment by kyooki210** [comment]
Sorry i dont understand your question.. what is extended mapping?

**Comment by aelamrani** [comment]
https://github.com/gravitee-io/gravitee-gateway/blob/7e65a0611ef2d47cda5d51f001586ca458a82f75/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L172

**Comment by kyooki210** [comment]
On the template mapping line 172?

**Comment by aelamrani** [comment]
Yes, basically did you extend the template of request mapping?

**Comment by kyooki210** [comment]
No Sir.. 

elasticsearch:
    enabled: true # Is the reporter enabled or not (default to true)
    endpoints:
      - http://${ds.elastic.host}:${ds.elastic.port}
#    lifecyle:
#      policy_property_name: index.lifecycle.name   #for openDistro, use 'opendistro.index_state_management.policy_id' instead of 'index.lifecycle.name'
#      policies:
#        monitor: my_policy ## ILM policy for the gravitee-monitor-* indexes
#        request: my_policy ## ILM policy for the gravitee-request-* indexes
#        health: my_policy ## ILM policy for the gravitee-health-* indexes
#        log: my_policy ## ILM policy for the gravitee-log-* indexes
#    index: gravitee
#    index_per_type: true
#    bulk:
#      actions: 1000           # Number of requests action before flush
#      flush_interval: 5       # Flush interval in seconds
#    settings:
#      number_of_shards: 1
#      number_of_replicas: 1
#      refresh_interval: 5s
#    pipeline:
#      plugins:
#        ingest: geoip, user_agent
#    security:
#      username: user
#      password: secret
#    http:
#      timeout: 30000 # in milliseconds
#      proxy:
#        type: HTTP #HTTP, SOCK4, SOCK5
#        http:
#          host: localhost
#          port: 3128
#          username: user
#          password: secret
#        https:
#          host: localhost
#          port: 3128
#          username: user
#          password: secret
#    template_mapping:
#      path: ${gravitee.home}/config/reporter/elasticsearch/templates
#      extended_request_mapping: request.ftl

**Comment by kyooki210** [comment]
No Sir..

![ssssss](https://user-images.githubusercontent.com/30793405/111248485-94f25000-863c-11eb-853a-21704d433aee.JPG)

**Comment by kyooki210** [comment]
hi, 

my elasticsearch version are 5.6.16.. i read gravitee changelog on version 3.3.4, it state "[elasticsearch] Template mapping of log is incorrect with ES 7.x ".. that mapping error also happening on elastic version 5.6.16? And what the recommended version of elastic & mongodb for gravitee version 3.x.x?

**Comment by aelamrani** [comment]
Hi, the error reported is related to the version 7 of ES, so It should not affect your installation as we are supporting ES 5.

Maybe you can share the logs from ES?

**Comment by kyooki210** [comment]
hi,
attach my log ES..

![image](https://user-images.githubusercontent.com/30793405/111258544-cb859600-864f-11eb-99a9-30b8b8183b31.png)

**Comment by aelamrani** [comment]
I meant your logs coming from ElasticSearch, not the log of Gravitee.io.

**Comment by kyooki210** [comment]
its the log from elastic search sir.. located on C:\ProgramData\Elastic\Elasticsearch\logs

**Comment by aelamrani** [comment]
Oh sorry I missed it.

Ok are you able to upgrade at least to 3.3.4?

**Comment by kyooki210** [comment]
so, maybe its also affected on elastic search version 5.x.x?

**Comment by kyooki210** [comment]
soo, are you suggesting for solving this issue is upgrading the gravitee to latest version? what about the elastic search? its need to be upgraded too? if its need to be upgraded too, what is the best suitable version for elastic search?

**Comment by aelamrani** [comment]
> so, maybe its also affected on elastic search version 5.x.x?

I don't think so, but I will not spend time to analyse as the version 3.3 is not supported anymore.

> soo, are you suggesting for solving this issue is upgrading the gravitee to latest version? what about the elastic search? its need to be upgraded too? if its need to be upgraded too, what is the best suitable version for elastic search?

I am suggesting to use a supported version.

**Comment by kyooki210** [comment]
oke... maybe i will try upgrading version of elastic search first to confirm that it not happening on the latest version of elasctic?

**Comment by aelamrani** [comment]
OK, but you will have to migrate your data. That's why I was suggesting to upgrade Gravitee.io.

**Comment by kyooki210** [comment]
so basically, this issue not from elastic search that are not suitable for gravite version something.. but its issue from gravitee?

**Comment by aelamrani** [comment]
A lot of people are using Gravitee with ES and AFAIK you are the first to report this issue. 

So what I can say is: this is not a known issue on Gravitee.io.

**Comment by kyooki210** [comment]
hmmmm... oke... than the only solution for this are upgrading version of gravitee, right?

**Comment by aelamrani** [comment]
Yes, or wait for the help of any other from the community.

**Comment by kyooki210** [comment]
hi, 

i think i found the problem.. 

![image](https://user-images.githubusercontent.com/30793405/111561457-0cec8180-87c7-11eb-8e82-3b5f49ccde79.png)

**Comment by kyooki210** [comment]
its possible that vert.x-eventloop causing the problem?

**Comment by aelamrani** [comment]
no
