### ISSUE TITLE
[Management] When dynamic properties are triggered to update, the API status change to out of sync and the front ask for deploy.

### ISSUE THREAD

**Issue by thiagolinsx** [gravitee-io/issues#5245]
### Expected Behavior
Changes to dynamic properties should not change the status of the API

### Current Behavior
Changes in dynamic properties are changing the status of the API to be out of sync.

### Possible Solution
The action that marks the API as out of sync should only be called when a modification to the API made by the user occurs. Or improve the "IF" to ignore changes in dynamic properties.

### Steps to Reproduce (for bugs)
1. Fresh install in Docker (following the docs, all standard)
2. Create a API from UI
3.  Setup a Dynamic Properties with every minute schedule
4. Deploy
5. After refresh page, api are out of sync

### Context
I don't know if an API is really out of sync or it was just an update on dynamic properties.

### Your Environment
* Version used: 3.6
* Docker

**Comment by jhaeyaert** [comment]
I'm faced to the same issue but on v3.15 (seems there since v3.13)

Seems due to an exception that occurs. When dynamic properties are updated, they are store on the api itself. If changes are detected on properties, the management console triggers an api redeploy transparently without requiring any user action (only if all changes are related to properties). Because of this exception, the api isn't redeployed and appears out of sync.

The exception is the following:
```
12:22:40.123 [sync-1] INFO  i.g.r.a.s.d.DynamicPropertiesService - Add a scheduled task to poll dynamic properties each */5 * * * * *
12:22:41.087 [vert.x-eventloop-thread-0] ERROR i.g.r.a.service.impl.ApiServiceImpl - An error occurs while trying to deploy API: 62710ef2-83bc-4007-b10e-f283bce00763
io.gravitee.rest.api.service.exceptions.UserNotFoundException: User [dynamic-property-updater] can not be found.
	at io.gravitee.rest.api.service.impl.UserServiceImpl.lambda$findById$1(UserServiceImpl.java:307)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.gravitee.rest.api.service.impl.UserServiceImpl.findById(UserServiceImpl.java:287)
	at io.gravitee.rest.api.service.UserService.findById(UserService.java:39)
	at jdk.internal.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at jdk.proxy2/jdk.proxy2.$Proxy45.findById(Unknown Source)
	at io.gravitee.rest.api.service.impl.ApiServiceImpl.deployCurrentAPI(ApiServiceImpl.java:1961)
	at io.gravitee.rest.api.service.impl.ApiServiceImpl.deploy(ApiServiceImpl.java:1901)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy2/jdk.proxy2.$Proxy60.deploy(Unknown Source)
	at io.gravitee.rest.api.services.dynamicproperties.DynamicPropertyUpdater.update(DynamicPropertyUpdater.java:181)
	at io.gravitee.rest.api.services.dynamicproperties.DynamicPropertyUpdater.lambda$handle$0(DynamicPropertyUpdater.java:122)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.vertx.core.Future.lambda$toCompletionStage$2(Future.java:360)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.Promise.complete(Promise.java:66)
	at io.gravitee.rest.api.services.dynamicproperties.provider.http.HttpProvider$1$2.lambda$handle$0(HttpProvider.java:130)
...
```

I guess the user 'dynamic-property-updater' does not exist and since this [commit](https://github.com/gravitee-io/gravitee-api-management/commit/7d663a3ad3f2726785b0c0f9cc4b8d8d3557fb7a#diff-e9478d5ebb7ddf0bcc3a3eaa1115438038b0ff159ef6b79a24e1b2196f979520L1986), the user is fetch from the database prior to emit a notification and an exception is thrown if it does not exists.

**Comment by LiliaEn** [comment]
Tested on 3.15.x
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Working as expected

**Comment by a-cordier** [comment]
putting back the issue here to keep some visibility on the pending master fix

**Comment by LiliaEn** [comment]
Tested on the default env v3.19.0
Working as expected on this env as well.
