### ISSUE TITLE
Added a Category with a logo image and on save getting an interval server error.

### ISSUE THREAD

**Issue by waynejohnn** [gravitee-io/issues#5304]
Added a Category with a logo image and on save getting an interval server error.
### Expected Behavior

Expecting the Category to be added and show on the list of categories. Now when I navigate to Categories under the settings, I can get Interval Server Error: Error log below:

17:39:51.939 [gravitee-listener-51] ERROR i.g.r.a.m.r.provider.ThrowableMapper - Internal error,
java.lang.NullPointerException: null,
	at io.gravitee.rest.api.management.rest.resource.AbstractCategoryResource.setPictures(AbstractCategoryResource.java:38),
	at io.gravitee.rest.api.management.rest.resource.CategoriesResource.lambda$getCategories$1(CategoriesResource.java:78),
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source),
	at java.base/java.util.ArrayList.forEach(Unknown Source),
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(Unknown Source),
	at java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source),
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source),
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source),
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source),
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source),
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source),
	at io.gravitee.rest.api.management.rest.resource.CategoriesResource.getCategories(CategoriesResource.java:83),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source),
	at java.base/java.lang.reflect.Method.invoke(Unknown Source),
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52),
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124),
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167),
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219),
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79),
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469),
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391),
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80),
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253),
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248),
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244),
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292),
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274),
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244),
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265),
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232),
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680),
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394),
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346),
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366),
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319),
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205),
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763),
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320),
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126),
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:155),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at io.gravitee.rest.api.security.filter.TokenAuthenticationFilter.doFilter(TokenAuthenticationFilter.java:155),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at io.gravitee.rest.api.security.filter.RecaptchaFilter.doFilter(RecaptchaFilter.java:86),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at io.gravitee.rest.api.security.filter.CsrfIncludeFilter.doFilter(CsrfIncludeFilter.java:41),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92),
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334),
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215),
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178),
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358),
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271),
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618),
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549),
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233),
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610),
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233),
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363),
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188),
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489),
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580),
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186),
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278),
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141),
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221),
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127),
	at org.eclipse.jetty.server.Server.handle(Server.java:500),
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383),
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547),
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375),
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273),
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311),
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103),
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117),
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336),
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313),
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171),
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129),
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375),
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806),
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938),
	at java.base/java.lang.Thread.run(Unknown Source),

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by phiz71** [comment]
Hi @waynejohnn, this is a known issue. It is linked to this one: #5275
What is the version you use?

**Comment by fabMrc** [comment]
Same problem on gravitee 3.7.0
