### ISSUE TITLE
[management] Domains are not loading by AM API

### ISSUE THREAD

**Issue by droderuan** [gravitee-io/issues#5520]
### Expected Behavior

Shows all domains created
### Current Behavior

Domains created by admin are not being shown when access **all domains**. When creating a domain, the redirect goes to the domain page and works properly. 
![image](https://user-images.githubusercontent.com/43659888/116941338-dfa84580-ac45-11eb-865c-e23aec3a9ed4.png)

After reloading the project or going back to **all domains**, the domains are not loaded.
In the network tab, the call stay **pending**:
![image](https://user-images.githubusercontent.com/43659888/116941218-a7086c00-ac45-11eb-8e5e-4166a399d32a.png)

While on am api throws an error:
```
19:12:37.707 [Thread-3] [] ERROR org.mongodb.driver.client - Callback onResult call produced an error
com.mongodb.MongoException: Receiver class io.gravitee.am.repository.mongodb.management.MongoDomainRepository does not define or inherit an implementation of the resolved method 'abstract io.reactivex.Flowable findAllByReferenceId(java.lang.String)' of interface io.gravitee.am.repository.management.api.DomainRepository.
	at com.mongodb.MongoException.fromThrowableNonNull(MongoException.java:79)
	at com.mongodb.async.client.AbstractSubscription.onError(AbstractSubscription.java:135)
	at com.mongodb.async.client.AbstractSubscription.onNext(AbstractSubscription.java:145)
	at com.mongodb.async.client.AbstractSubscription.processResultsQueue(AbstractSubscription.java:217)
	at com.mongodb.async.client.AbstractSubscription.tryProcessResultsQueue(AbstractSubscription.java:172)
	at com.mongodb.async.client.SingleResultCallbackSubscription$1.onResult(SingleResultCallbackSubscription.java:48)
	at com.mongodb.async.client.FindIterableImpl$1$1.onResult(FindIterableImpl.java:220)
	at com.mongodb.async.client.FindIterableImpl$1$1.onResult(FindIterableImpl.java:211)
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:191)
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:134)
	at com.mongodb.async.client.FindIterableImpl$1.onResult(FindIterableImpl.java:211)
	at com.mongodb.async.client.FindIterableImpl$1.onResult(FindIterableImpl.java:205)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.async.client.OperationExecutorImpl$1$1$1.onResult(OperationExecutorImpl.java:94)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.operation.FindOperation$3.onResult(FindOperation.java:827)
	at com.mongodb.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:412)
	at com.mongodb.operation.CommandOperationHelper$10.onResult(CommandOperationHelper.java:481)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:253)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:85)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:467)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:111)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:399)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:376)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:677)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:644)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:568)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:276)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:297)
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:137)
	at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:105)
	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:511)
	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:76)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:634)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:619)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:443)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:193)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:215)
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.AbstractMethodError: Receiver class io.gravitee.am.repository.mongodb.management.MongoDomainRepository does not define or inherit an implementation of the resolved method 'abstract io.reactivex.Flowable findAllByReferenceId(java.lang.String)' of interface io.gravitee.am.repository.management.api.DomainRepository.
	at jdk.internal.reflect.GeneratedMethodAccessor173.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at jdk.proxy2/jdk.proxy2.$Proxy23.findAllByReferenceId(Unknown Source)
	at io.gravitee.am.service.impl.DomainServiceImpl.lambda$findAllByEnvironment$4(DomainServiceImpl.java:185)
	at io.reactivex.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onSuccess(SingleFlatMapPublisher.java:96)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle$SwitchIfEmptyMaybeObserver.onSuccess(MaybeSwitchIfEmptySingle.java:82)
	at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:89)
	at io.reactivex.internal.operators.observable.ObservableElementAtMaybe$ElementAtObserver.onNext(ObservableElementAtMaybe.java:82)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onNext(ObservableToPublisher.java:66)
	at com.mongodb.async.client.AbstractSubscription.onNext(AbstractSubscription.java:142)
	... 54 common frames omitted
```

On MongoDB Compass, all domains are storage and look to works fine:
![image](https://user-images.githubusercontent.com/43659888/116941476-21d18700-ac46-11eb-9dee-154e2ce2d1b5.png)

I found this #601, but the link to the discussion about the issue is not available anymore.
### Steps to Reproduce (for bugs)

1. Follow [the development guide](https://docs.gravitee.io/am/current/am_devguide_bootstrap.html)
2. Start the AM gateway, AM API and AM UI.
3. Login with admin
4. Create a Domain
5. Click on the menu on the top-right, then `All domains`
6. Domains created not shown

### Context

I received a task to understand how to create plugins and I'm now trying to run the whole AM project. By now I'm running the setup of the project and trying to understand how the modules work.

### Your Environment

* Version used: Access Management 3.8
* Browser Name and version: Google Chrome Version 89.0.4389.82 (Official Build) (64-bit)
* Operating System and version: Linux Mint 20.1 Cinnamon
* Java: OpenJdk 16
* IDE: IntelliJ IDEA 2021.1.1 (Community Edition)

**Comment by tcompiegne** [comment]
Hi @droderuan ,

Seems your plugins folder is out of sync. Can you copy/paste the latest `gravitee-am-repository-mongodb-3.9.0-SNAPSHOT.zip` into the plugins folder of both the rest-api and gateway and try again ?

Regards.

**Comment by droderuan** [comment]
Hello @tcompiegne ,

First, thanks for helping. 
When you say latest snapshot, is from here [gravitee-repository-mongodb](https://github.com/gravitee-io/gravitee-repository-mongodb) right? I did what you say but I'm getting `Exception in thread "main" java.lang.NoClassDefFoundError: io/gravitee/repository/Repository` on the both projects. What I tried first was to delete the `gravitee-am-repository-mongodb-3.8.0.zip` and placed the `gravitee-am-repository-mongodb-3.9.0-SNAPSHOT.zip`, no success. Then deleted everything with **_mongo_** in the name and leave just the `gravitee-am-repository-mongodb-3.9.0-SNAPSHOT.zip`, but still getting the exception.

The plugins on am-management-api is:
```
gravitee-am-certificate-javakeystore-3.8.0.zip
gravitee-am-certificate-pkcs12-3.8.0.zip
gravitee-am-extensiongrant-jwtbearer-3.8.0.zip
gravitee-am-factor-email-3.8.0.zip
gravitee-am-factor-otp-3.8.0.zip
gravitee-am-factor-sms-3.8.0.zip
gravitee-am-identityprovider-azure-ad-3.8.0.zip
gravitee-am-identityprovider-facebook-3.8.0.zip
gravitee-am-identityprovider-franceconnect-3.8.0.zip
gravitee-am-identityprovider-github-3.8.0.zip
gravitee-am-identityprovider-google-3.8.0.zip
gravitee-am-identityprovider-http-3.8.0.zip
gravitee-am-identityprovider-inline-3.8.0.zip
gravitee-am-identityprovider-jdbc-3.8.0.zip
gravitee-am-identityprovider-ldap-3.8.0.zip
gravitee-am-identityprovider-linkedin-3.8.0.zip
gravitee-am-identityprovider-mongo-3.8.0.zip
gravitee-am-identityprovider-oauth2-generic-3.8.0.zip
gravitee-am-identityprovider-salesforce-3.8.0.zip
gravitee-am-identityprovider-twitter-3.8.0.zip
gravitee-am-management-api-services-purge-3.8.0.zip
gravitee-am-management-api-services-sync-3.8.0.zip
gravitee-am-policy-enrich-auth-flow-3.8.0.zip
gravitee-am-policy-enrich-profile-3.8.0.zip
gravitee-am-reporter-file-3.8.0.zip
gravitee-am-reporter-jdbc-3.8.0.zip
gravitee-am-reporter-mongodb-3.8.0.zip
gravitee-am-repository-jdbc-3.8.0.zip
gravitee-am-repository-mongodb-3.8.0.zip
gravitee-am-resource-smtp-3.8.0.zip
gravitee-am-resource-twilio-3.8.0.zip
gravitee-cockpit-connectors-ws-1.3.0.zip
gravitee-notifier-email-1.2.8.zip
gravitee-notifier-webhook-1.0.6.zip
gravitee-policy-callout-http-1.10.1.zip
gravitee-policy-groovy-1.11.1.zip
gravitee-policy-ipfiltering-1.5.0.zip
gravitee-policy-request-validation-1.10.0.zip
```

and on am-gateway:

```
gravitee-am-certificate-javakeystore-3.8.0.zip
gravitee-am-certificate-pkcs12-3.8.0.zip
gravitee-am-extensiongrant-jwtbearer-3.8.0.zip
gravitee-am-factor-email-3.8.0.zip
gravitee-am-factor-otp-3.8.0.zip
gravitee-am-factor-sms-3.8.0.zip
gravitee-am-gateway-handler-discovery-3.8.0.zip
gravitee-am-gateway-handler-oidc-3.8.0.zip
gravitee-am-gateway-handler-saml2-3.8.0.zip
gravitee-am-gateway-handler-scim-3.8.0.zip
gravitee-am-gateway-handler-users-3.8.0.zip
gravitee-am-gateway-services-sync-3.8.0.zip
gravitee-am-identityprovider-azure-ad-3.8.0.zip
gravitee-am-identityprovider-facebook-3.8.0.zip
gravitee-am-identityprovider-franceconnect-3.8.0.zip
gravitee-am-identityprovider-github-3.8.0.zip
gravitee-am-identityprovider-google-3.8.0.zip
gravitee-am-identityprovider-http-3.8.0.zip
gravitee-am-identityprovider-inline-3.8.0.zip
gravitee-am-identityprovider-jdbc-3.8.0.zip
gravitee-am-identityprovider-ldap-3.8.0.zip
gravitee-am-identityprovider-linkedin-3.8.0.zip
gravitee-am-identityprovider-mongo-3.8.0.zip
gravitee-am-identityprovider-oauth2-generic-3.8.0.zip
gravitee-am-identityprovider-salesforce-3.8.0.zip
gravitee-am-identityprovider-twitter-3.8.0.zip
gravitee-am-policy-enrich-auth-flow-3.8.0.zip
gravitee-am-policy-enrich-profile-3.8.0.zip
gravitee-am-reporter-file-3.8.0.zip
gravitee-am-reporter-jdbc-3.8.0.zip
gravitee-am-reporter-mongodb-3.8.0.zip
gravitee-am-repository-jdbc-3.8.0.zip
gravitee-am-repository-mongodb-3.8.0.zip
gravitee-am-resource-smtp-3.8.0.zip
gravitee-am-resource-twilio-3.8.0.zip
gravitee-policy-callout-http-1.10.1.zip
gravitee-policy-groovy-1.11.1.zip
gravitee-policy-ipfiltering-1.5.0.zip
gravitee-policy-request-validation-1.10.0.zip
```

**Comment by tcompiegne** [comment]
> When you say latest snapshot, is from here gravitee-repository-mongodb right? 

-> This one is for APIM, for AM it's here : https://github.com/gravitee-io/graviteeio-access-management/tree/master/gravitee-am-repository/gravitee-am-repository-mongodb

I think you have built the master branch, so you need to grab the latest plugins and replace the 3.8.0 ones.

**Comment by droderuan** [comment]
> -> This one is for APIM, for AM it's here: https://github.com/gravitee-io/graviteeio-access-management/tree/master/gravitee-am-repository/gravitee-am-repository-mongodb

The problem was solved by getting the plugin from that repo. Thanks a lot! To update I need to do the same thing with others plugins from that repo, copy and paste on _am-api_ and _am-gateway_? 

And updating the docs from [the development guide](https://docs.gravitee.io/am/current/am_devguide_bootstrap.html) maybe could help, like changing the link or add some instructions, because the link points to 3.8.0.
> Download the latest AM full distribution available: https://download.gravitee.io/graviteeio-am/distributions/graviteeio-am-full-3.8.0.zip. Unzip it into the directory of your choice. You will need these files later on to copy plugins into your local repository.

Or add something like:
> If you get some error associated with any plugin, try to update them manually. To do that, follow:
> * Inside each **_am-certificate_**, **_am-extensiongrant_**, **_am-factor, am-identityprovider_**, **_am-management-api/am-management-api-services_**, _**am-policy**_, **_am-reporter_**, **_am-repository_**, **_am-resource_**, run `nvm clean package`
> * Each directory above, will have target folder for each plugin. Copy the `.zip` and change the plugins from `am-gateway` and `am-management-api`

Just an idea, I'm new to java, but if I can help, will be a pleasure.

Anyway, my issue is solved and thanks!
