### ISSUE TITLE
[management] Error when updating user's avatar

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5533]
In 3.8.1, running from the ZIP distribution, I have this error when I try to update the avatar of a user: 
```
gio_apim_management_api | 20:13:10.497 [gravitee-listener-41] ERROR i.g.r.a.m.r.provider.ThrowableMapper - Internal error
gio_apim_management_api | java.lang.IllegalArgumentException: input == null!
gio_apim_management_api | 	at java.desktop/javax.imageio.ImageIO.getImageReaders(Unknown Source)
gio_apim_management_api | 	at io.gravitee.rest.api.security.utils.ImageUtils.rescale(ImageUtils.java:118)
gio_apim_management_api | 	at io.gravitee.rest.api.security.utils.ImageUtils.verifyAndRescale(ImageUtils.java:89)
gio_apim_management_api | 	at io.gravitee.rest.api.security.utils.ImageUtils.verifyAndRescale(ImageUtils.java:73)
gio_apim_management_api | 	at io.gravitee.rest.api.management.rest.resource.organization.CurrentUserResource.updateCurrentUser(CurrentUserResource.java:273)
```

It could be linked to #5471, since the version of TwelveMonkeys has changed.

**Comment by aelamrani** [comment]
Seems to be due to the upgrade of Jetty https://github.com/gravitee-io/gravitee-parent/blob/e8b83f72afb96af25bb8cac0bdc747f614762706/pom.xml#L107
