### ISSUE TITLE
[management] Cannot publish / unpublish a page with a link

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5559]
### How to reproduce:

- Create a page on root folder of an API documentation
- Create a link on Aside
- Try to publish / unpublish => Internal Server Error

```

09:37:10.179 [gravitee-listener-51] ERROR i.g.r.a.m.r.provider.ThrowableMapper - Internal error
java.lang.NullPointerException: null
	at io.gravitee.rest.api.service.impl.PageServiceImpl.lambda$changeRelatedPagesPublicationStatus$20(PageServiceImpl.java:1302)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.gravitee.rest.api.service.impl.PageServiceImpl.changeRelatedPagesPublicationStatus(PageServiceImpl.java:1297)
	at io.gravitee.rest.api.service.impl.PageServiceImpl.update(PageServiceImpl.java:1187)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by phiz71** [comment]
Already on nightly since 3.8.2 has been merged

**Comment by patelami** [comment]
Env: nightly

As a user, I should be able to publish and unpublish the markdown pages **PASS**
