### ISSUE TITLE
[gateway] cannot deploy an API with a healthcheck configuration on an endpoint

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5570]
Given an API with a health-check configuration on one endpoint.
When I deploy the API on the gateway
Then I have an error.

```gio_apim_gateway  | 08:58:31.007 [vert.x-eventloop-thread-5] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
gio_apim_gateway  | java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class io.gravitee.definition.model.services.healthcheck.Step (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; io.gravitee.definition.model.services.healthcheck.Step is in unnamed module of loader java.net.URLClassLoader @12bc6874)
gio_apim_gateway  | 	at io.gravitee.gateway.services.healthcheck.rule.EndpointRuleHandler.handle(EndpointRuleHandler.java:104)
gio_apim_gateway  | 	at io.gravitee.gateway.services.healthcheck.rule.EndpointRuleHandler.handle(EndpointRuleHandler.java:60)
```

**Comment by gaetanmaisse** [comment]
Good luck @patelami to test this one without any help :trollface:

**Comment by patelami** [comment]
Env: docker version of APIM

Given an API with a health-check configuration on one endpoint.
When I deploy the API on the gateway
Then I have do not have an error `java.lang.ClassCastException` in logs for the gateway 

PASS
