### ISSUE TITLE
[management] check api sync fails for reimported api

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#5641]
At least, since v3.8.1 (not tested below that version), when importing a previously existing api using management console, some error logs appear:

```
12:34:18.525 [gravitee-listener-100] ERROR i.g.r.a.service.impl.ApiServiceImpl - An error occurs while trying to check API synchronization state fd60b2ff-34b9-47b6-a0b2-ff34b9e7b689
java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4429)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3181)
	at io.gravitee.rest.api.service.impl.ApiServiceImpl.isSynchronized(ApiServiceImpl.java:1847)
	at jdk.internal.reflect.GeneratedMethodAccessor713.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy53.isSynchronized(Unknown Source)
	at io.gravitee.rest.api.management.rest.resource.ApiResource.setSynchronizationState(ApiResource.java:751)
	at io.gravitee.rest.api.management.rest.resource.ApiResource.isApiSynchronized(ApiResource.java:329)
	at jdk.internal.reflect.GeneratedMethodAccessor712.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

### Expected Behavior
Check api sync should work without error.

### Current Behavior
An error appears in the management rest api logs (see above).

### Possible Solution
When deleting an api, an Event with `null` payload is stored in database. When reimporting the same api (with the same identifier), the previous event with the `null` payload is retrieved and used to check the api sync status. The `null` payload cannot be deserialized and a `IllegalArgumentException` exception is thrown by jackson.

Here is the code throwing the exception (`ApiServiceImpl.isSynchronized`):

```
boolean enabled = objectMapper.getDeserializationConfig().isEnabled(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
Api payloadEntity = objectMapper.readValue(lastEvent.getPayload(), Api.class);
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, enabled);
```

Note: in the same time, we should use a dedicated `objectMapper` for this special case instead of changing its configuration on the fly. The `objectMapper` is a common instance, it could lead to race conditions. Also, If a json mapping exception occurred, the configuration is not restored to its initial state.

### Steps to Reproduce (for bugs)

1. Create an api
2. Export it
3. Delete the api
4. Import it
5. Check the rest api logs, you should see the stack trace mentioned above.

### Your Environment
* Version used: APIM 3.8.1, master

**Comment by leleueri** [comment]
In addition of the exception given in the first comment, I also have this one :

```
14:07:35.005 [searchindexer-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
io.gravitee.rest.api.service.exceptions.TechnicalManagementException: Unable to delete document for content [ 755e697a-be92-46b5-9e69-7abe9276b581 - io.gravitee.rest.api.model.ApiPageEntity ]
	at io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.process(SearchEngineServiceImpl.java:129)
	at jdk.internal.reflect.GeneratedMethodAccessor543.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy57.process(Unknown Source)
	at io.gravitee.rest.api.services.search.ScheduledSearchIndexerService.lambda$run$0(ScheduledSearchIndexerService.java:100)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at io.gravitee.rest.api.services.search.ScheduledSearchIndexerService.run(ScheduledSearchIndexerService.java:92)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: value must not be null
	at org.apache.lucene.document.Field.<init>(Field.java:238)
	at org.apache.lucene.document.StringField.<init>(StringField.java:61)
	at io.gravitee.rest.api.service.impl.search.lucene.transformer.PageDocumentTransformer.transform(PageDocumentTransformer.java:49)
	at io.gravitee.rest.api.service.impl.search.lucene.transformer.PageDocumentTransformer.transform(PageDocumentTransformer.java:33)
	at io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.lambda$deleteLocally$3(SearchEngineServiceImpl.java:194)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.deleteLocally(SearchEngineServiceImpl.java:191)
	at io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.process(SearchEngineServiceImpl.java:126)
	... 17 common frames omitted
```
