### ISSUE TITLE
[reporter][file] NPEs thrown in log

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#5668]
After upgrading test environment to APIM 3.8.3, NPEs are thrown repeatedly in logs, seemingly for every request:

```
10:43:04.488 [vert.x-eventloop-thread-2] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
        at io.gravitee.reporter.file.FileReporter.report(FileReporter.java:56)
        at io.gravitee.node.reporter.vertx.eventbus.EventBusReporterWrapper.handle(EventBusReporterWrapper.java:91)
        at io.gravitee.node.reporter.vertx.eventbus.EventBusReporterWrapper.handle(EventBusReporterWrapper.java:33)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:278)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:264)
        at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:567)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$4(EventBusImpl.java:527)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
```

We did not experience this with 3.7.2, the previous version we ran.

**Comment by brasseld** [comment]
Hi @larsnaesbye 

Do you have any error / stack trace when starting the gateway ?

Can you provide your gateway log file ? 

it seems that something is going wrong with file system.

Thanks for your feedback.

**Comment by larsnaesbye** [comment]
Hi @brasseld No, no other errors happen before. It looks as if it can write correctly:

```
09:28:23.385 [vert.x-worker-thread-0] [] INFO  i.g.r.file.vertx.VertxFileWriter - Initializing file reporter to write into file: /opt/graviteeio-gateway/logs/metrics/health-check-2021_06_02.json
09:28:23.402 [vert.x-worker-thread-0] [] INFO  i.g.r.file.vertx.VertxFileWriter - Initializing file reporter to write into file: /opt/graviteeio-gateway/logs/metrics/log-2021_06_02.json
09:28:23.402 [vert.x-worker-thread-0] [] INFO  i.g.r.file.vertx.VertxFileWriter - Initializing file reporter to write into file: /opt/graviteeio-gateway/logs/metrics/node-2021_06_02.json
09:28:23.403 [vert.x-worker-thread-0] [] INFO  i.g.r.file.vertx.VertxFileWriter - Initializing file reporter to write into file: /opt/graviteeio-gateway/logs/metrics/request-2021_06_02.json
09:28:23.507 [vert.x-eventloop-thread-2] [] INFO  i.g.reporter.file.FileReporter - File reporter successfully started
```

**Comment by larsnaesbye** [comment]
Whoops, not wholly true. Just before the NPE is this:

```
09:28:31.980 [vert.x-eventloop-thread-2] [] ERROR i.v.c.e.impl.HandlerRegistration - Failed to handleMessage. address: node:metrics
```

**Comment by larsnaesbye** [comment]
I can confirm that 3.7.2 and 3.7.4 work fine as they do not show this NPE. 3.8.0 and 3.8.3 with same configuration do not.

**Comment by larsnaesbye** [comment]
@brasseld Here's the docker log when starting up.

[startup.zip](https://github.com/gravitee-io/issues/files/6594370/startup.zip)

**Comment by larsnaesbye** [comment]
Hey @brasseld  - do you have an idea what causes this? It must have been introduced in 3.8 somehow.
