### ISSUE TITLE
[resource-cache] Error when redeploy an api

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#5671]
We are seeing the following exception each time we redeploy an API that has a cache resource configured

### Current Behavior
```
 08:32:10.240 [gio.sync-1] [29a392ab-940c-4902-a392-ab940cd9022d] INFO i.g.r.cache.HazelcastCacheResource - Destroying
  resource
  08:32:10.241 [gio.sync-1] [29a392ab-940c-4902-a392-ab940cd9022d] ERROR i.g.g.r.internal.ResourceManagerImpl - Unable to
  stop resource
  java.lang.UnsupportedOperationException: Unsupported operation
  at
  com.hazelcast.internal.dynamicconfig.DynamicConfigurationAwareConfig.setMapConfigs(DynamicConfigurationAwareConfig.java:281)
  at io.gravitee.resource.cache.HazelcastCacheResource.doStop(HazelcastCacheResource.java:151)
  at io.gravitee.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:41)
  at io.gravitee.gateway.resource.internal.ResourceManagerImpl.lambda$doStop$1(ResourceManagerImpl.java:81)
  at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
  at io.gravitee.gateway.resource.internal.ResourceManagerImpl.doStop(ResourceManagerImpl.java:78)
  at io.gravitee.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:41)
  at io.gravitee.gateway.handlers.api.ApiReactorHandler.doStop(ApiReactorHandler.java:261)
  at io.gravitee.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:41)
  at
  io.gravitee.gateway.reactor.handler.impl.DefaultReactorHandlerRegistry.update(DefaultReactorHandlerRegistry.java:129)
  at io.gravitee.gateway.reactor.impl.DefaultReactor.onEvent(DefaultReactor.java:130)
  at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
  at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
  at io.gravitee.gateway.handlers.api.manager.impl.ApiManagerImpl.update(ApiManagerImpl.java:182)
  at io.gravitee.gateway.handlers.api.manager.impl.ApiManagerImpl.register(ApiManagerImpl.java:115)
  at io.gravitee.gateway.handlers.api.manager.impl.ApiManagerImpl.register(ApiManagerImpl.java:133)
  at io.gravitee.gateway.services.sync.SyncManager.lambda$computeApiEvents$11(SyncManager.java:266)
  at java.base/java.util.HashMap.forEach(Unknown Source)
  at io.gravitee.gateway.services.sync.SyncManager.computeApiEvents(SyncManager.java:242)
  at io.gravitee.gateway.services.sync.SyncManager.synchronizeApis(SyncManager.java:183)
  at io.gravitee.gateway.services.sync.SyncManager.refresh(SyncManager.java:113)
  at io.gravitee.gateway.services.sync.SyncService.run(SyncService.java:134)
  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
  at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps to Reproduce (for bugs)
1. Create, start & deploy an api with deployed plan
2. Add a cache resource
3. Redeploy

### Your Environment

* Version used: 3.8.x

**Comment by patelami** [comment]
Env: docker container nightly tag

PASS

**Comment by jhaeyaert** [comment]
There are still multiple problems hiding behind the scene:
- The cache resource configuration defined at api level is not taken in account by the gateway when starting the api
- The cache lifecycle must be rethought because of the distributed nature of the hazelcast cache:
      1. when redeploying an api on a local gateway: how to reinit the cache while the old api an the new api uses the same cache name and one needs to drop the cache, the other needs to create it
     2. when considering the whole cluster: when should we drop the old cache while it could still be used by another gateway
