### ISSUE TITLE
Access Management 3.x: Command failed with error 67: 'namespace name generated from index name is too long'  AWS DocumentDB 

### ISSUE THREAD

**Issue by paulocoliver** [gravitee-io/issues#5791]
I'm getting an error message "Error occurs during creation of index" using AWS DocumentDB (MongoDB compatibility)
```
12:21:34.491 [graviteeio-node] [] ERROR i.g.p.r.i.RepositoryPluginHandler - Unable to load repository repository-am-mongodb for scope MANAGEMENT. Retry in 5000 ms...
12:21:39.492 [graviteeio-node] [] INFO i.g.p.r.i.RepositoryPluginHandler - Repository [MANAGEMENT] loaded by mongodb
12:21:39.765 [Thread-6] [] ERROR i.g.a.r.m.c.AbstractMongoRepository - Error occurs during creation of index
com.mongodb.MongoCommandException: Command failed with error 67: 'namespace name generated from index name is too long' on server ttp2.aaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017. The full response is {"ok": 0.0, "code": 67, "errmsg": "namespace name generated from index name is too long", "operationTime": {"$timestamp": {"t": 1624710099, "i": 1}}}

```

### Current Behavior
pods k8s does not stay healthy

### Possible Solution
maybe decrease the length of the index name

### Steps to Reproduce (for bugs)
1. Use AWS DocumentDB as database

### Context
One of our customers requires the use of DocumentDB

### Your Environment
AWS EKS

**Comment by paulocoliver** [comment]
Access management gateway log:
```
Caused by: com.mongodb.MongoCommandException: Command failed with error 67: 'namespace name generated from index name is too long' on server ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017. The full response is {"ok": 0.0, "code": 67, "errmsg": "namespace name generated from index name is too long", "operationTime": {"$timestamp": {"t": 1624710988, "i": 1}}}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:390)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:376)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:677)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:644)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Unknown Source)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown Source)
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:137)
	at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:105)
	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:511)
	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:76)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:634)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:619)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at java.base/sun.nio.ch.Invoker$2.run(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
12:36:28.480 [graviteeio-node] [] ERROR i.g.p.r.i.RepositoryPluginHandler - Unexpected error while creating context for repository instance
java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@1f43cab7 has not been refreshed yet
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1095)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1107)
	at io.gravitee.plugin.repository.internal.RepositoryPluginHandler.registerRepositoryDefinitions(RepositoryPluginHandler.java:156)
	at io.gravitee.plugin.repository.internal.RepositoryPluginHandler.loadRepository(RepositoryPluginHandler.java:138)
	at io.gravitee.plugin.repository.internal.RepositoryPluginHandler.handle(RepositoryPluginHandler.java:107)
	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:105)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:103)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:100)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.DistinctOps$1$2.accept(Unknown Source)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:93)
	at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
	at io.gravitee.am.gateway.event.EventManagerImpl.publishEvent(EventManagerImpl.java:73)
	at io.gravitee.am.gateway.event.EventManagerImpl.publishEvent(EventManagerImpl.java:51)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:78)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.am.gateway.bootstrap.Bootstrap.start(Bootstrap.java:162)
	at io.gravitee.am.gateway.bootstrap.Bootstrap.main(Bootstrap.java:171)
12:36:28.480 [graviteeio-node] [] ERROR i.g.p.r.i.RepositoryPluginHandler - Unable to load repository repository-am-mongodb for scope MANAGEMENT. Retry in 5000 ms...
12:36:33.480 [graviteeio-node] [] INFO  i.g.p.r.i.RepositoryPluginHandler - Repository [MANAGEMENT] loaded by mongodb
12:36:33.751 [graviteeio-node] [] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017], mode=MULTIPLE, requiredClusterType=REPLICA_SET, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500, requiredReplicaSetName='rs0'}
12:36:33.751 [graviteeio-node] [] INFO  org.mongodb.driver.cluster - Adding discovered server ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017 to client view of cluster
12:36:33.769 [graviteeio-node] [] INFO  org.mongodb.driver.cluster - No server chosen by com.mongodb.async.client.ClientSessionHelper$1@37af24cb from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
12:36:33.789 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:9}] to ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017
12:36:33.850 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 0]}, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=60600548, setName='rs0', canonicalAddress=ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017, hosts=[ttp.cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017, ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017], passives=[], arbiters=[], primary='ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017', tagSet=TagSet{[]}, electionId=7fffffff0000000000000002, setVersion=null, lastWriteDate=Sat Jun 26 12:36:33 GMT 2021, lastUpdateTimeNanos=425040400891929}
12:36:33.854 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.cluster - Adding discovered server ttp.cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017 to client view of cluster
12:36:33.856 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.cluster - Adding discovered server ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017 to client view of cluster
12:36:33.861 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.cluster - Server ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017 is no longer a member of the replica set.  Removing from client view of cluster.
12:36:33.861 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.cluster - Canonical address ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017 does not match server address.  Removing ttp.cluster-cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017 from client view of cluster
12:36:33.871 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:10}] to ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017
12:36:33.873 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp.cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:11}] to ttp.cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017
12:36:33.875 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 0]}, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=2650308, setName='rs0', canonicalAddress=ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017, hosts=[ttp.cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017, ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017], passives=[], arbiters=[], primary='ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017', tagSet=TagSet{[]}, electionId=7fffffff0000000000000002, setVersion=null, lastWriteDate=Sat Jun 26 12:36:33 GMT 2021, lastUpdateTimeNanos=425040426431483}
12:36:33.876 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.cluster - Discovered replica set primary ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017
12:36:33.950 [cluster-ClusterId{value='60d71f5127aa3d0e50115198', description='null'}-ttp.cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017] [] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=ttp.cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 0]}, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=76363803, setName='rs0', canonicalAddress=ttp.cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017, hosts=[ttp.cxaspqxggnbm.us-east-2.docdb.amazonaws.com:27017, ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017], passives=[], arbiters=[], primary='ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017', tagSet=TagSet{[]}, electionId=null, setVersion=null, lastWriteDate=Sat Jun 26 12:36:33 GMT 2021, lastUpdateTimeNanos=425040501382653}
12:36:34.162 [Thread-6] [] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:12}] to ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017
12:36:34.268 [Thread-6] [] ERROR i.g.a.r.m.c.AbstractMongoRepository - Error occurs during creation of index
com.mongodb.MongoCommandException: Command failed with error 67: 'namespace name generated from index name is too long' on server ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017. The full response is {"ok": 0.0, "code": 67, "errmsg": "namespace name generated from index name is too long", "operationTime": {"$timestamp": {"t": 1624710994, "i": 1}}}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:390)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:376)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:677)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:644)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Unknown Source)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown Source)
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:137)
	at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:105)
	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:511)
	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:76)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:634)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:619)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at java.base/sun.nio.ch.Invoker$2.run(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
12:36:34.268 [graviteeio-node] [] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoCredentialRepository': Invocation of init method failed; nested exception is com.mongodb.MongoCommandException: Command failed with error 67: 'namespace name generated from index name is too long' on server ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017. The full response is {"ok": 0.0, "code": 67, "errmsg": "namespace name generated from index name is too long", "operationTime": {"$timestamp": {"t": 1624710994, "i": 1}}}
12:36:34.269 [graviteeio-node] [] ERROR i.g.p.c.i.PluginContextFactoryImpl - Unable to refresh plugin context
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoCredentialRepository': Invocation of init method failed; nested exception is com.mongodb.MongoCommandException: Command failed with error 67: 'namespace name generated from index name is too long' on server ttp2.aaaaaaaaaaaa.us-east-2.docdb.amazonaws.com:27017. The full response is {"ok": 0.0, "code": 67, "errmsg": "namespace name generated from index name is too long", "operationTime": {"$timestamp": {"t": 1624710994, "i": 1}}}
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at io.gravitee.plugin.core.internal.PluginContextFactoryImpl.create(PluginContextFactoryImpl.java:59)
	at io.gravitee.plugin.repository.internal.RepositoryPluginHandler.loadRepository(RepositoryPluginHandler.java:130)
	at io.gravitee.plugin.repository.internal.RepositoryPluginHandler.handle(RepositoryPluginHandler.java:107)
	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:105)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:103)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:100)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.DistinctOps$1$2.accept(Unknown Source)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:93)
	at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
	at io.gravitee.am.gateway.event.EventManagerImpl.publishEvent(EventManagerImpl.java:73)
	at io.gravitee.am.gateway.event.EventManagerImpl.publishEvent(EventManagerImpl.java:51)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:78)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.am.gateway.bootstrap.Bootstrap.start(Bootstrap.java:162)
	at io.gravitee.am.gateway.bootstrap.Bootstrap.main(Bootstrap.java:171)


```

**Comment by tcompiegne** [comment]
Hi @paulocoliver ,

You can turn off index creation with the `ensureIndexOnStart` property : 

```
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    ensureIndexOnStart: true
```

```
oauth2:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    ensureIndexOnStart: true
```

You can find the list of indexes here : 

https://github.com/gravitee-io/graviteeio-access-management/blob/master/gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js

You can edit this file to add a shorter name for your indexes, for example : 

``` 
db.collection.createIndex({ fieldA: 1, fieldB: 1 }, { name: "idx_field_a_b" })
```

**Comment by paulocoliver** [comment]
Hi @tcompiegne, 
It worked using your solution.
Thank you!
