### ISSUE TITLE
[policy-ratelimit] Unable to use quota notification.properties

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#5834]

**Comment by RachidKelidou** [comment]
The following properties are not working : 

- ${notification.properties['quota.counter']}
- ${notification.properties['quota.limit']}


We get an exception : 


```
----
FTL stack trace ("~" means nesting-related):
- Failed at: ${notification.properties["quota.limi... [in template "1473156034" at line 6, column 1]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
at freemarker.core.Environment.visit(Environment.java:347)
at freemarker.core.Environment.visit(Environment.java:353)
at freemarker.core.Environment.process(Environment.java:326)
at freemarker.template.Template.process(Template.java:383)
at io.gravitee.notifier.api.AbstractConfigurableNotifier.templatize(AbstractConfigurableNotifier.java:55)
at io.gravitee.notifier.email.EmailNotifier.doSend(EmailNotifier.java:93)
at io.gravitee.notifier.api.AbstractNotifier.send(AbstractNotifier.java:47)
at com.graviteesource.ae.notifier.notification.impl.NotificationServiceImpl.lambda$send$2(NotificationServiceImpl.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.graviteesource.ae.notifier.notification.impl.NotificationServiceImpl.lambda$send$3(NotificationServiceImpl.java:86)
at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
at io.vertx.reactivex.ContextScheduler$ContextWorker$TimedAction.run(ContextScheduler.java:184)
at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:829)
```
