### ISSUE TITLE
getting error "No bean named 'graviteeTransactionManager' is defined" 

### ISSUE THREAD

**Issue by asdarunasd** [gravitee-io/issues#595]
i have configured gravitee in ubuntu 16.4 server.  i can access gateway and management ip directly in browser with the port. But when i try to access the portal, following error message is popping up 
 
"No bean named 'graviteeTransactionManager' is defined: No matching PlatformTransactionManager bean found for qualifier 'graviteeTransactionManager' - neither qualifier match nor bean name match!"

**Comment by brasseld** [comment]
Hi @asdarunasd 

Please provide:
1) Your complete stack trace
2) The connector used (mongo, redis, cassandra, dynamodb, ...)
2) The version of gravitee used.

Regards,

**Comment by asdarunasd** [comment]
Log while running management API 

 at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)
16:25:49.834 [gravitee-listener-15] ERROR i.g.m.rest.provider.ThrowableMapper - Internal error
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'graviteeTransactionManager' is defined: No matching PlatformTransactionManager bean found for qualifier 'graviteeTransactionManager' - neither qualifier match nor bean name match!
        at org.springframework.beans.factory.annotation.BeanFactoryAnnotationUtils.qualifiedBeanOfType(BeanFactoryAnnotationUtils.java:107)
        at org.springframework.beans.factory.annotation.BeanFactoryAnnotationUtils.qualifiedBeanOfType(BeanFactoryAnnotationUtils.java:66)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.determineQualifiedTransactionManager(TransactionAspectSupport.java:381)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.determineTransactionManager(TransactionAspectSupport.java:359)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:271)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy40.findByVisibility(Unknown Source)
        at io.gravitee.management.rest.resource.ApisResource.listApis(ApisResource.java:87)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)


2) I am using mongo

3) Version 1.2.0

**Comment by brasseld** [comment]
Why not upgrading your Gravitee.io stack ?

According to me, you have this exception because, early in the stack trace, you're not able to connect to MongoDB.

**Comment by asdarunasd** [comment]
We have configured gravitee version 1.2.0 successfully in docker.. So we are trying to create the same instance in another server as standalone...So that is why we didn't upgrade the stack.  


Initial log of management API

  Gravitee.IO Management Standalone Runtime Bootstrap Environment

  GRAVITEE_HOME: /home/gravitee/gravitee-management-standalone-1.2.0

  GRAVITEE_OPTS:

  JAVA: /usr/bin/java

  JAVA_OPTS:  -Djava.net.preferIPv4Stack=true -Xms1024m -Xmx2048m -Djava.awt.headless=true -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8

  CLASSPATH: /home/gravitee/gravitee-management-standalone-1.2.0/lib/gravitee-management-api-standalone-bootstrap-1.2.0.jar

=========================================================================

16:24:15.829 [gravitee] INFO  i.g.management.standalone.Container - Initializing Gravitee Management API context...
16:24:16.459 [gravitee] INFO  i.g.m.r.s.PropertiesConfiguration - Loading Gravitee Management configuration.
16:24:16.465 [gravitee] INFO  i.g.m.r.s.PropertiesConfiguration -       Gravitee Management configuration loaded from /home/gravitee/gravitee-management-standalone-1.2.0/config/gravitee.yml
16:24:16.532 [gravitee] INFO  i.g.m.r.s.PropertiesConfiguration - Loading Gravitee Management configuration. DONE
16:24:16.541 [gravitee] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - Loading plugin handlers
16:24:16.544 [gravitee] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - Find 6 plugin handler(s):
16:24:16.546 [gravitee] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - io.gravitee.plugin.fetcher.internal.FetcherPluginHandler
16:24:16.547 [gravitee] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - io.gravitee.plugin.policy.internal.PolicyPluginHandler
16:24:16.548 [gravitee] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - io.gravitee.management.repository.plugins.RepositoryPluginHandler
16:24:16.549 [gravitee] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - io.gravitee.management.services.plugins.ServicePluginHandler
16:24:16.550 [gravitee] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - io.gravitee.management.idp.core.plugin.IdentityProviderPluginHandler
16:24:16.550 [gravitee] INFO  i.g.p.c.s.PluginHandlerBeanFactoryPostProcessor - io.gravitee.plugin.resource.internal.ResourcePluginHandler
16:24:17.515 [gravitee] INFO  i.g.m.r.p.RepositoryPluginHandler - Loading repository for scope MANAGEMENT: mongodb
16:24:17.516 [gravitee] INFO  i.g.m.r.p.RepositoryPluginHandler - Loading repository for scope ANALYTICS: elasticsearch
16:24:17.719 [gravitee] INFO  org.eclipse.jetty.util.log - Logging initialized @2592ms
16:24:17.811 [gravitee] INFO  i.g.management.standalone.Container - Start Gravitee Management API...
16:24:17.812 [gravitee] INFO  i.g.m.standalone.node.ManagementNode - Gravitee.io - Management API is now starting...
16:24:17.812 [gravitee] INFO  i.g.m.standalone.node.ManagementNode -    Starting component: PluginEventListener
16:24:17.812 [gravitee] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.plugin.core.internal.PluginEventListener
16:24:17.812 [gravitee] INFO  i.g.c.event.impl.EventManagerImpl - Register new listener PluginEventListener for event type class io.gravitee.plugin.core.api.PluginEvent
16:24:17.813 [gravitee] INFO  i.g.m.standalone.node.ManagementNode -    Starting component: PluginRegistry
16:24:17.814 [gravitee] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.plugin.core.internal.PluginRegistryImpl
16:24:17.814 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - Initializing plugin registry.
16:24:17.817 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugins from /home/gravitee/gravitee-management-standalone-1.2.0/plugins
16:24:17.821 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/gravitee/gravitee-management-standalone-1.2.0/plugins/gravitee-management-api-idp-ldap-1.2.0.zip
16:24:17.891 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/gravitee/gravitee-management-standalone-1.2.0/plugins/.work/gravitee-management-api-idp-ldap-1.2.0/gravitee-management-api-idp-ldap-1.2.0.jar
16:24:17.895 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/gravitee/gravitee-management-standalone-1.2.0/plugins/gravitee-management-api-services-subscriptions-1.2.0.zip
16:24:17.903 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/gravitee/gravitee-management-standalone-1.2.0/plugins/.work/gravitee-management-api-services-subscriptions-1.2.0/gravitee-management-api-services-subscriptions-1.2.0.jar
16:24:17.904 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/gravitee/gravitee-management-standalone-1.2.0/plugins/gravitee-management-api-idp-repository-1.2.0.zip
16:24:17.914 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/gravitee/gravitee-management-standalone-1.2.0/plugins/.work/gravitee-management-api-idp-repository-1.2.0/gravitee-management-api-idp-repository-1.2.0.jar
16:24:17.914 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /home/gravitee/gravitee-management-standalone-1.2.0/plugins/gravitee-management-api-idp-memory-1.2.0.zip
16:24:17.918 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /home/gravitee/gravitee-management-standalone-1.2.0/plugins/.work/gravitee-management-api-idp-memory-1.2.0/gravitee-management-api-idp-memory-1.2.0.jar
16:24:17.918 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available policy:
16:24:17.922 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available reporter:
16:24:17.922 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available service:
16:24:17.922 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl -     > subscriptions-refresher [1.2.0] has been loaded
16:24:17.923 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available repository:
16:24:17.923 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available identity_provider:
16:24:17.923 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl -     > ldap-idp [1.2.0] has been loaded
16:24:17.923 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl -     > gravitee-idp [1.2.0] has been loaded
16:24:17.923 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl -     > inmemory-idp [1.2.0] has been loaded
16:24:17.923 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available resource:
16:24:17.923 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available fetcher:
16:24:17.923 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - All plugins have been loaded. Installing...
16:24:17.923 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - Installing REPOSITORY plugins...
16:24:17.924 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - Installing IDENTITY_PROVIDER plugins...
16:24:17.929 [gravitee] INFO  i.g.m.i.c.p.IdentityProviderPluginHandler - Register a new identity provider plugin: ldap-idp [io.gravitee.management.idp.ldap.LdapIdentityProvider]
16:24:17.930 [gravitee] INFO  i.g.m.i.c.p.IdentityProviderPluginHandler - Register a new identity provider plugin: inmemory-idp [io.gravitee.management.idp.memory.InMemoryIdentityProvider]
16:24:17.931 [gravitee] INFO  i.g.m.i.c.p.IdentityProviderPluginHandler - Register a new identity provider plugin: gravitee-idp [io.gravitee.management.idp.repository.RepositoryIdentityProvider]
16:24:17.931 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - Installing RESOURCE plugins...
16:24:17.931 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - Installing POLICY plugins...
16:24:17.931 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - Installing SERVICE plugins...
16:24:17.931 [gravitee] INFO  i.g.m.s.plugins.ServicePluginHandler - Register a new service: subscriptions-refresher [io.gravitee.management.services.subscriptions.ScheduledSubscriptionsService]
16:24:18.066 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - Installing REPORTER plugins...
16:24:18.066 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - Installing FETCHER plugins...
16:24:18.066 [gravitee] INFO  i.g.p.c.internal.PluginRegistryImpl - Plugins have been loaded and installed.
16:24:18.066 [gravitee] INFO  i.g.m.standalone.node.ManagementNode -    Starting component: JettyEmbeddedContainer
16:24:18.082 [gravitee] WARN  o.e.j.server.handler.ContextHandler - o.e.j.s.ServletContextHandler@70e3f36f{/,null,null} contextPath ends with /*
16:24:18.123 [gravitee] INFO  org.eclipse.jetty.server.Server - jetty-9.3.13.v20161014
16:24:18.140 [gravitee] INFO  o.e.j.server.AbstractNCSARequestLog - Opened /home/gravitee/gravitee-management-standalone-1.2.0/logs/gravitee_accesslog_2017_05_17.log
16:24:18.303 [gravitee] INFO  i.g.m.s.c.b.BasicSecurityConfigurerAdapter - Loading authentication identity providers for Basic authentication
16:24:18.303 [gravitee] INFO  i.g.m.s.c.b.BasicSecurityConfigurerAdapter - Loading identity provider of type memory at position 0
16:24:18.365 [gravitee] INFO  i.g.m.s.c.b.BasicSecurityConfigurerAdapter - Loading identity provider of type gravitee at position 1
16:24:20.070 [gravitee] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@70e3f36f{/management,null,AVAILABLE}
16:24:20.081 [gravitee] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@33eb0d4{HTTP/1.1,[http/1.1]}{0.0.0.0:8083}
16:24:20.082 [gravitee] INFO  org.eclipse.jetty.server.Server - Started @4956ms
16:24:20.082 [gravitee] INFO  i.g.m.standalone.node.ManagementNode - Gravitee.io - Management API [id: 03208f43-deea-465b-a08f-43deea565b56 - version: 1.2.0 (build: 132) revision#2b7a22213073b1525148d4350f4fa1ec6723aef5] started in 2270 ms.
16:25:28.374 [gravitee-listener-19] ERROR i.g.m.rest.provider.ThrowableMapper - Internal error
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'graviteeTransactionManager' is defined: No matching PlatformTransactionManager bean found for qualifier 'graviteeTransactionManager' - neither qualifier match nor bean name match!
        at org.springframework.beans.factory.annotation.BeanFactoryAnnotationUtils.qualifiedBeanOfType(BeanFactoryAnnotationUtils.java:107)
        at org.springframework.beans.factory.annotation.BeanFactoryAnnotationUtils.qualifiedBeanOfType(BeanFactoryAnnotationUtils.java:66)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.determineQualifiedTransactionManager(TransactionAspectSupport.java:381)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.determineTransactionManager(TransactionAspectSupport.java:359)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:271)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy40.findByVisibility(Unknown Source)
        at io.gravitee.management.rest.resource.ApisResource.listApis(ApisResource.java:87)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)

**Comment by brasseld** [comment]
Ok get it:

```
16:24:17.923 [gravitee] INFO i.g.p.c.internal.PluginRegistryImpl - List of available repository:
16:24:17.923 [gravitee] INFO i.g.p.c.internal.PluginRegistryImpl - List of available identity_provider:
```

You have no repository connector installed in the `plugins` folder.
Please add corresponding MongoDB connector.

Thanks for your feedback.

**Comment by asdarunasd** [comment]
Did that and it worked........Thank you so much .....You are awesome...Have a great day..:)

**Comment by brasseld** [comment]
You're welcome !
