### ISSUE TITLE
[management][gateway] First dynamic dictionary start causes an IllegalArgumentException on the gateway

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#6044]
When creating a dynamic dictionary and starting it for the first time, an `IllegalArgumentException` appears during the dictionary deployment on the gateway side.

### Expected Behavior
The dictionary should be deployed without error.

### Current Behavior
An `IllegalArgumentException` appears in the gateway logs during the first deployment of the dynamic dictionary. However, the next dictionary refreshes are well handled.

```
08:55:27.558 [gio.sync-1] [] ERROR i.g.g.services.sync.SyncManager - An error occurs while synchronizing dictionaries
java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4429)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3181)
	at io.gravitee.gateway.services.sync.synchronizer.DictionarySynchronizer.toDictionary(DictionarySynchronizer.java:170)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:119)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.drainNormal(FlowableGroupBy.java:634)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.drain(FlowableGroupBy.java:559)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.subscribe(FlowableGroupBy.java:530)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupedUnicast.subscribeActual(FlowableGroupBy.java:462)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe.subscribeActual(FlowableFlatMapMaybe.java:54)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
	at io.reactivex.internal.operators.parallel.ParallelFromPublisher.subscribe(ParallelFromPublisher.java:58)
	at io.reactivex.internal.operators.parallel.ParallelRunOn.subscribe(ParallelRunOn.java:70)
	at io.reactivex.internal.operators.parallel.ParallelPeek.subscribe(ParallelPeek.java:80)
	at io.reactivex.internal.operators.parallel.ParallelJoin.subscribeActual(ParallelJoin.java:58)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.drainNormal(FlowableGroupBy.java:350)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.drain(FlowableGroupBy.java:279)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.onNext(FlowableGroupBy.java:186)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:547)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:471)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at io.gravitee.gateway.services.sync.synchronizer.AbstractSynchronizer.lambda$searchLatestEvents$0(AbstractSynchronizer.java:91)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy.subscribeActual(FlowableGroupBy.java:78)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableCountSingle.subscribeActual(FlowableCountSingle.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.blockingGet(Single.java:2869)
	at io.gravitee.gateway.services.sync.synchronizer.DictionarySynchronizer.synchronize(DictionarySynchronizer.java:74)
	at io.gravitee.gateway.services.sync.SyncManager.refresh(SyncManager.java:163)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Possible Solution
We should check why the dictionary event sent to the gateway contains a `null` value and avoid it.

### Steps to Reproduce (for bugs)
Create a dynamic dictionary with the following information:

1. - Http url: https://api.gravitee.io/echo
2. - Jolt transformation: 

```json
[
  {
    "operation": "shift",
    "spec": {
      "headers": {
        "*": {
          "$": "[#2].key",
          "@": "[#2].value"
        }
      }
    }
  }
]
```
3. Start the dictionary.

### Your Environment
* Version used: 3.10.1 (3.10.x branch)

**Comment by mouligno** [comment]
@jhaeyaert can we close this one ?

**Comment by mouligno** [comment]
@jhaeyaert ?

**Comment by LiliaEn** [comment]
Tested on 3.10.x
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Dynamic dictionary starts without any error.
