### ISSUE TITLE
[gateway] bump org json dependency to fix EE CAS IdP plugin

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#6078]
```
15:03:07.747 [vert.x-eventloop-thread-0] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NoSuchMethodError: 'java.util.Map org.json.JSONObject.toMap()'
    at com.graviteesource.am.identityprovider.cas.authentication.CASAuthenticationProvider.lambda$loadUserByUsername$0(CASAuthenticationProvider.java:139)
    at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:82)
    at io.reactivex.internal.operators.maybe.MaybeFromSingle$FromSingleObserver.onSuccess(MaybeFromSingle.java:76)
    at io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:49)
    at io.vertx.reactivex.ext.web.client.HttpRequest$9.handle(HttpRequest.java:659)
    at io.vertx.reactivex.ext.web.client.HttpRequest$9.handle(HttpRequest.java:656)
    at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:371)
```

**Comment by tcompiegne** [comment]
Currently `json-20140107.jar` is resolved instead of a new one.

**Comment by tcompiegne** [comment]
Was bring by google tink : https://github.com/google/tink/issues/450
