### ISSUE TITLE
Access Management - K8S - JDBC

### ISSUE THREAD

**Issue by klebersjunior** [gravitee-io/issues#6148]
### Expected Behavior

How configure Access Management with JDBC driver in Helm File?

### Current Behavior

I configure helm "jdbc" section with correct parameters but i received error:

Search...
	at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:78)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.am.gateway.bootstrap.Bootstrap.start(Bootstrap.java:162)
	at io.gravitee.am.gateway.bootstrap.Bootstrap.main(Bootstrap.java:171)
14:39:10.519 [graviteeio-node] [] ERROR i.g.p.r.i.RepositoryPluginHandler - Unable to load repository repository-am-jdbc for scope MANAGEMENT. Retry in 5000 ms...
14:39:15.519 [graviteeio-node] [] INFO  i.g.p.r.i.RepositoryPluginHandler - Repository [MANAGEMENT] loaded by jdbc
14:39:16.220 [graviteeio-node] [] INFO  i.g.a.r.j.c.ConnectionFactoryProvider - Initializing connection pool for management.jdbc. database
14:39:16.224 [graviteeio-node] [] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'managementRepositoryConfiguration': Unsatisfied dependency expressed through field 'connectionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in io.gravitee.am.repository.jdbc.management.ManagementRepositoryConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.r2dbc.spi.ConnectionFactory]: Circular reference involving containing bean 'managementRepositoryConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'connectionFactory' threw exception; nested exception is java.lang.IllegalArgumentException: Could not find delegating driver [postgres]
14:39:16.226 [graviteeio-node] [] ERROR i.g.p.c.i.PluginContextFactoryImpl - Unable to refresh plugin context
 

### Possible Solution

I don't have a idea.

### Steps to Reproduce (for bugs)

1. Download Access Management Helm File
2. Update data with your jdbc credentials and insert driver url
3. Change "management" and "oauth" section, "mongodb" to "jdbc"
4.

### Context

Use Access Management with AWS RDS Postgres

### Your Environment

Version used: AM 3.1
Browser Name and version: Chrome
Operating System and version: Kubernetes

**Comment by tcompiegne** [comment]
Hi @klebersjunior can you share your jdbc helm section (remove any sensitive data) ?

**Comment by klebersjunior** [comment]
jdbc:
  driver: postgres
  host: <<host>>
  port:<<port>>
  database: <<database>>
  username: <<username>>
  password: <<password>>
  # URLs to download the drivers
  drivers:
    - https://jdbc.postgresql.org/download/postgresql-42.2.23.jar
  pool:
    acquireRetry:  1
    initialSize: 0
    maxSize: 10
    maxIdleTime: 30000
    maxLifeTime: 30000
    maxAcquireTime: 0
    maxCreateConnectionTime: 0
