### ISSUE TITLE
[AM][management ui] Random event errors in interface

### ISSUE THREAD

**Issue by edsonlara** [gravitee-io/issues#6209]
In several actions fails after an error in server log, browser console and notifications, repeating the action shows that it was done,  

### Current Behavior
App notification at bottom (not always, sometimes blank page), it is not in all cases, you can browse the management portal normally

> "An error ocurred when creating an event"

Browser console:

> Object { headers: {…}, status: 500, statusText: "Internal Server Error", url: "http://am-api.dom.tld/management/organizations/DEFAULT/environments/DEFAULT/domains/f2bc65e4-3998-4722-bc65-e43998272256", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://am-api.dom.tld/management/organizations/DEFAULT/environments/DEFAULT/domains/f2bc65e4-3998-4722-bc65-e43998272256: 500 Internal Server Error", error: {…} }

Management API log

> 16:55:30.353 [Thread-3] [] ERROR i.g.am.service.impl.EventServiceImpl - An error occurs while trying to create an event
> java.util.NoSuchElementException: The MaybeSource is empty
>         at io.reactivex.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onComplete(MaybeToSingle.java:98)
>         at io.reactivex.internal.operators.observable.ObservableElementAtMaybe$ElementAtObserver.onComplete(ObservableElementAtMaybe.java:102)
>         at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
>         at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onComplete(ObservableFromPublisher.java:46)
>         at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
>         at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:189)
>         at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:260)
>         at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:129)
>         at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.lambda$first$0(BatchCursorPublisher.java:110)
>         at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:282)
>         at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:292)
>         at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:292)
>         at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:129)
>         at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:547)
>         at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:168)
>         at com.mongodb.reactivestreams.client.internal.BatchCursor.lambda$next$0(BatchCursor.java:35)
>         at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
>         at reactor.core.publisher.Mono.subscribe(Mono.java:4252)
>         at reactor.core.publisher.Mono.subscribeWith(Mono.java:4363)
>         at reactor.core.publisher.Mono.subscribe(Mono.java:4083)
>         at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.lambda$first$1(BatchCursorPublisher.java:115)
>         at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
>         at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
>         at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
>         at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1812)
>         at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
>         at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173)
>         at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
>         at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:549)
>         at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$2(OperationExecutorImpl.java:78)
>         at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
>         at com.mongodb.internal.operation.FindOperation$3.onResult(FindOperation.java:756)
>         at com.mongodb.internal.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:532)
>         at com.mongodb.internal.operation.CommandOperationHelper$1.onResult(CommandOperationHelper.java:462)
>         at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
>         at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:282)
>         at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
>         at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:94)
>         at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:641)
>         at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:156)
>         at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
>         at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:502)
>         at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:479)
>         at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:785)
>         at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:752)
>         at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:621)
>         at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:618)
>         at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250)
>         at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233)
>         at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
>         at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
>         at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:562)
>         at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
>         at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
>         at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:144)
>         at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:118)
>         at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:107)
>         at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:618)
>         at com.mongodb.internal.connection.InternalStreamConnection.access$600(InternalStreamConnection.java:81)
>         at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:742)
>         at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:727)
>         at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:621)
>         at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:618)
>         at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250)
>         at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233)
>         at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
>         at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:439)
>         at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
>         at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
>         at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
>         at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:829)
> 16:55:30.356 [Thread-3] [] ERROR i.g.a.m.h.m.a.p.ManagementExceptionMapper - Unexpected error occurred
> io.gravitee.am.service.exception.TechnicalManagementException: An error occurs while trying to create an event
>         at io.gravitee.am.service.impl.EventServiceImpl.lambda$create$0(EventServiceImpl.java:58)
>         at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:73)
>         at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:116)
>         at io.reactivex.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onComplete(MaybeToSingle.java:98)
>         at io.reactivex.internal.operators.observable.ObservableElementAtMaybe$ElementAtObserver.onComplete(ObservableElementAtMaybe.java:102)
>         at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
>         at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onComplete(ObservableFromPublisher.java:46)
>         at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
>         at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:189)
>         at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:260)
>         at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:129)
>         at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.lambda$first$0(BatchCursorPublisher.java:110)
>         at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:282)
>         at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:292)
>         at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:292)
>         at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:129)
>         at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:547)
>         at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:168)
>         at com.mongodb.reactivestreams.client.internal.BatchCursor.lambda$next$0(BatchCursor.java:35)
>         at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
>         at reactor.core.publisher.Mono.subscribe(Mono.java:4252)
>         at reactor.core.publisher.Mono.subscribeWith(Mono.java:4363)
>         at reactor.core.publisher.Mono.subscribe(Mono.java:4083)
>         at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.lambda$first$1(BatchCursorPublisher.java:115)
>         at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
>         at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
>         at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
>         at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1812)
>         at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
>         at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173)
>         at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
>         at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:549)
>         at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$2(OperationExecutorImpl.java:78)
>         at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
>         at com.mongodb.internal.operation.FindOperation$3.onResult(FindOperation.java:756)
>         at com.mongodb.internal.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:532)
>         at com.mongodb.internal.operation.CommandOperationHelper$1.onResult(CommandOperationHelper.java:462)
>         at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
>         at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:282)
>         at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
>         at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:94)
>         at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:641)
>         at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:156)
>         at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
>         at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:502)
>         at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:479)
>         at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:785)
>         at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:752)
>         at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:621)
>         at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:618)
>         at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250)
>         at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233)
>         at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
>         at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
>         at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:562)
>         at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
>         at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
>         at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:144)
>         at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:118)
>         at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:107)
>         at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:618)
>         at com.mongodb.internal.connection.InternalStreamConnection.access$600(InternalStreamConnection.java:81)
>         at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:742)
>         at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:727)
>         at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:621)
>         at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:618)
>         at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250)
>         at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233)
>         at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
>         at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:439)
>         at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
>         at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
>         at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
>         at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:829)

### Steps to Reproduce (for bugs)
Install mongo cluster (3 nodes, create an user)
Deploy app in two servers, replicate configuration (only mongo conf, URI format with auth)
Put them behind a HAproxy, each app different backend (gw.dom.tld, ui.dom.tld, api.dom.tld)
Modify constants.json

### Objective
Deploy it with failover

### Your Environment
2x Centos 7 servers for GW, API and UI (haproxy balanced)
3x Centos 7 servers for Mongo (with replicaset)
Zip installation (3.11.0)
Firefox, Chrome any version

**Comment by tcompiegne** [comment]
Hi @edsonlara, can you share the mongo.uri value ? (please remove any sensitive data).

Best regards

**Comment by edsonlara** [comment]
In management, oauth and referenced properties, same network.
> mongodb://graviteeuser:password@172.16.0.3:27017,172.16.0.4:27017,172.166.0.5:27017/am?replicaSet=rs0&readPreference=nearest

**Comment by tcompiegne** [comment]
Can you remove the readPreference and try again ?

**Comment by edsonlara** [comment]
that seems to do the trick, thanks.
Any clarification in the cause? my situation is that in one point, am planning to move one of the app server and one of the db servers in a remote location (vpn tunnel) so the parameter was a logical option.
