### ISSUE TITLE
[APIM] [AE] error when creating an alert with system email notification

### ISSUE THREAD

**Issue by RachidKelidou** [gravitee-io/issues#6231]
APIM 3.10.3 + AE 1.4.1

when trying to add an alert, if you want to create an alert notification using the "system email" mode, you get an error message in a red popup : 

**resource notifiers/default-email.json not found.**

![image](https://user-images.githubusercontent.com/79910027/134305279-b64c7c3c-392c-41ad-bc3b-e8537d46fcb5.png)

Also there is a stacktrace (management api) : 

```
gio_apim_management_api | 10:59:41.693 [gravitee-listener-47] ERROR i.g.r.a.m.r.provider.ThrowableMapper - Internal error
gio_apim_management_api | java.lang.IllegalArgumentException: resource notifiers/default-email.json not found.
gio_apim_management_api |       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:219)
gio_apim_management_api |       at com.google.common.io.Resources.getResource(Resources.java:195)
gio_apim_management_api |       at io.gravitee.rest.api.service.impl.NotifierServiceImpl.getSchema(NotifierServiceImpl.java:265)
gio_apim_management_api |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gio_apim_management_api |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
gio_apim_management_api |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
gio_apim_management_api |       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
gio_apim_management_api |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
gio_apim_management_api |       at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
gio_apim_management_api |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
gio_apim_management_api |       at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
gio_apim_management_api |       at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
gio_apim_management_api |       at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
gio_apim_management_api |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
gio_apim_management_api |       at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
gio_apim_management_api |       at com.sun.proxy.$Proxy63.getSchema(Unknown Source)
gio_apim_management_api |       at io.gravitee.rest.api.management.rest.resource.NotifierResource.getNotifierSchema(NotifierResource.java:82)
gio_apim_management_api |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gio_apim_management_api |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
gio_apim_management_api |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
gio_apim_management_api |       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
gio_apim_management_api |       at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
gio_apim_management_api |       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
gio_apim_management_api |       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
gio_apim_management_api |       at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
gio_apim_management_api |       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
gio_apim_management_api |       at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
gio_apim_management_api |       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
gio_apim_management_api |       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
gio_apim_management_api |       at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
gio_apim_management_api |       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
gio_apim_management_api |       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
gio_apim_management_api |       at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
gio_apim_management_api |       at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
gio_apim_management_api |       at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
gio_apim_management_api |       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
gio_apim_management_api |       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
gio_apim_management_api |       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
gio_apim_management_api |       at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
gio_apim_management_api |       at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
gio_apim_management_api |       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
gio_apim_management_api |       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
gio_apim_management_api |       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
gio_apim_management_api |       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
gio_apim_management_api |       at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
gio_apim_management_api |       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
gio_apim_management_api |       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)
gio_apim_management_api |       at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
gio_apim_management_api |       at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:149)
gio_apim_management_api |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at io.gravitee.rest.api.security.filter.TokenAuthenticationFilter.doFilter(TokenAuthenticationFilter.java:162)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at io.gravitee.rest.api.security.filter.RecaptchaFilter.doFilter(RecaptchaFilter.java:97)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
gio_apim_management_api |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at io.gravitee.rest.api.security.filter.CsrfIncludeFilter.doFilter(CsrfIncludeFilter.java:39)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
gio_apim_management_api |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
gio_apim_management_api |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
gio_apim_management_api |       at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
gio_apim_management_api |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
gio_apim_management_api |       at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
gio_apim_management_api |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
gio_apim_management_api |       at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
gio_apim_management_api |       at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
gio_apim_management_api |       at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
gio_apim_management_api |       at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
gio_apim_management_api |       at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
gio_apim_management_api |       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
gio_apim_management_api |       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
gio_apim_management_api |       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
gio_apim_management_api |       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
gio_apim_management_api |       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
gio_apim_management_api |       at org.eclipse.jetty.server.Server.handle(Server.java:516)
gio_apim_management_api |       at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
gio_apim_management_api |       at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
gio_apim_management_api |       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
gio_apim_management_api |       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
gio_apim_management_api |       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
gio_apim_management_api |       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
gio_apim_management_api |       at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
gio_apim_management_api |       at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
gio_apim_management_api |       at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by RubenMMSantos** [comment]
Testing covered by devs due to it being a very technical issue (needs a local build and manual fine tuning) which requires some time to validate.
