### ISSUE TITLE
[management] Fetching Documentation Page from external source (GitHub/Gitlab) return 401 or 404

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6331]
When trying to fetch Documentation Page from external source (GitHub/Gitlab) in 3.11.1 , the page is not fetched and the logs show : 
GitHub : Status code: 404. Message: Not Found
GitLab : Status code: 401. Message: Unauthorized
Not tested with other sources available.

The exact same settings work in 3.10.3

### Steps to Reproduce (for bugs)

1. In UI Console, create an API and a Documentation page from external source (GitHub or GitLab)
2. The page will correctly be displayed in the UI
3. Try to fetch the page from the FETCH button
4. With a page from GitHub the following error is raised : 
```
20:06:44.737 [gravitee-listener-97] ERROR i.g.fetcher.github.GitHubFetcher - io.gravitee.fetcher.api.FetcherException: Unable to fetch 'https://api.github.com/repos/me/myproject/contents/test-swagger-api.json?ref=main'. Status code: 404. Message: Not Found
java.util.concurrent.CompletionException: io.gravitee.fetcher.api.FetcherException: Unable to fetch 'https://api.github.com/repos/me/myproject/contents/test-swagger-api.json?ref=main'. Status code: 404. Message: Not Found
at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
at io.gravitee.fetcher.github.GitHubFetcher.request(GitHubFetcher.java:198)
at io.gravitee.fetcher.github.GitHubFetcher.fetch(GitHubFetcher.java:96)
at io.gravitee.rest.api.service.impl.PageServiceImpl.fetchPage(PageServiceImpl.java:1419)
...
```
5. With a page from GitLab : 
```
07:54:50.281 [gravitee-listener-93] ERROR i.g.r.a.service.impl.PageServiceImpl - Unable to fetch Gitlab content (io.gravitee.fetcher.api.FetcherException: Unable to fetch 'https://gitlab.com/api/v4/projects/moi%2Fmonprojet/repository/files/test-swagger-api.json?ref=main'. Status code: 401. Message: Unauthorized)
io.gravitee.fetcher.api.FetcherException: Unable to fetch Gitlab content (io.gravitee.fetcher.api.FetcherException: Unable to fetch 'https://gitlab.com/api/v4/projects/moi%2Fmonprojet/repository/files/test-swagger-api.json?ref=main'. Status code: 401. Message: Unauthorized)
	at io.gravitee.fetcher.gitlab.GitlabFetcher.request(GitlabFetcher.java:247)
	at io.gravitee.fetcher.gitlab.GitlabFetcher.fetch(GitlabFetcher.java:104)
	at io.gravitee.rest.api.service.impl.PageServiceImpl.fetchPage(PageServiceImpl.java:1419)
	at io.gravitee.rest.api.service.impl.PageServiceImpl.fetch(PageServiceImpl.java:2106)
	at io.gravitee.rest.api.service.impl.PageServiceImpl.fetch(PageServiceImpl.java:2091)
...
```

### Your Environment

* Version used: 3.11.1
* Browser Name and version:
* Operating System and version:

**Comment by mouligno** [comment]
LGTM

**Comment by LiliaEn** [comment]
Tested on 3.12.X env.
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
Tested using Github file only.
Works as expected.
