### ISSUE TITLE
[gateway] OpenTracing hanging gateway

### ISSUE THREAD

**Issue by LjupchoKostoski** [gravitee-io/issues#6366]
- Description
  - After OpenTracing With Jaeger is enabled , gateway don't respond to requests

- Steps to Reproduce
1. Install Jaeger Tracer Plugin
2. Enable tracing > enabled:true in gateway gravitee.yml file
3. Create Test API with some Policy
4. Ping API with Postman
5. No response , Unhandled exception from gateway logs 
```
   12:12:23.498 [vert.x-eventloop-thread-0] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
    java.lang.NoSuchMethodError: 'java.lang.Object io.vertx.core.Context.getLocal(java.lang.String)'
	at io.gravitee.tracer.jaeger.JaegerTracer.receiveRequest(JaegerTracer.java:242)
	at io.gravitee.tracer.jaeger.JaegerTracer.receiveRequest(JaegerTracer.java:66)
	at io.gravitee.node.tracing.vertx.LazyVertxTracer.receiveRequest(LazyVertxTracer.java:40)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:155)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:127)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:111)
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:103)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:193)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:178)
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```
 6. Disable tracing > enabled:false in gateway gravitee.yml file to confirm that tracing is the problem
 7. Ping API with Postman
 8. Response 200 OK

Environment
Version used: 3.11.1
Browser Name and version: Chrome
Operating System and version: Docker Desktop

**Comment by phiz71** [comment]
tracing is not activated on our azure env, so can't be tested there
