### ISSUE TITLE
[Console] Error log on delete action

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6583]
An error is logged on a delete action even if everything worked fine

### Expected Behavior

Shouldn't log an error if no error.

### Current Behavior

```
.gravitee.rest.api.service.exceptions.TechnicalManagementException: Unable to delete document for content [ f7f04c62-ab99-4bf6-b04c-62ab99cbf687 - io.gravitee.rest.api.model.api.ApiEntity ]
	at io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.process(SearchEngineServiceImpl.java:138)
	at jdk.internal.reflect.GeneratedMethodAccessor657.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy63.process(Unknown Source)
	at io.gravitee.rest.api.services.search.ScheduledSearchIndexerService.lambda$run$0(ScheduledSearchIndexerService.java:100)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at io.gravitee.rest.api.services.search.ScheduledSearchIndexerService.run(ScheduledSearchIndexerService.java:92)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurr
```

### Your Environment

* Version used: 3.10 +
* Browser Name and version:
* Operating System and version:

**Comment by LiliaEn** [comment]
Tested on the 3.10.X env
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
Works as expected.
