### ISSUE TITLE
[AM 3.14.0] start gateway docker container

### ISSUE THREAD

**Issue by bkhadige** [gravitee-io/issues#6754]
## :collision: Describe the bug

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webAuthn': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalArgumentException: Invalid root certificate
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:176)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1828)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1270)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
	... 36 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid root certificate
	at io.vertx.ext.auth.webauthn.WebAuthnOptions.putRootCertificate(WebAuthnOptions.java:356)
	at io.vertx.ext.auth.webauthn.WebAuthnOptions.init(WebAuthnOptions.java:176)
	at io.vertx.ext.auth.webauthn.WebAuthnOptions.<init>(WebAuthnOptions.java:147)
	at io.gravitee.am.gateway.handler.vertx.auth.webauthn.WebAuthnFactory.defaultWebAuthn(WebAuthnFactory.java:134)
	at io.gravitee.am.gateway.handler.vertx.auth.webauthn.WebAuthnFactory.getObject(WebAuthnFactory.java:62)
	at io.gravitee.am.gateway.handler.vertx.auth.webauthn.WebAuthnFactory.getObject(WebAuthnFactory.java:44)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
	... 45 common frames omitted
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Wed Dec 15 08:00:00 UTC 2021
	at java.base/sun.security.x509.CertificateValidity.valid(Unknown Source)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(Unknown Source)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(Unknown Source)
	at io.vertx.ext.auth.webauthn.WebAuthnOptions.putRootCertificate(WebAuthnOptions.java:352)
	... 51 common frames omitted

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by bkhadige** [comment]
made another test using docker-compose up --force-recreate  same error

**Comment by brasseld** [comment]
Hi @bkhadige 

Known issue, due to a certificate not being updated from vertx-auth.

Please jump to 3.14.1

**Comment by bkhadige** [comment]
Hi @brasseld 
Thanks for your help moving to 3.14.1 solved the problem
