### ISSUE TITLE
[gateway] Bridge and client gateway are not starting properly 

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#6809]
```
10:17:03.588 [graviteeio-node] [] ERROR i.g.n.p.s.impl.ServiceManagerImpl - Unexpected error while starting service
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.gravitee.repository.management.api.InstallationRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.context.annotation.Lazy(true), @org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1790)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1346)
	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1.getTarget(ContextAnnotationAutowireCandidateResolver.java:95)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:195)
	at jdk.proxy3/jdk.proxy3.$Proxy21.find(Unknown Source)
	at io.gravitee.gateway.standalone.node.GatewayNodeMetadataResolver.getInstallationId(GatewayNodeMetadataResolver.java:85)
	at io.gravitee.gateway.standalone.node.GatewayNodeMetadataResolver.resolve(GatewayNodeMetadataResolver.java:62)
	at io.gravitee.gateway.standalone.node.GatewayNode.metadata(GatewayNode.java:55)
	at io.gravitee.gateway.services.sync.SyncService.doStart(SyncService.java:116)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.plugins.service.impl.ServiceManagerImpl.doStart(ServiceManagerImpl.java:66)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractNode.startComponents(AbstractNode.java:202)
	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:76)
	at io.gravitee.gateway.standalone.node.GatewayNode.doStart(GatewayNode.java:78)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:106)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:154)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:163)
```

**Comment by marcambier** [comment]
As discussed with the team,
I move this ticket in "ready to release", as there is no remote environment with bridge feature enabled that can permit QA to test that.
