### ISSUE TITLE
[gateway][mfa] unable to enroll user with OTP

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#6822]
## :collision: Describe the bug

When MFA OTP is enabled for a domain, a user can flash the QR code but can't validate the code provided by the 2FA Mobile App

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. create a new domain
2. create MFA OTP plugin
3. create a new user
4. create an app
5. enable the mongo idp
6. enable mfa on the app
7. try to connect the user on the GW App
8. the MFA page is displayed with the OTP QRCode
9. flash the code with an mobile App (ex: Google Authenticator)
10. enter the code display by the mobile app in the challenge validation form
11. the error "invalid code" is displayed

## :rainbow: Expected behaviour

The code should be validated and the enrollment process should finish

## :movie_camera: Useful information

```
17:12:45.845 [async-channel-group-0-handler-executor] [] ERROR i.g.a.f.o.provider.OTPFactorProvider - An error occurs while validating 2FA code
java.lang.IllegalArgumentException: Empty key
	at java.base/javax.crypto.spec.SecretKeySpec.<init>(Unknown Source)
	at io.gravitee.am.factor.otp.utils.TOTP.hmac_sha(TOTP.java:67)
	at io.gravitee.am.factor.otp.utils.TOTP.generateTOTP(TOTP.java:184)
	at io.gravitee.am.factor.otp.utils.TOTP.generateTOTP(TOTP.java:121)
	at io.gravitee.am.factor.otp.utils.TOTP.generateTOTP(TOTP.java:105)
	at io.gravitee.am.factor.otp.provider.OTPFactorProvider.lambda$verify$0(OTPFactorProvider.java:52)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)


```
## :computer: Desktop :

versions : 3.10.12

**Comment by leleueri** [comment]
due to gravitee-io/issues#6714
