### ISSUE TITLE
Elasticsearch 5x not supported despite doc?

### ISSUE THREAD

**Issue by bitsofinfo** [gravitee-io/issues#688]
Docs state: 

https://docs.gravitee.io/apim_installguide_gateway.html

```
You can download MongoDB 3.x from MongoDB Download Site and Elasticsearch 2.x or 5.x from Elastic Download Site
--
```

I start the gateway with:

```
docker run  \
        --publish 82:8082  \
        --env GRAVITEEIO_MONGODB_HOST=192.168.1.122  \
        --env GRAVITEEIO_MONGODB_PORT=27017  \
        --env GRAVITEEIO_ELASTIC_HOST=192.168.1.122  \
        --env GRAVITEEIO_ELASTIC_PORT=9300  \
        --name gateway  \
        --detach  \
        graviteeio/gateway:latest
```

On elasticsearch 5.0.0 node logs:

```
[2017-07-12T10:23:40,309][WARN ][o.e.t.n.Netty4Transport  ] [HuC1k1D] exception caught on transport layer [[id: 0x7c5789b1, L:/192.168.1.122:9300 - R:/192.168.1.122:65456]], closing connection
java.lang.IllegalStateException: Received message from unsupported version: [2.0.0] minimal compatible version is: [5.0.0]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1379) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) ~[transport-netty4-5.5.0.jar:5.5.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
```

**Comment by NicolasGeraud** [comment]
Hi @ bitsofinfo ,

what version of gravitee are you using ?
have you change elastic plugins 2x (default one) to 5x ?

**Comment by bitsofinfo** [comment]
Latest docker images 

When I pointed to an ES 2.3.x instance, then it worked fine

**Comment by NicolasGeraud** [comment]
our default bundle include es2 plugins.

**Comment by brasseld** [comment]
I'm currently working on documentation to explain how to move from ES 2.x to 5.x using default distribution.

**Comment by brasseld** [comment]
See: https://docs.gravitee.io/apim_installguide_repositories_elasticsearch.html#moving_to_elasticsearch_5_x
