### ISSUE TITLE
[gateway][bridge] Bridge repository client is not backward compatible

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#6884]
## :collision: Describe the bug
Gateway 3.10.x reports errors in logs when connected to a gateway bridge in v3.15.x

```
08:09:23.574 [gio.sync-1] [] ERROR i.g.r.b.c.m.HttpApiKeyRepository - Unexpected error while invoking bridge: io.gravitee.repository.exceptions.TechnicalException: An error occurs while invoking the bridge server
08:09:23.575 [gio.sync-1] [] ERROR i.g.g.s.s.cache.ApiKeysCacheService - An error occurs while doing a full api-keys refresh for APIs [[BBAF89D4-3584-48E8-9CC0-B611DDF203C2, 090ddddb-f0a4-41f0-8ddd-dbf0a491f0c9]]
io.gravitee.repository.exceptions.TechnicalException: java.util.concurrent.ExecutionException: io.gravitee.repository.exceptions.TechnicalException: An error occurs while invoking the bridge server
	at io.gravitee.repository.bridge.client.management.AbstractRepository.blockingGet(AbstractRepository.java:75)
	at io.gravitee.repository.bridge.client.management.HttpApiKeyRepository.findByCriteria(HttpApiKeyRepository.java:62)
	at io.gravitee.gateway.services.sync.cache.task.ApiKeyRefresher.doRefresh(ApiKeyRefresher.java:42)
	at io.gravitee.gateway.services.sync.cache.task.FullApiKeyRefresher.call(FullApiKeyRefresher.java:35)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: io.gravitee.repository.exceptions.TechnicalException: An error occurs while invoking the bridge server
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at io.gravitee.repository.bridge.client.management.AbstractRepository.blockingGet(AbstractRepository.java:72)
	... 7 common frames omitted
Caused by: io.gravitee.repository.exceptions.TechnicalException: An error occurs while invoking the bridge server
	at io.gravitee.repository.bridge.client.http.HttpRequest.lambda$send$1(HttpRequest.java:117)
	at io.vertx.ext.web.client.impl.HttpContext.handleFailure(HttpContext.java:367)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:361)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:336)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:303)
	at io.vertx.ext.web.client.impl.HttpContext.fail(HttpContext.java:284)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$8(HttpContext.java:522)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unrecognized field "id" (class io.gravitee.repository.management.model.ApiKey), not marked as ignorable (11 known properties: "application", "revokedAt", "expireAt", "plan", "createdAt", "subscription", "updatedAt", "key", "daysToExpirationOnLastNotification", "revoked", "paused"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.gravitee.repository.management.model.ApiKey["id"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4314)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4245)
	at io.vertx.core.json.jackson.DatabindCodec.fromValue(DatabindCodec.java:84)
	at io.vertx.core.json.JsonObject.mapTo(JsonObject.java:117)
	at io.gravitee.repository.bridge.client.utils.BodyCodecs.lambda$list$1(BodyCodecs.java:39)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.gravitee.repository.bridge.client.utils.BodyCodecs.lambda$list$2(BodyCodecs.java:39)
	at io.vertx.ext.web.codec.impl.BodyCodecImpl$1.end(BodyCodecImpl.java:124)
	at io.vertx.core.streams.impl.PipeImpl.handleSuccess(PipeImpl.java:116)
	at io.vertx.core.streams.impl.PipeImpl.lambda$to$2(PipeImpl.java:102)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:373)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:588)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:267)
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:822)
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:694)
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:658)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.Abstra^C	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
```

## :sunrise_over_mountains: To Reproduce
Deploy a gateway 3.10.x and connect it to a bridge in version 3.15.x.

## :rainbow: Expected behavior
We should be backward compatible to allow rolling upgrade without any downtime.

## :movie_camera: Useful information
Not relevant

## :computer: Desktop :

***Please complete the following information:***
Not relevant
## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

If a customer upgrades from 3.10.x to 3.15.x it could have troubles during the deployment phase when all the instances are not all on the same version.

***What are the impacted versions?***

I suppose it affects the 3.5.x and 3.10.x versions.

## :link: Dependencies

Not relevant

**Comment by phiz71** [comment]
Tested with curl command. Ok
