### ISSUE TITLE
[gateway] NPE is raised when TLS is anable without truststore

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7107]
## :collision: Describe the bug
When the Gateway is configured with TLS and keystore but without truststore, a NullPointer is raised by the GraviteeNode module.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. configure secure connection on Gateway https://docs.gravitee.io/am/current/am_installguide_gateway_configuration.html#enable_https_support
2. start the GW

## :rainbow: Expected behaviour

The GW should start

## :warning: Potential impacts

3.15.0

## :link: Dependencies

From https://github.com/gravitee-io/issues/issues/6473

**Comment by apoddany** [comment]
stack trace : 
```
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "io.gravitee.node.vertx.configuration.HttpServerConfiguration.getTrustStoreType()" is null
	at io.gravitee.node.vertx.configuration.HttpServerConfiguration.getHttpServerOptions(HttpServerConfiguration.java:319)
	at io.gravitee.node.vertx.ReactivexVertxHttpServerFactory.getObject(ReactivexVertxHttpServerFactory.java:47)
	at io.gravitee.node.vertx.ReactivexVertxHttpServerFactory.getObject(ReactivexVertxHttpServerFactory.java:28)
```
