### ISSUE TITLE
MongoAuditReporter Error after AM upgrade 3.15.0 to 3.15.2

### ISSUE THREAD

**Issue by vangodev** [gravitee-io/issues#7136]
After upgrading AM from 3.15.0 to 3.15.2, the following error is seen in the log:

`09:49:16.884 [Thread-9] [] ERROR i.g.a.r.m.audit.MongoAuditReporter - An error has occurred during creation of index {"referenceType": 1, "referenceId": 1, "actor.alternativeId": 1, "timestamp": -1}
com.mongodb.MongoCommandException: Command failed with error 67 (CannotCreateIndex): 'namespace name generated from index name "gravitee-am.reporter_audits_b43018b0-d0cf-40fb-b018-b0d0cfa0fb26.$referenceType_1_referenceId_1_actor.alternativeId_1_timestamp_-1" is too long (127 byte max)' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "namespace name generated from index name \"gravitee-am.reporter_audits_b43018b0-d0cf-40fb-b018-b0d0cfa0fb26.$referenceType_1_referenceId_1_actor.alternativeId_1_timestamp_-1\" is too long (127 byte max)", "code": 67, "codeName": "CannotCreateIndex"}
        at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:195)
        at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:493)
        at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:479)
        at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:785)
        at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:752)
        at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:621)
        at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:618)
        at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250)
        at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
        at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:562)
        at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
        at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
        at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:144)
        at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:118)
        at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:107)
        at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:618)
        at com.mongodb.internal.connection.InternalStreamConnection.access$600(InternalStreamConnection.java:81)
        at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:742)
        at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:727)
        at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:621)
        at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:618)
        at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250)
        at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
`

**Comment by tcompiegne** [comment]
@vangodev are you using DocumentDB ?

**Comment by vangodev** [comment]
@brasseld no, not that I'm aware of

**Comment by tcompiegne** [comment]
OK limit has been removed since 4.2. 

Thanks for the feedback.

**Comment by tcompiegne** [comment]
Introduced by https://github.com/gravitee-io/issues/issues/7064

**Comment by vangodev** [comment]
Confirmation that after upgrading MongoDB from 3.6 to 4.2 the error is gone
