### ISSUE TITLE
[APIM] Condition generated automatically when maximum time limit is set in API logging does not work

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7205]
## :collision: Describe the bug
Condition generated automatically when maximum time limit is set in API logging does not work. 
I get the following error:

```
[vert.x-eventloop-thread-5] [] WARN  i.g.g.c.l.c.e.ExpressionLanguageBasedConditionEvaluator - Error parsing condition #request.timestamp <= 1646041253064l
io.gravitee.el.exceptions.ExpressionEvaluationException: The template evaluation returns an error. Expression:
#request.timestamp <= 1646041253064l
	at io.gravitee.el.spel.SpelTemplateEngine.getValue(SpelTemplateEngine.java:62)
	at io.gravitee.el.spel.SpelTemplateEngine.getValue(SpelTemplateEngine.java:68)
	at io.gravitee.gateway.core.logging.condition.el.ExpressionLanguageBasedConditionEvaluator.evaluate(ExpressionLanguageBasedConditionEvaluator.java:43)
	at io.gravitee.gateway.core.logging.condition.el.ExpressionLanguageBasedConditionEvaluator.evaluate(ExpressionLanguageBasedConditionEvaluator.java:29)
	at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.evaluate(LoggableRequestProcessor.java:76)
	at io.gravitee.gateway.handlers.api.processor.logging.ApiLoggableRequestProcessor.evaluate(ApiLoggableRequestProcessor.java:40)
	at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.handle(LoggableRequestProcessor.java:47)
	at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.handle(LoggableRequestProcessor.java:34)
	at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.handle(StreamableProcessorDecorator.java:39)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:80)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.policy.keyless.KeylessPolicy.onRequest(KeylessPolicy.java:39)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.execute(ExecutablePolicy.java:106)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:67)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.handle(LoggableRequestProcessor.java:72)
	at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.handle(LoggableRequestProcessor.java:34)
	at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.handle(StreamableProcessorDecorator.java:39)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.handle(EmptyStreamableProcessor.java:30)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:106)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:90)
	at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:84)
	at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:37)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$4(DefaultReactor.java:99)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:43)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:60)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:29)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:60)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:29)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:107)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.route(VertxReactorHandler.java:64)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:60)
	at io.gravitee.gateway.standalone.vertx.ws.VertxWebSocketReactorHandler.handle(VertxWebSocketReactorHandler.java:48)
	at io.gravitee.gateway.standalone.vertx.ws.VertxWebSocketReactorHandler.handle(VertxWebSocketReactorHandler.java:33)
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:67)
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:30)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:145)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:156)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1001E: Type conversion problem, cannot convert from java.lang.String to java.lang.Boolean
	at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:75)
	at org.springframework.expression.common.ExpressionUtils.convertTypedValue(ExpressionUtils.java:57)
	at org.springframework.expression.common.LiteralExpression.getValue(LiteralExpression.java:92)
	at io.gravitee.el.spel.SpelTemplateEngine.getValue(SpelTemplateEngine.java:60)
	... 77 common frames omitted
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.lang.Boolean] for value '#request.timestamp <= 1646041253064l'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value '#request.timestamp <= 1646041253064l'
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
	at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:70)
	... 80 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid boolean value '#request.timestamp <= 1646041253064l'
	at org.springframework.core.convert.support.StringToBooleanConverter.convert(StringToBooleanConverter.java:66)
	at org.springframework.core.convert.support.StringToBooleanConverter.convert(StringToBooleanConverter.java:32)
	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:386)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
	... 82 common frames omitted
```
If we copy the condition and set it manually it works, but not when is automatically generated.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to Settings > API Logging
2. Set maximum time limit and save
3. Go to the API > Analytics > Logs > Configure logging
4. Enable logging and save
5. If condition does not show up, refresh page.
6. Make request to the API with postman.

## :computer: Desktop :

***Please complete the following information:***
 - Docker installation APIM 3.15.3
 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
Maybe a syntax issue with the condition set from env settings, it needs `{}`

**Comment by gcusnieux** [comment]
@mouligno you are right, the good syntax is `{#request.timestamp <= 1646041253064l}`

**Comment by mouligno** [comment]
LGTM
