### ISSUE TITLE
[reporter] log reporter index creation issue as warn instead of error

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7263]
## :collision: Describe the bug

Since gravitee-io/issues#7064 when AM start, we have this error into the log:

```
13:31:19.534 [Thread-28] [] ERROR i.g.a.r.m.audit.MongoAuditReporter - An error has occurred during creation of index {"referenceType": 1, "referenceId": 1, "timestamp": -1}
com.mongodb.MongoCommandException: Command failed with error 85 (IndexOptionsConflict): 'Index with name: referenceType_1_referenceId_1_timestamp_-1 already exists with a different name' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Index with name: referenceType_1_referenceId_1_timestamp_-1 already exists with a different name", "code": 85, "codeName": "IndexOptionsConflict"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:195)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:493)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:479)

```

## :rainbow: Expected behaviour

IMHO the level should be WARN in case of index creation error. And If we can evaluate the error code to ignore the case of existing index, it should be better.

## :link: Dependencies

Link to  gravitee-io/issues#7064

**Comment by leleueri** [comment]
Don't see this exception anymore :thinking: 
Keep this ticket open just in case

**Comment by tcompiegne** [comment]
Can't reproduce it.
