### ISSUE TITLE
[policy] policy-ssl-enforcement: support x509 attributes

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#7276]
## :collision: Describe the bug
the `S`attribute is not supported

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Implement this test
```
@Test
public void shouldSuccess() throws SSLPeerUnverifiedException {
    when(configuration.isRequiresSsl()).thenReturn(true);
    when(configuration.isRequiresClientAuthentication()).thenReturn(true);
    when(configuration.getWhitelistClientCertificates()).thenReturn(Collections.singletonList("C=FR, O=GraviteeSource, CN=localhost, OU=Eng, L=Lille 1, S=Lille"));
    when(sslSession.getPeerPrincipal()).thenReturn(new X500Principal("CN=localhost, O=GraviteeSource, C=FR, OU=Eng, L=Lille 1, S=Lille"));

    policy.onRequest(request, response, policyChain);

    verify(policyChain).doNext(request, response);
}
```

The error is:

```
java.lang.IllegalArgumentException: Unknown object id - S - passed to distinguished name

	at org.bouncycastle.asn1.x500.style.IETFUtils.decodeAttrName(Unknown Source)
	at org.bouncycastle.asn1.x500.style.BCStyle.attrNameToOID(Unknown Source)
	at org.bouncycastle.asn1.x500.style.IETFUtils.rDNsFromString(Unknown Source)
	at org.bouncycastle.asn1.x500.style.BCStyle.fromString(Unknown Source)
	at org.bouncycastle.asn1.x500.X500Name.<init>(Unknown Source)
	at org.bouncycastle.asn1.x500.X500Name.<init>(Unknown Source)
```

## :rainbow: Expected behaviour
There's a lot of DNs in an x509 certificate. We must support all of them
See:
 - https://docs.oracle.com/cd/E24191_01/common/tutorials/authz_cert_attributes.html
 - https://www.ibm.com/docs/en/ibm-mq/7.5?topic=certificates-distinguished-names

## Current behaviour
The policy fails with a useless `java.lang.reflect.InvocationTargetException`

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.10.7

**Comment by ytvnr** [comment]
Validated by unit test mentioned in the issue
