### ISSUE TITLE
 typescript error TS2339:   on windows when executing   'gulp serve' failed

### ISSUE THREAD

**Issue by kevin-jiang** [gravitee-io/issues#746]
**I type to build master branch and get the following errors when executing 'gulp serve'**
ERROR in ./src/management/api/policies/policies.controller.ts
(95,41): error TS2365: Operator '!==' cannot be applied to types 'number' and 'string'.
ERROR in ./src/management/api/policies/policies.controller.ts
(95,67): error TS2365: Operator '!==' cannot be applied to types 'number' and 'string'.
ERROR in ./src/management/api/policies/policies.controller.ts
(95,97): error TS2365: Operator '!==' cannot be applied to types 'number' and 'string'.
ERROR in ./src/management/api/policies/policies.controller.ts
(96,20): error TS2339: Property 'policyId' does not exist on type 'string'.
ERROR in ./src/management/api/policies/policies.controller.ts
(97,57): error TS2339: Property 'policyId' does not exist on type 'string'.
ERROR in ./src/management/api/policies/policies.controller.ts
(99,22): error TS2339: Property 'name' does not exist on type 'string'.
ERROR in ./src/management/api/policies/policies.controller.ts
(100,22): error TS2339: Property 'type' does not exist on type 'string'.
.................
ERROR in ./src/management/api/history/apiHistory.controller.ts
(89,25): error TS2339: Property 'properties' does not exist on type 'string'.
ERROR in ./src/management/api/healthcheck/healthcheck.controller.ts
(290,13): error TS2322: Type 'string' is not assignable to type 'number'.
ERROR in ./src/management/api/healthcheck/healthcheck.controller.ts
(305,13): error TS2322: Type 'string' is not assignable to type 'number'.

the following are my env versions.
D:\api-gateway\gravitee-management-webui (master) (gravitee-management-webui@1.8.4)
λ node -v
v6.11.2
D:\api-gateway\gravitee-management-webui (master) (gravitee-management-webui@1.8.4)
λ npm -v
3.10.10
D:\api-gateway\gravitee-management-webui (master) (gravitee-management-webui@1.8.4)
λ tsc -v
Version 2.3.2
D:\api-gateway\gravitee-management-webui (master) (gravitee-management-webui@1.8.4)
λ gulp -version
[15:45:49] CLI version 1.4.0
[15:45:49] Local version 4.0.0-alpha.2

**Comment by kevin-jiang** [comment]
and i removed all the code , and downed from git again, 
this time , i used  yarn install.  and met a  new error:

C:\gravitee-management-webui (master) (gravitee-management-webui@1.8.4)
λ gulp serve
[17:04:42] Using file C:\gravitee-management-webui\gulpfile.js
[17:04:42] Working directory changed to C:\gravitee-management-webui
[17:04:44] Loading C:\gravitee-management-webui\gulp_tasks\browsersync.js
[17:04:44] Loading C:\gravitee-management-webui\gulp_tasks\karma.js
[17:04:45] Loading C:\gravitee-management-webui\gulp_tasks\misc.js
[17:04:45] Loading C:\gravitee-management-webui\gulp_tasks\protractor.js
[17:04:45] Loading C:\gravitee-management-webui\gulp_tasks\webpack.js
keywords if/then/else require v5 option
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
C:\Users\ThinkPad\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:132
localGulp.run.apply(localGulp, tasks);
^
TypeError: Cannot read property 'apply' of undefined
at C:\Users\ThinkPad\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:132:18
at _combinedTickCallback (internal/process/next_tick.js:73:7)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)
at Module.runMain (module.js:606:11)
at run (bootstrap_node.js:389:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:504:3
C:\gravitee-management-webui (master) (gravitee-management-webui@1.8.4)

this the help of Elamrani Azize @aelamrani, i  install globally gulp-cli
npm install -g gulp-cli. and executing  gulp serve again.  and met the following error:

ERROR in ./~/css-loader?importLoaders=1!./~/sass-loader!./~/postcss-loader!./src/index.scss
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\gravitee-management-webui\node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (C:\gravitee-management-webui\node_modules\node-sass\lib\extensions.js:121:13)
    at foundBinariesList (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\gravitee-management-webui\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\gravitee-management-webui\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\gravitee-management-webui\node_modules\sass-loader\index.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (C:\gravitee-management-webui\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\gravitee-management-webui\node_modules\loader-runner\lib\loadLoader.js:36:3)
 @ ./src/index.scss 4:14-168
 @ ./src/index.ts

ERROR in ./~/css-loader?importLoaders=1!./~/sass-loader!./~/postcss-loader!./~/angular-loading-bar/build/loading-bar.css
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\gravitee-management-webui\node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (C:\gravitee-management-webui\node_modules\node-sass\lib\extensions.js:121:13)
    at foundBinariesList (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\gravitee-management-webui\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\gravitee-management-webui\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\gravitee-management-webui\node_modules\sass-loader\index.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (C:\gravitee-management-webui\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\gravitee-management-webui\node_modules\loader-runner\lib\loadLoader.js:36:3)
 @ ./~/angular-loading-bar/build/loading-bar.css 4:14-143
 @ ./src/management/management.module.ts
 @ ./src/index.ts
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  4.9 kB       0
[21:09:35] Finished 'webpack:watch' after 55 s
[21:09:35] Starting 'watch'...
[21:09:35] Finished 'watch' after 208 ms
[21:09:35] Starting 'browsersync'...
[HPM] Proxy created: /management  ->  http://localhost:8083
[21:09:35] Finished 'browsersync' after 71 ms
[21:09:35] Finished 'serve' after 55 s
[BS] [BrowserSync SPA] Running...
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.56.1:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.56.1:3001
 -------------------------------------
[BS] Serving files from: .tmp
[BS] Serving files from: src

**Comment by kevin-jiang** [comment]
WARNING in ./src/management/configuration/roles/user/add/add.user.dialog.controller.ts
[70, 5]: misplaced 'else'
[21, 86]: expected parameter: 'role' to have a typedef
[21, 97]: expected parameter: 'roleScope' to have a typedef
[34, 62]: expected parameter: 'users' to have a typedef
[42, 35]: expected parameter: 'query' to have a typedef
[55, 42]: expected parameter: 'item' to have a typedef
[65, 33]: expected parameter: 'user' to have a typedef
[75, 37]: expected parameter: 'user' to have a typedef
[46, 74]: missing whitespace
[48, 33]: missing whitespace
[48, 77]: missing whitespace

 @ ./src/management/management.module.ts 254:35-115
 @ ./src/index.ts

WARNING in ./src/management/configuration/roles/user/delete/delete.user.role.dialog.controller.ts
[16, 89]: expected parameter: 'role' to have a typedef
[16, 99]: expected parameter: 'username' to have a typedef

 @ ./src/management/management.module.ts 255:43-134
 @ ./src/index.ts

WARNING in ./src/portal/api/subscribe/api-subscribe.ts
[116, 4]: Missing semicolon
[20, 39]: expected parameter: '$state' to have a typedef
[21, 52]: expected parameter: 'NotificationService' to have a typedef
[24, 42]: expected parameter: 'Constants' to have a typedef
[25, 43]: expected parameter: '$translate' to have a typedef
[31, 51]: expected parameter: 'path' to have a typedef
[34, 100]: expected parameter: 'quotaPeriodTimeUnitTranslated' to have a typedef
[41, 48]: expected parameter: 'translatedMessage' to have a typedef
[50, 39]: expected parameter: 'application' to have a typedef
[60, 45]: expected parameter: 'application' to have a typedef
[67, 35]: expected parameter: 'application' to have a typedef
[70, 96]: expected parameter: 'apiKeys' to have a typedef
[81, 36]: expected parameter: 'application' to have a typedef
[85, 90]: expected parameter: 'subscriptions' to have a typedef
[100, 38]: expected parameter: 'e' to have a typedef

 @ ./src/portal/api/subscribe/api-subscribe.component.ts 18:22-48
 @ ./src/portal/portal.module.ts
 @ ./src/index.ts

ERROR in ./~/css-loader?importLoaders=1!./~/sass-loader!./~/postcss-loader!./src/index.scss
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\gravitee-management-webui\node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (C:\gravitee-management-webui\node_modules\node-sass\lib\extensions.js:121:13)
    at foundBinariesList (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\gravitee-management-webui\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\gravitee-management-webui\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\gravitee-management-webui\node_modules\sass-loader\index.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (C:\gravitee-management-webui\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\gravitee-management-webui\node_modules\loader-runner\lib\loadLoader.js:36:3)
 @ ./src/index.scss 4:14-168
 @ ./src/index.ts

ERROR in ./~/css-loader?importLoaders=1!./~/sass-loader!./~/postcss-loader!./~/angular-loading-bar/build/loading-bar.css
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\gravitee-management-webui\node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (C:\gravitee-management-webui\node_modules\node-sass\lib\extensions.js:121:13)
    at foundBinariesList (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\gravitee-management-webui\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\gravitee-management-webui\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\gravitee-management-webui\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\gravitee-management-webui\node_modules\sass-loader\index.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (C:\gravitee-management-webui\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\gravitee-management-webui\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\gravitee-management-webui\node_modules\loader-runner\lib\loadLoader.js:36:3)
 @ ./~/angular-loading-bar/build/loading-bar.css 4:14-143
 @ ./src/management/management.module.ts
 @ ./src/index.ts
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  4.9 kB       0
[21:09:35] Finished 'webpack:watch' after 55 s
[21:09:35] Starting 'watch'...
[21:09:35] Finished 'watch' after 208 ms
[21:09:35] Starting 'browsersync'...
[HPM] Proxy created: /management  ->  http://localhost:8083
[21:09:35] Finished 'browsersync' after 71 ms
[21:09:35] Finished 'serve' after 55 s
[BS] [BrowserSync SPA] Running...
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.56.1:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.56.1:3001
 -------------------------------------
[BS] Serving files from: .tmp
[BS] Serving files from: src
^C终止批处理操作吗(Y/N)?
^C
C:\gravitee-management-webui  (gravitee-management-webui@1.8.4)

**Comment by kevin-jiang** [comment]
![qq 20170827215652](https://user-images.githubusercontent.com/5965992/29750469-ab19b1c0-8b72-11e7-9fe4-bbde1972f3a5.png)

indeed, there is no vendor dir in node-sass

**Comment by aelamrani** [comment]
Can you remove the node_modules directory et execute `yarn install` then launch the app with `gulp serve`

**Comment by kevin-jiang** [comment]
i just create a empty vendor dir, and rebuild the  node-sass   using npm rebuild node-sass --save-dev. the error is fixed

**Comment by aelamrani** [comment]
You should not have to build manually node-sass..
I suggested to remove the node_modules directory of the root to properly build hierarchies with correct versions defined on the yarn.lock file...

**Comment by aelamrani** [comment]
@kevin-jiang is it ok for you now? Can i close this issue?

**Comment by kevin-jiang** [comment]
@aelamrani  , i just executing the gulp serve again, now it's working very well, you can close this issue.  Thank you very much today,  so glad to launch to app  finally.
