### ISSUE TITLE
[discovery] [eureka] Failed to initialize DiscoveryClient

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7505]
## :collision: Describe the bug
With 3.15.6-ee, Eureka Service Discovery can not be started and the following exception is raised in the logs : 

```
11:13:00.096 [gio.sync-2] [02e02dbd-408e-4529-a02d-bd408ee52969] ERROR i.g.p.c.i.PluginContextFactoryImpl - Unable to refresh plugin context
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.gravitee.discovery.eureka.EurekaServiceDiscovery': Invocation of init method failed; nested exception is java.lang.RuntimeException: Failed to initialize DiscoveryClient!
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
...
Caused by: java.lang.RuntimeException: Failed to initialize DiscoveryClient!
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:411)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:269)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:265)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:257)
	at io.gravitee.discovery.eureka.EurekaServiceDiscovery.afterPropertiesSet(EurekaServiceDiscovery.java:95)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 27 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:989)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:592)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:514)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:483)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:429)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:396)
	at com.netflix.discovery.converters.XmlXStream.<init>(XmlXStream.java:51)
	at com.netflix.discovery.converters.XmlXStream.<clinit>(XmlXStream.java:42)
	at com.netflix.discovery.converters.wrappers.CodecWrappers$XStreamXml.<init>(CodecWrappers.java:358)
	at com.netflix.discovery.converters.wrappers.CodecWrappers.create(CodecWrappers.java:133)
	at com.netflix.discovery.converters.wrappers.CodecWrappers.getEncoder(CodecWrappers.java:75)
	at com.netflix.discovery.converters.wrappers.CodecWrappers.getEncoder(CodecWrappers.java:66)
	at com.netflix.discovery.provider.DiscoveryJerseyProvider.<init>(DiscoveryJerseyProvider.java:77)
	at com.netflix.discovery.shared.transport.jersey.EurekaJerseyClientImpl$EurekaJerseyClientBuilder$MyDefaultApacheHttpClient4Config.<init>(EurekaJerseyClientImpl.java:202)
	at com.netflix.discovery.shared.transport.jersey.EurekaJerseyClientImpl$EurekaJerseyClientBuilder.build(EurekaJerseyClientImpl.java:178)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory$JerseyEurekaHttpClientFactoryBuilder.buildLegacy(JerseyEurekaHttpClientFactory.java:219)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory$JerseyEurekaHttpClientFactoryBuilder.build(JerseyEurekaHttpClientFactory.java:194)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory.create(JerseyEurekaHttpClientFactory.java:151)
	at com.netflix.discovery.shared.transport.jersey.Jersey1TransportClientFactories.newTransportClientFactory(Jersey1TransportClientFactories.java:59)
	at com.netflix.discovery.DiscoveryClient.scheduleServerEndpointTask(DiscoveryClient.java:485)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:398)
	... 33 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @72f46a4e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
	at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:40)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
	... 54 common frames omitted

```

It is working in 3.15.4 even if raising warnings regarding  Illegal access:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/opt/graviteeio-gateway/plugins/.work/gravitee-service-discovery-eureka-1.1.1/lib/xstream-1.4.10.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Suspected to be related to the JDK version in use
3.15.4-ee is JDK 11 and 3.15.6-ee is JDK 17

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Setup Eureka Service Discovery as described in the documentation

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.6-ee

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by a-cordier** [comment]
@apoddany the issue has been reproduced and a fixed released version of the plugin has been made available at https://github.com/gravitee-io-community/gravitee-service-discovery-eureka/releases/tag/1.2.1

**Comment by ppgravitee** [comment]
@apoddany is this issue solved for you ?

**Comment by apoddany** [comment]
yes confirmed as solved
