### ISSUE TITLE
[gateway] gateway does not start if openssl is enabled

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7742]
## :collision: Describe the bug
When enabling openssl in the gravitee.yml file of the gateway as : 
```
http:
#  port: 8082
#  host: 0.0.0.0
...
  ssl:
#    clientAuth: none # Supports none, request, requires
#    tlsProtocols: TLSv1.2, TLSv1.3
...
#    sni: false
    openssl: true # Used to rely on OpenSSL Engine instead of default JDK SSL Engine
```
The gateway will not start with the following exception : 
```
io.vertx.core.VertxException: OpenSSL is not available
        at io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(SSLHelper.java:75)
        at io.vertx.core.net.impl.SSLHelper.<init>(SSLHelper.java:127)
        at io.vertx.core.net.impl.SSLHelper.<init>(SSLHelper.java:158)
        at io.vertx.core.net.impl.TCPServerBase.createSSLHelper(TCPServerBase.java:90)
        at io.vertx.core.http.impl.HttpServerImpl.createSSLHelper(HttpServerImpl.java:203)
        at io.vertx.core.net.impl.TCPServerBase.listen(TCPServerBase.java:150)
        at io.vertx.core.net.impl.TCPServerBase.bind(TCPServerBase.java:100)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:217)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:149)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:135)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:140)
        at io.gravitee.gateway.standalone.vertx.ReactorVerticle.start(ReactorVerticle.java:90)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
        at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
        at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
        at io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(SSLHelper.java:74)
```
And when setting `openssl: false` the gateway starts but sometimes throw this error with JAVA_OPTS=-Djavax.net.debug=ssl": 
```
javax.net.ssl|ERROR|D1|vert.x-eventloop-thread-2|2022-05-24 15:16:22.153 GMT|null:-1|Fatal (INTERNAL_ERROR): closing inbound before receiving peer's close_notify (
"throwable" : {
  javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.SSLEngineImpl.closeInbound(Unknown Source)
        at io.netty.handler.ssl.JdkSslEngine.closeInbound(JdkSslEngine.java:57)
        at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1867)
        at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1067)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)}
)
```
## :rainbow: Expected behaviour
Enabling openssl should not prevent the gateway to start as in previous 3.10

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: replicated in 3.15.8 but not in 3.10.3

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by apoddany** [comment]
@gcusnieux my bad. looks like only when HC is set for an existing API as : 
```
gio_apim_gateway-3.15.8 | 16:25:28.882 [gio.sync-0] [0a4dd4e2-2ed1-4fe9-8dd4-e22ed18fe9cb] ERROR i.g.g.s.h.v.EndpointHealthcheckVerticle - An error occurs while creating an health-check runner
gio_apim_gateway-3.15.8 | io.vertx.core.VertxException: OpenSSL is not available
gio_apim_gateway-3.15.8 | 	at io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(SSLHelper.java:75)
gio_apim_gateway-3.15.8 | 	at io.vertx.core.net.impl.SSLHelper.<init>(SSLHelper.java:127)
gio_apim_gateway-3.15.8 | 	at io.vertx.core.net.impl.SSLHelper.<init>(SSLHelper.java:143)
```
1. Enable HC on an API
2. Enable openssl as above
3. Restart the gateway

**Comment by gcusnieux** [comment]
Ok thanks! Do you know the OS ?

**Comment by apoddany** [comment]
@gcusnieux I replicated in Docker 3.15.8 and 3.16.4 : 
```
/opt/graviteeio-gateway # more /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.4
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by mouligno** [comment]
Covered by integration test on the gateway
