### ISSUE TITLE
[Gateway] gRPC traffic does not pass through the gateway if the endpoint works via https

### ISSUE THREAD

**Issue by grignix** [gravitee-io/issues#7760]
## :collision: Describe the bug
gRPC traffic does not pass through the gateway if the endpoint works via https

Gravitee 3.15.4

if Endpoint address http://example.org/echo then gRPC traffic passes normally

if Endpoint address https://example.org/echo gRPC traffic does not go through, in analytics Status 502

Error: Failed to create SSL connection

in the logs on the gateway

```
15:28:22.444 [vert.x-eventloop-thread-3] [] DEBUG i.g.g.reactor.impl.DefaultReactor - Receiving a request 2017c048-3dd0-4233-97c0-483dd05233c4 for path /api/grpc-tests/resttest.Messaging/GetMessageById
15:28:22.444 [vert.x-eventloop-thread-3] [] DEBUG i.g.g.s.core.SecurityPolicyResolver - Authentication handler [key_less] has been selected to secure incoming request 2017c048-3dd0-4233-97c0-483dd05233c4
15:28:22.461 [vert.x-eventloop-thread-3] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: Cannot invoke "io.vertx.core.http.HttpClientRequest.putHeader(String, String)" because "this.httpClientRequest" is null
        at io.gravitee.connector.http.HttpConnection.lambda$writeUpstreamHeaders$5(HttpConnection.java:303)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.gravitee.connector.http.HttpConnection.writeUpstreamHeaders(HttpConnection.java:303)
        at io.gravitee.connector.http.HttpConnection.writeHeaders(HttpConnection.java:283)
        at io.gravitee.connector.http.HttpConnection.write(HttpConnection.java:263)
        at io.gravitee.connector.http.HttpConnection.write(HttpConnection.java:49)
        at io.gravitee.gateway.core.endpoint.factory.impl.EndpointFactoryImpl$ConnectorProxyConnection.write(EndpointFactoryImpl.java:122)
        at io.gravitee.gateway.core.endpoint.factory.impl.EndpointFactoryImpl$ConnectorProxyConnection.write(EndpointFactoryImpl.java:74)
        at io.gravitee.gateway.core.logging.LoggableProxyConnection.write(LoggableProxyConnection.java:104)
        at io.gravitee.gateway.core.logging.LoggableProxyConnection.write(LoggableProxyConnection.java:39)
        at io.gravitee.gateway.core.invoker.EndpointInvoker.lambda$invoke$2(EndpointInvoker.java:82)
        at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$5(AbstractStreamableProcessorChain.java:71)
        at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.write(EmptyStreamableProcessor.java:47)
        at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$5(AbstractStreamableProcessorChain.java:71)
        at io.gravitee.gateway.api.stream.SimpleReadWriteStream.write(SimpleReadWriteStream.java:44)
        at io.gravitee.gateway.api.stream.SimpleReadWriteStream.write(SimpleReadWriteStream.java:24)
        at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.write(AbstractStreamableProcessorChain.java:103)
        at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.write(StreamableProcessorDecorator.java:74)
        at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:130)
        at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:35)
        at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.write(StreamableProcessorDecorator.java:74)
        at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.write(StreamableProcessorDecorator.java:74)
        at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.write(EmptyStreamableProcessor.java:47)
        at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.write(AbstractStreamableProcessorChain.java:103)
        at io.gravitee.gateway.core.logging.LoggableClientRequest.lambda$bodyHandler$0(LoggableClientRequest.java:69)
        at io.gravitee.gateway.core.logging.LoggableClientRequest.lambda$bodyHandler$0(LoggableClientRequest.java:69)
        at io.gravitee.gateway.http.vertx.VertxHttpServerRequest.lambda$bodyHandler$0(VertxHttpServerRequest.java:190)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.http.impl.HttpEventHandler.handleChunk(HttpEventHandler.java:51)
        at io.vertx.core.http.impl.Http1xServerRequest.onData(Http1xServerRequest.java:531)
        at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:128)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
        at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:227)
        at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:280)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by gcusnieux** [comment]
Hello @grignix, 
Can I have more informations ? 
 - an API export
 - a call to api
 - the SSL conf of GRPC server

**Comment by gcusnieux** [comment]
Hello @grignix, 
if you use a proxy like nginx to provide SSL environment behind a GRPC endoint, your issue is maybe related to gravitee-io/issues#6719

**Comment by grignix** [comment]
When requesting Kreya "**grpc-web**" through gravitee, we get an error 502, in gravitee "Error: Failed to create SSL connection" what is described above
![image](https://user-images.githubusercontent.com/26620272/174300074-45d0d4f9-9f3e-431c-a070-ec2f515a9a07.png)
When requesting Kreya "**grpc**" through gravitee
![image](https://user-images.githubusercontent.com/26620272/174300139-1a22d79f-50b3-4752-8b39-0146018f06a7.png)
In gravitee ui, logs does not at all be. On gravity gw in the logs only:

15:32:31.881 [vert.x-eventloop-thread-0] [] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x75c67417, L:/[100.64.51.44:443](http://100.64.51.44:443/) - R:/[172.20.66.7:62481](http://172.20.66.7:62481/)] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

**Comment by grignix** [comment]
![image](https://user-images.githubusercontent.com/26620272/174314085-be494c2c-eed6-414b-b64d-aee06bee6f7a.png)

**Comment by gcusnieux** [comment]
blocked by https://github.com/gravitee-io/issues/issues/6719
