### ISSUE TITLE
[APIM] in version 3.15.9 the display of healthcheck logs is broken

### ISSUE THREAD

**Issue by grignix** [gravitee-io/issues#7841]
## :collision: Describe the bug
in api version 3.15.9 the display of healthcheck logs is broken, in version 3.15.8 everything is OK

## Current behaviour
api & ui version 3.15.**9** 
![image](https://user-images.githubusercontent.com/26620272/174095389-cff34afb-2382-4778-b086-ce3c4034e7d3.png)
## :rainbow: Expected behaviour
api version 3.15.**8** & ui version 3.15.9 
![image](https://user-images.githubusercontent.com/26620272/174096346-b9d4c534-53ea-4edb-8f93-e628cfb90318.png)

**Comment by grignix** [comment]
Hello @[gcusnieux](https://github.com/gcusnieux)  
api can be found here https://github.com/gravitee-io/issues/files/8920808/t1-1-0.zip, this is the same api as in https://github.com/gravitee-io/issues /issues/7844

checked, in version 3.15.10 the problem exists **and a new problem appeared**, if the gateway is version 3.15.10 then "Latest check" is empty
![image](https://user-images.githubusercontent.com/26620272/176463753-cca50304-3f35-4a1e-a0b9-5552732389e9.png)

in gravitee gateway logs

14:30:50.055 [RxCachedThreadScheduler-1] [] ERROR i.g.e.t.f.FreeMarkerComponent - Impossible to generate from template /es7x/index/health.ftl
freemarker.core.NonMethodException: For "...(...)" callee: Expected a method or function, but this has evaluated to a sequence (io.netty.handler.codec.HeadersUtils$1 wrapped into f.t.DefaultListAdapter):
==> step.getResponse().getHeaders().names  [in template "es7x/index/health.ftl" at line 51, column 24]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list step.getResponse().getHeaders()...  [in template "es7x/index/health.ftl" at line 51, column 17]
	- Reached through: @compress single_line=true  [in template "es7x/index/health.ftl" at line 8, column 1]
----
	at freemarker.core.MethodCall._eval(MethodCall.java:67)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:99)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:389)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.Environment.visitAndTransform(Environment.java:514)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at freemarker.template.Template.process(Template.java:383)
	at io.gravitee.elasticsearch.templating.freemarker.FreeMarkerComponent.generateFromTemplate(FreeMarkerComponent.java:109)
	at io.gravitee.reporter.elasticsearch.indexer.es7.ES7BulkIndexer.generateData(ES7BulkIndexer.java:34)
	at io.gravitee.reporter.elasticsearch.indexer.AbstractIndexer.getSource(AbstractIndexer.java:193)
	at io.gravitee.reporter.elasticsearch.indexer.AbstractIndexer.transform(AbstractIndexer.java:118)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
	at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscriptions.SubscriptionArbiter.setSubscription(SubscriptionArbiter.java:99)
	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onSubscribe(FlowableOnErrorNext.java:69)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext.subscribeActual(FlowableOnErrorNext.java:40)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Jun 29, 2022 2:31:00 PM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
For "...(...)" callee: Expected a method or function, but this has evaluated to a sequence (io.netty.handler.codec.HeadersUtils$1 wrapped into f.t.DefaultListAdapter):
==> step.getResponse().getHeaders().names  [in template "es7x/index/health.ftl" at line 51, column 24]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list step.getResponse().getHeaders()...  [in template "es7x/index/health.ftl" at line 51, column 17]
	- Reached through: @compress single_line=true  [in template "es7x/index/health.ftl" at line 8, column 1]
----

Java stack trace (for programmers):
----
freemarker.core.NonMethodException: [... Exception message was already printed; see it above ...]
	at freemarker.core.MethodCall._eval(MethodCall.java:67)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:99)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:389)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.Environment.visitAndTransform(Environment.java:514)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at freemarker.template.Template.process(Template.java:383)
	at io.gravitee.elasticsearch.templating.freemarker.FreeMarkerComponent.generateFromTemplate(FreeMarkerComponent.java:109)
	at io.gravitee.reporter.elasticsearch.indexer.es7.ES7BulkIndexer.generateData(ES7BulkIndexer.java:34)
	at io.gravitee.reporter.elasticsearch.indexer.AbstractIndexer.getSource(AbstractIndexer.java:193)
	at io.gravitee.reporter.elasticsearch.indexer.AbstractIndexer.transform(AbstractIndexer.java:118)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
	at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscriptions.SubscriptionArbiter.setSubscription(SubscriptionArbiter.java:99)
	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onSubscribe(FlowableOnErrorNext.java:69)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext.subscribeActual(FlowableOnErrorNext.java:40)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by mouligno** [comment]
hi @grignix we've catched this one and are currently working on it : https://github.com/gravitee-io/issues/issues/7930

**Comment by grignix** [comment]
Hi @[mouligno](https://github.com/mouligno) these are different errors, in version 3.15.9 broken is apim-management-api,  in 3.15.10 version another error was added https://github.com/gravitee-io/issues/issues/7930

**Comment by mouligno** [comment]
Yes my comment was about the 3.15.10 one ! thanks for sharing

**Comment by mouligno** [comment]
LGTM

**Comment by LiliaEn** [comment]
Tested on 3.15.x env
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Working as expected
![Screenshot 2022-07-21 at 08.55.33.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/bb66e716-fe33-456e-8e49-01cc824dfcc7)
