### ISSUE TITLE
[management] unable to remove domain

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7913]
On JDBC implementation, we are not able to remove a domain due to the following error :

```
08:09:26.429 [reactor-tcp-nio-4] [] ERROR i.g.a.s.impl.UserActivityServiceImpl - An unexpected error has occurred while deleting userActivity 'execute; bad SQL grammar [DELETE FROM user_activities WHERE user_activities.reference_type = $1 AND (user_activities.reference_id = $2)]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42P01] relation "user_activities" does not exist'
org.springframework.r2dbc.BadSqlGrammarException: execute; bad SQL grammar [DELETE FROM user_activities WHERE user_activities.reference_type = $1 AND (user_activities.reference_id = $2)]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42P01] relation "user_activities" does not exist
	at org.springframework.r2dbc.connection.ConnectionFactoryUtils.convertR2dbcException(ConnectionFactoryUtils.java:235)
	at org.springframework.r2dbc.core.DefaultDatabaseClient.lambda$inConnection$4(DefaultDatabaseClient.java:125)
	at reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3719)
	at reactor.core.publisher.Mono.lambda$onErrorResume$32(Mono.java:3809)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredError(MonoUsingWhen.java:287)
	
```

**Comment by leleueri** [comment]
Not an issue, this error comes from the env on which the test has been done.
Liquibase has failed to run the script, so the user_activities table has not been created.
