### ISSUE TITLE
[Management] Healthcheck is failing to report in ES due to issue on headers.

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7930]
## :collision: Describe the bug

Healthcheck is failing to report in ES due to issue on headers.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information

````
un 29, 2022 5:13:41 AM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
For "...(...)" callee: Expected a method or function, but this has evaluated to a sequence (io.netty.handler.codec.HeadersUtils$1 wrapped into f.t.DefaultListAdapter):
==> step.getResponse().getHeaders().names  [in template "es7x/index/health.ftl" at line 51, column 24]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list step.getResponse().getHeaders()...  [in template "es7x/index/health.ftl" at line 51, column 17]
	- Reached through: @compress single_line=true  [in template "es7x/index/health.ftl" at line 8, column 1]
----

Java stack trace (for programmers):
----
freemarker.core.NonMethodException: [... Exception message was already printed; see it above ...]
	at freemarker.core.MethodCall._eval(MethodCall.java:67)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:99)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:389)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:383)
05:13:41.019 [RxCachedThreadScheduler-1] [] ERROR i.g.e.t.f.FreeMarkerComponent - Impossible to generate from template /es7x/index/health.ftl
freemarker.core.NonMethodException: For "...(...)" callee: Expected a method or function, but this has evaluated to a sequence (io.netty.handler.codec.HeadersUtils$1 wrapped into f.t.DefaultListAdapter):
==> step.getResponse().getHeaders().names  [in template "es7x/index/health.ftl" at line 51, column 24]
```
## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x]
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
LGTM
