### ISSUE TITLE
[gateway] unable to initialize Extension Grant plugin

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8144]
After submitting the ExtGrant config to the REST API, the GW throws a NullPointer

```
12:33:10.826 [async-channel-group-0-handler-executor] [] ERROR i.g.a.p.h.a.c.ProviderPluginManager - An unexpected error occurs while loading
java.lang.NullPointerException: Cannot invoke "io.gravitee.am.extensiongrant.jwtbearer.JWTBearerExtensionGrantConfiguration.getPublicKey()" because "this.jwtBearerTokenGranterConfiguration" is null
	at io.gravitee.am.extensiongrant.jwtbearer.provider.JWTBearerExtensionGrantProvider.afterPropertiesSet(JWTBearerExtensionGrantProvider.java:66)
	at io.gravitee.am.plugins.handlers.api.core.ProviderPluginManager.createProvider(ProviderPluginManager.java:109)
	at io.gravitee.am.plugins.extensiongrant.core.ExtensionGrantPluginManager.create(ExtensionGrantPluginManager.java:58)
	at io.gravitee.am.gateway.handler.oauth2.service.granter.extensiongrant.impl.ExtensionGrantManagerImpl.updateExtensionGrantProvider(ExtensionGrantManagerImpl.java:175)
	at io.gravitee.am.gateway.handler.oauth2.service.granter.extensiongrant.impl.ExtensionGrantManagerImpl.lambda$afterPropertiesSet$0(ExtensionGrantManagerImpl.java:102)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$recurseCursor$4(BatchCursorFlux.java:94)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:171)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)
	at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:549)
	at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:163)
	at com.mongodb.reactivestreams.client.internal.BatchCursor.lambda$next$0(BatchCursor.java:35)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)

```

**Comment by patelami** [comment]
Env: 3.18
Result: PASS
