### ISSUE TITLE
Errors while installa

### ISSUE THREAD

**Issue by sanjimoh** [gravitee-io/issues#8337]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by sanjimoh** [comment]
Complete gateway pod logs attached -
[graviteeio-apim3x-gateway-844846d49f-jpnv4.log](https://github.com/gravitee-io/issues/files/9387571/graviteeio-apim3x-gateway-844846d49f-jpnv4.log)

**Comment by sanjimoh** [comment]
Hi, I would really appreciate if someone can help me here. Thanks!

**Comment by sanjimoh** [comment]
Looking at the error, it appears to me, is there some version mismatch? Something got dropped causing a backward incompatible change or similar?

```
Caused by: java.lang.ClassNotFoundException: io.gravitee.definition.model.Path
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.net.FactoryURLClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 82 common frames omitted
```

I took a look at the `gravitee-api-management` codebase & I do not any `Path` definition -

https://github.com/gravitee-io/gravitee-api-management/tree/3.15.10/gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model
