### ISSUE TITLE
[dynamy-routing-policy] Route to default endpoint only replacing host

### ISSUE THREAD

**Issue by tfabien** [gravitee-io/issues#8362]
## :rainbow: Feature

**As an** Api Designer

**I want to** route request to a backend url, using the default endpoint, but replacing host

**So that** I can dynamicaly route to a specific host following a naming convention without maintaining the whole backend url inside the policy

## :sunrise_over_mountains: Additional information

Gravitee dynamic-routing policy states:
```
A typical use case is defining this kind of routing:
- Requests from http://gateway/apis/store/12/info are redirected to http://backend_store12/info
- Requests from http://gateway/apis/store/45/info are redirected to http://backend_store45/info
```
The problem I see here, is that you have to explicitely define an endpoint for every "store" and maintain this list
This can be a hassle, especially if you have a lot of stores...

If you have an organization where stores backend uris follow a convention (say `https://storeXXX/myLocalApiPath/API-NAME` for any given `XXX` store and `API-NAME` ), you could dynamically route to this store/api without declaring it in the endpoints

The only way you can achieve this at the moment is by defining the whole backend URL (eg: including the `/myLocalApiPath/myApi` part) inside the dynamic routing Policy
```json
"dynamic-routing": {
    "rules": [
        {
            "pattern": "/v1/stores/(?<store>.*)/(?<restOfUri>.*)",
            "url": "http://store{#groups['store']}/myLocalApiPath/myApi/{#group['restOfUri]}"
        }
    ]
}
```
But this solution leads us to maintaining the whole backend uri inside the policy, and not juste the host

What I would like to do is defining a `default` endpoint such as `http://store[PLACEHOLDER]/myLocalApiPath/myApi`:
```json
"dynamic-routing": {
    "rules": [
        {
            "pattern": "/v1/stores/(?<store>.*)/(?<restOfUri>.*)",
            "url": "{#endpoints['default'].replace('[PLACEHOLDER]', #group['store'])}/{#group['restOfUri]}"
        }
    ]
}
```
This cannot be done at the moment because `{#endpoints['default']}` only returns the `default:` placeholder that will be resolved after all policies have executed on to an url by the ProxyEndpointResolver

Hence the target url generated by the policy would still be `default:restOfUri`, which would still be resolved as `http://store[PLACEHOLDER]/myLocalApiPath/myApi/restOfUri` later on...

A possible solution would be to export the resolved endpoint(s) to an `request.resolved.endpoint` attribute, much like the 
`request.endpoint` attribute that already exist.
After the policy execution we would get
```
{#context.attributes['request.endpoint']} // -> default:/restofUri
{#context.attributes['request.resolved.endpoint']} // -> http://store[PLACEHOLDER]/myLocalApiPath/myApi/restOfUri/restofUri
```
And we could then add a second dynamic routing policy to use this attribute...
```json
"dynamic-routing": {
    "rules": [
        {
            "pattern": "/v1/stores/(?<store>.*)/.*",
            "url": "{#attributes['request.resolved.endpoint'].replace('[PLACEHOLDER]', #group['store'])}"
        }
    ]
```
Thus `http://store[PLACEHOLDER]/myLocalApiPath/myApi/restOfUri/restofUri` would become `http://storeXXX/myLocalApiPath/myApi/restOfUri/restofUri`

If I were to change the endpoint definition of the API (eg: changing it to ` http://store[PLACEHOLDER]/my__NEW__LocalApiPath/myApi`), I would still get the correct dynamic endpoint uri without changing anything to the policies

Note:
- It would also probably be possible to add a custom SpEL function for resolving endpoint (eg: `{#resolve(#endpoints['default'])}`)
- Maybe it is possible to access/resolve endpoints inside the Groovy policy, but I didn't find the adequate properties...
- Another way to do that would be to have a policy just for enforcing the resolved endpoint's Host...

**Comment by tfabien** [comment]
Another possible way I tried but didn't work
- Define endpoint `default` as `http://store{#context.attributes['store']}/myLocalApiPath/myApi/`
- Use the update attributes policy to extract and store the store id for each request, hoping it would be used while resolving the endpoint...
This configuration leads to an error while deploying the api:
```
io.gravitee.el.exceptions.ExpressionEvaluationException: The template evaluation returns an error.
 at io.gravitee.el.spel.SpelTemplateEngine.getValue(SpelTemplateEngine.java:62)
 at io.gravitee.el.spel.SpelTemplateEngine.getValue(SpelTemplateEngine.java:68)
 at io.gravitee.el.spel.SpelTemplateEngine.convert(SpelTemplateEngine.java:48)
 at io.gravitee.connector.http.HttpConnectorFactory.convert(HttpConnectorFactory.java:81)
 at io.gravitee.connector.http.HttpConnectorFactory.resolve(HttpConnectorFactory.java:62)
 at io.gravitee.connector.http.HttpConnectorFactory.create(HttpConnectorFactory.java:46)
 at io.gravitee.gateway.core.endpoint.lifecycle.impl.EndpointGroupLifecycleManager.start(EndpointGroupLifecycleManager.java:161
```
