### ISSUE TITLE
Traffic shadowing policy doesn't work 

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8385]
# Describe the bug

Trying to implement the traffic shadowing policy, but not seeing the shadow endpoint triggered at all

# To Reproduce

Steps to reproduce the behaviour:

1.  Create a dummy API

1.  Implement the traffic shadowing policy

1.  Use a shadow endpoint in another group for the policy

1.  Then, setup the policy, by specifying the target {{ {#endpoints['shadow']}

}} !<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/187645082-3779188c-52cd-40a7-9b58-1671a408cde5.png](https://user-images.githubusercontent.com/89140082/187645082-3779188c-52cd-40a7-9b58-1671a408cde5.png))

1.  When calling the API /TESTPOI able to see a call on it but nothing on the shadow endpoint.

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/187644993-cf896e64-fe91-451d-a8dd-211cc2f1506b.png](https://user-images.githubusercontent.com/89140082/187644993-cf896e64-fe91-451d-a8dd-211cc2f1506b.png))

# Expected behaviour

The shadow endpoint to be triggered when the other one is

# Current behaviour

For now, the shadow endpoint is not getting any calls, when calling the API <span class="error">[errorWhenDoingCall.txt]</span>([https://github.com/gravitee-io/issues/files/9460314/errorWhenDoingCall.txt](https://github.com/gravitee-io/issues/files/9460314/errorWhenDoingCall.txt))

**Comment by mouligno** [comment]
Related to this one i think https://github.com/gravitee-io/issues/issues/6025

**Comment by kirestoj01** [comment]
Here is my stack trace from investigation for another ticket with same issue.

```
10:54:49.110 [vert.x-eventloop-thread-5] [] ERROR i.g.g.policy.impl.ExecutablePolicy - Error during traffic-shadowing policy execution
java.lang.NoSuchMethodError: 'io.gravitee.common.http.HttpHeaders io.gravitee.gateway.api.Request.headers()'
	at io.gravitee.policy.trafficshadowing.TrafficShadowingPolicy.onRequestContent(TrafficShadowingPolicy.java:54)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.stream(ExecutablePolicy.java:120)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.prepareStreamablePolicyChain(StreamablePolicyChain.java:62)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:49)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:80)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.policy.v3.keyless.KeylessPolicyV3.onRequest(KeylessPolicyV3.java:39)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.execute(ExecutablePolicy.java:110)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:67)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.handle(EmptyStreamableProcessor.java:30)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:126)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:109)
	at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:66)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$4(DefaultReactor.java:85)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:43)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:60)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:29)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:62)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:31)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:99)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.route(VertxReactorHandler.java:84)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:66)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:38)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:145)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
10:54:49.111 [vert.x-eventloop-thread-5] [] ERROR i.g.g.policy.impl.OrderedPolicyChain - Unexpected error while running onXXXXContent for policy io.gravitee.gateway.policy.impl.ExecutablePolicy@44c6f229
io.gravitee.gateway.policy.PolicyException: java.lang.NoSuchMethodError: 'io.gravitee.common.http.HttpHeaders io.gravitee.gateway.api.Request.headers()'
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.stream(ExecutablePolicy.java:124)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.prepareStreamablePolicyChain(StreamablePolicyChain.java:62)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:49)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:80)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.policy.v3.keyless.KeylessPolicyV3.onRequest(KeylessPolicyV3.java:39)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.execute(ExecutablePolicy.java:110)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:67)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.handle(EmptyStreamableProcessor.java:30)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:126)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:109)
	at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:66)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$4(DefaultReactor.java:85)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:43)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:60)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:29)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:62)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:31)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:99)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.route(VertxReactorHandler.java:84)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:66)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:38)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:145)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'io.gravitee.common.http.HttpHeaders io.gravitee.gateway.api.Request.headers()'
	at io.gravitee.policy.trafficshadowing.TrafficShadowingPolicy.onRequestContent(TrafficShadowingPolicy.java:54)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.stream(ExecutablePolicy.java:120)
	... 60 common frames omitted
```

I also test issue present in 3.19.3
