### ISSUE TITLE
Heartbeat service isn't working anymore

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#8417]
## :collision: Describe the bug

When starting the gateway with the heartbeat service activated there are some exceptions thrown and events aren't updated.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Start APIM 3.15.15 with the heartbeat service activated 
2. Open the logs
3. 💥 

```shell
07:41:13.743 [vert.x-worker-thread-5] [] ERROR i.g.r.j.m.JdbcEventRepository - Failed to create event:
org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; ERROR: duplicate key value violates unique constraint "pk_events"
  Detail: Key (id)=(b8265b67-c0cf-49cf-a65b-67c0cf99cf11) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_events"
  Detail: Key (id)=(b8265b67-c0cf-49cf-a65b-67c0cf99cf11) already exists.
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:981)
        at io.gravitee.repository.jdbc.management.JdbcEventRepository.create(JdbcEventRepository.java:174)
        at io.gravitee.repository.jdbc.management.JdbcEventRepository.create(JdbcEventRepository.java:51)
        at io.gravitee.gateway.services.heartbeat.HeartbeatService.onMessage(HeartbeatService.java:166)
        at io.gravitee.node.cluster.standalone.StandaloneTopic.lambda$addMessageConsumer$0(StandaloneTopic.java:106)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_events"
  Detail: Key (id)=(b8265b67-c0cf-49cf-a65b-67c0cf99cf11) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
```

Same error happens with MongoDB

## :rainbow: Expected behaviour

Everything should be fine and heartbeat events should be updated.

**Comment by gaetanmaisse** [comment]
Tested on 3.15.x env, the gateway started without any error logs

![image](https://user-images.githubusercontent.com/4112568/188895893-715a1f4a-ff88-4f0b-8f56-a45f53c07246.png)
