### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal character in query at index

### ISSUE THREAD

**Issue by jeyhunkh** [gravitee-io/issues#8473]
Hi everyone. I have an issue related to Gravitee API Management. I have added path "<span class="error">[http://myservice.service.consul/cashTerminal?command=check&amp;account=123456789102||CARD&amp;txn_id=9876543210123%10| http://myservice.service.consul/cashTerminal?command=check&amp;account=123456789102%7C%7CCARD&amp;txn_id=9876543210123%10]</span>" and when I send a request to this URL Gateway shows an error. Error is shown below. The cause of this problem is the "||" in the URL. If I omit the double pipe "||" then there is no problem. However, if I use it, then it makes an error. Is there any way to pass this error ?

<pre> java.lang.IllegalArgumentException: Illegal character in query at index 93: [http://myservice.service.consul/cashTerminal?command=check&amp;account=123456789102](http://myservice.service.consul/cashTerminal?command=check&account=123456789102)([http://myservice.service.consul/cashTerminal?command=check&amp;account=123456789102](http://myservice.service.consul/cashTerminal?command=check&account=123456789102))||CARD&txn_id=9876543210123%10
 at java.net.URI.create(URI.java:852)
 at io.gravitee.gateway.core.invoker.EndpointInvoker.addQueryParameters(EndpointInvoker.java:175)
 at io.gravitee.gateway.core.invoker.EndpointInvoker.buildURI(EndpointInvoker.java:155)
 at io.gravitee.gateway.core.invoker.EndpointInvoker.invoke(EndpointInvoker.java:79)
 at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleProxyInvocation(ApiReactorHandler.java:120)
 at io.gravitee.gateway.handlers.api.ApiReactorHandler.lambda$handleClientRequest$1(ApiReactorHandler.java:93)
 at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:67)
 at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:55)
 at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:89)
 at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:105)
 at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:42)
 at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:59)
 at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:55)
 at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:89)
 at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:105)
 at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:42)
 at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:59)
 at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:55)
 at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.handle(LoggableRequestProcessor.java:64)
 at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.handle(LoggableRequestProcessor.java:34)
 at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.handle(StreamableProcessorDecorator.java:38)
 at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:59)
 at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:55)
 at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:89)
 at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:54)
 at io.gravitee.policy.keyless.KeylessPolicy.onRequest(KeylessPolicy.java:39)
 at sun.reflect.GeneratedMethodAccessor830.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:95)
 at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:50)
 at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:45)
 at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:72)
 at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:54)
 at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:105)
 at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:42)
 at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:59)
 at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:104)
 at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:86)
 at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:89)
 at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:43)
 at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$2(DefaultReactor.java:96)
 at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:46)
 at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:41)
 at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:55)
 at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:29)
 at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:44)
 at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:41)
 at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:60)
 at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:30)
 at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:44)
 at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:103)
 at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.route(VertxReactorHandler.java:48)
 at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:44)
 at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:29)
 at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
 at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
 at io.vertx.core.http.impl.HttpServerRequestImpl.handleBegin(HttpServerRequestImpl.java:149)
 at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:132)
 at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
 at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
 at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
 at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
 at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
 at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:748)
 Caused by: java.net.URISyntaxException: Illegal character in query at index 93: [http://myservice.service.consul/cashTerminal?command=check&amp;account=123456789102](http://myservice.service.consul/cashTerminal?command=check&account=123456789102)([http://myservice.service.consul/cashTerminal?command=check&amp;account=123456789102](http://myservice.service.consul/cashTerminal?command=check&account=123456789102))||CARD&txn_id=9876543210123%10
 at java.net.URI$Parser.fail(URI.java:2848)
 at java.net.URI$Parser.checkChars(URI.java:3021)
 at java.net.URI$Parser.parseHierarchical(URI.java:3111)
 at java.net.URI$Parser.parse(URI.java:3053)
 at java.net.URI.<init>

 (URI.java:588) at java.net.URI.create(URI.java:850) ... 87 more ```

 </init></pre>

**Comment by gaetanmaisse** [comment]
Hi @jeyhunkh, I'm super late to the party but can you try to use `%7C` instead of `|` in the URL?

**Comment by gaetanmaisse** [comment]
As no recent activity has been on this issue, I will close it. If needed please reopen it!
