### ISSUE TITLE
Cannot start Hazelcast instance

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8537]
## :collision: Describe the bug
When installed the 3.18.10 hazelcast it cannot start 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. added in the gravitee.yml flie this part to set the type to hazelcast:
```yaml
ratelimit: 
  type: hazelcast 

#cluster:
# enabled: true 
# hazelcast: 
#   configurationFile: ${gravitee.home}/config/hazelcast.xml
```
 
2. Downloaded the hazelcast plugin from https://download.gravitee.io/#graviteeio-apim/plugins/repositories/gravitee-apim-repository-hazelcast/ 3.18.10 with the same apim version and imported accordingly
  
3. the error from the logs:  
```
12:32:49.605 [graviteeio-node] [] INFO i.g.g.r.p.RepositoryPluginHandler - Repository [RATE_LIMIT] loaded by hazelcast
12:32:49.622 [graviteeio-node] [] WARN o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt:
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rateLimitRepository': Unsatisfied dependency expressed through field 'hazelcastInstance'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.hazelcast.core.HazelcastInstance' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
12:32:49.627 [graviteeio-node] [] ERROR i.g.p.c.i.PluginContextFactoryImpl - Unable to refresh plugin context
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rateLimitRepository': Unsatisfied dependency expressed through field 'hazelcastInstance'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.hazelcast.core.HazelcastInstance' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
at io.gravitee.plugin.core.internal.PluginContextFactoryImpl.create(PluginContextFactoryImpl.java:58)
at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.loadRepository(RepositoryPluginHandler.java:128)
at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.handle(RepositoryPluginHandler.java:99)
at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugin$8(PluginEventListener.java:140)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugin(PluginEventListener.java:138)
at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$5(PluginEventListener.java:121)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:121)
at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:66)
at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:43)
at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:35)
at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:113)
at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:89)
at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
at io.gravitee.node.container.AbstractNode.startComponents(AbstractNode.java:178)
at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:76)
at io.gravitee.gateway.standalone.node.GatewayNode.doStart(GatewayNode.java:92)
at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:87)
at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:155)
at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:164)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.hazelcast.core.HazelcastInstance' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1799)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1355)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
… 49 common frames omitted
12:32:49.627 [graviteeio-node] [] ERROR i.g.g.r.p.RepositoryPluginHandler - Unexpected error while creating context for repository instance
java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@37344d31 has not been refreshed yet
at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1141)
at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1153)
at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.registerRepositoryDefinitions(RepositoryPluginHandler.java:155)
at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.loadRepository(RepositoryPluginHandler.java:137)
at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.handle(RepositoryPluginHandler.java:99)
at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugin$8(PluginEventListener.java:140)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugin(PluginEventListener.java:138)
at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$5(PluginEventListener.java:121)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:121)
at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:66)
at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:43)
at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:35)
at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:113)
at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:89)
at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
at io.gravitee.node.container.AbstractNode.startComponents(AbstractNode.java:178)
at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:76)
at io.gravitee.gateway.standalone.node.GatewayNode.doStart(GatewayNode.java:92)
at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:87)
at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:155)
at io.gravitee.gateway.standalone.boostrap.Bootstrap.main([Bootstrap.java:164](http://bootstrap.java:164/))
```
 - Environment: [e.g. 3.18.10]

**Comment by gaetanmaisse** [comment]
Closing since the original ticket has been closed after a discussion with the customer.
