### ISSUE TITLE
ratelimit with Redis not working

### ISSUE THREAD

**Issue by zerr0s** [gravitee-io/issues#8619]
Hello,

I'm trying to use redis as backend for ratelimit. I've found all documentation and tried to configure the gateway using this docker compose:
```
gateway:
    image: graviteeio/apim-gateway:${APIM_VERSION:-3}
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8082:8082"
    volumes:
      - /data/prod/apps/gravitee/data/apim-gateway/logs:/opt/graviteeio-gateway/logs
      - /data/prod/apps/gravitee/data/apim-gateway/plugins-ext:/opt/graviteeio-gateway/plugins-ext
      - /data/prod/apps/gravitee/data/apim-gateway/drivers:/opt/graviteeio-gateway/plugins/ext/repository-jdbc
    environment:
      - gravitee_management_type=jdbc
      - gravitee_management_jdbc_prefix=apim_
      - gravitee_management_jdbc_url=jdbc:postgresql://postgres:5432/gravitee?ssl=false
      - gravitee_management_jdbc_username=xxxx
      - gravitee_management_jdbc_password=xxxxx
      - gravitee_ratelimit_type=redis
      - gravitee_ratelimit_redis_host=redis
      - gravitee_ratelimit_redis_port=6379
      - gravitee_ratelimit_redis_timeout=2000
      - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200
      - gravitee_plugins_path_0=/opt/graviteeio-gateway/plugins
      - gravitee_plugins_path_1=/opt/graviteeio-gateway/plugins-ext
    networks:
      - database
      - frontend
```

The result log is:

```
12:36:56.777 [graviteeio-node] [] ERROR i.g.n.p.s.impl.ServiceManagerImpl - Unexpected error while starting service
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.gravitee.repository.ratelimit.api.RateLimitRepository<?>' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	at io.gravitee.gateway.services.ratelimit.AsyncRateLimitService.doStart(AsyncRateLimitService.java:52)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.plugins.service.impl.ServiceManagerImpl.doStart(ServiceManagerImpl.java:59)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractNode.startComponents(AbstractNode.java:178)
	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:76)
	at io.gravitee.gateway.standalone.node.GatewayNode.doStart(GatewayNode.java:80)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:87)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:155)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:164)
12:36:56.777 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Gateway Sync Service
12:36:56.777 [graviteeio-node] [] INFO  i.g.g.services.sync.SyncService - Sync service has been initialized with delay [5000MILLISECONDS]
12:36:56.777 [graviteeio-node] [] INFO  i.g.g.services.sync.SyncService - Associate a new HTTP handler on /sync
12:36:56.781 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service API keys cache
12:36:56.781 [graviteeio-node] [] INFO  i.g.g.s.s.cache.ApiKeysCacheService - Associate a new HTTP handler on /apikeys
12:36:56.781 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Subscriptions cache repository
12:36:56.781 [graviteeio-node] [] INFO  i.g.g.s.s.c.SubscriptionsCacheService - Associate a new HTTP handler on /subscriptions
12:36:56.782 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.gateway.services.sync.SyncManager
12:36:56.782 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.gateway.services.sync.synchronizer.ApiSynchronizer
12:36:56.782 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.gateway.services.sync.synchronizer.DictionarySynchronizer
12:36:56.782 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.gateway.services.sync.synchronizer.OrganizationSynchronizer
12:36:56.782 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.gateway.services.sync.synchronizer.DebugApiSynchronizer
12:36:56.843 [graviteeio-node] [] INFO  i.g.g.s.s.s.OrganizationSynchronizer - 0 organization(s) synchronized in 51ms.
12:36:56.851 [graviteeio-node] [] INFO  i.g.g.s.s.s.ApiSynchronizer - 0 apis synchronized in 8ms
12:36:56.855 [graviteeio-node] [] INFO  i.g.g.s.s.s.DictionarySynchronizer - 0 dictionary(ies) synchronized in 4ms.
12:36:56.858 [graviteeio-node] [] INFO  i.g.c.event.impl.EventManagerImpl - Register new listener ApiKeysCacheService for event type class io.gravitee.gateway.reactor.ReactorEvent
12:36:56.858 [graviteeio-node] [] INFO  i.g.c.event.impl.EventManagerImpl - Register new listener SubscriptionsCacheService for event type class io.gravitee.gateway.reactor.ReactorEvent
12:36:56.898 [graviteeio-node] [] INFO  i.g.g.s.h.i.s.StandaloneHeartbeatStrategy - Start gateway heartbeat service
12:36:56.898 [graviteeio-node] [] INFO  i.g.g.s.h.i.s.StandaloneHeartbeatStrategy - Gateway heartbeat service scheduled with fixed delay 5000 MILLISECONDS
12:36:56.899 [graviteeio-node] [] INFO  i.g.g.s.h.i.s.StandaloneHeartbeatStrategy - Start gateway heartbeat service: DONE
12:36:56.899 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Gateway - Debug service
12:36:56.899 [graviteeio-node] [] INFO  i.g.gateway.debug.DebugService - Starting component: VertxDebugService
12:36:56.899 [graviteeio-node] [] INFO  i.g.g.debug.vertx.VertxDebugService - Starting Vertx DEBUG container and deploy only 1 Verticle
12:36:56.900 [graviteeio-node] [] INFO  i.g.gateway.debug.DebugService - Starting component: DebugReactorEventListener
12:36:56.900 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.gateway.jupiter.debug.DebugReactorEventListener
12:36:56.900 [graviteeio-node] [] INFO  i.g.c.event.impl.EventManagerImpl - Register new listener DebugReactorEventListener for event type class io.gravitee.gateway.reactor.ReactorEvent
12:36:56.900 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - 	Starting component: ManagementService
12:36:56.900 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Node Management API service
12:36:56.901 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - 	Starting component: NodeMonitoringEventHandler
12:36:56.901 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service io.gravitee.node.monitoring.handler.NodeMonitoringEventHandler
12:36:56.902 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - 	Starting component: NodeInfosService
12:36:56.902 [graviteeio-node] [] INFO  i.g.n.m.infos.NodeInfosService - Starting node infos service
12:36:56.902 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Node Infos Service
12:36:56.903 [vert.x-eventloop-thread-5] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - Start HTTP listener for Node Management API
12:36:56.905 [graviteeio-node] [] INFO  i.g.n.m.infos.NodeInfosService - Start node infos service: DONE
12:36:56.905 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - 	Starting component: NodeHealthCheckService
12:36:56.905 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Initializing service Node Health-check service
12:36:56.917 [graviteeio-node] [] ERROR i.g.g.standalone.node.GatewayNode - An error occurred while starting component class io.gravitee.node.monitoring.healthcheck.NodeHealthCheckService
java.lang.IllegalArgumentException: Cannot instantiate interface io.gravitee.node.api.healthcheck.Probe : io.gravitee.gateway.repository.healthcheck.RateLimitRepositoryProbe
	at io.gravitee.common.spring.factory.SpringFactoriesLoader.createSpringFactoriesInstances(SpringFactoriesLoader.java:96)
	at io.gravitee.common.spring.factory.SpringFactoriesLoader.getSpringFactoriesInstances(SpringFactoriesLoader.java:70)
	at io.gravitee.common.spring.factory.SpringFactoriesLoader.getFactoriesInstances(SpringFactoriesLoader.java:56)
	at io.gravitee.node.monitoring.healthcheck.ProbeManagerImpl.getProbes(ProbeManagerImpl.java:41)
	at io.gravitee.node.monitoring.healthcheck.NodeHealthCheckService.doStart(NodeHealthCheckService.java:76)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractNode.startComponents(AbstractNode.java:178)
	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:76)
	at io.gravitee.gateway.standalone.node.GatewayNode.doStart(GatewayNode.java:80)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:87)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:155)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:164)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.gravitee.gateway.repository.healthcheck.RateLimitRepositoryProbe': Unsatisfied dependency expressed through field 'rateLimitRepository'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.gravitee.repository.ratelimit.api.RateLimitRepository<io.gravitee.repository.ratelimit.model.RateLimit>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBean(AbstractAutowireCapableBeanFactory.java:343)
	at io.gravitee.common.spring.factory.SpringFactoriesLoader.createSpringFactoriesInstances(SpringFactoriesLoader.java:90)
	... 17 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.gravitee.repository.ratelimit.api.RateLimitRepository<io.gravitee.repository.ratelimit.model.RateLimit>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1799)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1355)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
	... 23 common frames omitted
12:36:56.918 [graviteeio-node] [] ERROR i.g.g.standalone.GatewayContainer - An unexpected error occurs while starting Gravitee.io - API Gateway
java.lang.IllegalArgumentException: Cannot instantiate interface io.gravitee.node.api.healthcheck.Probe : io.gravitee.gateway.repository.healthcheck.RateLimitRepositoryProbe
	at io.gravitee.common.spring.factory.SpringFactoriesLoader.createSpringFactoriesInstances(SpringFactoriesLoader.java:96)
	at io.gravitee.common.spring.factory.SpringFactoriesLoader.getSpringFactoriesInstances(SpringFactoriesLoader.java:70)
	at io.gravitee.common.spring.factory.SpringFactoriesLoader.getFactoriesInstances(SpringFactoriesLoader.java:56)
	at io.gravitee.node.monitoring.healthcheck.ProbeManagerImpl.getProbes(ProbeManagerImpl.java:41)
	at io.gravitee.node.monitoring.healthcheck.NodeHealthCheckService.doStart(NodeHealthCheckService.java:76)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractNode.startComponents(AbstractNode.java:178)
	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:76)
	at io.gravitee.gateway.standalone.node.GatewayNode.doStart(GatewayNode.java:80)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:87)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:155)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:164)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.gravitee.gateway.repository.healthcheck.RateLimitRepositoryProbe': Unsatisfied dependency expressed through field 'rateLimitRepository'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.gravitee.repository.ratelimit.api.RateLimitRepository<io.gravitee.repository.ratelimit.model.RateLimit>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBean(AbstractAutowireCapableBeanFactory.java:343)
	at io.gravitee.common.spring.factory.SpringFactoriesLoader.createSpringFactoriesInstances(SpringFactoriesLoader.java:90)
	... 17 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.gravitee.repository.ratelimit.api.RateLimitRepository<io.gravitee.repository.ratelimit.model.RateLimit>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1799)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1355)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
	... 23 common frames omitted
12:36:56.918 [graviteeio-node] [] INFO  i.g.g.standalone.GatewayContainer - Shutting-down Gravitee.io - API Gateway...
12:36:56.918 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - Gravitee.io - API Gateway is stopping
12:36:56.920 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - 	Stopping component: AlertEventProducerManager
12:36:56.921 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Destroying service Alert Engine - Event producer
12:36:56.938 [vert.x-eventloop-thread-5] [] INFO  i.g.n.m.h.v.e.ManagementEndpointManagerImpl - Register a new endpoint for Management API: GET / [io.gravitee.node.management.http.node.NodeEndpoint]
12:36:56.938 [vert.x-eventloop-thread-5] [] INFO  i.g.n.m.h.v.e.ManagementEndpointManagerImpl - Register a new endpoint for Management API: GET /configuration [io.gravitee.node.management.http.configuration.ConfigurationEndpoint]
12:36:56.938 [vert.x-eventloop-thread-5] [] INFO  i.g.n.m.h.v.v.ManagementVerticle - HTTP listener for Node Management bind to port TCP:18082
12:36:56.938 [vert.x-eventloop-thread-4] [] INFO  i.g.g.d.vertx.DebugReactorVerticle - Debug HTTP listener ready to accept requests on port 8482
12:36:57.021 [graviteeio-node] [] ERROR i.g.p.a.i.AlertEventProducerManagerImpl - Unexpected error while stopping event producer: io.gravitee.ae.connector.ws.WsEventProducer@6dd729
java.lang.NullPointerException: Cannot invoke "io.gravitee.ae.connector.ws.AbstractConnector.stop()" because "this.connector" is null
	at io.gravitee.ae.connector.ws.WsEventProducer.doStop(WsEventProducer.java:211)
	at io.gravitee.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:41)
	at io.gravitee.plugin.alert.internal.AlertEventProducerManagerImpl.doStop(AlertEventProducerManagerImpl.java:69)
	at io.gravitee.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:41)
	at io.gravitee.node.container.AbstractNode.stopComponents(AbstractNode.java:218)
	at io.gravitee.node.container.AbstractNode.doStop(AbstractNode.java:121)
	at io.gravitee.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:41)
	at io.gravitee.node.container.spring.SpringBasedContainer.doStop(SpringBasedContainer.java:90)
	at io.gravitee.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:41)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:95)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:155)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:164)
12:36:57.021 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - 	Stopping component: KeyStoreLoaderManager
12:36:57.021 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Destroying service io.gravitee.node.certificates.KeyStoreLoaderManager
12:36:57.021 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - 	Stopping component: ReporterManager
12:36:57.021 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Destroying service Reporter service
12:36:57.021 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - 	Stopping component: NodeMonitorService
12:36:57.022 [graviteeio-node] [] ERROR i.g.g.standalone.node.GatewayNode - An error occurred while stopping component NodeMonitorService
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ExecutorService.isShutdown()" because "this.executorService" is null
	at io.gravitee.node.monitoring.monitor.NodeMonitorService.doStop(NodeMonitorService.java:144)
	at io.gravitee.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:41)
	at io.gravitee.node.container.AbstractNode.stopComponents(AbstractNode.java:218)
	at io.gravitee.node.container.AbstractNode.doStop(AbstractNode.java:121)
	at io.gravitee.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:41)
	at io.gravitee.node.container.spring.SpringBasedContainer.doStop(SpringBasedContainer.java:90)
	at io.gravitee.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:41)
	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:95)
	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:155)
	at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:164)
12:36:57.022 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - 	Stopping component: NodeHealthCheckService
12:36:57.022 [graviteeio-node] [] INFO  i.g.common.service.AbstractService - Destroying service Node Health-check service
12:36:57.022 [graviteeio-node] [] INFO  i.g.g.standalone.node.GatewayNode - 	Stopping component: NodeInfosService
```

Is this a missconfig from me ?

**Comment by zerr0s** [comment]
hummmm. i found the problem. I have to add the redis plugin, but there is no link in documentation to download it. I follow a link for jdbc and search in this page the redis plugin.
