### ISSUE TITLE
Gateway time-out when httpClient calls in Javascript policy

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8691]
## :collision: Describe the bug
When using httpClient calls in Javascript policy, timeout are observed on the gateway : 
```
httpClient.send(new Request(req.url, req.method, req.headers, req.body));
```

```
[vertx-blocked-thread-checker] [] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 4192669 ms, time limit is 2000 ms"
io.vertx.core.VertxException: Thread blocked
	at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$Signaller.block(Unknown Source)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.waitingGet(Unknown Source)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at io.gravitee.policy.javascript.model.js.JsHttpClient.shutDown(JsHttpClient.java:115)
	at io.gravitee.policy.javascript.JavascriptPolicy.eval(JavascriptPolicy.java:263)
	at io.gravitee.policy.javascript.JavascriptPolicy.executeStreamScript(JavascriptPolicy.java:245)
	at io.gravitee.policy.javascript.JavascriptPolicy.lambda$onRequestContent$1(JavascriptPolicy.java:142)
	at io.gravitee.policy.javascript.JavascriptPolicy$$Lambda$1784/0x00000008017be260.apply(Unknown Source)
	at io.gravitee.gateway.api.http.stream.TransformableRequestStream.end(TransformableRequestStream.java:39)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.lambda$prepareStreamablePolicyChain$1(StreamablePolicyChain.java:81)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain$$Lambda$1786/0x0000000801805820.handle(Unknown Source)
```

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create an API with JS Policy and add some httpClient method calls
2. Make some attempt to call the API
3. Check the gateway logs

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material
https://github.com/gravitee-io/gravitee-policy-javascript

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18.13

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gcusnieux** [comment]
http calls from javascript policy was an experimental feature but is not officially supported, you have to use the http-callout policy to do this
