### ISSUE TITLE
[management] Traffic shadowing policy does not work

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8911]
## :collision: Describe the bug
Traffic Shadowing policy does not work. When you try to consume API that has the policy in the flow, the policy fails to run but the API is consumed on default endpoint anyway. 
The following stacktrace is in the Gateway Logs:

```
11:21:26.843 [vert.x-eventloop-thread-1] [] ERROR i.g.g.policy.impl.ExecutablePolicy - Error during traffic-shadowing policy execution
java.lang.NoSuchMethodError: 'io.gravitee.common.http.HttpHeaders io.gravitee.gateway.api.Request.headers()'
	at io.gravitee.policy.trafficshadowing.TrafficShadowingPolicy.onRequestContent(TrafficShadowingPolicy.java:54)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.stream(ExecutablePolicy.java:120)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.prepareStreamablePolicyChain(StreamablePolicyChain.java:62)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:49)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:80)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.policy.v3.keyless.KeylessPolicyV3.onRequest(KeylessPolicyV3.java:39)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.execute(ExecutablePolicy.java:110)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:67)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.handle(EmptyStreamableProcessor.java:30)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:126)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:109)
	at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:66)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$4(DefaultReactor.java:85)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:43)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:60)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:29)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:62)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:31)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:99)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.route(VertxReactorHandler.java:84)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:66)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:38)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:145)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
11:21:26.843 [vert.x-eventloop-thread-1] [] ERROR i.g.g.policy.impl.OrderedPolicyChain - Unexpected error while running onXXXXContent for policy io.gravitee.gateway.policy.impl.ExecutablePolicy@563942b5
io.gravitee.gateway.policy.PolicyException: java.lang.NoSuchMethodError: 'io.gravitee.common.http.HttpHeaders io.gravitee.gateway.api.Request.headers()'
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.stream(ExecutablePolicy.java:124)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.prepareStreamablePolicyChain(StreamablePolicyChain.java:62)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:49)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:80)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.policy.v3.keyless.KeylessPolicyV3.onRequest(KeylessPolicyV3.java:39)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.execute(ExecutablePolicy.java:110)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:67)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.handle(EmptyStreamableProcessor.java:30)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:126)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:109)
	at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:66)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$4(DefaultReactor.java:85)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:43)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:60)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:29)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:62)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:31)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:99)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.route(VertxReactorHandler.java:84)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:66)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:38)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:145)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'io.gravitee.common.http.HttpHeaders io.gravitee.gateway.api.Request.headers()'
	at io.gravitee.policy.trafficshadowing.TrafficShadowingPolicy.onRequestContent(TrafficShadowingPolicy.java:54)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.stream(ExecutablePolicy.java:120)
	... 60 common frames omitted
```

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create simple API with 2 groups of endpoints
2. Set Traffic Shadowing policy to forward the request to endpoint from group 2.
3. Consume the API
4. See stacktrace in GW logs.

## :rainbow: Expected behaviour
The policy should copy the request from the default endpoint to the endpoint defined in the policy.

## Current behaviour
The policy is not working, not stopping the API to execute. 

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [3.18.19; 3.19.7; 3.20.1]
 - OS: Docker

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Same as https://github.com/gravitee-io/issues/issues/8385

**Comment by gaetanmaisse** [comment]
Closing as a duplicate of #8385
