### ISSUE TITLE
Debug API logs not working

### ISSUE THREAD

**Issue by keepeek-rd** [gravitee-io/issues#9017]
## Describe the bug

When I activate the debug API logs, the debug does not work in the logs interface and I end up with normal logs (in non-debug mode). I see a stacktrace in the gateway logs.

## To Reproduce

Steps to reproduce the behaviour:

1.  Go to APIs > choose API > Analytics > Logs > Configure the logging
2.  Click on Enabled, save, and deploy API
3.  On logs vue, no debug log displayed
4.  On gateway applicative log, stacktrace is displayed

## Expected behaviour

I should get API debug logs in admin interface

## Current behaviour

Normal API logs are displayed

## Useful information

<div class="preformatted panel" style="border-width: 1px;"> 
 <div class="preformattedContent panelContent"> 
  <pre>gio_apim_gateway | 14:39:04.580 [gio.sync-10] [f5ef0c1e-e532-4e25-af0c-1ee5329e2516] INFO i.g.g.h.a.m.impl.ApiManagerImpl - API id[f5ef0c1e-e532-4e25-af0c-1ee5329e2516] name[XXX] version[1.0] has been updated
gio_apim_gateway | Apr 13, 2023 2:39:05 PM freemarker.log._JULLoggerFactory$JULLogger error
gio_apim_gateway | SEVERE: Error executing FreeMarker template
gio_apim_gateway | FreeMarker template error:
gio_apim_gateway | ?size is unsupported for freemarker.ext.beans.OverloadedMethodsModel
gio_apim_gateway |
gio_apim_gateway | ----
gio_apim_gateway | FTL stack trace ("" means nesting-related):
gio_apim_gateway | - Failed at: #list headerValue as value [in template "es7x/index/log.ftl" at line 85, column 9]
gio_apim_gateway | - Reached through: @compress single_line=true [in template "es7x/index/log.ftl" at line 2, column 1]
gio_apim_gateway | ----
gio_apim_gateway |
gio_apim_gateway | Java stack trace (for programmers):
gio_apim_gateway | ----
gio_apim_gateway | freemarker.template.TemplateModelException: [... Exception message was already printed; see it above ...]
gio_apim_gateway | at freemarker.ext.beans.OverloadedMethodsModel.size(OverloadedMethodsModel.java:81)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:312)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
gio_apim_gateway | at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
gio_apim_gateway | at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
gio_apim_gateway | at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:383)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForHashListing(IteratorBlock.java:416)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:272)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
gio_apim_gateway | at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
gio_apim_gateway | at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
gio_apim_gateway | at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:347)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:353)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:389)
gio_apim_gateway | at freemarker.core.Environment.visitAndTransform(Environment.java:514)
gio_apim_gateway | at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:347)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:353)
gio_apim_gateway | at freemarker.core.Environment.process(Environment.java:326)
gio_apim_gateway | at freemarker.template.Template.process(Template.java:383)
gio_apim_gateway | at io.gravitee.elasticsearch.templating.freemarker.FreeMarkerComponent.generateFromTemplate(FreeMarkerComponent.java:109)
gio_apim_gateway | at io.gravitee.reporter.elasticsearch.indexer.es7.ES7BulkIndexer.generateData(ES7BulkIndexer.java:34)
gio_apim_gateway | at io.gravitee.reporter.elasticsearch.indexer.AbstractIndexer.getSource(AbstractIndexer.java:175)
gio_apim_gateway | at io.gravitee.reporter.elasticsearch.indexer.AbstractIndexer.transform(AbstractIndexer.java:122)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
gio_apim_gateway | at io.reactivex.rxjava3.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
gio_apim_gateway | at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
gio_apim_gateway | at io.reactivex.rxjava3.internal.subscriptions.SubscriptionArbiter.setSubscription(SubscriptionArbiter.java:87)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onSubscribe(FlowableOnErrorNext.java:65)
gio_apim_gateway | at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
gio_apim_gateway | at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
gio_apim_gateway | at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableOnErrorNext.subscribeActual(FlowableOnErrorNext.java:39)
gio_apim_gateway | at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
gio_apim_gateway | at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15863)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:161)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:404)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:178)
gio_apim_gateway | at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
gio_apim_gateway | at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
gio_apim_gateway | at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
gio_apim_gateway | at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
gio_apim_gateway | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
gio_apim_gateway | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
gio_apim_gateway | at java.base/java.lang.Thread.run(Unknown Source)
gio_apim_gateway |
gio_apim_gateway | 14:39:05.766 [RxCachedThreadScheduler-1] [] ERROR i.g.e.t.f.FreeMarkerComponent - Impossible to generate from template /es7x/index/log.ftl
gio_apim_gateway | freemarker.template.TemplateModelException: ?size is unsupported for freemarker.ext.beans.OverloadedMethodsModel
gio_apim_gateway |
gio_apim_gateway | ----
gio_apim_gateway | FTL stack trace ("" means nesting-related):
gio_apim_gateway | - Failed at: #list headerValue as value [in template "es7x/index/log.ftl" at line 85, column 9]
gio_apim_gateway | - Reached through: @compress single_line=true [in template "es7x/index/log.ftl" at line 2, column 1]
gio_apim_gateway | ----
gio_apim_gateway | at freemarker.ext.beans.OverloadedMethodsModel.size(OverloadedMethodsModel.java:81)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:312)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
gio_apim_gateway | at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
gio_apim_gateway | at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
gio_apim_gateway | at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:383)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForHashListing(IteratorBlock.java:416)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:272)
gio_apim_gateway | at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
gio_apim_gateway | at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
gio_apim_gateway | at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
gio_apim_gateway | at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:347)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:353)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:389)
gio_apim_gateway | at freemarker.core.Environment.visitAndTransform(Environment.java:514)
gio_apim_gateway | at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:347)
gio_apim_gateway | at freemarker.core.Environment.visit(Environment.java:353)
gio_apim_gateway | at freemarker.core.Environment.process(Environment.java:326)
gio_apim_gateway | at freemarker.template.Template.process(Template.java:383)
gio_apim_gateway | at io.gravitee.elasticsearch.templating.freemarker.FreeMarkerComponent.generateFromTemplate(FreeMarkerComponent.java:109)
gio_apim_gateway | at io.gravitee.reporter.elasticsearch.indexer.es7.ES7BulkIndexer.generateData(ES7BulkIndexer.java:34)
gio_apim_gateway | at io.gravitee.reporter.elasticsearch.indexer.AbstractIndexer.getSource(AbstractIndexer.java:175)
gio_apim_gateway | at io.gravitee.reporter.elasticsearch.indexer.AbstractIndexer.transform(AbstractIndexer.java:122)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
gio_apim_gateway | at io.reactivex.rxjava3.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
gio_apim_gateway | at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
gio_apim_gateway | at io.reactivex.rxjava3.internal.subscriptions.SubscriptionArbiter.setSubscription(SubscriptionArbiter.java:87)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onSubscribe(FlowableOnErrorNext.java:65)
gio_apim_gateway | at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
gio_apim_gateway | at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
gio_apim_gateway | at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableOnErrorNext.subscribeActual(FlowableOnErrorNext.java:39)
gio_apim_gateway | at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
gio_apim_gateway | at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15863)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:161)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:404)
gio_apim_gateway | at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:178)
gio_apim_gateway | at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
gio_apim_gateway | at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
gio_apim_gateway | at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
gio_apim_gateway | at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
gio_apim_gateway | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
gio_apim_gateway | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
gio_apim_gateway | at java.base/java.lang.Thread.run(Unknown Source)</pre> 
 </div> 
</div>

I notice that it come from proxy headers response, if I disable headers from debug log on proxy, I can get debug log without header.

here is the proxy response if It can help :

<div class="preformatted panel" style="border-width: 1px;"> 
 <div class="preformattedContent panelContent"> 
  <pre>HEADER:
Date: Fri, 14 Apr 2023 12:08:13 GMT
Content-Encoding: gzip
Content-Type: application/hal+json;charset=UTF-8;version=1
content-length: 238
X-Gravitee-Transaction-Id: c661b882-9333-4266-a1b8-829333626673
X-Gravitee-Request-Id: c661b882-9333-4266-a1b8-829333626673

BODY:
{
  "version": 1,
  "release": "X.XX.X",
  "serverVersion": "X.XX.X",
  "_links": {
    "self": {
      "href": "http://fixed.dev.local:9982/api"
    },
    "curies": [
      {
        "name": "XXX",
        "href": "http://fixed.dev.local:9982/api/doc/rels/{rel}",
        "templated": true
      }
    ],
    "XXX:XXX": {
      "href": "http://fixed.dev.local:9982/api/XXX"
    },
    "XXX:XXX": {
      "href": "http://fixed.dev.local:9982/api/XXX"
    },
    "XXX:XXX": {
      "href": "http://fixed.dev.local:9982/api/XXX"
    },
    "XXX:XXX": {
      "href": "http://fixed.dev.local:9982/api/XXX"
    },
    "XXX:XXX": {
      "href": "http://fixed.dev.local:9982/api/XXX"
    },
    "help": {
      "href": "http://fixed.dev.local:9982/api/XXX"
    }
  }
}

</pre> 
 </div> 
</div>

## Environment

APIM Docker 3.20.4

**Comment by keepeek-rd** [comment]
wouldn't there be a workarround?
it's blocking for our version upgrade :(

**Comment by keepeek-rd** [comment]
@gaetanmaisse yes I mean detailed logs (from the API logs interface, when I click on a log line to get the detail)
URL ex:
https://XXX/apim-ui/#!/environments/default/apis/XXX/logs/XXX?timestamp=1685518854262&from=1685518554687&to=1685518854687&page=1&size=15

I reprocude only on our API.

but with this debug trace, you can't be able to reproduce the problem by forcing this content in the body of the api response?


?size is unsupported for freemarker.ext.beans.OverloadedMethodsModel gio_apim_gateway
