### ISSUE TITLE
After gateway timeout, Gravitee Gateway is not handling http requests

### ISSUE THREAD

**Issue by meveno** [gravitee-io/issues#9086]
## Describe the bug

After a timeout, the gateway is unavailable (it doesn't serve requests) and we see this exception repeatidly in the log :

io.vertx.core.http.impl.NoStackTraceTimeoutException: The timeout period of 10000ms has been exceeded while executing GET / for server rec-annuaire-postgrest-api.postgrest-api.svc.cluster.local:3000 12:30:25.468 <span class="error">[vert.x-eventloop-thread-1]</span> [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception java.lang.NullPointerException: Cannot invoke "io.vertx.core.http.HttpClientRequest.headers()" because "this.httpClientRequest" is null at io.gravitee.connector.http.HttpConnection.lambda$writeUpstreamHeaders$6(HttpConnection.java:324) at java.base/java.lang.Iterable.forEach(Unknown Source) at io.gravitee.connector.http.HttpConnection.writeUpstreamHeaders(HttpConnection.java:323) at io.gravitee.connector.http.HttpConnection.writeHeaders(HttpConnection.java:300) at io.gravitee.connector.http.HttpConnection.write(HttpConnection.java:280) at io.gravitee.connector.http.HttpConnection.write(HttpConnection.java:50) at io.gravitee.gateway.core.endpoint.factory.impl.EndpointFactoryImpl$ConnectorProxyConnection.write(EndpointFactoryImpl.java:120) at io.gravitee.gateway.core.endpoint.factory.impl.EndpointFactoryImpl$ConnectorProxyConnection.write(EndpointFactoryImpl.java:74) at io.gravitee.gateway.core.logging.LoggableProxyConnection.write(LoggableProxyConnection.java:104) at io.gravitee.gateway.core.logging.LoggableProxyConnection.write(LoggableProxyConnection.java:39) at io.gravitee.gateway.core.invoker.EndpointInvoker.lambda$invoke$2(EndpointInvoker.java:79) at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$5(AbstractStreamableProcessorChain.java:70) at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.write(EmptyStreamableProcessor.java:47) at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$5(AbstractStreamableProcessorChain.java:70) at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:120) at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:35) at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.write(AbstractStreamableProcessorChain.java:99) at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.write(StreamableProcessorDecorator.java:74) at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:120) at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:35) at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.write(StreamableProcessorDecorator.java:74) at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.write(EmptyStreamableProcessor.java:47) at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.write(AbstractStreamableProcessorChain.java:99) at io.gravitee.gateway.core.logging.LoggableClientRequest.lambda$bodyHandler$0(LoggableClientRequest.java:68) at io.gravitee.gateway.http.vertx.VertxHttpServerRequest.lambda$bodyHandler$0(VertxHttpServerRequest.java:187) at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) at io.vertx.core.http.impl.HttpEventHandler.handleChunk(HttpEventHandler.java:51) at io.vertx.core.http.impl.Http1xServerRequest.onData(Http1xServerRequest.java:531) at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:128) at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240) at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:227) at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:280) at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63) at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Unknown Source)

## Expected behaviour

The gateway is serving request or at least the healthcheck is ko so the kube scheduler is not restarting the pod...

## Environment

Gravitee docker image : graviteeio/apim-gateway:3.20.10

## Potential impacts

Gateway does not serve requests.

**Comment by meveno** [comment]
It seems fixed in the latest gravitee gateway version.

**Comment by meveno** [comment]
Bad news,
We are still having this exception :(
```
16:15:34.221 [vert.x-eventloop-thread-3] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: Cannot invoke "io.vertx.core.http.HttpClientRequest.headers()" because "this.httpClientRequest" is null
	at io.gravitee.connector.http.HttpConnection.lambda$writeUpstreamHeaders$6(HttpConnection.java:324)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at io.gravitee.connector.http.HttpConnection.writeUpstreamHeaders(HttpConnection.java:323)
	at io.gravitee.connector.http.HttpConnection.writeHeaders(HttpConnection.java:300)
	at io.gravitee.connector.http.HttpConnection.write(HttpConnection.java:280)
	at io.gravitee.connector.http.HttpConnection.write(HttpConnection.java:50)
	at io.gravitee.gateway.core.endpoint.factory.impl.EndpointFactoryImpl$ConnectorProxyConnection.write(EndpointFactoryImpl.java:120)
	at io.gravitee.gateway.core.endpoint.factory.impl.EndpointFactoryImpl$ConnectorProxyConnection.write(EndpointFactoryImpl.java:74)
	at io.gravitee.gateway.core.logging.LoggableProxyConnection.write(LoggableProxyConnection.java:104)
	at io.gravitee.gateway.core.logging.LoggableProxyConnection.write(LoggableProxyConnection.java:39)
	at io.gravitee.gateway.core.invoker.EndpointInvoker.lambda$invoke$2(EndpointInvoker.java:79)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$5(AbstractStreamableProcessorChain.java:70)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.write(EmptyStreamableProcessor.java:47)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$5(AbstractStreamableProcessorChain.java:70)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:120)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:35)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.write(AbstractStreamableProcessorChain.java:99)
	at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.write(StreamableProcessorDecorator.java:74)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:120)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:35)
	at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.write(StreamableProcessorDecorator.java:74)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.write(EmptyStreamableProcessor.java:47)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.write(AbstractStreamableProcessorChain.java:99)
	at io.gravitee.gateway.core.logging.LoggableClientRequest.lambda$bodyHandler$0(LoggableClientRequest.java:68)
	at io.gravitee.gateway.http.vertx.VertxHttpServerRequest.lambda$bodyHandler$0(VertxHttpServerRequest.java:187)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.http.impl.HttpEventHandler.handleChunk(HttpEventHandler.java:51)
	at io.vertx.core.http.impl.Http1xServerRequest.onData(Http1xServerRequest.java:531)
	at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:128)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:227)
	at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:280)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by meveno** [comment]
Stil having the issue with the latest patch version ...

```
2023-12-21 14:51:23.195 +0100 [vert.x-eventloop-thread-2] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: Cannot invoke "io.vertx.core.http.HttpClientRequest.headers()" because "this.httpClientRequest" is null
	at io.gravitee.connector.http.HttpConnection.lambda$writeUpstreamHeaders$6(HttpConnection.java:324)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at io.gravitee.connector.http.HttpConnection.writeUpstreamHeaders(HttpConnection.java:323)
	at io.gravitee.connector.http.HttpConnection.writeHeaders(HttpConnection.java:300)
	at io.gravitee.connector.http.HttpConnection.write(HttpConnection.java:280)
	at io.gravitee.connector.http.HttpConnection.write(HttpConnection.java:50)
	at io.gravitee.gateway.core.endpoint.factory.impl.EndpointFactoryImpl$ConnectorProxyConnection.write(EndpointFactoryImpl.java:120)
	at io.gravitee.gateway.core.endpoint.factory.impl.EndpointFactoryImpl$ConnectorProxyConnection.write(EndpointFactoryImpl.java:74)
	at io.gravitee.gateway.core.logging.LoggableProxyConnection.write(LoggableProxyConnection.java:104)
	at io.gravitee.gateway.core.logging.LoggableProxyConnection.write(LoggableProxyConnection.java:39)
	at io.gravitee.gateway.core.invoker.EndpointInvoker.lambda$invoke$2(EndpointInvoker.java:79)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$5(AbstractStreamableProcessorChain.java:76)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.write(EmptyStreamableProcessor.java:47)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$5(AbstractStreamableProcessorChain.java:76)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:120)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:35)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.write(AbstractStreamableProcessorChain.java:105)
	at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.write(StreamableProcessorDecorator.java:74)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:120)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.write(StreamablePolicyChain.java:35)
	at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.write(StreamableProcessorDecorator.java:74)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.write(EmptyStreamableProcessor.java:47)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.write(AbstractStreamableProcessorChain.java:105)
	at io.gravitee.gateway.core.logging.LoggableClientRequest.lambda$bodyHandler$0(LoggableClientRequest.java:68)
	at io.gravitee.gateway.core.logging.LoggableClientRequest.lambda$bodyHandler$0(LoggableClientRequest.java:68)
	at io.gravitee.gateway.http.vertx.VertxHttpServerRequest.lambda$bodyHandler$0(VertxHttpServerRequest.java:187)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.http.impl.HttpEventHandler.handleChunk(HttpEventHandler.java:51)
	at io.vertx.core.http.impl.Http1xServerRequest.onData(Http1xServerRequest.java:531)
	at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:128)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:227)
	at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:280)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by meveno** [comment]
After further investigation, it seems to happen on one unique configured API.
This API is between a offline application that is using PouchDB library (v8.0.1) to sync local changes to a remote CouchDB server (v3.3.1).

**Comment by meveno** [comment]
Seems other people are having the same issue : https://community.gravitee.io/t/gravitee-gateway-timeout-this-httpclientrequest-is-null/1727

**Comment by meveno** [comment]
Any update on this ?
