### ISSUE TITLE
Null Exception when loading gateway apim page on management console

### ISSUE THREAD

**Issue by fabMrc** [gravitee-io/issues#9101]
Hi

On 3.20.8 gravitee.io apim when I click on gateways page to display gateway instance on the management console It fails and I have in log :

 2023-06-19 14:22:11.820 <span class="error">[gravitee-listener-171]</span> ERROR i.g.r.a.m.r.provider.ThrowableMapper - Internal error
 java.lang.NullPointerException: null
 at io.gravitee.rest.api.service.impl.InstanceServiceImpl$1.apply(InstanceServiceImpl.java:126)
 at io.gravitee.rest.api.service.impl.InstanceServiceImpl$1.apply(InstanceServiceImpl.java:109)
 at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
 at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
 at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
 at io.gravitee.rest.api.service.impl.EventServiceImpl.search(EventServiceImpl.java:306)
 at jdk.internal.reflect.GeneratedMethodAccessor2279.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
 at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
 at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
 at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
 at com.sun.proxy.$Proxy91.search(Unknown Source)
 at io.gravitee.rest.api.service.impl.InstanceServiceImpl.search(InstanceServiceImpl.java:101)
 at io.gravitee.rest.api.management.rest.resource.InstancesResource.getInstances(InstancesResource.java:65)
 at jdk.internal.reflect.GeneratedMethodAccessor2278.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

I tried some analysis :

*   Analytics purge and stop all gateway + clear node_monitoring mongo collections

But it is always fail. So I think there is other information that is responsable of the error. On an other gravitee.io 3.20.8 environment I do not have the issue. It is not easy to debug because I have no access to source code so I have to push a new issue here

**Comment by fabMrc** [comment]
ok after decompiling code it seems be linked to events data 

```
db.getCollection("events").find({"type": {$regex : "GATEWAY" }})
```

```
public List<InstanceEntity> findAllStarted(ExecutionContext executionContext) {
        LOGGER.debug("Find started instances by event");
        EventQuery query = new EventQuery();
        query.setTypes(instancesRunningOnly);
        Collection<EventEntity> events = this.eventService.search(executionContext, query);
        return (List)events.stream().map((event) -> {
            List<String> environments = this.extractProperty(event, EventProperties.ENVIRONMENTS_HRIDS_PROPERTY.getValue());
            List<String> organizations = this.extractProperty(event, EventProperties.ORGANIZATIONS_HRIDS_PROPERTY.getValue());
            return this.convert(event, environments, organizations);
        }).collect(Collectors.toList());
    }
```
ENVIRONMENTS_HRIDS_PROPERTY and ORGANIZATIONS_HRIDS_PROPERTY do not exists on old events before our upgrade

**Comment by fabMrc** [comment]
ok when I delete all events collection it resolve the bug.

**Comment by gaetanmaisse** [comment]
What was the APIM version before the upgrade?
