### ISSUE TITLE
Upgrade vertx to 4.4.7+ : memory leak

### ISSUE THREAD

**Issue by zzuzdm** [gravitee-io/issues#9588]
#Description
OOM、Thread blocked
2 gateway instance get the same error

#To Reproduce
cant not reproduce with stress tests
(10000 qps  36 hours) 

#Useful information

qps: 200~300
uptime:  3 month

log:
13:37:10.188 [vert.x-eventloop-thread-4] [] ERROR io.vertx.core.impl.ContextBase - Unhandled exception
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
	at io.netty.util.internal.InternalThreadLocalMap.expandIndexedVariableTableAndSet(InternalThreadLocalMap.java:361)
	at io.netty.util.internal.InternalThreadLocalMap.setIndexedVariable(InternalThreadLocalMap.java:340)
	at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:185)
	at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:142)
	at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:75)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:245)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.evict(SimpleConnectionPool.java:550)
	at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.checkExpired(SharedClientHttpStreamEndpoint.java:115)
	at io.vertx.core.http.impl.HttpClientImpl.lambda$static$1(HttpClientImpl.java:136)
	at io.vertx.core.http.impl.HttpClientImpl$$Lambda$1266/0x00007fc5847957d0.accept(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)
	at io.vertx.core.net.impl.pool.ConnectionManager.forEach(ConnectionManager.java:33)
	at io.vertx.core.http.impl.HttpClientImpl.checkExpired(HttpClientImpl.java:236)
	at io.vertx.core.http.impl.HttpClientImpl.access$100(HttpClientImpl.java:78)
	at io.vertx.core.http.impl.HttpClientImpl$PoolChecker.handle(HttpClientImpl.java:230)
	at io.vertx.core.http.impl.HttpClientImpl$PoolChecker.handle(HttpClientImpl.java:218)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:948)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.ContextBase.emit(ContextBase.java:297)
	at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:207)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:937)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

VM Dump View:
Summary:
<img width="1623" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/7aed3eea-7717-44af-93b4-9bd205eabaaf">
Thread ("vert.x-eventloop-thread-6" prio=5 tid=27 RUNNABLE):
<img width="1587" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/31db453a-f961-4be4-8fc7-004bf4f24d6a">
<img width="1589" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/e719a5e3-72f4-4f0e-b6f3-e74337a1b987">
<img width="1574" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/517f20f6-f05c-4790-bd4e-9ad2dab43822">

<img width="1599" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/73d4c09f-725e-431a-879e-276f48c9feca">
<img width="1592" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/cc185519-c0eb-47bc-8c22-58fe051aa2d9">
<img width="1567" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/cc53fecc-9696-4e41-b1cc-1485dca755d0">
<img width="1497" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/bd3ea873-c4e3-4b3e-bc0d-7227c9e041bf">
<img width="1569" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/8e106d6c-86fa-4972-9a3a-a23c6200ee6c">
<img width="1539" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/00aaa5da-07b9-465a-a84b-2f702a919882">
<img width="1576" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/44ea9ee8-6040-46cf-ae36-398c02f88d3a">
<img width="1576" alt="image" src="https://github.com/gravitee-io/issues/assets/7220588/a0e87329-8c50-4d7c-bfe1-82664bb6b828">

Environment
APIM Version 4.1.2

Oracle jdk 17.0.8+9-LTS-211

VM options  -Djava.net.preferIPv4Stack=true -Xms4g -Xmx4g -Djava.awt.headless=true -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Dvertx.disableFileCaching=true -Dvertx.disableFileCPResolving=true -Dvertx.disableContextTiming=true -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory

CentOS7

**Comment by zzuzdm** [comment]
io.netty.util.internal.InternalThreadLocalMap  indexedVariables has 100 million+ items（InternalThreadLocalMap.UNSET）

![image](https://github.com/gravitee-io/issues/assets/7220588/7a701dc1-19ee-4b2e-9ebf-d298ddc7c58a)

**Comment by zzuzdm** [comment]
i think this issue is related 
vertx shoud be update to 4.4.7 + 
https://github.com/eclipse-vertx/vert.x/pull/5082
