### ISSUE TITLE
Errors in main dashboard in  4.3.3

### ISSUE THREAD

**Issue by fabMrc** [gravitee-io/issues#9736]
Hello

I have 723 APIS and I am using g.io 4.3.3, when I want to display the HC tab dashboard I have a angular popup error that display max count clause 1024 error. I am using ES 7.20.x and mongo 7 as repository It is a fresh sandbox installation of gravitee.io because I have the same with my current platform and I would like to be sure it was not related to my datas.

Here the log in api management :

2024-05-14 08:45:38.734 [gravitee-listener-1417] ERROR i.g.r.a.m.r.provider.ThrowableMapper - Internal error org.apache.lucene.search.IndexSearcher$TooManyNestedClauses: Query contains too many nested clauses; maxClauseCount is set to 1024 at org.apache.lucene.search.IndexSearcher$3.consumeTerms(IndexSearcher.java:844) at org.apache.lucene.search.TermQuery.visit(TermQuery.java:239) at org.apache.lucene.search.BooleanQuery.visit(BooleanQuery.java:584) at org.apache.lucene.search.BooleanQuery.visit(BooleanQuery.java:584) at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:804) at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:810) at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:686) at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:523) at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:538) at io.gravitee.rest.api.service.impl.search.lucene.searcher.AbstractDocumentSearcher.search(AbstractDocumentSearcher.java:91) at io.gravitee.rest.api.service.impl.search.lucene.searcher.AbstractDocumentSearcher.search(AbstractDocumentSearcher.java:64) at io.gravitee.rest.api.service.impl.search.lucene.searcher.ApiDocumentSearcher.search(ApiDocumentSearcher.java:212) at io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.lambda$search$6(SearchEngineServiceImpl.java:291) at java.base/java.util.Optional.flatMap(Optional.java:289) at io.gravitee.rest.api.service.impl.search.SearchEngineServiceImpl.search(SearchEngineServiceImpl.java:277) at io.gravitee.rest.api.service.v4.impl.ApiSearchServiceImpl.searchIds(ApiSearchServiceImpl.java:422) at jdk.internal.reflect.GeneratedMethodAccessor429.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220) at jdk.proxy3/jdk.proxy3.$Proxy90.searchIds(Unknown Source) at jdk.internal.reflect.GeneratedMethodAccessor429.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) at jdk.proxy3/jdk.proxy3.$Proxy90.searchIds(Unknown Source) at io.gravitee.rest.api.service.impl.ApiServiceImpl.search(ApiServiceImpl.java:1974) at jdk.internal.reflect.GeneratedMethodAccessor447.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220) at jdk.proxy3/jdk.proxy3.$Proxy86.search(Unknown Source) at io.gravitee.rest.api.management.rest.resource.ApisResource.searchPagedApis(ApisResource.java:492) at jdk.internal.reflect.GeneratedMethodAccessor445.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) at org.glassfish.jersey.internal.Errors.process(Errors.java:292) at org.glassfish.jersey.internal.Errors.process(Errors.java:274) at org.glassfish.jersey.internal.Errors.process(Errors.java:244) at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)

Also I have lot of log error when I go to the main api status dashboard. It is very slow to display the panel API lifecycle and API status also:

2024-05-14 08:45:36.847 [gravitee-listener-1420] ERROR o.g.j.server.ServerRuntime$Responder - An I/O error has occurred while writing a response message entity to the container output stream. org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:67) at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116) at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:677) at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:385) at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:375) at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:264) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) at org.glassfish.jersey.internal.Errors.process(Errors.java:292) at org.glassfish.jersey.internal.Errors.process(Errors.java:274) at org.glassfish.jersey.internal.Errors.process(Errors.java:244) at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736) at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614) at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365) at io.gravitee.rest.api.security.filter.GraviteeContextAuthorizationFilter.doFilter(GraviteeContextAuthorizationFilter.java:65) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) Caused by: org.eclipse.jetty.io.EofException: null at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:117) at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:275) at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254) at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:368) at org.eclipse.jetty.server.internal.HttpConnection$SendCallback.process(HttpConnection.java:845) at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:250) at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:231) at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.send(HttpConnection.java:1420) at org.eclipse.jetty.server.HttpStream$Wrapper.send(HttpStream.java:179) at org.eclipse.jetty.server.HttpStream$Wrapper.send(HttpStream.java:179) at org.eclipse.jetty.session.AbstractSessionManager$SessionStreamWrapper.send(AbstractSessionManager.java:1460) at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1250) at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:751) at org.eclipse.jetty.server.handler.ContextResponse.write(ContextResponse.java:56) at org.eclipse.jetty.ee10.servlet.ServletContextResponse.write(ServletContextResponse.java:288) at org.eclipse.jetty.ee10.servlet.HttpOutput.channelWrite(HttpOutput.java:205) at org.eclipse.jetty.ee10.servlet.HttpOutput.channelWrite(HttpOutput.java:190) at org.eclipse.jetty.ee10.servlet.HttpOutput.write(HttpOutput.java:797) at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61) ... 100 common frames omitted Caused by: java.io.IOException: Broken pipe at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method) at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:66) at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:217) at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:153) at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:563) at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:642) at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:111) ... 154 common frames omitted

Finally the tasks tab is always pending, to finish the request it needs to put the focus on another ui component, it seems to be a pb of angular event management

**Comment by phiz71** [comment]
Hello @fabMrc, this bug has probably the same root cause as this one https://github.com/gravitee-io/issues/issues/9730, which has been fixed in 4.3.4.

Is it possible for you to update to the latest 4.3.x and verify if the error is still there or not ?

FYI, this maxClauseCount error is not related to ES but to apache Lucene. APIM use it to index APIs and users, to facilitate the search by keyword.
