### ISSUE TITLE
[GKO] ApiDefinition problem adding more than one flow pre through terraform kubernetes provider 

### ISSUE THREAD

**Issue by ivank** [gravitee-io/issues#9806]
## Describe the bug

With GKO, we can't add more than one pre action in a flow, using terraform kubernetes_manifest.

```
╷
│ Error: Plugin did not respond
│
│   with module.content-library.kubernetes_manifest.app,
│   on modules/content-library/main.tf line 337, in resource "kubernetes_manifest" "app":
│  337: resource "kubernetes_manifest" "app" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-kubernetes_v2.30.0_x5 plugin:

panic: ElementKeyInt(0): can't use tftypes.Object["condition":tftypes.String, "consumers":tftypes.List[tftypes.Object["consumerId":tftypes.String, "consumerType":tftypes.Number]], "enabled":tftypes.Bool, "id":tftypes.String, "methods":tftypes.List[tftypes.String], "name":tftypes.String, "path-operator":tftypes.Object["operator":tftypes.String, "path":tftypes.String], "post":tftypes.Tuple[tftypes.Object["condition":tftypes.String, "configuration":tftypes.DynamicPseudoType, "description":tftypes.String, "enabled":tftypes.Bool, "name":tftypes.String, "policy":tftypes.String]], "pre":tftypes.Tuple[tftypes.Object["condition":tftypes.String, "configuration":tftypes.Object["addHeaders":tftypes.Tuple[tftypes.Object["name":tftypes.String, "value":tftypes.String]], "scope":tftypes.String], "description":tftypes.String, "enabled":tftypes.Bool, "name":tftypes.String, "policy":tftypes.String], tftypes.Object["condition":tftypes.String, "configuration":tftypes.Object["addHeaders":tftypes.Tuple[tftypes.Object["name":tftypes.String, "value":tftypes.String]], "scope":tftypes.String], "description":tftypes.String, "enabled":tftypes.Bool, "name":tftypes.String, "policy":tftypes.String]]] as tftypes.Object["condition":tftypes.String, "consumers":tftypes.List[tftypes.Object["consumerId":tftypes.String, "consumerType":tftypes.Number]], "enabled":tftypes.Bool, "id":tftypes.String, "methods":tftypes.List[tftypes.String], "name":tftypes.String, "path-operator":tftypes.Object["operator":tftypes.String, "path":tftypes.String], "post":tftypes.Tuple[tftypes.Object["condition":tftypes.String, "configuration":tftypes.DynamicPseudoType, "description":tftypes.String, "enabled":tftypes.Bool, "name":tftypes.String, "policy":tftypes.String]], "pre":tftypes.Tuple[tftypes.Object["condition":tftypes.String, "configuration":tftypes.DynamicPseudoType, "description":tftypes.String, "enabled":tftypes.Bool, "name":tftypes.String, "policy":tftypes.String]]]

goroutine 37 [running]:
github.com/hashicorp/terraform-plugin-go/tftypes.NewValue(...)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tftypes/value.go:278
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.DeepUnknown({0x2515f48, 0xc002260060?}, {{0x2515f48?, 0xc0032b4f30?}, {0x1d74720?, 0xc000c98588?}}, 0xc000c99c98)
        github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/scaffold.go:86 +0x19ae
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.DeepUnknown({0x2515ce0, 0xc002275b00?}, {{0x2515ce0?, 0xc0032b56b0?}, {0x1e9f520?, 0xc0032b09c0?}}, 0xc000c99b18)
        github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/scaffold.go:33 +0x1cb4
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.DeepUnknown({0x2515f48, 0xc002276cf0?}, {{0x2515f48?, 0xc0032b8120?}, {0x1d74720?, 0xc000c98720?}}, 0xc000c99ae8)
        github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/scaffold.go:80 +0x17d5
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.DeepUnknown({0x2515ce0, 0xc003248030?}, {{0x2515ce0?, 0xc0032bc7b0?}, {0x1e9f520?, 0xc0032b0300?}}, 0xc000c98c78)
        github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/scaffold.go:33 +0x1cb4
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.DeepUnknown({0x2515ce0, 0xc0032ad890?}, {{0x2515ce0?, 0xc0032bde00?}, {0x1e9f520?, 0xc0032adb00?}}, 0xc000c988e8)
        github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/scaffold.go:33 +0x1cb4
github.com/hashicorp/terraform-provider-kubernetes/manifest/provider.(*RawProviderServer).PlanResourceChange(0xc00044e600, {0x250ebf8, 0xc0009f1110}, 0xc001045310)
        github.com/hashicorp/terraform-provider-kubernetes/manifest/provider/plan.go:369 +0x3173
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).PlanResourceChange(0xc000180d20, {0x250ebf8?, 0xc0009f0e10?}, 0xc001045310)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_PlanResourceChange.go:73 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc0000bcaa0, {0x250ebf8?, 0xc0009f0420?}, 0xc0004701c0)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov5/tf5server/server.go:811 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x210e3e0?, 0xc0000bcaa0}, {0x250ebf8, 0xc0009f0420}, 0xc00044ea00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:500 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000142e00, {0x250ebf8, 0xc000a0e360}, {0x2517120, 0xc000bd41a0}, 0xc00107d440, 0xc000e59ec0, 0x35b12a0, 0x0)
        google.golang.org/grpc@v1.62.1/server.go:1386 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc000142e00, {0x2517120, 0xc000bd41a0}, 0xc00107d440)
        google.golang.org/grpc@v1.62.1/server.go:1797 +0x100c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.62.1/server.go:1027 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 21
        google.golang.org/grpc@v1.62.1/server.go:1038 +0x135

Error: The terraform-provider-kubernetes_v2.30.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

When I reformat it, it is clearly visible that the `pre` field is expecting a tuple, but should be a list.

```
panic: ElementKeyInt(0): can't use 
tftypes.Object[
    "condition":tftypes.String, 
    "consumers":tftypes.List[
        tftypes.Object[
            "consumerId":tftypes.String, 
            "consumerType":tftypes.Number
        ]
    ], 
    "enabled":tftypes.Bool, 
    "id":tftypes.String, 
    "methods":tftypes.List[tftypes.String], 
    "name":tftypes.String, 
    "path-operator":tftypes.Object
        ["operator":tftypes.String, 
        "path":tftypes.String
    ], 
    "post":tftypes.Tuple[
        tftypes.Object[
            "condition":tftypes.String, 
            "configuration":tftypes.DynamicPseudoType, 
            "description":tftypes.String, 
            "enabled":tftypes.Bool, 
            "name":tftypes.String, 
            "policy":tftypes.String
        ]
    ], 
    "pre":tftypes.Tuple[
        tftypes.Object[
            "condition":tftypes.String, 
            "configuration":tftypes.Object[
                "content":tftypes.String, 
                "customClaims":tftypes.Tuple[
                    tftypes.Object[
                        "name":tftypes.String, 
                        "value":tftypes.String
                    ]
                ], 
                "expiresIn":tftypes.Number, 
                "expiresInUnit":tftypes.String, 
                "issuer":tftypes.String, 
                "keyResolver":tftypes.String, 
                "signature":tftypes.String, 
                "x509CertificateChain":tftypes.String
            ], 
            "description":tftypes.String, 
            "enabled":tftypes.Bool, 
            "name":tftypes.String, 
            "policy":tftypes.String
        ], 
        tftypes.Object[
            "condition":tftypes.String, 
            "configuration":tftypes.Object[
                "addHeaders":tftypes.Tuple[
                    tftypes.Object[
                        "name":tftypes.String, 
                        "value":tftypes.String
                    ]
                ], 
                "scope":tftypes.String
            ], 
            "description":tftypes.String, 
            "enabled":tftypes.Bool, 
            "name":tftypes.String, 
            "policy":tftypes.String
        ]
    ]
] as 
tftypes.Object[
    "condition":tftypes.String, 
    "consumers":tftypes.List[
        tftypes.Object[
            "consumerId":tftypes.String, 
            "consumerType":tftypes.Number
        ]
    ], 
    "enabled":tftypes.Bool, 
    "id":tftypes.String, 
    "methods":tftypes.List[tftypes.String], 
    "name":tftypes.String, 
    "path-operator":tftypes.Object[
        "operator":tftypes.String, 
        "path":tftypes.String
    ], 
    "post":tftypes.Tuple[
        tftypes.Object[
            "condition":tftypes.String, 
            "configuration":tftypes.DynamicPseudoType, 
            "description":tftypes.String, 
            "enabled":tftypes.Bool, 
            "name":tftypes.String, 
            "policy":tftypes.String
        ]
    ], 
    "pre":tftypes.Tuple[
        tftypes.Object[
            "condition":tftypes.String, 
            "configuration":tftypes.DynamicPseudoType, 
            "description":tftypes.String, 
            "enabled":tftypes.Bool, 
            "name":tftypes.String, 
            "policy":tftypes.String
        ]
    ]
]
```

Not sure how this whole thing works, but I presume the types that terraform-provider-kubernetes generates from the CRD is wrong, but not sure what can be done? Maybe be more explicit

## To Reproduce

[to-reproduce](#to-reproduce)

Steps to reproduce the behaviour:

The terraform config we have is mostly this one:

```terraform
data "google_container_cluster" "gke" {
  name = "gke"
}

data "google_client_config" "current" {}

provider "kubernetes" {
  host = "https://${data.google_container_cluster.gke.endpoint}"

  token = data.google_client_config.current.access_token

  cluster_ca_certificate = base64decode(

    data.google_container_cluster.gke.master_auth.cluster_ca_certificate,

  )
}

provider "helm" {

  kubernetes {

    token = data.google_client_config.current.access_token

    host = "https://${data.google_container_cluster.gke.endpoint}"
    cluster_ca_certificate = base64decode(
      data.google_container_cluster.gke.master_auth.cluster_ca_certificate,
    )
  }
}

resource "helm_release" "gko" {
 name = "gko"
 namespace = kubernetes_namespace.apim.id
 repository = "https://helm.gravitee.io"
 chart = "gko"
 version = "0.13.1"
 verify = false
 timeout = 1200
}


resource "kubernetes_manifest" "app" {
  manifest = {
    apiVersion = "gravitee.io/v1alpha1"
    kind       = "ApiDefinition"
    metadata = {
      name      = "Content Library"
      namespace = "default"
    }
    spec = {
      description = ""
      version     = "1.0"
      name        = "Content Library"

      proxy = {
        virtual_hosts = [{ path = "/content-library" }]
      }

      plans = [
        {
          name     = "GIO-AM OAUTH plan"
          security = "OAUTH2"
          securityDefinition = jsonencode({
            oauthResource       = "user-introspection"
            extractPayload      = true
            checkRequiredScopes = false
            requiredScopes      = []
            modeStrict          = false
            propagateAuthHeader = false
          })
          validation = "AUTO"
          type       = "API"
          status     = "PUBLISHED"
          flows = [
            {
              enabled = true
              name    = ""
              path-operator = {
                path     = "/"
                operator = "STARTS_WITH"
              }
              pre = [
                {
                  name        = "Transform Headers"
                  description = ""
                  enabled     = true
                  policy      = "transform-headers"
                  configuration = {
                    addHeaders = [
                      {
                        name  = "Authorization"
                        value = "Bearer Test"
                      }
                    ]
                    scope = "REQUEST"
                  }
                },
                {
                  name        = "Transform Headers"
                  description = ""
                  enabled     = true
                  policy      = "transform-headers"
                  configuration = {
                    addHeaders = [
                      {
                        name  = "Authorization"
                        value = "Bearer Test"
                      }
                    ]
                    scope = "REQUEST"
                  }
                }
              ]
            }
          ]
        }
      ]

      flows = []
    }
  }
}

```

## Expected behaviour

[expected-behaviour](#expected-behaviour)

Apply more than one pre

## Current behaviour

[current-behaviour](#current-behaviour)

Cannot add more than more pre

## Environment

[environment](#environment)

Terraform 1.8.2 Terraform Kuberentes Provider 2.30.0 Gateway: 4.3.3 GKO: 0.13.1

**Comment by ivank** [comment]
Found a temporary workaround: https://github.com/hashicorp/terraform-provider-kubernetes/issues/2487#issuecomment-2156820495
Doesn't look like its GKO's problem
